### ISSUE TITLE
Are attributes supported with SST + FFS?

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#1006]
The heat transfer example in `adiosvm/Tutorial/heat2d/cpp/` terminates with the following error when using SST engine and FFS marshaling:

```
gndx       = 100
gndy       = 100
rank 0 reads 2D slice 100 x 100 from offset (0,0)
ERROR: found null pointer in call to Attribute<T>::Data()

Usage: heatAnalysis  input  output N  M
  input:   name of input data file/stream
  output:  name of output data file/stream
  N:       number of processes in X dimension
  M:       number of processes in Y dimension
```

It seems that InquireAttribute() is returning an empty attribute object.

https://github.com/pnorbert/adiosvm/blob/872dfdb2d78bd3d932509d22e3b7e361ee6b0084/Tutorial/heat2d/cpp/analysis/heatAnalysis.cpp#L133-L134

Since the same workflow works with SST + BP, InSituMPI and BPFile, I think it is a problem with FFS marshaling.

**Comment by keichi** [comment]
Got it, I found this out because JAXA is mainly using this workflow for testing. I can just comment out these lines for now.

**Comment by eisenhauer** [comment]
Yeah, sorry.  JAXA is a bit of a unique case here because of the architecture heterogeneity not being supported by BP and the attributes not being supported by FFS.  I’ll try to get the attributes sorted reasonably soon.

g

**Comment by eisenhauer** [comment]
Attribute support for FFS marshaling has been merged to master.  Currently FFS marshaling supports attributes to the extent that BP does, which is not completely.  In particular, the support ignores the need to make attributes work (still be applied) even if timesteps are dropped, or a reader arrives late to a stream.  That work is ongoing in SST, but I'll close this now as basic support is in place.
