### ISSUE TITLE
Some scalars do not get written

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#1033]
Some scalars in an IO object are not getting written. No error is being returned.
adios2_put and adios2_end_step return success, but bpls shows that the variables are not written.
Arrays are getting written correctly.

Test performed on a local linux machine.

**Comment by williamfgc** [comment]
@kshitij-v-mehta can you try the current master?

**Comment by kshitij-v-mehta** [comment]
Thanks, it works now.

**Comment by williamfgc** [comment]
@kshitij-v-mehta  Thank you! We have CI tests with a handful of global variables that passed just fine. Like I mentioned, I am scared of Fortran optimizations so we better do the right thing.
