### ISSUE TITLE
Variable::Shape() is not updated over timesteps

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#1071]
I have an application that writes a variable whose shape changes every timestep. However, the return value of `Variable::Shape()` is not updated when reading the file back.

Here is a small piece of code to reproduce this problem (run with one process):

https://gist.github.com/keichi/2afd215e9da0200d2dbf4bd142f1095a

Output:

```
Writing:
Step 1 shape (1, 3)
Step 2 shape (2, 3)
Step 3 shape (3, 3)
Step 4 shape (4, 3)
Step 5 shape (5, 3)
Step 6 shape (6, 3)
Step 7 shape (7, 3)
Step 8 shape (8, 3)
Step 9 shape (9, 3)
Step 10 shape (10, 3)
Reading:
Step 0 shape (1, 3)
Step 1 shape (1, 3)
Step 2 shape (1, 3)
Step 3 shape (1, 3)
Step 4 shape (1, 3)
Step 5 shape (1, 3)
Step 6 shape (1, 3)
Step 7 shape (1, 3)
Step 8 shape (1, 3)
Step 9 shape (1, 3)
```

bpls output:

```
$ bpls -d test.bp
  double   v     10*{1, 3}
    (0,0,0)    0 1 2 0 1 2
    (2,0,0)    0 1 2 0 1 2
    (4,0,0)    0 1 2 0 1 2
    (6,0,0)    0 1 2 0 1 2
    (8,0,0)    0 1 2 0 1 2
```

**Comment by pnorbert** [comment]
What does bpls -D show?

**Comment by keichi** [comment]
@pnorbert 
```
$ bpls -D test.bp
  double   v     10*{1, 3}
        step 0:
          block 0: [0:0, 0:2]
        step 1:
          block 0: [0:1, 0:2]
        step 2:
          block 0: [0:2, 0:2]
        step 3:
          block 0: [0:3, 0:2]
        step 4:
          block 0: [0:4, 0:2]
        step 5:
          block 0: [0:5, 0:2]
        step 6:
          block 0: [0:6, 0:2]
        step 7:
          block 0: [0:7, 0:2]
        step 8:
          block 0: [0:8, 0:2]
        step 9:
          block 0: [0:9, 0:2]
```

**Comment by pnorbert** [comment]
Okay, so the adios2::core internals are working fine, but the shape in the
public api is not updated.

**Comment by pnorbert** [comment]
I added a test for this in branch [changing-shape](https://github.com/ornladios/ADIOS2/tree/changing-shape)

The public IO object's VariableBase map is only partially updated every step. Only the _m_StepsStart_  is incremented but the _m_Shape_ is not updated.

**Comment by pnorbert** [comment]
The core internals are NOT working fine...
When advancing the step, the shape is not updated (nor anything else except for the step count).
```
void IO::ResetVariablesStepSelection(const bool zeroStart,
                                     const std::string hint)
{
    ...
    variable->ResetStepsSelection(zeroStart);  
}
```
The metadata contains the correct shapes (so the file content is correct), but it needs to be re-parsed at the correct position and update the variable information, including Shape, Min, Max (and Value for values). 

Note that min/max is set to the global min/max at Open, and is not set to the min/max of the step. This is incorrect behavior for the stream reading.

**Comment by keichi** [comment]
Is there any workaround I can use for now? I need this to write out the isosurface mesh.

**Comment by pnorbert** [comment]
Write a new file each step. That is a workaround. And in the future,
streaming read will handle a series of files according to issue #1046

**Comment by keichi** [comment]
- `void Engine::Get(Variable<T> variable, std::vector<T> &dataV)`
- `void Engine::Get(const std::string &variableName, std::vector<T> &dataV)`

 do not resize the vector after the first step. We need to fix this too.
