### ISSUE TITLE
Add MGARD as a dependency to CI tests

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#1102]
@chuckatkins I added some tests in #1101 that are only tested locally. I need your help to add to the CI build from the https://github.com/CODARcode/MGARD mgard3 branch. Thanks!

**Comment by chuckatkins** [comment]
Initial work revealed that MGARD internally causes segfaults on the CI images.  Further testing revealed the problems are within MGard itself so we are unable to enable it in the ADIOS CI until it can cleanly run it's own test suite.  Otherwise it will be a blocker for the rest of ADIOS CI.

**Comment by williamfgc** [comment]
@tugluk please keep us posted. Thanks!

**Comment by chuckatkins** [comment]
Closing for now.  We can re-open when memory issues are addressed upstream.

**Comment by williamfgc** [comment]
@chuckatkins thanks, MGARD is not providing a release or stable API, we should treat this as experimental.
