### ISSUE TITLE
adios_iotest read mode should decompose the actual variables in data

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#1103]
currently the decomposition is always (write, read) calculated based on the definitions in the configuration file. However, if one runs the same config with a different decomposition for reading than how it was generated, the decomposition will not match the actual data. The decomposition therefore should be performed on the shape of the actual variable at a later point when reading in.

**Comment by chuckatkins** [comment]
@pnorbert is this still a deficiency in `adios2_iotest`?
