### ISSUE TITLE
Allowing appending to existing files

### ISSUE THREAD

**Issue by iamcalvinlau** [ornladios/ADIOS2#1108]
Currently, it seems like writing out data can only create/replace a file/directory of files. I would like to be able to append to an existing set of files. 

For example, currently, if I run a job with 10 steps, then re-run the job with another 10 steps; currently, I will see just 10 steps in my bp files instead of 20 steps. I would like to be able to aggregate the 20 steps into the same set of bp files instead.

**Comment by C0nsultant** [comment]
In-person statement from Scott Klasky:

> This will be available in June with new/improved BPFile Engines.

**Comment by williamfgc** [comment]
@C0nsultant @iamcalvinlau I want to clarify this is not a silver-bullet, robust solution for long-term workflows which also include appending data (not just metadata). You must preserve the number of processes doing independent I/O (N ranks produce N files, aggregated files won't be supported), there is also the limitation of keeping metadata size under 2Gb, which depending on how often you append it can easily blow up the final size. 
Nevertheless, the feature will be added, but I'd strongly encourage to use a better workaround (e.g. create a separate bp set of files) if possible as you're aware of the limitations which are the same as ADIOS2.

**Comment by sklasky** [comment]
I think we resolved this as something which we just need metadata support, and I will talk to lipeng about this when I return.

**Comment by williamfgc** [comment]
@sklasky thanks for clarifying, this is doable.
