### ISSUE TITLE
SST: reading when there are zero size blocks

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#1111]
It seems SST reading does not bring the correct data when some processes write zero size blocks. 
The sick example was seen in EPOCH, where some variables' data is only written from rank 0 but actually all processes define and put() the variable. All non-zero rank writes a count=0 size array. 
This causes no problem at reading with BPFile. But when reading with SST, the data is invalid. 

There is no test or example at the moment to re-create this problem. 
In general, zero-sized blocks are allowed as it regularly happens in particle codes (picongpu, xgc, etc). 

We need tests like this.

**Comment by JasonRuonanWang** [comment]
@pnorbert Did you have this problem when you use FFS or BP?

**Comment by pnorbert** [comment]
I uses default settings. Did not test with both.

**Comment by eisenhauer** [comment]
There is a test for this circumstance now, so I think this is fixed.
