### ISSUE TITLE
Minor change request for adios2-config 

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1115]
`adios2-config` prints out extra `ADIOS2_DIR` information. However, a few makefiles in our ADIOS-VM examples are not working with the extra information. Is there any way to print only libraries or flags only? Maybe, we can simply remove that line.

Here is a part of Makefile in heat2d:
```
ADIOS2_FLIB=`${ADIOS2_DIR}/bin/adios2-config --libs` -ladios2_f
```

**Comment by pnorbert** [comment]
Also note, that adios2-config does not work without cmake. The script should be static, info generated at the time of installation.
