### ISSUE TITLE
Attribute read wrong value

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1118]
I am trying to read attr values but getting incorrect values. To reproduce this, I used the heat2d example with the following modification:

Writing (io_adios2.F90)
```
        call adios2_define_attribute(attr_test, io, "myattr", 4, adios2_err);
```

Reading (heatAnalysis_adios2_file.F90)
```
    call adios2_get(fh, "myattr", myattr, adios2_mode_sync, ierr)
    print *, 'myattr', myattr
```

Then, I got the following output (it should be 4):
```
 Input file: heat.bp
 myattr           0
 myattr           0
 myattr           0
```

bpls shows correct numbers:
```
$ bpls heat.bp 
File info:
  of variables:  1
  of attributes: 3
  statistics:    Min / Max 

  double   T              6*{768, 1024} = 0 / 200
  string   T/description  attr   = "Temperature from simulation"
  string   T/unit         attr   = "C"
  int      myattr         attr   = 4
```

I tried also the followings without any success
```
        call adios2_define_attribute(attr_test, io, "myattr", 4, "", adios2_err);
        call adios2_define_attribute(attr_test, io, "myattr", 4, "T", adios2_err);
```

**Comment by williamfgc** [comment]
Hi @jychoi-hpc , attributes are not accessed with Get (this is for variables only). The subroutine `adios2_attribute_data` is used for it. Please check https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/bindings/fortran/TestBPWriteReadAttributes.f90 for attribute writer/reader example. Thanks!

**Comment by jychoi-hpc** [comment]
I see. Thank you for pointing out the example. I was looking at old codes and thought attribute was same. 

Right, I didn't get any compile time or runtime error. For others, it would be difficult to notice.
