### ISSUE TITLE
Using NVMe on Summit

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1124]
I am trying to write data to VNMEs on Summit (i.e., each process write own data to the local SSDs) but getting the following error:
```
ERROR: couldn't open file restart_dir/xgc.restart.f0.00005.bp.dir//xgc.restart.f0.00005.bp.6, check permissions or path existence, in call to POSIX open
```

It look like ADIOS didn't create a directory for subfiles (at least one process per node need to create a directory for subfiles before others writing).

**Comment by williamfgc** [comment]
HI @jychoi-hpc are NVMe local to each rank and no one else have access to them? If that's the case I need to add an option so each rank has to create a directory. In adios2, rank 0 creates a directory and there is a barrier.

**Comment by jychoi-hpc** [comment]
Yes, Summit NVMes are local to node and no one else can access. 

It will be good to make all ranks (or at least one rank per node) to create a directory.

**Comment by williamfgc** [comment]
OK, thanks. @jychoi-hpc please try the latest master. I just merged a fix. Thanks!
