### ISSUE TITLE
bpmeta utility

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1128]
I found there is no bpmeta equivalent utility in Adios2. 
After writing data with metadata off, there is no way to regenerate meta data with Adios2.

**Comment by williamfgc** [comment]
Hi @jychoi-hpc please, reuse adios1 bpmeta. We haven't migrated it yet, but it should work.

**Comment by jychoi-hpc** [comment]
I will adios1 bemeta. I tested adios1 bpmeta working with adios2 files.
