### ISSUE TITLE
bpls -D crashes with local single value

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1130]
I used `adios2::LocalValueDim` to write a per-proc value in a test, and it appears to confuse `bpls` when using the `-D` option in the current release (tag `v2.3.0`).

Code to reproduce:
```cxx
#include <adios2.h>

int main(int argc, char** argv)
{
  MPI_Init(&argc, &argv);
  auto comm = MPI_COMM_WORLD;
  int rank, size;
  MPI_Comm_rank(comm, &rank);
  MPI_Comm_size(comm, &size);
  
  adios2::ADIOS ad(comm, adios2::DebugON);

  adios2::IO bpio = ad.DeclareIO("writer");

  auto varRankLocal = bpio.DefineVariable<int>("RankLocal", {adios2::LocalValueDim});

  auto bpWriter = bpio.Open("test.bp", adios2::Mode::Write, comm);
  bpWriter.Put(varRankLocal, rank);
  bpWriter.Close();  

  MPI_Finalize();
  return 0;
}
```

After running it on two procs (though the same problem happens on a single proc):
```sh
[kai@macbook build-dbg (topic/adios2 *)]$ mpirun -n 2 src/libpsc/tests/test_adios2_local_single_value
[kai@macbook build-dbg (topic/adios2 *)]$ bpls -d test.bp
  int      RankLocal  scalar
    (0)    0 1

[kai@macbook build-dbg (topic/adios2 *)]$ bpls -d -D test.bp
  int      RankLocal  scalar
        step 0:
[Kais-MacBook-Pro-269:96320] *** Process received signal ***
[Kais-MacBook-Pro-269:96320] Signal: Segmentation fault: 11 (11)
[Kais-MacBook-Pro-269:96320] Signal code: Address not mapped (1)
[Kais-MacBook-Pro-269:96320] Failing at address: 0x0
[Kais-MacBook-Pro-269:96320] [ 0] 0   libsystem_platform.dylib            0x00007fff5e2c5f5a _sigtramp + 26
[Kais-MacBook-Pro-269:96320] [ 1] 0   libsystem_c.dylib                   0x00007fff966af1a8 __sF + 152
[Kais-MacBook-Pro-269:96320] [ 2] 0   bpls                                0x000000010162562e _ZN6adios25utils17printVariableInfoIiEEiPNS_4core6EngineEPNS2_2IOEPNS2_8VariableIT_EE + 750
[Kais-MacBook-Pro-269:96320] [ 3] 0   bpls                                0x0000000101621216 _ZN6adios25utils11doList_varsEPNS_4core6EngineEPNS1_2IOE + 3510
[Kais-MacBook-Pro-269:96320] [ 4] 0   bpls                                0x0000000101620257 _ZN6adios25utils6doListEPKc + 1655
[Kais-MacBook-Pro-269:96320] [ 5] 0   bpls                                0x000000010161f362 _ZN6adios25utils8bplsMainEiPPc + 2194
[Kais-MacBook-Pro-269:96320] [ 6] 0   bpls                                0x0000000101629579 main + 41
[Kais-MacBook-Pro-269:96320] [ 7] 0   libdyld.dylib                       0x00007fff5dfb7015 start + 1
[Kais-MacBook-Pro-269:96320] [ 8] 0   ???                                 0x0000000000000004 0x0 + 4
[Kais-MacBook-Pro-269:96320] *** End of error message ***
Segmentation fault: 11
```

**Comment by williamfgc** [comment]
@germasch can you try the latest master? We are planning a patch release this month to address issues like the above.

**Comment by williamfgc** [comment]
@germasch Nevermind, the latest master doesn't work either. We are going to push a fix. Thanks!

**Comment by pnorbert** [comment]
@germasch This has been fixed. bpls -D works for local values. Also bpls -d works for local values. 
bpls -Dd however, does not work correctly for local values at the moment but we are working on fixing that too.

**Comment by germasch** [comment]
Thanks, latest master bpls works for me.

I think there are some general issues with reading back local values. In all fairness, I gather that's a known issue, as they documentation says
"As of beta release version 2.2.0 local variable reads are not supported, yet. This is work in progress. Please use global arrays and values as a workaround."

I'm not sure this is a discussion to be had here, though. Briefly, here are two points:
* having ShapeID == LocalValue when writing a variable, but having it changed to GlobalArray when read is not exactly intuitive. I can see how it's hard to find proper semantics, though.
* When reading, even though the shape id is claimed to be GlobalArray, SetSelection() doesn't work.

Anyway, if you think that's a discussion worth having, I could open a new issue for it with more details (as I understand things as of now).

**Comment by williamfgc** [comment]
Hi @germasch thanks for the feedback. We had a similar discussion that weighted on your points. About your first point, I agree, it can be confusing at first, but typically the workflows we deal with is that application developer would do the write in HPC clusters, while user scientists would do analysis when reading somewhere else. You're right, there is no proper semantics...it's basically, OK each rank has a value, but I want to see the whole thing (as a vector) when reading, if all ranks write a localvalue it would be natural to access each value by index = rankID. About #2 we have a ticket I am currently working on #1134. Please don't hesitate to provide more feedback. Thanks!

**Comment by williamfgc** [comment]
#1134 is resolved. Closing this as well.
