### ISSUE TITLE
NULL engine requested

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#1132]
Sometimes for performance testing, the easiest way to turn off an output from in an existing application is just to use the NULL engine (in adios 1.x).

**Comment by williamfgc** [comment]
@pnorbert let's talk about it tomorrow, it wasn't clear to me if NULL means 0 buffering and 0 POSIX I/O write, or it's just the latter. Either way, shouldn't be hard to implement, though.
