### ISSUE TITLE
BP marshaling in SST requires extra global MPI operations

### ISSUE THREAD

**Issue by eisenhauer** [ornladios/ADIOS2#1133]
SST has a need to aggregate metadata from different ranks to provide it to the reader ranks.  SST's metadata includes SST-based metadata in addition to the metadata associated with written application data.  For FFS marshaling, we piggyback aggregating FFS-based metadata along with SST-based things using the same global operations.   Unfortunately the BP3Serializer operation AggregateCollectiveMetadata() is does it's own MPI global operations, so we cannot use it in such a way that we can get by with the same global operations for both sorts of aggregation.  Ideally AggregateCollectiveMetadata() would be augmented with different routines that would assemble aggregate metadata using individual rank metadata that SST has transported to rank 0 (or some other rank).

**Comment by williamfgc** [comment]
Ultimately, I see this as a limitation of the SST design in convoluting the FFS serializer with the transport manager. As a result, it always needs that extra collective metadata, regardless of external buffering method (in this case BP, but could be any other). As we discussed internally, we can always add the SST "metadata" into the BP buffer as local variables.

**Comment by eisenhauer** [comment]
It would be, if the FFS serializer were actually required for SST.  It isn't.  I wouldn't want to make the BP serializer required either.

**Comment by williamfgc** [comment]
My point is that SST seems to be doing an extra aggregation if not using FFS, hence the convolution. Your choice about reusing BP. I think the solution workaround with BP is a reasonable one, and BP is heavily tested and used by apps.

**Comment by eisenhauer** [comment]
Resolved with Norbert.  We'll split the Aggregate operation as planned.  I'll leave this open until it's done.

**Comment by eisenhauer** [comment]
Closing this issue now because measurements have indicated that the extra MPI operations are not the dominant cost when scaling BP marshaling in a staging environment.  Particularly, they could only contribute at most a 2x slowdown, and we're seeing 10x at 4096 ranks (as compared to marshaling which does not have either the extra writer-side operations or any writer-side "combination" operation).  Given that we can't remove the dominant combination op, it's not worth trying to optimize out the MPI ops.  Instead, we'll address this in the future with next-generation marshaling...
