### ISSUE TITLE
RemoveAllVariables in Python bindings

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#1155]
I think `RemoveAllVariables` is missing in the glue file for the Python bindings. I see it in the IO class definition, but I'm getting an error when I try to use it in my Python module

```
AttributeError: 'adios2.IO' object has no attribute 'RemoveAllVariables'
```

@williamfgc

**Comment by williamfgc** [comment]
@suchyta1 good catch, thanks! I guess it makes sense for your work to add more low-level functionality to Python. I never bothered until now. Will do a PR. Thanks!

**Comment by williamfgc** [comment]
@suchyta1 added!
