### ISSUE TITLE
add tests after doing a make install on CI

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#1166]
Not sure if possible, but maybe it is time for external tests. Current master is broken after `make install` as we are not testing outside local ctest.

**Comment by keichi** [comment]
This is just an idea, but maybe we can run CI in [pnorbert/adiosvm](https://github.com/pnorbert/adiosvm) too? This CI would pull the master branch of ADIOS from this repository, build/install ADIOS, and then build the tutorial apps. We can be sure that the tutorial apps are compatible with the latest ADIOS.

**Comment by williamfgc** [comment]
@keichi we have a nightly repo that @chuckatkins kickstarted. We haven't added much, but we should, please see: https://github.com/ornladios/ADIOS2-Testing/tree/master/external/gray-scott . Regression tests would certainly be helpful.

**Comment by williamfgc** [comment]
@keichi  [adios2 cdash](https://open.cdash.org/index.php?project=ADIOS&date=2019-06-19) shows that the master was in fact broken.

**Comment by keichi** [comment]
@williamfgc Thanks, I didn't know this repository existed. It's exactly what I meant. I guess we can add the endianness interoperability tests here in the future?

**Comment by chuckatkins** [comment]
Fixed by #1523
