### ISSUE TITLE
pybind11 deprecation warnings

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1194]
Sorry for posting so many issues, by the way. This one is a low priority one, but I am a bit annoyed with all the warnings I get from pybind11 using a deprecated (in python 3.7) API (`warning: 'PyThread_set_key_value' is deprecated`) when building adios2.

It looks like this has been fixed in upstream pybind11: https://github.com/pybind/pybind11/pull/1454, so it'd be great if pybind11 could be updated at some point.

**Comment by williamfgc** [comment]
@germasch this is great, the more posting, the better. These show up on my Mac as well, as you know it's very difficult to add Mac related stuff to CI, since they make it hard to get a MacOS VM.

**Comment by germasch** [comment]
Thanks. I actually would expect this to appear on Linux as well, as long as the python version is recent enough.
