### ISSUE TITLE
SST Compiling Issue

### ISSUE THREAD

**Issue by AaronV77** [ornladios/ADIOS2#1209]
I'm having the following problem with ADIOS2:

```
/usr/bin/ld: warning: libadios2_sst.so.2, needed by /home/valorosoa/Packages/ADIOS2/lib//libadios2.so, not found (try using -rpath or -rpath-link)
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstFFSMarshalAttribute'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstFFSWriterBeginStep'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstProvideTimestep'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstWriterClose'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstReaderGetParams'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstReleaseStep'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstReaderClose'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstReaderOpen'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstWaitForCompletion'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstGetCurMetadata'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstFFSPerformGets'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstFFSMarshal'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstStreamDestroy'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstFFSWriterEndStep'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstReaderInitFFSCallback'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstAdvanceStep'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstReadRemoteMemory'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstWriterOpen'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstCurrentStep'
/home/valorosoa/Packages/ADIOS2/lib//libadios2.so: undefined reference to `SstFFSGetDeferred'
collect2: error: ld returned 1 exit status
```

Here is how I am compiling:
```
mpic++ -o adios example_2.cpp -L/home/valorosoa/Packages/ADIOS2/lib/ -ladios2 -I/home/valorosoa/Packages/ADIOS2/include/
```

Background: I've installed ADIOS2 to a separate directory for testing, I've changed the line 'CMAKE_INSTALL_PREFIX' to the /home/valorosoa/Packages/ADIOS2 directory. Is this linking error something that I am doing wrong or is it somewhere in the ADIOS2 makefile?

Thanks.

**Comment by AaronV77** [comment]
Okay so I tired just installing ADIOS2 without adjusting the install directory and everything works find with the following: `mpic++ -o adios example_2.cpp -ladiso2' 

There is still something wrong when you install ADIOS2 to a specified location in cmake.

**Comment by chuckatkins** [comment]
How are you compiling your code?  Is it a CMake project, hand crafted makefile?  The issue you're seeing is because adios dependency libraries can't be found.  Try using the installed `adios2-config` to generate the compile and link flags you need to use.  That should add the necessary search paths to the compilation line.

**Comment by AaronV77** [comment]
@chuckatkins I'm using ccmake and then just changing the "CMAKE_INSTALL_PREFIX" to the specified directory. Then I run make and then make install.

**Comment by chuckatkins** [comment]
@AaronV77 My question is in regard to how you're building *your* code, not ADIOS.  ADIOS looks like it's built and installed correctly.  The issue seems to be a problem with how your code is consuming ADIOS.

**Comment by AaronV77** [comment]
@chuckatkins I included how I built the code in the second comment of this issue. I am now getting the following when I try to run it: `./adios: error while loading shared libraries: libadios2.so.2: cannot open shared object file: No such file or directory`

**Comment by chuckatkins** [comment]
@AaronV77 sorry for the misunderstanding, that's not really what I meant.  Regardless though, it looks like you're missing some extra linker flags relating to rpath and rpath-link that convey where dependent libraries are located.  Just adding the `-L/prefix/lib -ladios2 -I/prefix/include` isn't sufficient.  If you're manually compiling something or just using a hand crafted makefile then `adios2-config` will output the flags necessary for using it:
```
adios2-config (--help | [--c-flags] [--c-libs] [--cxx-flags] [--cxx-libs] [-fortran-flags] [--fortran-libs])
  --help           Display help information
  -c               Both compile and link flags for the C bindings
  --c-flags        Preprocessor and compile flags for the C bindings
  --c-libs         Linker flags for the C bindings
  -x               Both compile and link flags for the C++ bindings
  --cxx-flags      Preprocessor and compile flags for the C++ bindings
  --cxx-libs       Linker flags for the C++ bindings
  -f               Both compile and link flags for the F90 bindings
  --fortran-flags  Preprocessor and compile flags for the F90 bindings
  --fortran-libs   Linker flags for the F90 bindings
```
If you're using it from a CMake based project instead, you can just do:
```cmake
find_package(ADIOS2)
find_package(MPI)
add_executable(foo foo.cxx)
target_link_libraries(foo MPI::MPI_C adios2::adios)
```

**Comment by AaronV77** [comment]
@chuckatkins I should not have to add the rpath= to compile this code, I believe that it is CMake's job to do this for me. Also I am not familiar with CMake what-so-ever and really don't understand what adios2-config is or does. Here is a step by step of what I'm doing:

1. I downloaded the following ADIOS2 release: https://github.com/ornladios/ADIOS2/archive/v2.3.0.tar.gz

2. I unpack the release and change into the directory to create the build directory. I then move into that build directory to then run the following command: `ccmake ../`

3. I then press c to configure, press e to exit, and then go to the following line CMAKE_INSTALL_PREFIX to point to the directory that I want it to build too. I then press c to configure again, then g to generate and exit.

4. I then run make -j 4, make install, and thats it. 

5. Here is an example of the code that I am trying to run which is very simple:
```
#include <adios2.h>
#include <mpi.h>
#include <iostream>

int main() {

    int rank, size;
    MPI_Init(NULL, NULL);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    #ifdef ADIOS2_HAVE_MPI
        adios2::ADIOS adios(MPI_COMM_WORLD);
        std::cout << "Here-1" << std::endl;
    #else 
        adiso2::ADIOS adios(MPI_COMM_WORLD);
        std::cout << "Here-2" << std::endl;
    #endif 

    MPI_Finalize();
     return 0;
}
```
It is a simple program to see if the MPI is enable in ADIOS2.

6. I compile the code like I've done before with the following: `mpicxx -o adios example_1.cpp -L/home/valorosoa/Packages/ADIOS2/lib -ladios2 -I/home/valorosoa/Packages/ADIOS2/include`

I get the following output:
```
/usr/bin/ld: warning: libadios2_sst.so.2, needed by /home/valorosoa/Packages/ADIOS2/lib/libadios2.so, not found (try using -rpath or -rpath-link)
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstFFSMarshalAttribute'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstFFSWriterBeginStep'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstProvideTimestep'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstWriterClose'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstReaderGetParams'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstReleaseStep'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstReaderClose'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstReaderOpen'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstWaitForCompletion'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstGetCurMetadata'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstFFSPerformGets'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstFFSMarshal'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstStreamDestroy'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstFFSWriterEndStep'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstReaderInitFFSCallback'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstAdvanceStep'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstReadRemoteMemory'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstWriterOpen'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstCurrentStep'
/home/valorosoa/Packages/ADIOS2/lib/libadios2.so: undefined reference to `SstFFSGetDeferred'
collect2: error: ld returned 1 exit status
```

and the reason is because of the linking to the libadios2_sst.so.2 shared object is not being found. This is weird because when I include the library path to the libadios2.so.2 shared object, it should know where its dependencies are, and libadios2_sst.so.2 is a dependency. Also the shared objects are all in the same directory, so it makes me believe that there is a linking error within CMake that is not finding this dependency for libadios2.so.2. I should not have to compile my code in the following way:
```mpicxx example_1.cpp -o adios2 -I/home/valorosoa/Packages/ADIOS2/include/ -Wl,-rpath=/home/valorosoa/Packages/ADIOS2/lib -L/home/valorosoa/Packages/ADIOS2/lib -ladios2```

Because even with this compiling it is still not going to work because I will get the following error: 
`./adios2: error while loading shared libraries: libadios2_sst.so.2: cannot open shared object file: No such file or directory`

If I inspect further into the binary: `ldd ./adios2`

I get the following: 
```
	linux-vdso.so.1 (0x00007ffdb47b3000)
	libadios2.so.2 => /home/valorosoa/Packages/ADIOS2/lib/libadios2.so.2 (0x00007f26a1a2f000)
	libmpich.so.0 => /usr/lib/x86_64-linux-gnu/libmpich.so.0 (0x00007f26a1579000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f26a11f0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f26a0fd8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f26a0be7000)
	libadios2_sst.so.2 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f26a09e3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f26a0645000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f26a0426000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f26a22fe000)
	libcr.so.0 => /usr/lib/libcr.so.0 (0x00007f26a021b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f26a0013000)
```

Which still shows the libadios2_sst.so.2 still not being found by the linker in some way. So when I added the `rpath` it made the linker happy because I statically included the location about for the libadios2_sst.so.2 and all its dependencies as well. 

To get the example to actually run I have to do the following: `LD_LIBRARY_PATH=/home/valorosoa/Packages/ADIOS2/lib ./adios2`

I got issues still if I installed into /usr/local but they were more manageable to compile and run the code. I hope this helps and explains the issue a little more. 

Thanks.

**Comment by williamfgc** [comment]
> I believe that it is CMake's job to do this for me

@AaronV77 you're absolute right, cmake will do this for you. One thing to consider is that is you're using mpicxx and linking manually (not cmake) so we are subject to the rules of library dependencies (libsst need to be found at runtime somehow by ld, e.g. LD_LIBRARY_PATH), in that sense we are no different from other frameworks with multiple libraries. You have 4 options:

1. Use cmake for your own compilation (we can help you with that), cmake has a clear distinction between private and public dependencies (you still need the lib directory under LD_LIBRARY_PATH at runtime) and saves you from all the manual work you're describing above. We decided to go with LD_LIBRARY_PATH for the case where multiple versions are installed. 

2. as @chuckatkins said use `adios2-config` with the corresponding flags. adios2-config will generate the required toolchain for projects using manual compilation. 

3. Build static libraries, which is the recommended way to run on Titan (-DBUILD_SHARED_LIBS=OFF)

4. Disable SST if you're not planning to use it (-DADIOS2_USE_SST=OFF)

1 and 2 are covered here: https://adios2.readthedocs.io/en/latest/using/using.html 
Also, since you're building from source I'd recommend using master.

**Comment by AaronV77** [comment]
Thank you @williamfgc and @chuckatkins.

**Comment by chuckatkins** [comment]
@AaronV77 I'd also suggest you use the 2.3.1 release we just tagged instead of 2.3.0.  There were a slew of bug fixes, many of which related to how `adios2-config` generates the flags needed by downstream consumers.
