### ISSUE TITLE
Constructor mismatch when running python examples

### ISSUE THREAD

**Issue by swsachith** [ornladios/ADIOS2#1234]
Followed the steps according to the installation guide:
https://adios2.readthedocs.io/en/latest/installation/installation.html

I’m using a virtual env with mpi4py and numpy installed with python version 3.6.6 locally on a RHEL7 (7.6). Here are the steps I followed and came across an error. 

- I pointed the PYTHONPATH location to the adios.so file (in the build dir: <adios_home>/adios2-build/lib64/python3.6/site-packages)

- ran the ctest -R Python : the test passed

- then ran both: `mpirun -n 4 python3 helloBPWriter.py `and  `python3 helloBPWriter.py` and it gave me the same error. 
```
Traceback (most recent call last):
  File "helloBPWriter.py", line 22, in <module>
    adios = adios2.ADIOS(comm, adios2.DebugON)
TypeError: ADIOS(): incompatible function arguments. The following argument types are supported:
    1. (debugMode: bool=True) -> adios2::py11::ADIOS
    2. (configFile: str='', debugMode: bool=True) -> adios2::py11::ADIOS
```

**Comment by germasch** [comment]
Did you compile ADIOS2 with MPI support? It looks to me like the adios2 python interface is compiled without MPI (which means  all of adios2 is built without MPI). I believe you have to build ADIOS2 and mpi4py both using the same underlying MPI implementation.

**Comment by williamfgc** [comment]
@swsachith please, post your CMake options and configuration output to help you debug and make sure the correct `mpi4py` , `numpy` and `python3-dev` are found by cmake. Thanks!

**Comment by swsachith** [comment]
Thanks will do. I thought the MPI and Python is enabled by default for the build (according to the guide: https://adios2.readthedocs.io/en/latest/installation/installation.html, i might've read it wrong). 

Did not know that I had to build mpi4py. Will do those and update the thread.

**Comment by williamfgc** [comment]
@swsachith you're right in your interpretation, the `AUTO` options is the default which means cmake will look for the python dependencies. If they are not found automatically it would just not build with Python and stop the build (not forced like in `ON`). This is why looking at your cmake configuration and output will help to see what's going on.

**Comment by swsachith** [comment]
@williamfgc Thanks for the clarification. I've attached the cmake output here. 
[cmake_output.txt](https://github.com/ornladios/ADIOS2/files/2906489/cmake_output.txt)

**Comment by williamfgc** [comment]
@swsachith thanks! Seems that Python dependencies are found (including mpi4py) by cmake, do you still get the same error after installing `mpi4py`?  the hello example might be broken (apologies for that). Please look under testing: https://github.com/ornladios/ADIOS2/tree/master/testing/adios2/bindings/python  for things running in our CI

**Comment by swsachith** [comment]
@williamfgc Actually this is after building mpi4py and with Python options again after your feedback. I will do the build process and update the thread.

**Comment by swsachith** [comment]
@williamfgc the example builds now. Thanks for the feedback. 
I then ran into the issue:  #1233 will fix the code as mentioned in the ticket and run the example.

**Comment by williamfgc** [comment]
@swsachith great, thanks!
