### ISSUE TITLE
Cannot read a BP file

### ISSUE THREAD

**Issue by bsmind** [ornladios/ADIOS2#1239]
I tried to open a BP file that was able to open with adios 1.13.1 version.
I installed the adios2 by following the instruction in adiosvm repository and passed all tests that comes with adios2 package. 

First, I tried to dump the contents using bpls command that comes with adios2.
And it gave me the following errors:
```
HDF5-DIAG: Error detected in HDF5 (1.8.17) MPI-process 0:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
HDF5-DIAG: Error detected in HDF5 (1.8.17) MPI-process 0:
  #000: H5O.c line 607 in H5Oget_info(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.17) MPI-process 0:
  #000: H5G.c line 454 in H5Gopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
Error: Could not open this file with any ADIOS2 file reading engines
```
I also tried to open the file in python
```
import adios2
from mpi4py import MPI
comm = MPI.COMM_WORLD
adios = adios2.ADIOS(comm)
ioReader = ioReader.Open("tau-metrics.bp", adios2.Mode.Read)
adios.RemoveAllIOs()
```
and it returns the following error messages:
```
Traceback (most recent call last):
  File "/home/sungsooha/Desktop/CODAR/PerformanceAnalysis/script.py", line 13, in <module>
    reader = ioReader.Open("./data/nwchem/20180801/tau-metrics.bp", adios2.Mode.Read)
ValueError: ERROR: ADIOS2 default BP3 engine doesn't support count statistics
```

Any suggestions?
[tau-metrics.bp.zip](https://github.com/ornladios/ADIOS2/files/2911336/tau-metrics.bp.zip)

**Comment by williamfgc** [comment]
@bsmind was this file generated with adios1? If so, we find very rare case that use `count statistics` as the exception says, so special files are not supported. There is 2 options:
1) Stick with adios1.
2) Migrate your writer workflow to adios2 (adios1 can read those files).

Since 2) can be a hassle and I am not familiar with your workflow, I'd stick with adios1 for now, but 2) would pay-off in the long run and that's what we are currently maintaining. Hope this helps, and sorry you encountered one of those corner cases we are not covering in adios2.

**Comment by bsmind** [comment]
@williamfgc Yes, the file was generated with adios1. Thank for the quick response with detailed information.

**Comment by williamfgc** [comment]
@bsmind hang on. Let me re-open this ticket as it might be a quick fix inside adios2 that I am testing now with what you sent. I need more info from you: does this file `tau-metrics.bp` has a companion `tau-metrics.bp.0`?

**Comment by williamfgc** [comment]
@bsmind can you try again with the latest master? Please make sure the 
`tau-metrics.bp.dir` is accessible

**Comment by bsmind** [comment]
@williamfgc Thank for the update. Now, I can read the bp file written with adios1 from adios2. However, I got 60 failures when I run `ctest`. The failures happen with tests that include 'Dump' and 'Validate' keyword. I share the log files I got here.  Are these expected failures?

[CTestCostData.txt](https://github.com/ornladios/ADIOS2/files/2916716/CTestCostData.txt)
[LastTest.log](https://github.com/ornladios/ADIOS2/files/2916717/LastTest.log)
[LastTestsFailed.log](https://github.com/ornladios/ADIOS2/files/2916718/LastTestsFailed.log)

**Comment by williamfgc** [comment]
@bsmind long shot: do you have another adios2 installation? Also, check LD_LIBRARY_PATH is not pointing at another location. You can rerun ctest with `ctest -VV -R HeatTransfer` as see the failure. Please open another ticket and close this one (I assumed is solved) if the problem persist. Thanks!

**Comment by bsmind** [comment]
@williamfgc my bad. It was conflicted with the previous installation. No failures. Thanks!
