### ISSUE TITLE
allow assert in python tests?

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1248]
In #1247, I'm hitting an issue where I added some tests that verify that I'm getting the expected result using the `assert` statement in Python. That's how it's commonly done in Python, in fact that's how `pytest` is doing it.

I looked in another python test, and the method currently used there appears to be
```python
if(attrStringData[0] != "one"):
    raise ValueError('attrStringData[0] failed')
```
which will work, but it's more code to write and less explicit when it actually fails, compared to
```python
assert attrStringData[0] == "one"
```
It looks like it's an easy change to have codacy accept `assert` use: https://github.com/heilaaks/snippy/commit/c8bfa51f64f0161572b43a2f726133b148e12c97

**Comment by williamfgc** [comment]
Hey @chuckatkins , can you take a look at this? I'd rather have you touch Codacy based on a recent issue with our accounts. Overall, this Codacy issue is the reason why I moved away with assert on Python, but we use assert heavily in google-test for the C++ and C bindings. It's not a bad thing to enable.

**Comment by germasch** [comment]
I'd be happy to close this, as the PR has been merged and nothing bad happened...
