### ISSUE TITLE
ClipContiguousMemory called for char* not template types T* 

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1255]
This is a follow-up from #1254, where looking at that more, I think it points to something fishy, but I can't tell whether it's an issue that can be hit in real life.

`helper::ClipContiguousMemory` gets instantiated for `std::string` when it's used from `BP3Deserializer` (and BP4), I believe in two places: In `ClipMemory` and in `PostDataRead`.

`helper::ClipContiguousMemory` does an `reinterpret_cast<char*>` on its `T* dest` argument, and then calls `CopyContiguousMemory` (`adiosMemory.inl`)
```cxx
            char *rawVariableData = reinterpret_cast<char *>(dest);

            CopyContiguousMemory(contiguousMemory + contiguousStart, stride,
                                 rawVariableData + variableStart,
                                 endianReverse);
```
The cast of a `std::string *` to a `char *` and then operating on the raw memory is highly likely broken, as obviously `std::string` is not a POD type. I only know that this gets instantiated, though, not that it ever actually gets called.

Second, and more generally (not specific to std::string), the `endianReverse` arg in the call above won't work for any type, since the info on the actual type has been eliminated by casting to `char *`, so `CopyContiguousMemory` will think it's `char` data and (I suppose) not reorder anything.

**Comment by williamfgc** [comment]
@germasch in BP3 and BP4 Serializer/Deserializer there is usually a specialization for the string type. Currently, those functions don't have it, but the declaration should include the `std::string` type to allow for future specializations.  About your second point, that's clearly a bug from a previous piece of commented out code, we just haven' t implemented a way to test endian interoperability, yet.

**Comment by germasch** [comment]
By the way, did you consider getting rid of ADIOS2_USE_Endian_Reverse (ie, turn it on always)? Unless there is a good reason to want to turn it off (performance?), it would reduce complexity and make it easier to test endian conversions. And it prevents the case where users are given a other-endian .bp file and find out that their ADIOS2 installation doesn't support endian conversion. For someone building their own ADIOS2, it's easy to turn on the option, but for preinstalled versions, it's much more hassle to get those updated.

**Comment by williamfgc** [comment]
@germasch that's a system admin/installer problem, not an adios2 issue per-se.
