### ISSUE TITLE
Update removed heatSimulation usage in ADIOS2 docs

### ISSUE THREAD

**Issue by HaochengLIU** [ornladios/ADIOS2#1277]
Hi, I'm working on implementing an ADIOS2 reader in VTK right now and trying to catch up with the new adios2 features. However, the [heatSimulation example](https://adios2.readthedocs.io/en/latest/utilities/utilities.html) seems to have been removed. 

Meanwhile, may I ask is there any other ways for me to generate some sample bp files for testing?

**Comment by williamfgc** [comment]
@HaochengLIU It's under `ADIOS2/examples/heatTransfer` . All tests get generated under `build/bin` , if running `ctest` from `build/` look under `build/testing` for generated bp files.

**Comment by HaochengLIU** [comment]
@williamfgc Hi William, thanks for the bp file info. 

Meanwhile, this issue is about that executable `heatSimulation`. I can not find it in my build dir. May I missing something here?

**Comment by williamfgc** [comment]
@HaochengLIU look for `build/bin/heatTransfer_*`

**Comment by HaochengLIU** [comment]
@williamfgc I am aware of the `buildbin/headTransfer_*` executables. However the [doc](https://adios2.readthedocs.io/en/latest/utilities/utilities.html) leads to `heatSimulation` and `heatAnalysis`. This is what missing in ADIOS2.

**Comment by williamfgc** [comment]
@HaochengLIU that's the one used in tutorials from another repo: https://github.com/pnorbert/adiosvm/tree/master/Tutorial/heat2d

**Comment by dpugmire** [comment]
Hi,
I have an ADIOS2 reader in VisIt. Can you describe what you are doing? We
likely have code for doing what you are trying to do.

Thanks,
Dave

**Comment by HaochengLIU** [comment]
@dpugmire Hi Dave, my initial goal is to add a vtk module for reading the ADIOS2 bp format data. I plan to attack 3d array first(to vtkImageData) then handling vtkUnstructuredGrid. If you are interested I can ping you once my branch is ready for review. I assume you are using the same account for vtk-m on gitlab?
