### ISSUE TITLE
std::map is "expensive"

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#1284]
When exposing attributes and variables, we probably shouldn't use `std::map` (red-black tree, logarithmic complexity) but at least `std::unordered_map` (buckets, average constant-time complexity) for efficiency.

Note that Python's `dict{}` returned in the Python API is also an unordered map.

**Comment by williamfgc** [comment]
@ax3l do we have numbers/metrics to back up this claim? When do we see the trade-off of higher memory (unordered_map) vs. performance for specific adios2 related applications. Bounds are theoretical anyways and depend on data, unordered_map O(1)-O(N) vs map log(N). My experience is that N has to be extremely large to see any noticeable difference, but the memory is always larger with unordered_map. 

Also, `std::map` has the implicit advantage of being sorted and doesn't invalidate iterators. It's also the better alternative if you're iterating in a sorted way (which is pretty common and human-readable when searching for variable names). Only if this is a real bottleneck for apps we should take a look at this.

As for Python `dict` is more widely adopted key/value container, and I wouldn't worry about mixing Python and performance.

**Comment by ax3l** [comment]
Sorry, I might have been to brief in the issue description: I noted that the C++ interface uses a sorted map while the python interface does not. I heard recently you have users with 10th-100th of thousands of variables, so I was wondering if it's worth taking a look.

I am not one of those, sorry for the noise and thanks for the info! :)

**Comment by williamfgc** [comment]
@ax3l no problem, thanks for bringing this up. I thought it was causing an issue. Now, if you see something, please say something. It's always good to push the limits on the library facilities from the scope of the application.
