### ISSUE TITLE
Generic handling of varying length variables

### ISSUE THREAD

**Issue by tobiasrau** [ornladios/ADIOS2#1288]
Hello,

I'm having problems with variables of varying length for each time step. I found #1245, but the solution presented there would require me to write the dimension of each variable as variable and when reading a variable I first have to find the dimension variable of my variable.
I'm not sure if this is the intended way to handle this situation.
At the moment I'm using the "Shape" entery of the variables to read it. This however results in the same error presented in #1245.

Would be nice if there is a solution without having me to create those extra variables.
If there is not, I would like to request this as a feature.

Thanks,
Tobias

**Comment by williamfgc** [comment]
Hi @tobiasrau, can you show a minimal reproducible example of what you're trying to achieve. #1245 addresses ChangingShape for a variable using SetSelection at write. Are you seeing a bug at read when requesting the variable? Correct if I am wrong in my assumption, but you can't use SetShape at read, the shape is what it is when the variable was written.

**Comment by tobiasrau** [comment]
Hello @williamfgc, thank you for your answer. This is not exactly what I'm looking for. Maybe I should reformulate my question:
How can I get the available shape dimension of my current time step?

Here is my simplified wrong way for 1D arrays.
    
    ...
    auto variables = io->AvailableVariables();
    for (auto var: variables)
    {
        size_t num = std::stio(var.second["Shape"]);    //<- This only gives global Shape
        if (var.second["Type"] == "float")
        {
            adios2::Variable<float> advar = io->InquireVariable<float>(var.first);
            advar.SetSelection({{0}, {num}});
            reader.Get<float>(advar, tmp_vec);
        }
    }
    ...

**Comment by williamfgc** [comment]
@tobiasrau thanks for the snippet. Yeah, you found a bug in AvailableVariables carrying the Shape. Please use the Shape() function instead. Are you using BeginStep and EndStep, BTW?

```
...
reader.BeginStep();

auto variables = io->AvailableVariables();
for (auto var: variables)
{
    // size_t num = std::stio(var.second["Shape"]);    //<- Bug
    if (var.second["Type"] == "float")
    {
        adios2::Variable<float> advar = io->InquireVariable<float>(var.first);
        adios2::Dims shape = var.Shape();
        advar.SetSelection({{0}, {num}});
        reader.Get<float>(advar, tmp_vec);
    }
      ...
      reader.EndStep();
}
...
```
Let me know if this works.

**Comment by tobiasrau** [comment]
Hello @williamfgc, thank you for that hint. Yes, I am using `BeginStep` and `EndStep`, but didn't include them to the snippet. I found out, that 

    advar.Shape()
    advar.Count()
    advar.SelectionSize()

are all returning the global shape. So those values are not helping me.
The solution to my particular problem was using the `BlocksInfo` of the reader.
So here is the working snippet

    ...
    reader.BeginStep();
    auto variables = io->AvailableVariables();
    for (auto var: variables)
    {
        if (var.second["Type"] == "float")
        {
            adios2::Variable<float> advar = io->InquireVariable<float>(var.first);
            auto info = reader.BlocksInfo(advar, currentTimeStep);
            auto num = info[0].Count[0];
            advar.SetSelection({{0}, {num}});
            ...
            reader.Get<float>(advar, tmp_vec);
        }
    }
    reader.EndStep();
    ...

Thank you again for your suggestions.

**Comment by williamfgc** [comment]
@tobiasrau sorry I wasn't clear, I meant using `var.Shape()` within the `BeginStep()/EndStep()` block. But it's great BlocksInfo worked for you (which is exactly how it's meant to be used). Thanks!

**Comment by tobiasrau** [comment]
Hello @williamfgc , `var.Shape()` didn't work at all. Just `advar.Shape()` was compiling. Yes, I used `advar.Shape()` inside the `BeginStep()/EndStep()` block. However, this returned only the global shape and not the shape of the actual time step.

**Comment by williamfgc** [comment]
@tobiasrau my bad, I meant `var.Shape()` as a generic member function, but you got the idea. Let me try to reproduce. In the meantime, please check that we already have a working test covering this scenario which might help you: https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/engine/bp/TestBPChangingShape.cpp 
BTW, are you using the latest master?

**Comment by tobiasrau** [comment]
Hello @williamfgc, I thought I was using the master branch, but it actually was 2.3.0. Sorry for the confusion. So I guess this should just work now.
