### ISSUE TITLE
Two more span related bugs

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1295]
I know it may look like I'm just poking holes in the code. But actually, I spent some time earlier implementing my proposed solution for multi-block buffered I/O and that's just what I saw along the way.

In #1293, I added another commit, which adds three tests for the current span stuff. The first one works. The 2nd one actually fails immediately:
```
[ RUN      ] ADIOS2_CXX11_API_IO.MultiBlockPutZeroCopySync2
unknown file: Failure
C++ exception with description "ERROR: units 50 not supported in call to BytesFactor
" thrown in the test body.
[  FAILED  ] ADIOS2_CXX11_API_IO.MultiBlockPutZeroCopySync2 (1 ms)
```

The third one may now be fixed with @williamfgc's latest patch, but for now I get this as output:
```
[kai@macbook build (pr/bug)]$ bin/bpls -dD multi0_sync3.bp
  double   var   {10}
        step 0:
          block 0: [0:4]
    (0)    5 6 7 8 9
          block 1: [0:4]
    (0)    5 6 7 8 9
```

**Comment by williamfgc** [comment]
@germasch not sure if they are span related, the first is clear, you're missing the units in your input. The second is realted to the Def/Sync pattern as you pointed out.

**Comment by williamfgc** [comment]
The more tests the better, thanks!

**Comment by germasch** [comment]
The first one is kinda my bad, I was looking to get a failure, and I did get a failure, and I didn't really look at what was wrong with it. That being said, the unit conversion thing is buggy, too, so I'll open another issue for that. The 2nd bug appears to be still alive after your fix, so I'll keep this open for that one.

**Comment by williamfgc** [comment]
@germasch is the 3rd one fixed?

**Comment by germasch** [comment]
I believe the `multi0_sync3.bp` one is still there. You can merge #1293, I commented that case out so that is passes the CI. If you enable it, you should get the failure.
.

**Comment by williamfgc** [comment]
@germasch OK, thanks!

**Comment by germasch** [comment]
Just started looking at this one, and actually there's no problem here, other than a bug in my test :( Sorry about that.

(The broken test is commented out in its merged form, so no harm right now. I'll submit a PR to fix it, though.)
