### ISSUE TITLE
Another data corruption bug

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1304]
The test for it is added in PR #1303 . It does't trigger for small data sizes, but changing the data size from 10 to 10000 in MultiBlockPutZeroCopySync3 will lead to an output file with incorrect data -- running the test on a single proc is enough to show the problem.

**Comment by germasch** [comment]
By the way, even though I think that should be pretty obvious, I know of course where those bugs are that I've lately posted here, because I see the bug first and write the test 2nd, for the most part. So feel free to ask if you don't want to have the fun of debugging yourself. (Even though I think I make that fairly straight forward by posting the small isolated tests that show the bug.)

**Comment by williamfgc** [comment]
I can't get a hold of the debugger right now, I will get to this in a couple of days.

**Comment by germasch** [comment]
You got it, the buffer gets resized and the span pointer that already has been handed to the app is invalidated. Silently corrupting the user's data isn't the best choice how to handle this, though.

> Span pointers should be updated dynamically with span.data(), just like any STL vector.data() to avoid iterator invalidation.

You might not have guessed it, but I happen to be familiar with iterator invalidation. My testing code doesn't, however, do anything that invalidates iterators (in fact, with std::span, that's impossible.) What I totally don't understand is what I should do with `span.data()` to fix this? (Okay, so let me be more explicit: No amount of calling `span.data()` is going to fix this.)

Fixing the underlying problem is hard, ie., after you hand out pointers, you can't safely grow your buffer. So you can declare this to be a limitation of the prealloc approach -- I'd consider that reasonable (though not particularly desirable). However, silent data corruption isn't acceptable in my book, so I think the solution is to throw an exception, which will likely kill the app, but that's still better than silent corruption.

FWIW, thinking about it, it doesn't require my somewhat convoluted example to create this problem. In fact taking the rather straightforward ` MultiBlockPutZeroCopySync` case will show the very same problem (for larger data sizes).

**Comment by williamfgc** [comment]
`in fact, with std::span, that's impossible`

It is not std::span per-se, is the fact that you assign the span pointer to another pointer before resizing the data, then resizing and not updating it. This is no different from iterator invalidation rules in std::vector::data() and they don't throw an exception for it, we are just following C++ convention (good or bad, not sure).

**Comment by germasch** [comment]
> > in fact, with std::span, that's impossible
> 
> It is not std::span per-se, is the fact that you assign the span pointer to another pointer before resizing the data, then resizing and not updating the then static external (to adios2) pointer. This is no different from iterator invalidation rules in std::vector::data() and they don't throw an exception for it, we are just following C++ convention (good or bad, not sure, we just have to deal with it).

It really doesn't matter that I assign the span pointer, if I were using the span directly, the same thing would happen -- a span doesn't magically update its data member. If adios2 was actually returning a reference to an internal object, then in theory, it could update the span under me, but actually that still wouldn't solve the problem. I'm not resizing anything -- adios2 is internally doing so, but how am I suppose to know that, and when it does so?

> You can assign the external (to adios2) pointer again after Put in sync mode using span.data(). But again, I can't confirm as I don't have access to a debugger right now, so it's OK to keep this open.

Nope, It doesn't need a debugger considering that Put() returns a span by value, there is no way span.data() will ever change.

> BTW, this is not silent at all. Anyone working with libraries has to be aware of the memory contracts of each API function.

Two points:
* Yes, it is silent.
* If one is violating memory contracts, it's perfectly acceptable to get undefined behavior, which includes silent corruption. However, I'd really like to know which memory contract I'm violating.

It may seem easy to just blame the user, but hey, you know hat's not true, because you even tried to handle it:
```cxx
    if (m_DebugMode && resizeResult == format::BP3Base::ResizeResult::Flush)
    {
        throw std::invalid_argument(
            "ERROR: returning a Span can't trigger "
            "buffer reallocation in BP3 engine, remove "
            "MaxBufferSize parameter, in call to Put\n");
    }

```
However, you're not handling the correct case(s).

**Comment by williamfgc** [comment]
> Nope, It doesn't need a debugger considering that Put() returns a span by value, there is no way span.data() will ever change.

span.data() in fact can change as it's pointing to some vector location address: https://stackoverflow.com/questions/1624803/does-resizing-a%20-vector-invalidate-iterators

Put in sync mode makes that change in the default engine. This is what I mean I need to add documentation.

**Comment by williamfgc** [comment]
> It may seem easy to just blame the user, but hey, you know hat's not true, because you even tried to handle it:

This simply misleading. resizeResult flush is only triggered when a MaxBufferSize is set, not in a default Put in sync mode case. It's actually very clear, flush means something different.

**Comment by williamfgc** [comment]
> Yes, it is silent.

It is silent the minute you handle span.data() to another pointer as adios2 doesn't know anything about an external pointer. adios2 can only track things correctly and avoid iterator invalidation if you use span.data() directly everytime you need access to an adios2 internal pointer.

**Comment by germasch** [comment]
> > It may seem easy to just blame the user, but hey, you know hat's not true, because you even tried to handle it:
> 
> This simply misleading. resizeResult flush is only triggered when a MaxBufferSize is set, not in a default Put in sync mode case. It's actually very clear, flush means something different.

I'm sorry, I was in fact wrong with respect to how I thought  your Span worked.  For its actual implementation, you're right, me storing the data pointer in MyDataView is the reason that things break on an internal ADIOS2 resize. So for what it does, the code is correct.

So if you document the behavior as-is, that's a choice to provide some kind of interface. The reason that I got confused is that I expected that your `Span<T>` behaves like `std::span<T>` from C++20, as you had advertised it.  `std::span` is just a non-owning pointer and a size, which will never change on you. Since you're using the name `Span`, I expected the same to be true for this interface, ie., it'd return a 'pinned' (not in the virtual memory sense) buffer that I can use just like something I malloc'd or new[]'d.

So I was wrong, there is consistent (and correctly implemented) behavior behind it.

I have some thoughts, though:
* Needs documentation that `Span` doesn't behave like `std::span` because `data()` of your Span can change under you in certain circumstances (which ones?)
* `span.begin() + 10` doesn't work (minor, wrong choice of iterator category).
* In case you care, this interface will never be thread-safe.
* Span doesn't behave like any of the STL containers. (Fundamentally, that's okay, one can have one's own data structures with their own semantics). STL containers invalidate iterators when you perform certain actions on the container (e.g., if you resize() a std::vector, iterators into it may become invalid). Invalidation always happens because the library user performs a certain action on a particular container, then iterators for that particular container are invalidated. There's nothing like "I'm creating a second std::vector, that may cause iterators into my first std::vector to be invalidated". That'd make std::vector just about useless.

A somewhat related point:
```cxx
    var.SetSelection(myData.selection(0));
    auto span0 = engine.Put(var);
    var.SetSelection(myData.selection(1));
    auto span1 = engine.Put(var);

    std::iota(span0.begin(), span1.end(), 0);
    std::iota(span1.begin(), span1.end(), m_Nx/2);
    engine.Close()
```
looks zero-copy, but there is a copy occurring in the 2nd `Put()` call. Correct semantics, but something to be aware of for users of this interface who really care about performance.

**Comment by williamfgc** [comment]
> Needs documentation that Span doesn't behave like std::span because data() of your Span can change under you in certain circumstances (which ones?)

Agree, I will get back to it by the end of the week. I rush into this to showcase the feature.

> Needs documentation that Span doesn't behave like std::span because data() of your Span can change under you in certain circumstances (which ones?)

You're right, it has a narrower scope depending on engine. It's a span<T> that points at a `std::vector<char>` in the default engine, for a future shared_memory engine I'd expect this to point to a `char*`, for which iterator invalidation rules apply for the case you're showing the effect of resizing with Put in sync mode. 

> In case you care, this interface will never be thread-safe.

That's a good point, we either put a mutex around resize (I don't know if there are any gainings in running the very serial buffering operation). That was actually the motivation for adding the bufferID parameter, since passing different bufferIDs would mean that each thread can "own" each buffer making it effectively "thread-safe".

> Correct semantics, but something to be aware of for users of this interface who really care about performance.

True, this could be a good research topic since  measurement would reveal the trade-offs.

**Comment by germasch** [comment]
> > Needs documentation that Span doesn't behave like std::span because data() of your Span can change under you in certain circumstances (which ones?)
> 
> Agree, I will get back to it by the end of the week. I rush into this to showcase the feature.

FWW, I don't have an issue with documentation not being worked out yet, new features need their shake-out period, anyway. I do think the "Span" name is misleading, but I already know we don't tend to agree on naming issues.

> > Needs documentation that Span doesn't behave like std::span because data() of your Span can change under you in certain circumstances (which ones?)
> 
> You're right, it has a narrower scope depending on engine. It's a span that points at a `std::vector<char>` in the default engine, for a future shared_memory engine I'd expect this to point to a `char*`, for which iterator invalidation rules apply for the case you're showing the effect of resizing with Put in sync mode.

I'm not sure I'm following this. As a user, I don't really want to care whether I get a pointer into a std::vector or some shared memory segment. I do want to know when it's safe to use the pointer, and under which circumstances it might change.

> > In case you care, this interface will never be thread-safe.
> 
> That's a good point, we either put a mutex around resize (I don't know if there are any gainings in running the very serial buffering operation). That was actually the motivation for adding the bufferID parameter, since passing different bufferIDs would mean that each thread can "own" each buffer making it effectively "thread-safe".

I don't see how a mutex internal to adios2 is going to fix this. One thread in the user code might be writing to the span.data() memory while another thread is doing a Put(var, ..., Sync) or a Put(var) which are causing a buffer resize. A mutex inside adios2 isn't going to prevent the user thread from writing to memory that is disappearing under it.

What are the semantics for blockID going to be? If it is "here's a buffer with a given id that isn't going to be used / resized / whatever by any other thread", that means that the engine internally has to manage a set of buffers, rather than the current single one (in BP3). That'd be good, because it wouldn't be as fragile to use as the current approach. But if you do go the way of changing the engine's internal memory management, you're basically at the point where you can always provide Spans that are safe to use (won't change under you). At which point you should just always do it, blockID or not?

**Comment by williamfgc** [comment]
@germasch is this issue resolved? Those are valid points above that are probably part of a much larger conversation that would include finding a use case. Please go ahead and close this issue if is in fact resolved. Thanks.

**Comment by germasch** [comment]
I believe the part about span.data() changing under the user falls into "works as designed" -- It makes it impossible to use a View-like data structure of the kind I introduced in the test, though.

However, from looking at the code, there is still an issue of a DoFlush being triggered by a PutSync while there outstanding Spans. Or do you want me to open another issue for that?

**Comment by williamfgc** [comment]
> However, from looking at the code, there is still an issue of a DoFlush being triggered by a PutSync while there outstanding Spans. Or do you want me to open another issue for that?

Yes, please.

**Comment by germasch** [comment]
Opened #1309, closing this for now.
