### ISSUE TITLE
DataMan example for callback function

### ISSUE THREAD

**Issue by disheng222** [ornladios/ADIOS2#1335]
Hi, 
We want to explore the callback functions in ADIOS2. I have installed the package with DataMan option on. I can find DataManCallbackReceiver in the bin/ directory, but don't find the corresponding sender executable or examples.

Any suggestions on this? 
Thanks.

Best,
Sheng

**Comment by JasonRuonanWang** [comment]
The callbacks were some of the early attempts of DataMan which were later deprecated in favor of the ADIOS2 standard write read API.
