### ISSUE TITLE
Build Issue "‘const void*’ to ‘void*’ [-fpermissive]"

### ISSUE THREAD

**Issue by tneuroth** [ornladios/ADIOS2#1354]
from https://github.com/ornladios/adios2.git source as of this morning.

Compiling with gcc 4.9 

`source/adios2/engine/insitumpi/InSituMPIReader.cpp:456:33: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
MPI_Isend(schedule.data(), ...`

I was able to fix it by changing to:

InSituMPIReader.cpp:456:33: `MPI_Isend( const_cast<void*>( reinterpret_cast<const void *>( schedule.data() ) ), ...`

**Comment by williamfgc** [comment]
@tneuroth I saw this with old MPI versions (the default on my Ubuntu 14), which doesn't comply with the standard (1st parameter should be `const void*` not `void*`). I don't think we go that far back in our CI and testing infrastructure. Would a more recent MPI be an option for you?

**Comment by tneuroth** [comment]
Hi William. It's no problem to update my MPI version. Thanks!
