### ISSUE TITLE
Tau undefined reference errors

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#1382]
I have built the latest adios master on Summit using the PGI 18.10 compiler. When I try to build an application with adios, I get the following error during the final link step:

```
/usr/bin/ld: warning: libtaustubs.so, needed by /ccs/proj/csc299/sw/ADIOS2-master-04.22.19/installation/pgi/18.10/lib64/libadios2.so, not found (try using -rpath or -rpath-link)
/ccs/proj/csc299/sw/ADIOS2-master-04.22.19/installation/pgi/18.10/lib64/libadios2_sst.so: undefined reference to `TauTimer_Start'
```

followed by more undefined reference errors.

Modules:
```
Currently Loaded Modules:
  1) hsi/5.0.2.p5
  2) xalt/1.1.3
  3) lsf-tools/2.0
  4) darshan-runtime/3.1.7
  5) DefApps
  6) cmake/3.13.4
  7) pgi/18.10
  8) spectrum-mpi/10.2.0.11-20190201
  9) cuda/9.2.148
 10) netcdf-fortran/4.4.4
```

**Comment by eisenhauer** [comment]
Hi Kshitij, can you please check to see if libtaustubs.so exists in /ccs/proj/csc299/sw/ADIOS2-master-04.22.19/installation/pgi/18.10/lib64/?  That might help narrow down if this is a problem with adios_config, or with the build, etc.

**Comment by kshitij-v-mehta** [comment]
libtaustubs.so exists in the installation directory. Also, manually specifying -ltaustubs on the link command fixes the issue.

**Comment by eisenhauer** [comment]
How are you linking the application?  Are you using adios-config?  If so, can you provide its output?

**Comment by kshitij-v-mehta** [comment]
I wasn't using adios2-config. I was manually providing all dependent libraries. Using adios2-config fixes the issue.
Thanks Greg.
