### ISSUE TITLE
Taustubs: Remove token output

### ISSUE THREAD

**Issue by sarats** [ornladios/ADIOS2#1388]
While running XGC, each rank prints the following in the log:
```
token: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-uwak6exr43zvhu2vasiddrov57baf37t/lib/libdarshan.so /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-18     .10/spectrum-mpi-10.2.0.11-20190201-fifj65soewhhhm6xhhzad3ilgp4hmgde/lib/libpami_cudahook.so
```

Debug messages left over from 
https://github.com/ornladios/ADIOS2/blob/806ed20de90f91e7d433f1c90937aa79f7d0f98a/source/adios2/toolkit/profiling/taustubs/tautimer.cpp#L111

This needs to be removed/commented out.

**Comment by jychoi-hpc** [comment]
I didn't know Sarat made this issue already. I made a duplicated one:
https://github.com/ornladios/ADIOS2/issues/1389

**Comment by jychoi-hpc** [comment]
I think this is fixed and the message is gone now.
