### ISSUE TITLE
"token:" message from libtaustubs.so

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1389]
https://github.com/ornladios/ADIOS2/blob/806ed20de90f91e7d433f1c90937aa79f7d0f98a/source/adios2/toolkit/profiling/taustubs/tautimer.cpp#L111

XGC people are reporting that they got "token:" message from stdout and found that it's from ADIOS (as above). I am wondering if there is any way to build Adios without creating or using "libtaustubs.so". 

Or, is there any way to supress "token:" message?

**Comment by khuck** [comment]
@jychoi-hpc yes, it can be compiled out, and I will remove the print statement too.

**Comment by jychoi-hpc** [comment]
Pushed a wrong button :)

@khuck thank you for the quick reply. If you let me know once you remote the print statement, I will rebuild ADIOS for XGC people.

I have another quick question: Will be there any performance implication if we build Adios with "libtaustubs.so" enabled?

**Comment by khuck** [comment]
@jychoi-hpc There is a non-zero performance implication, but it is very small.  I can entirely disable the timers by default, and push that change to the same branch.

**Comment by jychoi-hpc** [comment]
There is no more "token" messages.
