### ISSUE TITLE
Gray-scott does not build with static ADIOS2 installation with SZ

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#1405]
w4g@hp  ~/adiosvm/Tutorial/gray-scott/build   master ●  cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /opt/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /opt/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- The Fortran compiler identification is GNU 7.4.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZFP: /usr/local/lib/libzfp.so  
-- Found MGARD: /usr/local/lib/libmgard.so  
-- Found ZeroMQ: /usr/lib/x86_64-linux-gnu/libzmq.so (found version "4.2.5") 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /opt/phdf5/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.2") found components:  C 
-- Found atl: /opt/adios2/lib/cmake/adios2/thirdparty/atl-config.cmake (found suitable version "2.2.1", minimum required is "2.2.1") 
-- Found dill: /opt/adios2/lib/cmake/adios2/thirdparty/dill-config.cmake (found version "2.4.0") 
-- Found ffs: /opt/adios2/lib/cmake/adios2/thirdparty/ffs-config.cmake (found suitable version "1.6.0", minimum required is "1.6.0") 
-- Found enet: /opt/adios2/lib/cmake/adios2/thirdparty/enet-config.cmake (found suitable version "1.3.14", minimum required is "1.3.14") 
-- Found EVPath: /opt/adios2/lib/cmake/adios2/thirdparty/EVPathConfigCommon.cmake (found version "4.4.0") 
-- Found ADIOS2: /opt/adios2/lib/cmake/adios2/adios2-config.cmake (found version "2.3.1") 
-- Configuring done
CMake Error at CMakeLists.txt:13 (add_executable):
  Target "gray-scott" links to target "SZ::SZ" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:16 (add_executable):
  Target "pdf_calc" links to target "SZ::SZ" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/w4g/adiosvm/Tutorial/gray-scott/build
 ✘ w4g@hp  ~/adiosvm/Tutorial/gray-scott/build   master ● 

**Comment by chuckatkins** [comment]
This should be resolved now.
