### ISSUE TITLE
Endian_Reverse is broken in master

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#1414]
Reading a big-endian BP file on a little-endian machine gives garbage data. The array content is wrong, but variable names, array shapes and min/max are correct.

- [ADIOS2BPWriteReadAsStream2D2x4Test_be_dump.txt](https://github.com/ornladios/ADIOS2/files/3181061/ADIOS2BPWriteReadAsStream2D2x4Test_be_dump.txt): bpls dump of a big-endian BP file on a little-endian machine (broken)
- [ADIOS2BPWriteReadAsStream2D2x4Test_le_dump.txt](https://github.com/ornladios/ADIOS2/files/3181062/ADIOS2BPWriteReadAsStream2D2x4Test_le_dump.txt): bpls dump of a little-endian BP file on a little-endian machine (correct )

**Comment by williamfgc** [comment]
hi @keichi I am working on a patch in the next few days so you won't be stalled. This will require adding external testing so a future master branch won't break this.

**Comment by keichi** [comment]
Great, thanks! Let me know if you need big-endian files for testing. I've also found out a way to run ppc64 (BE) Debian on x86 using qemu-user and chroot, if that helps.

**Comment by williamfgc** [comment]
Hi @keichi thanks! I have a patch (running CI now) that I tested previous generated files. I will try to find some time to set up a repo where big-endian files can be added. That way at least we test this at least nightly. I will keep you posted. 

In the meantime, this patch should fix the currently broken Endian_Reverse support. BTW, set `ADIOS2_USE_Endian_Reverse=ON`explicitly when configuring adios2 with cmake. Thanks!

**Comment by keichi** [comment]
@williamfgc I've confirmed the fix, thanks!
