### ISSUE TITLE
ITER restart writing error on Summit 

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1433]
I am looking at the ITER restart writing error on Summit which Seung-Hoe is trying to run.

I found a case over the weekend in which I was able to reproduce the error consistently. 

One thing I found is that, it happens with aggregation and the common error message is like:
```
[b03n12:54694] *** An error occurred in MPI_Isend
[b03n12:54694] *** reported by process [2154496201,1220]
[b03n12:54694] *** on communicator MPI COMMUNICATOR 13 SPLIT FROM 12
[b03n12:54694] *** MPI_ERR_COUNT: invalid count argument
[b03n12:54694] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
```
which happened around the following code (MPIChain.cpp):
```
       helper::CheckMPIReturn(
            MPI_Isend(sendBuffer.m_Buffer.data(),
                      static_cast<int>(sendBuffer.m_Position), MPI_CHAR,
                      m_Rank - 1, 1, m_Comm, &requests[1]),
            ", aggregation Isend data at iteration " + std::to_string(step) +
                "\n");
```

I feel like there is a chance the count value in MPI_Isend (`static_cast<int>(sendBuffer.m_Position)` can be overflowed. Is there any logic to handle when the buffer position is larger than 2^31 (the limit of signed int)?

**Comment by williamfgc** [comment]
Thanks @jychoi-hpc , I will work on it

**Comment by williamfgc** [comment]
Hi @jychoi-hpc can you try the latest master? Please let me know. Thanks!

**Comment by jychoi-hpc** [comment]
Sorry, it's not working. I am getting an error. 

Here is a small case we can reproduce this error by using `adios_iotest`:

* Create `config.txt`:
```
<?xml version="1.0"?>
<!-- XGC Config XML file for ADIOS2 -->
<adios-config>
    <io name="restart">
        <engine type="BPFile">
            <parameter key="collectivemetadata" value="On"/>
            <parameter key="Profile" value="Off"/>
            <parameter key="SubStreams" value="1"/>
            <!--
            -->
        </engine>
    </io>
</adios-config> 
```
* Create `adios2cfg.xml`:
```
<?xml version="1.0"?>
<!-- XGC Config XML file for ADIOS2 -->
<adios-config>
    <io name="restart">
        <engine type="BPFile">
            <parameter key="collectivemetadata" value="On"/>
            <parameter key="Profile" value="Off"/>
            <!--
            <parameter key="SubStreams" value="1"/>
            -->
        </engine>
    </io>
</adios-config> 
```

* Execute the following command line:
```
mpirun -n 2 ./adios_iotest -a 1 -c config.txt -d 2 -w -x adios2cfg.xml
```

**Comment by pnorbert** [comment]
Can you provide the correct .txt file please. Right now it is the same as
the .xml file.

**Comment by jychoi-hpc** [comment]
Oops, sorry. I just updated my previous write.

**Comment by jychoi-hpc** [comment]
I just found my mistake in adios2cfg.xml and changed. Please make sure to set "SubStreams=1" to enable aggregation.

**Comment by williamfgc** [comment]
Hi @jychoi-hpc can this be marked as resolved? Let me know, thanks!

**Comment by jychoi-hpc** [comment]
My test worked but I haven't heard anything yet from PPPL people. I will reopen if I heard anything from PPPL people.
