### ISSUE TITLE
getparam() in fortran

### ISSUE THREAD

**Issue by guj** [ornladios/ADIOS2#1457]
Enable the getparam() in fortran So xml files can provide user app settings. Thanks.

**Comment by williamfgc** [comment]
@guj please let me know if this works for you.

**Comment by guj** [comment]
Hi William,

It works for me. This comes handy. Thanks!!

A side note, when user is using the xml file to configure,  do you think the adios2 declare_io() should only allow the IO names  in the configure file?  

- Junmin

**Comment by williamfgc** [comment]
@guj OK, thanks! 

 > A side note, when user is using the xml file to configure, do you think the adios2 declare_io() should only allow the IO names in the configure file?

The users should be able to enforce that restriction with `const bool inADIOS2ConfigFile = io.InConfigFile();` Some IO workflows might be static or their runtime parameters might come from other places (argv).

**Comment by guj** [comment]
I see. And looks like it is not in the fortran interface.  Not needed for now.  Thanks @williamfgc 

 - Junmin

**Comment by williamfgc** [comment]
@guj please, let's close this and open a new ticket, thanks!
