### ISSUE TITLE
"make install" fails on Summit when using XL compiler

### ISSUE THREAD

**Issue by lwan86** [ornladios/ADIOS2#1460]
I am trying to build the latest master of ADIOS on Summit using XL compiler. The "make" was successful, but when I ran "make install", the following cmake error occurred:

CMake Error in CMakeLists.txt:
  The compiler feature "cxx_auto_type" is not known to CXX compiler

  "XL"

  version 16.1.1.3.

Failed

**Comment by chuckatkins** [comment]
@lwan86 which version of CMake are you using?

**Comment by lwan86** [comment]
@chuckatkins I think I used the default one, which is 3.14.2

**Comment by chuckatkins** [comment]
@lwan86 I've been trying to reproduce this but haven't been able to yet.  What does the initial configure output look like?

**Comment by lwan86** [comment]
@chuckatkins The following is the initial configure output from cmake

ADIOS2 build configuration:
  ADIOS Version: 2.3.1
  C++ Compiler : GNU 4.8.5
    /usr/bin/c++

  Fortran Compiler : GNU 4.8.5
    /usr/bin/f95

  Installation prefix: /ccs/home/lwan86/adios2-master-summit/install-dir
        bin: bin
        lib: lib64
    include: include
      cmake: lib64/cmake/adios2

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: OFF
    Build Options:
      Blosc    : OFF
      BZip2    : OFF
      ZFP      : OFF
      SZ       : OFF
      MGARD    : OFF
      PNG      : OFF
      MPI      : ON
      DataMan  : OFF
      SSC      : OFF
      SST      : OFF
      ZeroMQ   : OFF
      HDF5     : OFF
      Python   : OFF
      Fortran  : ON
      SysVShMem: ON
      Profiling: ON
      Endian_Reverse: OFF

-- Configuring done
-- Generating done
-- Build files have been written to: /ccs/home/lwan86/adios2-master-summit/build

**Comment by lwan86** [comment]
@chuckatkins These are the loaded modules:

Currently Loaded Modules:
  1) xl/16.1.1-3   2) spectrum-mpi/10.3.0.0-20190419   3) hsi/5.0.2.p5   4) xalt/1.1.3   5) lsf-tools/2.0   6) darshan-runtime/3.1.7   7) DefApps   8) cmake/3.14.2

**Comment by chuckatkins** [comment]
It looks like there's a mismatch in the compilers used (the config summary shows the system gcc being used).  Try to export the `CC=xlc CXX=xlc++ FC=xlf` environment variables and then try again from a clean build directory.

**Comment by lwan86** [comment]
Just tried. It works.
