### ISSUE TITLE
Blosc Transform

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#1486]
Hi,

opening since I did not find an issue on it. Are we still planning to add a [blosc](https://github.com/Blosc/c-blosc) transform again to ADIOS2?

We are using it all the time in PIConGPU as parallel compressor (https://arxiv.org/abs/1706.00522) and like the modern methods it implements as a meta-compressor (e.g. zstd and bitshuffle pre-conditioners) as well.

I think to remember we talked last time if we want to implement (thread/OpenMP) parallelization of transformation steps in general.

**Comment by williamfgc** [comment]
@ax3l any particular blosc version being targeted?

**Comment by ax3l** [comment]
Just the latest and potentially the upcoming blosc2 api's (still experimental but will support accelerated ARM and PPC in the near future).

On June 12, 2019 9:59:51 PM GMT+02:00, William F Godoy <notifications@github.com> wrote:
>@ax3l any particular blosc version being targeted?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ornladios/ADIOS2/issues/1486#issuecomment-501433074

--
Sent from my smartphone.
Please excuse my brevity.

**Comment by williamfgc** [comment]
@ax3l just trying to squeeze blosc support into the upcoming release. Still there are a few issues that we haven't tested. See #1538

**Comment by chuckatkins** [comment]
@ax3l @williamfgc so can we close this as "fixed" for now and use new issues for problems and / or feature requests?

**Comment by williamfgc** [comment]
@chuckatkins I am fine either way, @ax3l your call.

**Comment by ax3l** [comment]
I would leave this open until the loop for >2GByte chunks is added as well. We did the same in ADIOS1 as I just checked: https://github.com/ornladios/ADIOS/pull/135 (credits to @psychocoderHPC)

**Comment by ax3l** [comment]
Just a note: `blosc2` released its first beta release: https://github.com/Blosc/c-blosc2/releases/tag/v2.0.0-beta.1

**Comment by williamfgc** [comment]
@ax3l thanks for sharing. Does `blosc2` support 64-bit data sizes or is still 32-bit (2Gb) max?

**Comment by ax3l** [comment]
Seams to be the same size yet, also since they try to be quite compatible for easy adoption:

https://github.com/Blosc/c-blosc/blob/v1.17.0/blosc/blosc.h#L42
https://github.com/Blosc/c-blosc2/blob/v2.0.0-beta.1/blosc/blosc2.h#L66

Just finished a Spack package for it and will submit it later on.

**Comment by psychocoderHPC** [comment]
@williamfgc In the old [issue](https://github.com/Blosc/c-blosc/issues/67), the developer said that `Blosc2` will support 64bit buffer but what @ax3l posted looks like that this is not the case.

I opened an issue to get a clear answer from the devs https://github.com/Blosc/c-blosc2/issues/72

**Comment by williamfgc** [comment]
@psychocoderHPC thanks, that would give us a clear picture. I know I've been pushing this for a while, but my understanding is that the real value of this effort is to support 64-bit sizes either at the adios2 level or the blosc level. We'll need to try and see which approach makes more sense for your efforts.

**Comment by ax3l** [comment]
Ok, looks like super-chunks are the way to go in c-blosc2 (example in the linked issue).

**Comment by ax3l** [comment]
Ok, looks like super-chunks are the way to go in c-blosc2 (example in the linked issue).

**Comment by ax3l** [comment]
We should also verify that we are able to read BP3 files with c-blosc and zstd transform in the ADIOS2 BP3-engine.

**Comment by ax3l** [comment]
[c-blosc2](https://github.com/Blosc/c-blosc2) has stable releases now :tada: and supports more hardware with intrinsics (ppc64le/altivec - Summit/Lassen/Sierra, arm/neon - Fugaku).

Shall we add this? :star_struck:

**Comment by psychocoderHPC** [comment]
> [c-blosc2](https://github.com/Blosc/c-blosc2) has stable releases now tada and supports more hardware with accelerated intrinsics (ppc64le/altivec - Summit/Lassen/Sierra, arm/neon - Fugaku).
> 
> Shall we add this? star_struck

I would like to see BLOSC2 support. The framing API in blosc 2 should make the implementation much easier compared to the self-written framing I used for blosc1 support.

**Comment by ax3l** [comment]
Closing this since c-blosc was implemented and in 2.9.0 replaced with c-blosc2.
