### ISSUE TITLE
Engine filename inconsistency...

### ISSUE THREAD

**Issue by eisenhauer** [ornladios/ADIOS2#1499]
Generally, I think that if you specify filename "X" to an engine in the writer-side Open() statement, you should also be able to specify "X" in the reader-side Open() statement and it should work.   That is, an Engine should consider itself free to add a file-type suffix upon file creation, but if it does, it should be transparent to the user in that it should also add it on the reader side (assuming that it isn't already present).  This isn't the way the BPfile engines work now.   I.E.

Writer.Open("Filename.bp");        /* creates a file named "Filename.bp" */
Writer.Close();
Reader.Open("Filename.bp");        /* works.  finds a file named "Filename.bp" */

Writer.Open("Filename");         /* automatically adds suffix .bp, creating "Filename.bp" */
Writer.Close();
Reader.Open("Filename");      /* fails to find Filename.bp */

So what's happening is that ADIOS2 is automatically adding the postfix on the writer side *if it isn't already present*, but not doing the same thing on the reader side.  This makes it more awkward to switch engines because the reader code has to change.

Demonstrate by removing the ".bp" suffix from all the filenames in any BP test...

**Comment by williamfgc** [comment]
This has a reason, Writers can only write `*.bp` file sets, while Readers can read `*.bp` or subfiles `*.bp.rank`, so readers must be specific in the name. My understanding is that this was settled a while ago, workflows should be able to manipulate strings very easily.

**Comment by eisenhauer** [comment]
Fixed with PR 1503.
