### ISSUE TITLE
add inConfigFile option to declareIO in fortran 

### ISSUE THREAD

**Issue by guj** [ornladios/ADIOS2#1500]
Would be nice to have in Fortran: 

When initiating adios2  from xml config, 
the declare_io function should make sure IO names are in the config file. 
(or have a way to check)

**Comment by williamfgc** [comment]
@guj I remember why it's not there. There is no way in currently no xml file tests with Fortran, we use some symbols that CMake defines that C++ can find. Let me tests outside, this should be a simple wrapper. Thanks!

**Comment by guj** [comment]
OK shall I close this issue?

**Comment by williamfgc** [comment]
@guj no, I will add it, let's keep this open

**Comment by chuckatkins** [comment]
@williamfgc Can this be closed now?
