### ISSUE TITLE
2.4.0-rc2?

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#1533]
Hi,

are you planning to tag a `2.4.0-rc2` version before the release?

Currently, the `master` works for our downstream efforts (cc @franzpoeschel ) and a further release candidate would help us integrating it in CI already.

**Comment by germasch** [comment]
And if you do, it'd be nice if you could merge my PR #1480 first, because that completes the MPI/serial unification that's new to 2.4.0.

**Comment by williamfgc** [comment]
@ax3l sorry for the late reply, we are in the process of adding last minute features to meet our deadlines. There is a [release branch](https://github.com/ornladios/ADIOS2/tree/release) @chuckatkins just put out. You can use that branch for further testing, we are fixing bugs until 2.4 is released at the end of this week. Thanks.

**Comment by williamfgc** [comment]
@germasch #1480 was merged, thanks!

**Comment by chuckatkins** [comment]
@ax3l, we don't plan on having an additional RC between now and the release.  With the release branch just pushed we will only be adding bug fixes, testing, documentation (also any existing PRs currently in flight).
