### ISSUE TITLE
Unfriendly error message when removing `.bp` file from directory context.

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#1539]
I have the following code:

```cpp
#include <iostream>
#include <vector>
#include <string>
#include <adios2.h>

int main(int argc, char** argv) {
  if (argc <= 1) {
    std::cerr << "Usage: ./profile_memory foo.bp [variablename]\n";
    return 1;
  }

  const std::size_t Nx = 10;
  std::vector<double> myFloats(Nx, std::numeric_limits<double>::quiet_NaN());

  adios2::ADIOS adios(adios2::DebugON);
  adios2::IO bpIO = adios.DeclareIO("ReadBP");
  adios2::Engine bpReader = bpIO.Open(std::string(argv[1]), adios2::Mode::Read);
  std::string variable_name = "T";
  if (argc == 3) {
    variable_name = argv[2];
  }
  adios2::Variable<double> bpFloats = bpIO.InquireVariable<double>(variable_name);

  if (bpFloats)
  {
    bpReader.Get<double>(bpFloats, myFloats, adios2::Mode::Sync);
  }
  else
  {
    std::cerr << "Could not find " << variable_name << " in file " << argv[1] << "\n";
    std::cerr << "Try ./profile_memory file.bp variable_name\n";
    return 1;
  }
  std::cout << "Floats = {";
  for (auto x : myFloats) {
    std::cout << x << ", ";
  }
  std::cout << "}\n";

  bpReader.Close();
  return 0;
}
```

(Full working example [here](https://github.com/NAThompson/profile_memory).) 

Now, if I copy `ADIOS2/bindings/Matlab/test/heat.bp` into my local directory, and run

```bash
$ ./profile_memory heat.bp
```

I get the error message:

```base
./profile_memory heat.bp
libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ERROR: couldn't open file heat.bp.dir/heat.bp.0, check permissions or path existence, in call to POSIX open
: unspecified iostream_category error
[1]    24585 abort      ./profile_memory heat.bp
```

I was unaware before hitting this that the `.bp` file is dependent on context; namely, I can't move a `.bp` around without potentially breaking it. Without this knowledge, the error message is not understandable. Can it be made more user-friendly?

For example:

```
.bp files do not exist independently of their directory context. Did you move the .bp file from the directory of its creation?
```

**Comment by williamfgc** [comment]
bp files access is valid without data SubFiles if data (basically calls to Get, or `bpls` with `-d`) is not requested. This information is reflected in the user guide. BP also reads a format from adios1.x that is a single file for data/metadata. I agree exceptions can be improved, but I would argue that the job of exceptions is to replace the user guide.

**Comment by williamfgc** [comment]
@NAThompson in that spirit, we can add comments to the examples explaining the BP file structure and citing the docs. That's something we don't do a good job or push hard enough due to the nature of our business. If you are willing to go the extra mile and make our examples more friendly to first time users, I will be happy to help.

**Comment by pnorbert** [comment]
Note that BP4 directories can be renamed and moved around without any
issue. So this is a temporary problem for BP3.

**Comment by chuckatkins** [comment]
@williamfgc @pnorbert @NAThompson are you guys okay with closing then since it's essentially a known issue inherent to bp3 (or did I misunderstand that)?

**Comment by williamfgc** [comment]
@chuckatkins you're correct, it's a design thing in bp3, moving into directories in bp4, it won't be an issue.

**Comment by NAThompson** [comment]
@williamfgc , @chuckatkins , I had no clue that a `.bp` file was even associated with a directory tree. That's independent of the `.bp` version, and I was hoping to submit a PR with an associated error message when the `.bp` file was moved.

**Comment by chuckatkins** [comment]
@williamfgc @NAThompson I'm happy to have this re-opened if there's a fix to be had.

**Comment by williamfgc** [comment]
@NAThompson [BP3 docs](https://adios2.readthedocs.io/en/latest/engines/engines.html#bp3-default)
