### ISSUE TITLE
Enable low-overhead portable JSON parser for config file

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#156]

**Comment by chuckatkins** [comment]
Just for context, we are currently using JSON for Modern C++ https://nlohmann.github.io/json/ which is a nice, compact, header-only library but seems to have compatibility issues with MSVC compilers.

**Comment by williamfgc** [comment]
@JasonRuonanWang told me he can stay away from json dependencies in DataMan

**Comment by JasonRuonanWang** [comment]
Just want to be clear. It's easy for me to replace the current JSON library with alternative JSON C++ implementations, but it's better to keep the JSON dependency, otherwise I would need to implement my own meta-data serialization method, which is a huge amount of work.

**Comment by JasonRuonanWang** [comment]
But I think the easiest way is to make DataMan optional, and document that it is only supported on Linux or Mac. I talked with @williamfgc the other day about this. At the end of the day, windows users probably will not use things like DataMan anyway. What they want to use is just open a BP file, take a look at the statistics, visualize data, etc. No one will run large scale data intensive workflows on Windows.

**Comment by JasonRuonanWang** [comment]
If you already found it a difficult problem, then I don't think there is an easy way for me to make it work either. But since you guys are looking at JSON config files anyway, I can use whatever JSON library you decide to use. Then we can remove the current JSON library.

**Comment by chuckatkins** [comment]
For whatever reason it was causing problems before, our current json library seems to work just fine now.
