### ISSUE TITLE
Static build for ADIOS2 on Summit: Enet not found error during installion

### ISSUE THREAD

**Issue by swatisgupta** [ornladios/ADIOS2#1565]
@eisenhauer 
Hi, 
   The static build for ADIOS2 failed to install on Summit after compilation - It fails to find Enet. I used GNU compilers version 6.4.0. The output from make install can be found below. 

make install
[  4%] Built target adios2sys_objects
[  6%] Built target atl
[ 11%] Built target dill
[ 21%] Built target ffs
[ 22%] Built target docs
[ 26%] Built target enet
[ 37%] Built target EVPath
[ 38%] Built target cmudp
[ 39%] Built target cmselect
[ 40%] Built target cmsockets
[ 41%] Built target cmenet
[ 42%] Built target cmmulticast
[ 43%] Built target cmib
[ 44%] Built target taustubs
[ 48%] Built target sst
[ 81%] Built target adios2
[ 82%] Built target sst_conn_tool
[ 84%] Built target adios_reorganize
[ 85%] Built target bpls
[ 88%] Built target adios_iotest
[100%] Built target adios2_f
Install the project...
-- Install configuration: "Release"
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/common/ADIOSConfig.h
Pre-installation cleanup of CMake files
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/CMakeFindDependencyMacro.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindBZip2.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindBlosc.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindCrayDRC.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindHDF5.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindLIBFABRIC.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindMGARD.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindMPI.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindPkgConfig.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindPythonFull.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindPythonModule.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindSZ.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindZFP.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/FindZeroMQ.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindBZip2.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindHDF5.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/fortranparam_mpi.f90.in
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/libver_mpi.c
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/libver_mpi.f90.in
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/mpiver.f90.in
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/test_mpi.c
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/test_mpi.cxx
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/test_mpi.f90.in
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindMPI/test_mpi_c.cxx
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/FindPkgConfig.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/GoogleTest.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/upstream/CMakeFindDependencyMacro.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_atl.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/atl-config.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/atl-config-version.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/atl-targets.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/atl-targets-release.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_dill.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/dill-config-common.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/dill-config-version.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/dill-config.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/dill-targets.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/dill-targets-release.cmake
-- Up-to-date: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindBinUtils.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindLibFFI.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_ffs.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/ffs-config.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/ffs-config-version.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/ffs-targets.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/ffs-targets-release.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_enet.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/enet-config.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/enet-config-version.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/enet-targets.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/enet-targets-release.cmake
-- Up-to-date: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindCERCSProject.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindIBVERBS.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindLIBFABRIC.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindNNTI.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindNVML.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/FindPkgConfig.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/upstream
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/upstream/FindPkgConfig.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_evpath.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_cmselect.so
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_cmsockets.so
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_cmudp.so
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_cmmulticast.so
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_cmenet.so
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_cmib.so
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/EVPathTargets.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/EVPathTargets-release.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/EVPathConfigCommon.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/EVPathConfigVersion.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/EVPathConfig.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/common/ADIOSMacros.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/common/ADIOSTypes.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/common/ADIOSTypes.inl
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libtaustubs.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/toolkit/sst/SSTConfig.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_sst.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/bin/sst_conn_tool
-- Installing: /ccs/home/ssinghal/ADIOS2-install/bin/bpls
-- Installing: /ccs/home/ssinghal/ADIOS2-install/bin/adios_reorganize
-- Installing: /ccs/home/ssinghal/ADIOS2-install/bin/adios_iotest
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/coupling2.xml
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/coupling2_blocking_01_simple.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/coupling2_blocking_02_dump_result.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/pipe2.xml
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/pipe2_01_simple.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/pipe2_02_link.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/pipe2_03_conditional.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/pipe2_04_nonblocking.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/pipe2_05_add_variables.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/wf_2_to_1.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/wf_2_to_1.xml
-- Installing: /ccs/home/ssinghal/ADIOS2-install/share/iotest-config/pipe2_06_busy.txt
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/libadios2_f.a
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_engine_begin_step_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_parameters_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_functions_allocate_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_io_open_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_io_define_attribute_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_operator_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_functions_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_attribute_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_adios_init_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_variable_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_variable_min_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_io_define_variable_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_attribute_data_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_engine_put_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_variable_max_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_engine_get_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_adios_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_io_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2_engine_mod.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/fortran/adios2.mod
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2_c.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/c/adios2_c_types.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/c/adios2_c_adios.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/c/adios2_c_io.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/c/adios2_c_variable.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/c/adios2_c_attribute.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/c/adios2_c_engine.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/c/adios2_c_operator.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/fstream/ADIOS2fstream.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/ADIOS.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/ADIOS.inl
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/IO.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/Variable.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/Attribute.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/Engine.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/Operator.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/include/adios2/cxx11/Types.h
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/adios2-config-version.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/adios2-config-common.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/adios2-targets.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/adios2-targets-release.cmake
-- Installing: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/adios2-config.cmake
/tmp/tmp.bSbXtooDsS ~/ADIOS2/build
Configuring adios2-config dummy CMake project
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpicc
-- Check for working C compiler: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpicxx
-- Check for working CXX compiler: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 6.4.0
-- Check for working Fortran compiler: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpif90
-- Check for working Fortran compiler: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpif90  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpif90 supports Fortran 90
-- Checking whether /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpif90 supports Fortran 90 -- yes
-- Found MPI_C: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpicxx (found version "3.1") 
-- Found MPI_Fortran: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.0-20190419-4um5hjogm3tepg4xe23hrptlrs2y7ez6/bin/mpif90 (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found atl: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/atl-config.cmake (found suitable version "2.2.1", minimum required is "2.2.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Checking for module 'libffi'
--   Found libffi, version 3.0.13
-- Found LibFFI: -lffi  
-- Found dill: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/dill-config.cmake (found version "2.4.0") 
-- Found ffs: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/ffs-config.cmake (found suitable version "1.6.0", minimum required is "1.6.0") 
-- Found EVPath: /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/EVPathConfigCommon.cmake (found version "4.4.0") 
CMake Error at /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/cmake-3.14.2-3zkrrk4chuq6wfhvxpmen2gzdpaoiorw/share/cmake-3.14/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  **Found package configuration file:

    /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/thirdparty/EVPathConfig.cmake

  but it set EVPath_FOUND to FALSE so package "EVPath" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: enet::enet**

Call Stack (most recent call first):
  /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/adios2-config-common.cmake:57 (find_dependency)
  /ccs/home/ssinghal/ADIOS2-install/lib64/cmake/adios2/adios2-config.cmake:29 (include)
  CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.bSbXtooDsS/CMakeFiles/CMakeOutput.log".
Failed

**Comment by KyleFromKitware** [comment]
@swatisgupta Can you provide the `-D` arguments you used when you configured with CMake?

**Comment by swatisgupta** [comment]
-DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/ccs/home/ssinghal/ADIOS2-install

**Comment by eisenhauer** [comment]
The dependency processing in ADIOS2 has seen signficant work and I think this is unlikely to still be an issue, but if it is, please re-open...
