### ISSUE TITLE
ADIOS2 adios2-config include paths are wrong after installation

### ISSUE THREAD

**Issue by khuck** [ornladios/ADIOS2#1569]
After installing ADIOS2 (on Linux, using MPICH 3.3 and GCC 8.1), the include paths are not correct.  For example, the output from adios2-config --cxx-flags is:

```-isystem /storage/users/khuck/src/ADIOS2/install_mpi/include -std=gnu++11 ```

But I get this error when trying to build with the installed library:

```
In file included from Tau_plugin_adios2.cpp:26:
/storage/users/khuck/src/ADIOS2/install_mpi/include/adios2.h:18:10: fatal error: cxx11/ADIOS.h: No such file or directory
 #include "cxx11/ADIOS.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tau_plugin_adios2.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

...probably because the full include path should be "adios2/cxx11/ADIOS.h", or the installation should be fixed, or the output from adios2-config should be:

```bash
-isystem -I/storage/users/khuck/src/ADIOS2/install_mpi/include -I/storage/users/khuck/src/ADIOS2/install_mpi/include/adios2 -std=gnu++11
```

**Comment by khuck** [comment]
Never mind, this is a problem on my end.

**Comment by chuckatkins** [comment]
@khuck thanks to @KyleFromKitware we finally have additional CI tests that validate the install for both cmake based projects using the package config files with imported targets and hand written make files using the adios2-config shell script.  Hopefully that will help ensure the install doesn't break again.

**Comment by khuck** [comment]
@chuckatkins thanks - It turns out I had an old commit that had weird errors in adios2-config.  No problems with current master.
