### ISSUE TITLE
Joined arrays are not working properly anymore

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#1576]
examples/basics/joinedArray/joinedArray_write.cpp

The variable 'table' is supposed to be a global array, but it shows up as a bunch of local arrays now. Both BP3 and BP4. 

```
$ mpirun -n 4 ./bin/joinedArray_write

$ ./bin/bpls -laD joinedArray.bp
  double   table  5*[4]*{__, 4} = 0 / 3.93
        step 0: 
          block 0: [0:5, 0:3] = 0 / 0.53
          block 1: [0:9, 0:3] = 1 / 1.93
          block 2: [0:4, 0:3] = 2 / 2.43
          block 3: [0:9, 0:3] = 3 / 3.93
        step 1: 
          block 0: [0:5, 0:3] = 0 / 0.53
          block 1: [0:9, 0:3] = 1 / 1.93
          block 2: [0:4, 0:3] = 2 / 2.43
          block 3: [0:9, 0:3] = 3 / 3.93
        step 2: 
          block 0: [0:5, 0:3] = 0 / 0.53
          block 1: [0:9, 0:3] = 1 / 1.93
          block 2: [0:4, 0:3] = 2 / 2.43
          block 3: [0:9, 0:3] = 3 / 3.93
        step 3: 
          block 0: [0:5, 0:3] = 0 / 0.53
          block 1: [0:9, 0:3] = 1 / 1.93
          block 2: [0:4, 0:3] = 2 / 2.43
          block 3: [0:9, 0:3] = 3 / 3.93
        step 4: 
          block 0: [0:5, 0:3] = 0 / 0.53
          block 1: [0:9, 0:3] = 1 / 1.93
          block 2: [0:4, 0:3] = 2 / 2.43
          block 3: [0:9, 0:3] = 3 / 3.93
```

**Comment by williamfgc** [comment]
@pnorbert JoinedDims never worked, you can see there is no tests. The decision was to push this for later since there was no immediate need from apps and prioritize other features.

**Comment by ax3l** [comment]
We (openPMD -> ECP WarpX / CAAR PIConGPU) are interested in this feature for particle data.

In our simulations, we never need All2All communications. Only I/O requires us to do All2All comms to find global shapes for particles (and their offsets). Since this is a bug fix needed, I will open another issue to document our request.

**Comment by pnorbert** [comment]
This was fixed a long time ago, joined array does work now
