### ISSUE TITLE
2.4.0 release ReadMe.md shows circleci:failed badge

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1591]
When going to the code view from the release page (https://github.com/ornladios/ADIOS2/tree/v2.4.0), the circleci badge shows "failed" -- and some of the other badges are broken links, which bothers me a little bit ;)

It's probably too late to fix as the release is done, but on the odd chance that this can be fixed from the circleci config side, I thought I'd bring it up.

**Comment by chuckatkins** [comment]
The release is already cut.  I'm going through and updating various failed badges.
