### ISSUE TITLE
"transport" parameters in adios config xml file are not parsed

### ISSUE THREAD

**Issue by lwan86** [ornladios/ADIOS2#1630]
Users can add one or more transports in their code through io.AddTransport() function. However, if they try to add transports through the xml file, they will be ignored.

**Comment by keichi** [comment]
@williamfgc I ran into this yesterday and fixed it by myself. Should I submit a PR?

**Comment by williamfgc** [comment]
@keichi this is working with the yaml format. See [an example file](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/yaml/config1.yaml). Yaml config files only work on the current master. For XML feel free to do a PR, I haven't got the time to get to it. Thanks!

**Comment by keichi** [comment]
Thanks William, I didn't know you started supporting YAML for config files. The PR above should make this work with XML too.
