### ISSUE TITLE
Building issue on Cori

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1648]
I just tried to build Adios2 on Cori and got the following error:
```
/opt/cray/pe/craype/2.5.18/bin/CC  -O2 -g -DNDEBUG   CMakeFiles/bpls.dir/bpls/bpls.cpp.o CMakeFiles/bpls.dir/__/__/thirdparty/pugixml/pugixml/src/pugixml.cpp.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/EncodingC.c.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/Directory.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/DynamicLoader.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/EncodingCXX.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/RegularExpression.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/SystemTools.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/CommandLineArguments.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/FStream.cxx.o  -o ../../bin/bpls ../../lib64/libadios2.a -ldl ../../lib64/libadios2_sst.a ../../lib64/libtaustubs.a ../../lib64/libadios2_evpath.a ../../lib64/libadios2_ffs.a ../../lib64/libadios2_atl.a -lm ../../lib64/libadios2_dill.a -L/usr/lib64/../lib64 -lffi ../../lib64/libadios2_enet.a 
/usr/bin/ld: cannot find -lffi
```

Here is my cmake command:
```
   CC=cc CXX=CC FC=ftn \
    cmake \
        -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DBUILD_SHARED_LIBS=ON \
        -DADIOS2_USE_MPI=ON \
        -DADIOS2_USE_Fortran=ON \
        -DADIOS2_USE_Python=ON \
        -DADIOS2_BUILD_EXAMPLES_EXPERIMENTAL=OFF \
        -DADIOS2_BUILD_TESTING=OFF \
        -DADIOS2_USE_ADIOS1=OFF \
        -DADIOS2_USE_HDF5=OFF \
        -DADIOS2_USE_SST=ON \
        -DADIOS2_USE_Profiling=OFF \
```

**Comment by williamfgc** [comment]
@jychoi-hpc  I've seen this in other environments. SST at some point depends on [libffi](https://github.com/libffi/libffi). It's typically installed in most systems, but somehow is missing for your particular environment on Cori.

**Comment by jychoi-hpc** [comment]
It looks like there is only a shared-lib ffi installed and, then, the cori linker cannot pick this:
```
jyc@cori05 src $ find /usr/lib64 -name "libffi.*"
/usr/lib64/libffi.so
/usr/lib64/libffi.so.7
/usr/lib64/libffi.so.7.1.0
/usr/lib64/pkgconfig/libffi.pc
```

**Comment by williamfgc** [comment]
Thanks! As we discussed, we could open a ticket on Cori to request a static libffi library.

**Comment by chuckatkins** [comment]
@jychoi-hpc Python support in ADIOS 2.x current requires you top build a dynamic library but the default configuration in most Cray environments is fully static (this is regardless of whether or not you specify BUILD_SHARED_LIBS or not).  To change this you can `export CRAYPE_LINK_TYPE=dynamic` and then try your configure / build from a clean build directory.

**Comment by rkube** [comment]
(base)  rkube@cori03  ~/repos/adios2-build  cmake -DCMAKE_INSTALL_PREFIX=/global/homes/r/rkube/local -DPYTHON_EXECUTABLE=/usr/common/software/python/3.7-anaconda-2019.07/bin/python -DADIOS2_USE_Python=ON ../ADIOS2
-- The C compiler identification is Intel 19.0.0.20190206
-- The CXX compiler identification is Intel 19.0.0.20190206
-- Cray Programming Environment 2.5.18 C
-- Check for working C compiler: /opt/cray/pe/craype/2.5.18/bin/cc
-- Check for working C compiler: /opt/cray/pe/craype/2.5.18/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.5.18 CXX
-- Check for working CXX compiler: /opt/cray/pe/craype/2.5.18/bin/CC
-- Check for working CXX compiler: /opt/cray/pe/craype/2.5.18/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Blosc (missing: BLOSC_LIBRARY BLOSC_INCLUDE_DIR) 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Could NOT find ZFP (missing: ZFP_LIBRARY ZFP_INCLUDE_DIR) 
-- Could NOT find SZ (missing: SZ_LIBRARY ZSTD_LIBRARY SZ_INCLUDE_DIR) 
-- Could NOT find MGARD (missing: MGARD_LIBRARY BLOSC_LIBRARY MGARD_INCLUDE_DIR) 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib64/libpng.so (found suitable version "1.6.34", minimum required is "1.6.0") 
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - /opt/cray/pe/craype/2.5.18/bin/ftn
-- The Fortran compiler identification is Intel 19.0.0.20190206
-- Cray Programming Environment 2.5.18 Fortran
-- Check for working Fortran compiler: /opt/cray/pe/craype/2.5.18/bin/ftn
-- Check for working Fortran compiler: /opt/cray/pe/craype/2.5.18/bin/ftn  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/cray/pe/craype/2.5.18/bin/ftn supports Fortran 90
-- Checking whether /opt/cray/pe/craype/2.5.18/bin/ftn supports Fortran 90 -- yes
-- Found MPI_C: /opt/cray/pe/craype/2.5.18/bin/cc (found version "3.1") 
-- Found MPI_CXX: /opt/cray/pe/craype/2.5.18/bin/CC (found version "3.1") 
-- Found MPI_Fortran: /opt/cray/pe/craype/2.5.18/bin/ftn (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components:  C Fortran CXX 
-- Could NOT find ZeroMQ (missing: ZeroMQ_LIBRARY ZeroMQ_INCLUDE_DIR) (Required is at least version "4.1")
-- Could NOT find DataSpaces (missing: DATASPACES_VERSION DATASPACES_INCLUDE_DIR DATASPACES_LIBRARIES DSPACES_LIBRARY) (Required is at least version "1.8")
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/common/software/python/3.7-anaconda-2019.07/lib/libhdf5.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so;/usr/common/software/python/3.7-anaconda-2019.07/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.10.4") found components:  C 
-- Found PythonInterp: /usr/common/software/python/3.7-anaconda-2019.07/bin/python (found version "3.7.3") 
-- Found PythonLibs: /usr/common/software/python/3.7-anaconda-2019.07/lib/libpython3.7m.so (found version "3.7.3") 
-- Found PythonModule_numpy: /usr/common/software/python/3.7-anaconda-2019.07/lib/python3.7/site-packages/numpy  
-- Found PythonModule_mpi4py: /usr/common/software/python/3.7-anaconda-2019.07/lib/python3.7/site-packages/mpi4py  
-- Found PythonFull: /usr/common/software/python/3.7-anaconda-2019.07/bin/python  found components:  Interp Libs numpy mpi4py 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libfabric'
--   No package 'libfabric' found
-- Could NOT find LIBFABRIC (missing: LIBFABRIC_LIBRARIES) (Required is at least version "1.6")
-- Looking for shmget
-- Looking for shmget - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  

-- ADIOS2 ThirdParty: Configuring KWSys
-- Checking whether header cstdio is available
-- Checking whether header cstdio is available - yes
-- Checking for Large File Support
-- Checking for Large File Support - yes
-- Checking whether C++ compiler has 'long long'
-- Checking whether C++ compiler has 'long long' - yes
-- Checking whether C++ compiler has '__int64'
-- Checking whether C++ compiler has '__int64' - yes
-- Checking whether long and __int64 are the same type
-- Checking whether long and __int64 are the same type - yes
-- Checking whether long long and __int64 are the same type
-- Checking whether long long and __int64 are the same type - no
-- Checking whether wstring is available
-- Checking whether wstring is available - yes
-- Checking whether C compiler has ptrdiff_t in stddef.h
-- Checking whether C compiler has ptrdiff_t in stddef.h - yes
-- Checking whether C compiler has ssize_t in unistd.h
-- Checking whether C compiler has ssize_t in unistd.h - yes
-- Checking whether CXX compiler has setenv
-- Checking whether CXX compiler has setenv - yes
-- Checking whether CXX compiler has unsetenv
-- Checking whether CXX compiler has unsetenv - yes
-- Checking whether CXX compiler has environ in stdlib.h
-- Checking whether CXX compiler has environ in stdlib.h - no
-- Checking whether CXX compiler has utimes
-- Checking whether CXX compiler has utimes - yes
-- Checking whether CXX compiler has utimensat
-- Checking whether CXX compiler has utimensat - yes
-- Checking whether CXX compiler struct stat has st_mtim member
-- Checking whether CXX compiler struct stat has st_mtim member - yes
-- Checking whether CXX compiler struct stat has st_mtimespec member
-- Checking whether CXX compiler struct stat has st_mtimespec member - no
-- Checking whether <ext/stdio_filebuf.h> is available
-- Checking whether <ext/stdio_filebuf.h> is available - yes

-- ADIOS2 ThirdParty: Configuring GTest

-- ADIOS2 ThirdParty: Configuring pybind11
-- Found PythonLibs: /usr/common/software/python/3.7-anaconda-2019.07/lib/libpython3.7m.so
-- pybind11 v2.2.4

-- ADIOS2 ThirdParty: Configuring pugixml

-- ADIOS2 ThirdParty: Configuring nlohmann_json

-- ADIOS2 ThirdParty: Configuring atl
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of double
-- Check size of double - done
-- Check size of float
-- Check size of float - done
-- Check size of int
-- Check size of int - done
-- Check size of short
-- Check size of short - done
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file windows.h
-- Looking for include file windows.h - not found
-- Looking for fork
-- Looking for fork - found
-- Found atl: /global/homes/r/rkube/repos/adios2-build/thirdparty/atl/atl/atl-config.cmake (found version "2.2.1") 

-- ADIOS2 ThirdParty: Configuring dill
-- Check size of void*
-- Check size of void* - done
-- Check size of long
-- Check size of long - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Checking for module 'libffi'
--   Found libffi, version 3.99999
-- Found LibFFI: -L/usr/lib64/../lib64;-lffi  
-- Enabling emulation
-- Looking for include file stdarg.h
-- Looking for include file stdarg.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Found dill: /global/homes/r/rkube/repos/adios2-build/thirdparty/dill/dill/dill-config.cmake (found version "2.4.0") 

-- ADIOS2 ThirdParty: Configuring ffs
-- Check size of off_t
-- Check size of off_t - done
-- Check size of long double
-- Check size of long double - done
-- Check size of long long
-- Check size of long long - done
-- Check size of size_t
-- Check size of size_t - done
-- Looking for socket
-- Looking for socket - found
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found dill: /global/homes/r/rkube/repos/adios2-build/thirdparty/dill/dill/dill-config.cmake (found suitable version "2.4.0", minimum required is "2.3.1") 
-- Found atl: /global/homes/r/rkube/repos/adios2-build/thirdparty/atl/atl/atl-config.cmake (found suitable version "2.2.1", minimum required is "2.2.1") 
-- Looking for netdb.h
-- Looking for netdb.h - found
-- Looking for sockLib.h
-- Looking for sockLib.h - not found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/times.h
-- Looking for sys/times.h - found
-- Looking for sys/uio.h
-- Looking for sys/uio.h - found
-- Looking for sys/un.h
-- Looking for sys/un.h - found
-- Looking for winsock.h
-- Looking for winsock.h - not found
-- Looking for strtof
-- Looking for strtof - found
-- Looking for strtod
-- Looking for strtod - found
-- Looking for strtold
-- Looking for strtold - found
-- Looking for getdomainname
-- Looking for getdomainname - found
-- Check size of struct iovec
-- Check size of struct iovec - done
-- Performing Test HAS_IOV_BASE_IOVEC
-- Performing Test HAS_IOV_BASE_IOVEC - Success
-- Found ffs: /global/homes/r/rkube/repos/adios2-build/thirdparty/ffs/ffs/ffs-config.cmake (found version "1.6.0") 

-- ADIOS2 ThirdParty: Configuring enet
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for gethostbyaddr_r
-- Looking for gethostbyaddr_r - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - found
-- Looking for poll
-- Looking for poll - found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Looking for inet_ntop
-- Looking for inet_ntop - found
-- Performing Test HAS_MSGHDR_FLAGS
-- Performing Test HAS_MSGHDR_FLAGS - Success
-- Performing Test HAS_SOCKLEN_T
-- Performing Test HAS_SOCKLEN_T - Success
-- Found enet: /global/homes/r/rkube/repos/adios2-build/thirdparty/enet/enet/enet-config.cmake (found version "1.3.14") 

-- ADIOS2 ThirdParty: Configuring EVPath
-- Performing Test HAVE_MATH
-- Performing Test HAVE_MATH - Success
-- Found ffs: /global/homes/r/rkube/repos/adios2-build/thirdparty/ffs/ffs/ffs-config.cmake (found suitable version "1.6.0", minimum required is "1.5.1") 
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Found enet: /global/homes/r/rkube/repos/adios2-build/thirdparty/enet/enet/enet-config.cmake (found suitable version "1.3.14", minimum required is "1.3.13") 
-- Looking for hostlib.h
-- Looking for hostlib.h - not found
-- Looking for sys/sockio.h
-- Looking for sys/sockio.h - not found
-- Performing Test HAVE_FDS_BITS
-- Performing Test HAVE_FDS_BITS - Failed
-- Looking for writev
-- Looking for writev - found
-- Looking for uname
-- Looking for uname - found
-- Looking for getloadavg
-- Looking for getloadavg - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Found EVPath: /global/homes/r/rkube/repos/adios2-build/thirdparty/EVPath/EVPath/EVPathConfigCommon.cmake (found version "4.4.0") 

-- Performing Test HAS_INTEL_IPO
-- Performing Test HAS_INTEL_IPO - Success
-- LTO enabled
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Verifying Fortran/CXX Compiler Compatibility
-- Verifying Fortran/CXX Compiler Compatibility - Success
-- Found MPI: TRUE (found version "3.1") found components:  C 

ADIOS2 build configuration:
  ADIOS Version: 2.4.0.180
  C++ Compiler : Intel 19.0.0.20190206 CrayPrgEnv
    /opt/cray/pe/craype/2.5.18/bin/CC

  Fortran Compiler : Intel 19.0.0.20190206 CrayPrgEnv
    /opt/cray/pe/craype/2.5.18/bin/ftn

  Installation prefix: /global/homes/r/rkube/local
        bin: bin
        lib: lib64
    include: include
      cmake: lib64/cmake/adios2
     python: lib64/python3.7/site-packages

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: ON
    Build Options:
      Blosc    : OFF
      BZip2    : ON
      ZFP      : OFF
      SZ       : OFF
      MGARD    : OFF
      PNG      : ON
      MPI      : ON
      DataMan  : OFF
      SSC      : OFF
      SST      : ON
      DataSpaces: OFF
      ZeroMQ   : OFF
      HDF5     : OFF
      Python   : ON
      Fortran  : ON
      SysVShMem: ON
      Profiling: ON
      Endian_Reverse: OFF
    RDMA Transport for Staging: Unconfigured

-- Configuring done
-- Generating done
-- Build files have been written to: /global/homes/r/rkube/repos/adios2-build

**Comment by jychoi-hpc** [comment]
This is just to share information here. I talked to NERSC help desk and was informed the location of the static libffi: `/global/common/sw/cray/sles15/x86_64/libffi/3.2.1/gcc/8.2.0/nprkfvh/lib64`

After setting the following environment,
```
LIBFFI_ROOT=/global/common/sw/cray/sles15/x86_64/libffi/3.2.1/gcc/8.2.0/nprkfvh
export PKG_CONFIG_PATH=$LIBFFI_ROOT/lib/pkgconfig:$PKG_CONFIG_PATH
```
I can build Adios2 as a static library on Cori.
