### ISSUE TITLE
Build issue on cori: python support not built

### ISSUE THREAD

**Issue by rkube** [ornladios/ADIOS2#1649]
I can't get ADIOS2 to build with python support.
This is my command line: 
cmake \
-DCMAKE_INSTALL_PREFIX=/global/homes/r/rkube/local \
-DPYTHON_EXECUTABLE=/usr/common/software/python/3.7-anaconda-2019.07/bin/python \
-DADIOS2_USE_Python=ON \
 ../ADIOS2

In the build options, python is off:

 Testing: ON
    Build Options:
      Blosc    : OFF
      BZip2    : OFF
      ZFP      : OFF
      SZ       : OFF
      MGARD    : OFF
      PNG      : OFF
      MPI      : ON
      DataMan  : OFF
      SSC      : OFF
      SST      : ON
      DataSpaces: OFF
      ZeroMQ   : OFF
      HDF5     : OFF
      Python   : OFF
      Fortran  : ON
      SysVShMem: ON
      Profiling: OFF
      Endian_Reverse: OFF
    RDMA Transport for Staging: Unconfigured

**Comment by williamfgc** [comment]
@rkube make sure you `python3-dev`, `python3-mpi4py`, and `python3-numpy`. Also, since you're using anaconda, we have adios2 packages in anaconda cloud.

**Comment by williamfgc** [comment]
Also, if it helps, cmake will report in the same configure output if a dependency is missing.

**Comment by chuckatkins** [comment]
@rkube Python support in ADIOS 2.x currently requires you to build a dynamic library but the default configuration in most Cray environments is fully static.  This is a behavior of the craype compiler wrappers and happens regardless of whether or not you specify the `BUILD_SHARED_LIBS` CMake option.  To change this you can `export CRAYPE_LINK_TYPE=dynamic` and then try your configure / build from a clean build directory.

**Comment by rkube** [comment]
@chuckatkins Thanks, this solved my problem.
@williamfgc I have these packages installed in my python environment. However, when static linking was configured, cmake didn't even check for them. I know about the adios2 package in the anaconda cloud, but I would like to work with EFFIS, which needs the full adios2 installation.

**Comment by williamfgc** [comment]
@rkube thanks for following up. For future reference we have some docs on the topic @chuckatkins pointed out: https://adios2.readthedocs.io/en/latest/setting_up/setting_up.html#building-on-hpc-systems To be fair, we should reach out to nersc and have adios2 modules installed.
