### ISSUE TITLE
Linking to ADIOS2 on Cori

### ISSUE THREAD

**Issue by iamcalvinlau** [ornladios/ADIOS2#1656]
Hi,

I am running into issues linking ADIOS2 on Cori for my (Fortran) code. 

ADIOS2 was built with 

> -DCMAKE_BUILD_Type=Release -DADIOS2_USE_SST=OFF 

using intel/19.0.3.199. 

ADIOS2 was linked via 

> -DADIOS2_HAVE_MPI_F -I/global/u1/c/clau/local/include/adios2/fortran

> /global/u1/c/clau/local/lib64/libadios2_f.a /global/u1/c/clau/local/lib64/libadios2.a -ldl /global/u1/c/clau/local/lib64/libtaustubs.a -lifcore -lirng -ldecimal -lmpichcxx_intel -lstdc++ -lifcore -lirng -lstdc++ -ldecimal -lstdc++

(from $ADIOS2_DIR/bin/adios2-config --fortran-flags and $ADIOS2_DIR/bin/adios2-config --fortran-libs).

Compilation fails and I end up with the errors:

> /usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o): in function `for_set_reentrancy':
for_reentrancy.c:(.text+0x0): multiple definition of `for_set_reentrancy'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):for_reentrancy.c:(.text+0x0): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o):(.data+0x140): multiple definition of `for__reentrancy_mode'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):(.bss+0x10): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o): in function `for__reentrancy_cleanup':
for_reentrancy.c:(.text+0xd0): multiple definition of `for__reentrancy_cleanup'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):for_reentrancy.c:(.text+0x60): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o):(.data+0x0): multiple definition of `for__static_threadstor_private'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):(.data+0x0): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o): in function `for__disable_asynch_deliv_private':
for_reentrancy.c:(.text+0x790): multiple definition of `for__disable_asynch_deliv_private'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):for_reentrancy.c:(.text+0xc0): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o): in function `for__enable_asynch_deliv_private':
for_reentrancy.c:(.text+0x7b0): multiple definition of `for__enable_asynch_deliv_private'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):for_reentrancy.c:(.text+0xe0): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o): in function `for__once_private':
for_reentrancy.c:(.text+0xb20): multiple definition of `for__once_private'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):for_reentrancy.c:(.text+0x100): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o): in function `for__reentrancy_init':
for_reentrancy.c:(.text+0xca0): multiple definition of `for__reentrancy_init'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):for_reentrancy.c:(.text+0x160): first defined here
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o):(.bss+0x1c): multiple definition of `for__reentrancy_initialized'; /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):(.bss+0x14): first defined here
/usr/bin/ld: link errors found, deleting executable `anc'

Any hints as to what to try? Thanks in advance.

**Comment by williamfgc** [comment]
@iamcalvinlau a few things:
1) can you compile a simple fortran program using `import adios2` ?
2) there are many libraries appearing twice in your linker, is this given by adios2-config?
3) can you provide the full linker command?

**Comment by iamcalvinlau** [comment]
1. For a simple program, I tried to compile the ADIOS2/fortran/simulation program (replacing the ADIOS2_FINC and ADIOS2_FLIB where appropriate in the head of the Makefile, ie.
> ADIOS2_FLIB=/global/u1/c/clau/local/lib64/libadios2_f.a /global/u1/c/clau/local/lib64/libadios2.a -ldl /global/u1/c/clau/local/lib64/libtaustubs.a -lifcore -lirng -ldecimal -lmpichcxx_intel -lstdc++ -lifcore -lirng -lstdc++ -ldecimal -lstdc++
#ADIOS2_FINC=-DADIOS2_HAVE_MPI_F -I/global/u1/c/clau/local/include/adios2/fortran
):

> ftn -g -O2 -DADIOS2_HAVE_MPI_F -I/global/u1/c/clau/local/include/adios2/fortran -c io_adios2.F90  
io_adios2.F90(92): error #6285: There is no matching specific subroutine for this generic subroutine call.   [ADIOS2_BEGIN_STEP]
    call adios2_begin_step( bp_writer, adios2_step_mode_append, 0., &
---------^
compilation aborted for io_adios2.F90 (code 1)
make: *** [Makefile:48: io_adios2.o] Error 1

For good measure, I also actually tried to do this with the available adios2/2.3.1 module on Cori with the same outcome.

**Comment by iamcalvinlau** [comment]
2. I've made some changes to the Makefile to pull out some dependencies more explicitly (we use a Python file to generate the dependencies normally so I believe it ended up trying to link to the libraries for each of the objects/modules). This change ended up getting me into a situation where I get

> ftn -pc64 -D_PETSc_3_6_1_AND_LATER -DPETSc -qopenmp -DDOUBLE_PRECISION -fpconstant -real-size 64 -g -O2 -parallel -DADIOS2   -DADIOS2_HAVE_MPI_F -I/global/u1/c/clau/adios2/include/adios2/fortran /global/u1/c/clau/adios2/lib64/libadios2_f.a /global/u1/c/clau/adios2/lib64/libadios2.a -ldl /global/u1/c/clau/adios2/lib64/libtaustubs.a -lifcore -lirng -ldecimal -lmpichcxx_intel -lstdc++ -lifcore -lirng -lstdc++ -ldecimal -lstdc++ -c fileIO_adios2.F90
ifort: warning #10145: no action performed for file '/global/u1/c/clau/adios2/lib64/libadios2_f.a'
ifort: warning #10145: no action performed for file '/global/u1/c/clau/adios2/lib64/libadios2.a'
ifort: warning #10145: no action performed for file '/global/u1/c/clau/adios2/lib64/libtaustubs.a'
updating git hash... successful_driftLorentz_mover_CYL-134-g32e826d98e797806cb7ff43067e6393cd2e78785-dirty
ftn -pc64 -D_PETSc_3_6_1_AND_LATER -DPETSc -qopenmp -DDOUBLE_PRECISION -fpconstant -real-size 64 -g -O2 -parallel -DADIOS2   -c initial.F90
cc -g -c xxhash.c
ftn -pc64 -D_PETSc_3_6_1_AND_LATER -DPETSc -qopenmp -DDOUBLE_PRECISION -fpconstant -real-size 64 -g -O2 -parallel -DADIOS2   -c initial.F90
ftn -pc64 -D_PETSc_3_6_1_AND_LATER -DPETSc -qopenmp -DDOUBLE_PRECISION -fpconstant -real-size 64 -g -O2 -parallel -DADIOS2   -c main.F90
ftn -pc64 -D_PETSc_3_6_1_AND_LATER -DPETSc -qopenmp -DDOUBLE_PRECISION -fpconstant -real-size 64 -g -O2 -parallel -DADIOS2 -o anc taehdf5.o precision.o parallel.o fileIO.o tools.o fft_gl.o splines.o grid.o petsc.o field.o particles.o poisson.o push.o units.o xxhashf.o control_logicals.o timers.o collisions.o antennas.o physics_conditions.o mesh.o fileIO_adios2.o initial.o xxhash.o main.o  
/usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libiomp5.a(ompt-general.o): in function `ompt_pre_init':
(.text+0x2600): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: fileIO_adios2.o: in function `fileio_adios2_mp_finaloutput_adios2_':
/global/cscratch1/sd/clau/2018-08/anc/2019-04_GKI_ADE/fileIO_adios2.F90:162: undefined reference to `adios2_engine_mod_mp_adios2_close_'
/usr/bin/ld: /global/cscratch1/sd/clau/2018-08/anc/2019-04_GKI_ADE/fileIO_adios2.F90:163: undefined reference to `adios2_adios_mod_mp_adios2_finalize_'
/usr/bin/ld: /global/cscratch1/sd/clau/2018-08/anc/2019-04_GKI_ADE/fileIO_adios2.F90:165: undefined reference to `adios2_engine_mod_mp_adios2_close_'
...
(More errors with similar undefined reference to `...')

**Comment by iamcalvinlau** [comment]
3. The Makefile which generated the above errors, renamed with *.txt at the end, is attached.
[Makefile.txt](https://github.com/ornladios/ADIOS2/files/3469332/Makefile.txt)

**Comment by williamfgc** [comment]
Hi @iamcalvinlau thank for reporting this. Before going to the more complex Makefile, I want to make sure adios2 modules and fortran library works in your current environment.  Let's stick with version 2.4.0 or the current master. The 2.3.1 module is outdated. 

Let's start making sure you have the right signature, see this [Fortran test](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/bindings/fortran/TestBPWriteTypes.f90) for this issue you're having:
> o_adios2.F90(92): error #6285: There is no matching specific subroutine for this generic subroutine call. [ADIOS2_BEGIN_STEP]
call adios2_begin_step( bp_writer, adios2_step_mode_append, 0., &
---------^
compilation aborted for io_adios2.F90 (code 1)

**Comment by iamcalvinlau** [comment]
For 1., I realized that the calls in the ADIOS2/Fortran example simulation may not have been updated for more recent versions (looks like the example uses 4 inputs, but the interfaces only exist for 2, 3, or 5 inputs).

**Comment by williamfgc** [comment]
@iamcalvinlau yes, there was a change in v2.4.0, we are trying our best to keep the API stable since v2.4.0. Sorry for the inconvenience. Hope this helps to get the first part working in your environment.

**Comment by iamcalvinlau** [comment]
@williamfgc I realized that in my haste to shift the dependency explicitly out of the automatically generated dependencies list, I made some mistakes in the Makefile. After fixing these mistakes, I end up with the "multiple definitions" error again. NERSC consultation suggested two different workarounds, and the one that works is to allow the compiler to have multiple definitions (and just use the first one) by adding a linker option for gcc `-Wl,--allow-multiple-definition`. With this additional linker option, I can successfully compile with ADIOS2. (I can also successfully compile without ADIOS2 or its associated linker options, so it may be some conflict with Cori's defaults?)

**Comment by germasch** [comment]
> Hi,
> Compilation fails and I end up with the errors:
> 
> > /usr/bin/ld: /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a(for_reentrancy.o): in function `for_set_reentrancy': for_reentrancy.c:(.text+0x0): multiple definition of `for_set_reentrancy'; 
> /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcore.a(for_reentrancy.o):for_reentrancy.c:(.text+0x0): first defined here

To add my two cents, the problem with the multiple definitions appears to happen because these two libraries are both linked: `libifcoremt.a` and `libifcore.a`. Just from the naming, I presume one is the multi-thread version of the other, and allowing multiple definitions as a workaround runs the risk that the wrong library is picked, which is probably  fine if no multi-threading is used, but may lead to weird races otherwise.

It looks like adios2 pulls in the non-threaded libifcore (`-lifcore`), and that's probably not the right thing. One thing worth trying might be to build adios2 explicitly with multithreading enabled, which would hopefully lead to it pulling it the right lib the. That may be as easy as adding the `-threads` flag, but I have no idea whether that actually works. I suppose you could try adding `-DCMAKE_Fortran_FLAGS=-threads` to the cmake invocation and see how it goes. (I guess it would help to see how the Fortran compiler is invoked when compiling your code, and you probably want to get the flags from there rather than me guessing.)

Mentioning @chuckatkins because he probably has more of a clue. `libifcore` appears to be the libgfortran equivalent for the Intel compiler, and since I guess it's usually added by the compiler invoking the linker, in some sense it might be best to not have `adios2-config` make guesses.
