### ISSUE TITLE
python high-level handling of scalars (GlobalValue)

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1671]
While working on the python HL API, I noticed this (small) issue: 

When reading a GlobalValue, the API will return a 1-d numpy array with one element, ie., `array([value])`. 

Current behavior:

```python
    def test_GlobalValue1d(self):
        with adios2.open(filename, 'r') as fh:
            for fh_step in fh:
                t = fh_step.current_step()
                val = fh_step.read('global_value')
                self.assertTrue(np.array_equal(val, np.array([global_values[t]])))
```

I'd propose changing this to returning a 0-d array, which is numpy's way of handling scalars. That'll make is possible to just say
```python
self.assertTrue(val == global_values[t])
```
and generally will be less confusing for users of the HL API, as they won't have to unpack the scalar value from the 1-d array first.

**Comment by williamfgc** [comment]
@germasch while I agree with the concept, I don't know if there is a way to overload `read` so it'd return different types (can't do it in C++). As you can see, a full `numpy` array is the common choice, adding a new function such as `read_value` would be a similar approach as the current `read_string` function.

**Comment by germasch** [comment]
In Python, even a single (non-overloaded) function can return different objects, e.g.,
```python
def func(x):
     if x >= 0:
        return np.sqrt(x)
    else:
        return "Can't take square root of a negative number"
```
(not that the example makes a lot of sense).

It's not even an issue here, though, since I'd just return a 0-d pyarray, no special case needed.

The outstanding PR enables the use of stepSelection on global values, and will do the right thing, ie., return a numpy array of the global value for the selected time steps.

**Comment by williamfgc** [comment]
@germasch OK, thanks for clarifying on handling steps. I see [`pybind11` can handle 0-d numpy arrays](https://github.com/pybind/pybind11/issues/1457) for a while. Thanks.

**Comment by williamfgc** [comment]
Related #1644
