### ISSUE TITLE
Inquiring MPI writer rank in Engine::BlocksInfo

### ISSUE THREAD

**Issue by franzpoeschel** [ornladios/ADIOS2#1679]
The method `Engine::BlocksInfo` does currently not give information about the rank that wrote the block. This would be helpful to optimize distribution of written data over reading ranks through increased data proximity.
Would it in general be possible to include such information? (Or am I missing something / taking an unidiomatic approach?)

**Comment by williamfgc** [comment]
@franzpoeschel I could add this information, especially since would be helpful to support multiblock Puts per rank, then the rank can be different from the Engine::BlockInfo vector index. If there is only one block per rank for each variable, then the vector index is sufficient. Hope it helps.

**Comment by franzpoeschel** [comment]
> then the vector index is sufficient

This is helpful to know and I can work with this for now. I would assume that as a permanent solution, having this information explicitly as a field in `Engine::BlockInfo` will be more reliable.

The vector index will probably not be sufficient either if one rank does not send data at all?

**Comment by williamfgc** [comment]
> The vector index will probably not be sufficient either if one rank does not send data at all?

Yes that's correct, as soon as we break the 1-to-1 pattern the index doesn't map the rank. Thanks for bringing this up.

**Comment by williamfgc** [comment]
@franzpoeschel I added the field WriterID. In N-to-N cases (N ranks, N files) it is equal to the rank than generated the block, but if we are using a different number of subfiles (N ranks, M files) it would be the subfile id. Hope this helps.

**Comment by franzpoeschel** [comment]
Thank you very much for the quick reaction! This feature is very useful to have.

**Comment by pnorbert** [comment]
@franzpoeschel Will this solution work for you? Note that with aggregation to M subfiles turned on, the number of actual file writers goes down from N to M, and you will get IDs from 0..M-1 and there will be multiple blocks with the same ID (N/M). So you will still not be able to identify the original N data producers with these IDs. However, if you are trying to optimize for reading from the M subfiles, this info should be sufficient.
