### ISSUE TITLE
Chunking in bp files

### ISSUE THREAD

**Issue by liangwang0734** [ornladios/ADIOS2#1684]
Does ADIOS 2 have a chunking option? And if it does, how can we set it for a bp file in C/C++ and in adios-python?

The [ADIOS 1 manual](https://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.13.1.pdf) mentioned it but it was not easy to figure out a basic usage.
There is no search result for 'chunk' on https://adios2.readthedocs.io/en/latest/

**Comment by pnorbert** [comment]
Hi, do you mean chunking for reading the data? You can get the list (a vector) of the blocks that a variable consists of, than you can use a block selection to read one specifically. Here is a snippet of code, which is not going to compile in this form but you may get the idea and the API from this.

```
std::string DimsToString(adios2::Dims &dims)
{
    std::string s = "\"";
    for (int i = 0; i < dims.size(); i++)
    {
        if (i > 0)
        {
            s += ", ";
        }
        s += std::to_string(dims[i]);
    }
    s += "\"";
    return s;
}


template <class T>
void ProcessVariable(int rank, const std::string &name,
                             const std::string &type,
                             const adios2::Engine &reader, adios2::IO &io)

    const adios2::Variable<T> variable = io.InquireVariable<T>(name);
    std::vector<typename adios2::Variable<T>::Info> blocks =
        reader.BlocksInfo(variable, reader.CurrentStep());
    for (auto &block : blocks)
    {
        std::cout << "        Rank " << rank << "     Variable '" << name
                      << "' found a block. dimensions = "
                      << DimsToString(block.Count)
                      << " offset = " << DimsToString(block.Start) <<
        std::endl;

        size_t myBlock = block.BlockID;
        variable.SetBlockSelection(myBlock);

        // allocate a dataPtr for the size of the block
        // the ptr will be filled by PerformGets()

        reader.Get<T>(variable, dataPtr,  adios2::Mode::Deferred);
    }
    reader.PerformGets();

    for (const auto &block: blocks)
    {
        adios2::Dims count = block.Count;
        const T* vectData = block.Data();
        for (int i = 0; i < count[0]; ++i)
        {
            T datum = vectData[i];
            std::cout << datum << " ";
        }
        std::cout << "\n";
    }
}
```

**Comment by pnorbert** [comment]
No, ADIOS2 has no chunking option because so far we don't see us implementing it in our existing engines, except maybe for wide-area-network streaming. Can you tell us why you would want this feature? 

We are not aware of anyone trying to use it in ADIOS 1.x either. Certainly none of its transport methods were providing better performance with it: as the manual says: _"Note: In ADIOS 1.13.1, chunking is implemented only "functionally" in any method; all of them will just read the whole variable at once"_

**Comment by liangwang0734** [comment]
Hi Norbert, my intention was to improving slicing performance, particularly when the slicing pattern is against the storage pattern. In a c-array of shape N0*N1*N2, slicing along the last dimension could be very slow as the last index varies fastest. With chunking, the average slicing speed could be largely improved. This was my typical motive to use chunking in hdf5 storage in the past for slicing large data (~ 1 TB) on a single node.

However, a colleague explained to me that in ADIOS, by default, the output is already done somewhat in a "chunking" way as each CPU writes its own portion before everything is zipped up as a single file. If this is the case, I think this issue is then nonexistent and I am going to close this issue.

Thank you for the discussion.
