### ISSUE TITLE
Problem installing version 2.4.0, parallel build

### ISSUE THREAD

**Issue by dpugmire** [ornladios/ADIOS2#1732]
Ahoy!
I'm having a problem installing version 2.4.0, parallel.
cmake version is 13.4.5

ran cmake as follows:
cmake -DADIOS2_BUILD_EXAMPLES:BOOL=OFF -DADIOS2_BUILD_TESTING:BOOL=OFF -DADIOS2_USE_ZeroMQ:BOOL=OFF -DADIOS2_USE_Fortran:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=install_path_dir  -DCMAKE_C_FLAGS:STRING=" -O2" -DCMAKE_CXX_FLAGS:STRING=" -O2" -DADIOS2_USE_SST:BOOL=ON -DADIOS2_USE_MPI:BOOL=ON -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ -DCMAKE_MPI_C_COMPILER=/usr/bin/mpicc -DCMAKE_MPI_CXX_COMPILER=/usr/bin/mpicxx ..

build works fine.
However, make install fails with this message:

CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findadios2_mpi.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "adios2_mpi", but CMake did not find one.

  Could not find a package configuration file provided by "adios2_mpi" with
  any of the following names:

    adios2_mpiConfig.cmake
    adios2_mpi-config.cmake

  Add the installation prefix of "adios2_mpi" to CMAKE_PREFIX_PATH or set
  "adios2_mpi_DIR" to a directory containing one of the above files.  If
  "adios2_mpi" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.LeCK43E66t/CMakeFiles/CMakeOutput.log".
Failed

I seek wisdom.
Thanks,
Dave

**Comment by williamfgc** [comment]
@chuckatkins @bradking can you guys take a look? This might be related to the MPI changes in the code. Thanks!

**Comment by dpugmire** [comment]
Related question.
Is it possible to generate both adios2.so and adios2_mpi.so ? This would solve a multitude of issues when building VisIt with ADIOS2 support.

**Comment by dpugmire** [comment]
@NAThompson to bring Nick in as well..

**Comment by chuckatkins** [comment]
> Related question.
> Is it possible to generate both adios2.so and adios2_mpi.so ? This would solve a multitude of issues when building VisIt with ADIOS2 support.

At the moment, no it's not possible.  However, @bradking is working on just that: To build an MPI enabled adios2 that will provide both the serial and MPI libraries in the same build.

**Comment by dpugmire** [comment]
Great, thanks!

**Comment by chuckatkins** [comment]
I believe all make install issues have since been resolved so I'm closing this for now.  If the problem still remains we can re-open.
