### ISSUE TITLE
Make FFS optional at build

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#1740]
Related to #1738 and #1495 

@eisenhauer @pnorbert @chuckatkins @JasonRuonanWang since FFS is not officially sanction as pointed out by @eisenhauer. I'd like to propose making it an optional flag `-DADIOS_USE_SST_FFS=OFF`. Thanks.

**Comment by chuckatkins** [comment]
Is there a compelling reason to still support it at all instead of removing it entirely?  If we want to still leave it then maybe we should mark the option advanced and deprecated for this release so when it's turned on we show a warning that it will be removed in a future release.

**Comment by eisenhauer** [comment]
Most compelling reason is probably that the control plane uses it (both directly and indirectly (via EVPath)) for general communication.  The optional bit is whether or not it is also used for marshaling application data...  You could make the compilation of the file ffs_marshal.c in SST/cp be compile-time optional, but not all of FFS. (Not sure why #1495 comes up, that was a bug in the tests.)

**Comment by williamfgc** [comment]
@chuckatkins @eisenhauer thanks for your input. My view is that keeping unmaintained code is not sustainable and creates a lot of headaches for users and developers. It should be either kept on a branch or fixed if we want to merge it into master or a release.

**Comment by chuckatkins** [comment]
> keeping unmaintained code is not sustainable

Hence the suggestion to not make it an option but to just remove it.  Sure, we still need it for the sake of the control plane, but if we're no longer supporting marshaling via ffs then I'd advocate for removing it rather than optioning it out.  That being said, I think we should wait until after 2.5

**Comment by chuckatkins** [comment]
FFS is still directly used by the control plane and evpath so it's not a dependency that could be or should be disabled or removed when using sst.
