### ISSUE TITLE
bpls is still using MPI?

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#1748]
As mentioned in #1745, bpls seems to use MPI somewhere in the ADIOS library, even though it is a serial code. How can we debug this and find the place where it happens?

**Comment by pnorbert** [comment]
Assigning William too, because this might come from the refactoring of BP base.

**Comment by williamfgc** [comment]
@pnorbert thanks for bringing this up. In principle, the refactoring is reusing the same constructors passing around `MPI_Comm` (I am just creating bases and moving up functionality). But I agree, it's worth to take a look and understand the issue. As @philip-davis reported it's happening on Cori with MPICH.

**Comment by bradking** [comment]
The problem was caused by commit 9d76d51d0040a704e261a8b5232acd76c366e5a8 from #1720.  It introduced `IsHDF5File` and a code path reaching it.  That function does:

```c++
            transportman::TransportMan tm(Comm::Duplicate(MPI_COMM_SELF),
                                          false);
```

The use of `MPI_COMM_SELF` without initializing MPI first is not allowed since `mpiwrap` was changed to switch off `MPI_COMM_NULL`.

**Comment by pnorbert** [comment]
Thanks, so how do you fix this properly?
I don't think this is the only place because this should not be called when the file argument is a string ending with .bp

**Comment by bradking** [comment]
What should `IsHDF5File` do in a serial program?  Currently it hard-codes use of MPI.

**Comment by pnorbert** [comment]
It should do what is in the try {} block (rank 0 does the check alone). The rest is to broadcast the decision to all ranks.

**Comment by bradking** [comment]
The broadcast is using the communicator from the caller and is fine.  The `try{}` block content is exactly the offending code path and is using MPI via `MPI_COMM_SELF`.  What should it do in a serial program without MPI?

**Comment by pnorbert** [comment]
The transport manager requires a communicator. What should be passed there
that works for a serial code as well for a single process in an MPI
application?

**Comment by bradking** [comment]
To report back here after discussing this on our call, using a plain default-constructed `Comm()` for the transport manager should work.  That will cause the `SMPI_*` wrappers to be used with `MPI_COMM_NULL` which is meant for operations only within the current process.

**Comment by pnorbert** [comment]
Can MPI_Wtime() cause any trouble when running without MPI_Init()?
BP4Reader.cpp is using this a lot to get elapsed time as a floating point number to implement timeouts.

**Comment by bradking** [comment]
I don't think `MPI_Wtime` is specified to be usable without `MPI_Init`, though it may work in some implementations.  I've been looking at replacing `MPI_Wtime` with `std::chrono`` since it is just used for a timeout.

**Comment by bradking** [comment]
See PR #1761 for removal of `MPI_Wtime` from BP4Reader.

**Comment by chuckatkins** [comment]
@pnorbert so is this fixed now?

**Comment by pnorbert** [comment]
This is fixed now. bpls binary from a parallel build on Cori (for Haswell) works on the login node.
