### ISSUE TITLE
BZip2 in Cmake auto mode fails on Titan

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#175]
Auto mode tries to compile with BZip2 even though it's not found. 
/usr/bin/ld: cannot find -lBZip2::BZip2
../../../lib64/libadios2sys.a(SystemTools.cxx.o): In function `adios2sys::SystemTools::ConvertToUnixSlashes(std::string&)':
SystemTools.cxx:(.text+0x1cbe): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/sha1sum: ../../../bin/heatTransfer_write_adios2: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [bin/heatTransfer_write_adios2] Error 1
make[1]: *** [examples/heatTransfer/write/CMakeFiles/heatTransfer_write_adios2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by chuckatkins** [comment]
bzip2 is found but the CMake code is using features only found in newer versions of the bzip2 find module.  I'll port the newer find module locally to make sure the build doesn't break.

**Comment by williamfgc** [comment]
Reopening issue as it's still seen on TItan:  > cmake -DCMAKE_BUILD_TYPE=Release -DADIOS1_DIR=/sw/xk6/adios/1.12.0/cle5.2_gnu4.9.3/ ../ADIOS2
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Cray Programming Environment 2.5.9 C
-- Check for working C compiler: /opt/cray/craype/2.5.9/bin/cc
-- Check for working C compiler: /opt/cray/craype/2.5.9/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.5.9 CXX
-- Check for working CXX compiler: /opt/cray/craype/2.5.9/bin/CC
-- Check for working CXX compiler: /opt/cray/craype/2.5.9/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/upstream/FindBZip2.cmake:39 (include):
  include could not find load file:

    /ccs/proj/csc250/wgodoy/ADIOS2/cmake/upstream/SelectLibraryConfigurations.cmake
Call Stack (most recent call first):
  cmake/FindBZip2.cmake:8 (include)
  cmake/DetectOptions.cmake:14 (find_package)
  CMakeLists.txt:79 (include)


CMake Error at cmake/upstream/FindBZip2.cmake:40 (SELECT_LIBRARY_CONFIGURATIONS):
  Unknown CMake command "SELECT_LIBRARY_CONFIGURATIONS".
Call Stack (most recent call first):
  cmake/FindBZip2.cmake:8 (include)
  cmake/DetectOptions.cmake:14 (find_package)
  CMakeLists.txt:79 (include)


-- Configuring incomplete, errors occurred!
See also "/ccs/proj/csc250/wgodoy/build_gnu/CMakeFiles/CMakeOutput.log".

**Comment by williamfgc** [comment]
Can we issue an easy exception message so the user can fix it like disable BZip2 in Cmake: -DADIOS2_USE_BZip2=OFF   ?

**Comment by chuckatkins** [comment]
Fixed by #188
