### ISSUE TITLE
Attempting to use an MPI routine after finalizing MPICH

### ISSUE THREAD

**Issue by philip-davis** [ornladios/ADIOS2#1752]
I am seeing this error message on Cori when doing coupled gray-scott runs. I only see this using the BP4 engine, and I only see it on the reader (pdf_calc) side. Here is a tar of my job directory:
[issue2.tar.gz](https://github.com/ornladios/ADIOS2/files/3622899/issue2.tar.gz)

This is a 256x8 job.

**Comment by pnorbert** [comment]
Fixed in pdf_calc in [https://github.com/pnorbert/adiosvm](https://github.com/pnorbert/adiosvm), commit [547306a](https://github.com/pnorbert/adiosvm/commit/547306a935d45204ec509e0af06540aac05d3045)
