### ISSUE TITLE
Warnings from static build on Titan

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#176]
../../../lib64/libadios2sys.a(SystemTools.cxx.o): In function `adios2sys::SystemTools::ConvertToUnixSlashes(std::string&)':
SystemTools.cxx:(.text+0x1cbe): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
../../../lib64/libgtest.a(gtest-all.cc.o): In function `testing::internal::StreamingListener::SocketWriter::MakeConnection()':
gtest-all.cc:(.text+0xd718): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by chuckatkins** [comment]
These can be safely ignored.  It's an artifact of the fully static build.

**Comment by williamfgc** [comment]
OK, let me try to compile a list of known issues. Thanks!
