### ISSUE TITLE
ZFP not found in 2.5.0

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#1800]
Hi,

within the release 2.4.0 to 2.5.0, the install of ADIOS2 cannot find zfp anymore.
Related to https://github.com/spack/spack/pull/12987

Probably caused by #1784

With Spack, ZFP 0.5.1-0.5.4 provided and ADIOS 2.5.0:
```
1 error found in build log:
     15    -- Detecting CXX compile features
     16    -- Detecting CXX compile features - done
     17    -- Found Blosc: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.3.0/c-blos
           c-1.17.0-q5lqzezea6b7b5v4lt2aogurt3k6y3w3/lib/libblosc.so (found suitable version "1.17.0
           ", minimum required is "1.7")
     18    -- Found BZip2: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.3.0/bzip2-
           1.0.8-y3jwkzygasvmix7wsxsp7ughqon54dl5/lib/libbz2.so (found version "1.0.8")
     19    -- Looking for BZ2_bzCompressInit
     20    -- Looking for BZ2_bzCompressInit - found
  >> 21    CMake Error at cmake/DetectOptions.cmake:36 (find_package):
     22      Could not find a package configuration file provided by "zfp" (requested
     23      version 0.5.1) with any of the following names:
     24    
     25        zfpConfig.cmake
     26        zfp-config.cmake
     27
```

**Comment by ax3l** [comment]
Ah, the problem is likely that ZFP does have various install methods and Spack uses the Makefile approach for it so far -.-

**Comment by chuckatkins** [comment]
CMake is the preferred build mechanism for zfp, see https://zfp.readthedocs.io/en/release0.5.5/installation.html, so the spack package should probably transition towards that (although I don't think there's a viable way to do that yet, right?).  That being said, I can restore the find module for "legacy" installations.

**Comment by ax3l** [comment]
Hm, I will just update the Spack package then. Sounds to me the CMake variant of ZFP is what we should support only...

**Comment by ax3l** [comment]
Urgh, ADIOS 1.13.1 does not understand the ZFP CMake install... Can we fix that and I can patch it in Spack?

**Comment by ax3l** [comment]
Ok, I provided a patch for ADIOS1 (https://github.com/ornladios/ADIOS/pull/204) that I can use. So let's stay with the ZFP CMake only version.
