### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AaronV77** [ornladios/ADIOS2#1813]
Hey everyone,

I'm getting the following error when trying to build 2.4 on Onyx at ERDC. I don't know why I'm getting this error message, because in cmake I am specifiying the gcc compiler and all should be well. Is this an ADIOS bug or something that I haven't loaded properly on Onyx? Lastly, this isn't a lot of information to go off of, so let me know what other files might be helpful for tracking down this issue. 

```
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: ../../../../../lib64/libadios2_enet.a(unix.c.o): in function `enet_address_set_host':
unix.c:(.text+0x15f): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../../../../../lib64/libadios2_evpath.a(ip_config.c.o): in function `get_qual_hostname':
ip_config.c:(.text+0xdba): warning: Using 'gethostbyaddr' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../../../../../lib64/libadios2_evpath.a(ip_config.c.o): in function `get_self_ip_iface':
ip_config.c:(.text+0x400): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Thanks!

**Comment by eisenhauer** [comment]
Thoughts, @chuckatkins ?   gethsotbyaddr/gethostbyname are deprecated and should be replaced, but getaddrinfo (and getnameinfo) are what you'd replace them with.  I think the Linux-generic solution here is to use the glibc-static package, but Crays are odd beasts...

**Comment by chuckatkins** [comment]
The warnings are expected when building networking code statically, although I'm not sure how that will affect the runtime behavior.  The error though should not be happening.  When building are you using gcc directly or through the craype wrappers?  On onyx, and really any cray, you generally want to be using the wrappers.  If you're using gcc directly then try using the wrappers instead by setting `export CC=cc CXX=CC FC=ftn`.

**Comment by eisenhauer** [comment]
As Chuck mentions, those warnings are expected when linking networking code statically, and generally they don't cause run-time failures.  Just a wild guess here, because it's not clear what you're doing, but on at least some Crays the default compilation environment produces executables that only run on the compute nodes, not the login nodes.  This always makes running tests considerably more awkward because you can't do it where you built the code.  Might this be the case here?

**Comment by AaronV77** [comment]
@eisenhauer is there a log for reasons why tests have failed? I believe that there is no aprun / mpirun able to be ran on our login nodes to prevent people running their code. Thanks

**Comment by eisenhauer** [comment]
There's no log per se, but you can run "ctest -VV" which gives verbose output from all the tests.  Then again, if absolutely everything is failing, simply running the "bin/hello_bpWriter" in your build directory would probably be informative.  It it works, it should give output like this:

bash-3.2$ bin/hello_bpWriter
Wrote file myVector_cpp.bp to disk. It can now be read by running ./bin/hello_bpReader.
bash-3.2$
