### ISSUE TITLE
endian_reverse should be in BP

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#1822]
Migrated from [here](https://github.com/spack/spack/pull/13107#discussion_r333224411) so it does not get lost.

The CMake flag `ADIOS2_USE_ENDIAN_REVERSE=ON` looks scary to me for the following reason: if a file was written in one endinaness and read again in another, the BP file format should encode that and our BPEngine could automatically take care of it. (E.g. HDF5 does it that way).

I was working/interning a few years ago in Juelich where serveral big and little endian machines were connected to the same file system and workflows going back and forth were common. Using various adios modules, depending on the origin of the data, would be very complicated.

If it's not possible to already express this in BP itself, which I think it should be for portability, then we should at least make this a runtime option for now.

**Comment by williamfgc** [comment]
@ax3l what's the actual issue? Please, see my explanation in the referenced link.

**Comment by pnorbert** [comment]
Basically, if you know you/your users need to deal with endianness, you
need to build adios with this flag everywhere. Then the conversion will
happen automatically and only if needed. It is not a forced flag on all
data.

I don't think this flag would make a big difference in read performance,
but never measured it myself, and it's not always on.

**Comment by williamfgc** [comment]
Also, there is a lack of testing due to limited access to such configuration in our CI. The feature itself is not fully tested (in CI or nightly), it was just done for one user who kindly provided some tests.

**Comment by ax3l** [comment]
The problem is that endian portability and conversion should be done automatically, not by a user and most certainly not by yet-an-other binary variant of the library. As explained in the description, that makes workflows super complicated.

Imagine the following: machine A writes big endinanness to the FS, machine B is small endian and also writes to the FS.
Now I process *both* data on system B, am I supposed to reload the ADIOS2 module for each access? Shall I link two ADIOS2 libraries? Thinks like that.

**Comment by williamfgc** [comment]
@ax3l nothing is preventing turning this ON if that is appropriate for the system use case.

> The problem is that endian portability and conversion should be done automatically

Not really, we only had one case that required this feature

**Comment by williamfgc** [comment]
@ax3l I think this is more of a system admin packaging problem than an adios2 problem. Would you agree?

**Comment by ax3l** [comment]
Well in my opinion, I think the workflow I describe in detail in the PR description is not supported yet and BP is not portable due to it.

I think a portable fileformat (BP) or adios engine of any kind should be self-aware of its endianness (just encode it) and then just flip during read properly when required, without interaction from user or sysadmin. I really do not think this should be a compile time option or even a runtime option, but a feature of adios data reading/writing.

**Comment by pnorbert** [comment]
I was not aware that the BP file itself is not recording its endianness
properly. I thought only the reader library is affected by the flag. If the
library is compiled with the flag, it should automatically read BP files
from both little and big endian systems.

Isn't that so?

**Comment by williamfgc** [comment]
@ax3l OK, thanks for your input. I see the confusion, and I second @pnorbert response. Any BP file (regardless of compilation options) is aware of its endianness. The decision workflow should be: do we ever going to read big and little endian BP files on our target system? If yes, then turn it on, but knowing that we don't test on CI or nightly, if no (the majority of our users) then do nothing.

**Comment by ax3l** [comment]
Ohh, [I see](https://github.com/ornladios/ADIOS2/blob/v2.5.0/source/adios2/helper/adiosMemory.inl#L183-L194). This is just enabling *potential* runtime endian-transforms, yet only when they are necessary!

I think there is a new doc string in 2.4.0+ as well that says: `Big/Little Endian Interoperability for different endianness platforms at write and read.`

Well, all of that makes a lot of sense now. The short spack variant string `Enable Endian Interoperability` confused me.

Mea cupla and thanks for the clarification. Will update the spack variant description.

**Comment by ax3l** [comment]
Shall we generally update the string on that option to something like `Enable endian conversion if a different endianness is detected between write and read.`?

**Comment by williamfgc** [comment]
@ax3l no problem, improving the documentation is always welcome. To be fair, I used [boost's endian_reverse terminology](https://www.boost.org/doc/libs/1_59_0/libs/endian/doc/conversion.html#endian_reverse), but feel free to make the description more clear.

**Comment by williamfgc** [comment]
Also, the functionality in the code is based on calls to [std::reverse](https://en.cppreference.com/w/cpp/algorithm/reverse), but this is more general than for just endianness.

**Comment by ax3l** [comment]
Hehe, sorry again for confusing this. I should have just immediately grep-ed in the source for what it is doing.
