### ISSUE TITLE
Dims of size_t potentially problematic in 32-bit systems

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#1823]
As we discussed last Monday, I think that the [definition of `adios2::Dims`](https://github.com/ornladios/ADIOS2/blob/v2.5.0/source/adios2/common/ADIOSTypes.h#L188) as of
```C++
using Dims = std::vector<size_t>;
```

might be potentially a bit problematic. The problem I am describing here applies to clusters of 32bit systems, such as Raspberry PI clusters, older Nvidia Tegra systems, among others. (Been there with PIConGPU, done that.)

`adios2::Dims` are used, inter alia, for (global) `shapes`, `counts` and `start`s (/offsets) in user-control. Since these metadata attributes are somewhat loose in ADIOS, user-level concepts like a [moving simulation window](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions#moving-window) can at some point overflow the range of `size_t` for e.g. the `start`. Similar problems can occur when writing the 1D shape of dataframes/tabular data, such as global particle arrays.

It is therefore probably safer to define this to a [fixed integer type, such as](https://github.com/openPMD/openPMD-api/blob/0.9.0-alpha/include/openPMD/Dataset.hpp#L33-L34)
```C++
#include <vector>
#include <cstdint>

// ...
using Dims = std::vector< std::uint64_t >;
```

**Comment by williamfgc** [comment]
There are lot more issues with 32-bit systems we'd need to tackle (starting with array indexing and memory limitations). The decision was to not dedicate resources and stick with what the STL does in memory which is all size_t based anyways, `e.g. vector::size()` . The only issue I see to trying to read large datasets from 64-bit systems on 32-bit platforms. Not sure if it's a priority, but I'd would be happy to help anyone willing to maintain and support this.

**Comment by ax3l** [comment]
The last thing you mention is a third case where this is problematic, yep.

Even if we cannot support internal data structures yet, if they are based on `vector::size()`, we can at least already fix the `adios2::Dims` which allows meta-data such as offsets (case: moving simulation window with only partial filling) to go very large over time.

**Comment by williamfgc** [comment]
Are there 32-bit production systems where we can test at scale?

**Comment by ax3l** [comment]
Testing is a good question, do you still have a [tiny Titan](https://www.olcf.ornl.gov/olcf-resources/rd-project/tiny-titan/) instance around? That's seriously one of the platforms we should support for teaching.
There are some cloud services though, [mythic-beasts](https://www.mythic-beasts.com/), [AWS](https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-linux-2-now-supports-32-bit-applications-and-libraries/), ...

> Those large offsets can't be used as indices in 32-bit systems...

Aren't they just meta-data in ADIOS as well for individual process groups? They would be stored and diff-ed for visualization/processing purposes anyway.

**Comment by williamfgc** [comment]
> Aren't they just meta-data in ADIOS as well for individual process groups?

We need to use (payload) offsets in calls to POSIX read, STL buffer and map access, both of which are `size_t` based, so a large enough offset from `uint64_t` dims can't even be used internally. My point is that there is little to no gain to not stick with the standard `size_t`, especially since the core business of adios has always been I/O performance at scale which translates to 64-bit production environments. The community is welcome to use adios2 in 32-bit systems, but [we don't dedicate resources for testing and maintenance](https://adios2.readthedocs.io/en/latest/setting_up/setting_up.html#building-on-hpc-systems) at the moment (it's a hard sell in 2019).

**Comment by ax3l** [comment]
I see. Then let's close this, it's not too urgent and I just wanted to document the use case. I agree with your rationale.
