### ISSUE TITLE
Downstream RPATH overwritten

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#1825]
I am using the `ADIOS2Config.cmake` module for v2.5.0 downstream in openPMD-api.

Somehow, the ADIOS2 `CMakeLists.txt` lines overwrite my *downstream* [`-DCMAKE_INSTALL_RPATH=$ORIGIN`](https://github.com/openPMD/openPMD-api/blob/130f7d3ceef25a1412515987728209ccd0ecb31e/setup.py#L60) setting to read `$ORIGIN/.libsopenpmd_api` instead of `$ORIGIN`.

https://github.com/ornladios/ADIOS2/blob/v2.5.0/CMakeLists.txt#L156-L179

As soon as I am not linking to ADIOS2 anymore, the problem is gone.

Probably we should only set the rpath as CMake property on targets or append to already set, user-provided `CMAKE_INSTALL_RPATH` locations?

**Comment by ax3l** [comment]
the problem is caused downstream by my setuptools scripts.

Reason: `libffi-2009cab3.so.5.0.6` not packaged. Sorry for the noise!

**Comment by ax3l** [comment]
related question: is `libffi` always shared, even if we try to build ADIOS2 as static library?

And if yes, what functionality do I loose if I disable it?

**Comment by eisenhauer** [comment]
@chuckatkins Can say more about the static/shared aspects.  But, libffi is used by dill, which is used by FFS/EVPath for dynamic code generation.  This DCG is used to reduce data transformation overhead in heterogeneous data exchanges, and for remote data transformation/filtering/reduction/subsampling, etc.  But as you've seen in other issues, easy fast support for heterogeneity isn't as much a priority in ADIOS, and there's no ADIOS API for remote data reduction/filtering, so this functionality is largely unused.  libffi comes into the picture when DILL doesn't have a native instruction port.  ffi is then used to create an emulation so EVPath could do still the data reduction, albeit slower than DCG speeds.  libffi *should* only be pulled in on unsupported architectures (x86 is supported).  So, aside from the shared/static nature of its inclusion, I'm curious why it's been pulled in to begin with.  Is this for Conda?  Which platform?

**Comment by ax3l** [comment]
Thanks for the details, this looks interesting for future use!

Conda (-forge) builds are by default shared like in proper Unix builds, same for Spack. I am currently updating our serial, x86_64 ["manylinux2010"](https://www.python.org/dev/peps/pep-0571/) binary wheel recipe [for PyPI](https://openpmd-api.readthedocs.io/en/0.9.0-alpha/dev/release.html#pypi) which is performed via a [`Dockerfile`](https://github.com/openPMD/openPMD-api/blob/dev/Dockerfile).

In that and some other usability situations (such as [wasm](https://github.com/openPMD/openPMD-api/issues/295)) the target architecture is well-defined and a fully static build is ideal for shipping. How do you recommend to configure ADIOS2 with regards to libffi in such a situation and what are the proper CMake flags for it? As it looks to me, libffi is only needed when the architecture is [not in that list](https://github.com/GTkorvo/dill/blob/v2.4.1/CMakeLists.txt#L62-L100)? Yet DILL pulls in `find_package(LibFFI)` [for all platforms so far](https://github.com/GTkorvo/dill/blob/v2.4.1/CMakeLists.txt#L142).

@chuckatkins According to Gregs argument above, should the `LibFFI` search be guarded in DILL? Or shall I just set `-DCMAKE_DISABLE_FIND_PACKAGE_LibFFI` as a user?

**Comment by eisenhauer** [comment]
If there's something you can do as a user, please go for it.  Generally I think that given the circumstances of how ADIOS2 uses EVPath/FFS, we should probably exclude the use of libffi with something in ADIOS2.  BUT, this is all kind of interwoven with complex logic and we have some folks at JAXA running this on Sparcs.  The Sparc DCG is incredibly old, so they build with it disabled, but I want to make sure we don't break what seems to be working for them.  So, I'll tackle this within ADIOS (maybe FFS/EVPATH/DILL), but it might be a little while before I get comfortable with the mods.
