### ISSUE TITLE
Staging tests don't work with multiconfig generators

### ISSUE THREAD

**Issue by chuckatkins** [ornladios/ADIOS2#1843]
The staging tests are expecting executables to be in bin/Foo whic is not the case for multi-config generators like Visual Studio and XCode.  See https://open.cdash.org/testDetails.php?test=816980556&build=6179972

The test commands likely need to be adapted to use generator expressions like `$<TARGET_FILE:Foo>` instead of assuming `${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Foo`

**Comment by eisenhauer** [comment]
Generator expressions are an arcane mysticism that have stretched the limits of my CMake-fu on the occasions I've tried to use them outside trivial use-cases.  (I.E. I've lost days to them, because I needed what they did, but not in a place where they were normally expanded.)  So, I'll give it a run, but I may need generator-expression-counseling...

**Comment by chuckatkins** [comment]
Basically `add_test(NAME FooTest COMMAND bar.py $<TARGET_FILE:Foo>)` resolves to passing the full path to the `Foo` output file as the first argument to `bar.py` for the test named `FooTest`.  It will adapt accordingly to multiconfig generators putting their output in `bin/Debug/Foo` and `bin/Release/Foo` in the same build by setting up different arguments for the test depending on which build configuration is being used at the time of execution.

**Comment by eisenhauer** [comment]
Yeah, that's a standard use case where generator expression expansion works, but not how staging-common test generation is setup  There's a bunch of string processing in the test command generation to create test variants with different engine parameters.  Currently the name of the executable for the reader and the writer is part of the _CMD string that serves as the basis for those test mutations.  We could change that to be <TARGET_FILE:TestCommonRead_f>, but it's in a string, so I think it doesn't get expanded trivially, and getting it expanded somewhere and then carried to where we need it to be is (at least to me) non-obvious.
