### ISSUE TITLE
cmake install with relative path fails

### ISSUE THREAD

**Issue by dpugmire** [ornladios/ADIOS2#1863]
make install will fail if I use an install dir with a relative path in it.

For instance: I have a build and install dir that are in the same subdir.

cmake -DCMAKE_INSTALL_PREFIX=../install SRC-DIR

make will be fine, but make install will fail.

(sorry i put the wrong command in... this is an edit. I did use the cmake_install_previx)

**Comment by NAThompson** [comment]
I just replicated this using CMake 3.14.5. But I don't get a hard fail; it appears `CMAKE_PREFIX_PATH` is simply ignored.

But just looking through the `CMakeLists.txt`, it appears that the `CMakeLists.txt` is looking for `CMAKE_INSTALL_PREFIX`.

**Comment by chuckatkins** [comment]
> For instance: I have a build and install dir that are in the same subdir.

@dpugmire does it work if you use separate directories?  i.e. source, build, and install all at the same level instead of subdirs of eachother?

**Comment by chuckatkins** [comment]
> make will be fine, but make install will fail.

And also, what fails with `make install`?

**Comment by chuckatkins** [comment]
AFAIK we have since resolved all of the make install issues.  If this still occurs, please re-open.
