### ISSUE TITLE
HDF5 Engine needs to support memory selections

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#1866]
The Gray-Scott example has ghost cells that must not be written. Since memory selection is supported in ADIOS, there is an option (in simulation/settings-file.json  "adios_memory_selection": true) to use it in Gray-Scott writer.cpp (var_u.SetMemorySelection()).

So far we have used the original writing code that used a function to copy out the actual data to provide a contiguous array for ADIOS Put() without memory selection. But BP and SST now supports memory selection and it's time to retire this code in Gray-Scott that does an extra memory copy. 

Plotting with gsplot.py will make it obvious that the data is invalid when writing with the HDF5 engine and using memory selections.

**Comment by pnorbert** [comment]
Changing this to Bug level since it is an issue with the Tutorial. The "proper" adios code is not portable to HDF5 output, forcing gray-scott to use inefficient code (extra copy).

**Comment by guj** [comment]
@pnorbert
Hi Norbert,  I am not sure  what you meant by "proper"adios code? 
where is the extra copy in gray-scott?

- Junmin

**Comment by pnorbert** [comment]
gray-scott/simulation/writer.cpp line 112
```
    std::vector<double> u = sim.u_noghost();
```
That function makes a copy of the data sim.u without the ghost cells. 
The "proper" code uses memory selection, and in line 89
```
     const std::vector<double> &u = sim.u_ghost();
```
will just use the sim.u data pointer as is.

**Comment by guj** [comment]
Hi Norbert, 

I let  adios_memory_selection = true in my setting
And tried both bp and h5. 
The gs.bp and gs.h5 have the same content. 

Anything else I shall set?  This. is my json setting file: 

    "L": 64,
    "Du": 0.2,
    "Dv": 0.1,
    "F": 0.01,
    "k": 0.05,
    "dt": 2.0,
    "plotgap": 100,
    "steps": 1000,
    "noise": 0.0000001,
    "output": "gs.h5",
    "checkpoint": false,
    "checkpoint_freq": 10,
    "checkpoint_output": "gs_ckpt.h5",
    "adios_config": "adios2.xml",
    "adios_span": false,
    "adios_memory_selection": true,
    "mesh_type": "image"


- Junmin

**Comment by pnorbert** [comment]
I was using 2.5.0. Is this the master? Maybe it was already fixed?
Can you run gsplot.py and make sure the plots look right?
Thanks

**Comment by guj** [comment]
Yes I am using master.

Here is video of gsplot.py on h5 file (plotga=10, steps=1000)

https://youtu.be/AmnNx29Q_HE <https://youtu.be/AmnNx29Q_HE>

- Junmin

**Comment by pnorbert** [comment]
Resolved. Thanks for testing this.

The issue appears on the VM with the ADIOS 2.5.0 installation from github source (commit 837d1b0eadd2bda0e6f39b151edb01d6e4bc5016). It does not appear with master or with an installation from the downloaded 2.5.0 tarball.
