### ISSUE TITLE
conda install fails if zeromq is not pre-installed on Mac

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#1869]
**Describe the bug**

On Mac, I ran:

```
(base) ➜  anaconda3 conda install -c williamfgc adios2-nompi
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/4nt/opt/anaconda3

  added / updated specs:
    - adios2-nompi


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    adios2-nompi-2.4.0         |      0_g9c94bbb0         3.0 MB  williamfgc
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following NEW packages will be INSTALLED:

  adios2-nompi       williamfgc/osx-64::adios2-nompi-2.4.0-0_g9c94bbb0


Proceed ([y]/n)? y


Downloading and Extracting Packages
adios2-nompi-2.4.0   | 3.0 MB    | ############################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) ➜  anaconda3 python3
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import adios2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/4nt/opt/anaconda3/lib/python3.7/site-packages/adios2.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Users/4nt/opt/anaconda3/lib/libadios2.2.4.0.dylib
  Reason: image not found
>>>
```

I was able to work around this via `brew install zeromq`, but then I hit:

```
(base) ➜  anaconda3 python3
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import adios2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/4nt/opt/anaconda3/lib/python3.7/site-packages/adios2.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/c-blosc/lib/libblosc.1.dylib
  Referenced from: /Users/4nt/opt/anaconda3/lib/libadios2.2.4.0.dylib
  Reason: image not found
```

I then ran:

```
$ conda install -c conda-forge python-blosc
```

but no joy.

**Expected behavior**

Actually I don't know what to expect here. Is conda supposed to bring in all subdependencies or am I expected to have them on my machine?

**Desktop (please complete the following information):**

 - OS/Platform: Mac

**Comment by williamfgc** [comment]
Hi @NAThompson , conda expects that you provide the appropriate dependencies, either from the system or from conda channels. For new environments, you have to add conda-forge as a channel as well, check the [description](https://anaconda.org/williamfgc/adios2-openmpi):

Depends on conda-forge packages, if starting from an empty environment:

`conda install -c williamfgc adios2-openmpi -c conda-forge`

**Comment by williamfgc** [comment]
Also, I notice conda is downloading v2.4.0 when the head is v2.5.0. Let me check with you tomorrow. Thanks for looking into this.

**Comment by NAThompson** [comment]
Got it to work by doing a source build of [blosc](https://github.com/Blosc/c-blosc).

**Comment by williamfgc** [comment]
you should be able to pull all of adios2 dependencies after a `conda update --all`, please let me know
This should do the work (assuming no conflict with system packages):
`conda update --all`
`conda install -c williamfgc adios2-openmpi -c conda-forge`

**Comment by NAThompson** [comment]
@williamfgc : Just tested your suggestion after uninstalling zeromq from brew; no joy. Same for `blosc`.

**Comment by williamfgc** [comment]
@NAThompson try from an empty environment first `conda create -n test_adios2-openmpi`
