### ISSUE TITLE
Operation parameters failing if not lower case

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#1875]
**Describe the bug**
Allow operation parameters to be case insensitive. Currently crashing if they are not lower case.

**To Reproduce**
`var.AddOperation("zfp", {{"Accuracy", "8"}});` fails
`var.AddOperation("zfp", {{"accuracy", "8"}});` works

**Desktop (please complete the following information):**
 - OS/Platform: any
 - Build: any compiler

**Comment by NAThompson** [comment]
Fixed in [2004](https://github.com/ornladios/ADIOS2/pull/2004).
