### ISSUE TITLE
MPI const void* issue

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#191]
source/adios2/CMakeFiles/adios2.dir/toolkit/profiling/iochrono/Timer.cpp.o
/mnt/c/Users/ywy/Software/ADIOS2/source/adios2/toolkit/format/bp1/BP1Aggregator.cpp: In member function ‘std::string adios2::format::BP1Aggregator::GetGlobalProfilingLog(const string&)’:
/mnt/c/Users/ywy/Software/ADIOS2/source/adios2/toolkit/format/bp1/BP1Aggregator.cpp:120:74: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
        MPI_Isend(&rankLogSize, 1, MPI_INT, 0, 0, m_MPIComm, &requestSize);

**Comment by chuckatkins** [comment]
Fixed by #192
