### ISSUE TITLE
ADIOS SST Engine is failing

### ISSUE THREAD

**Issue by abidmalikwaterloo** [ornladios/ADIOS2#1910]
I am using ADIOS2 in my application. I am not an expert on ADIOS. I am getting the following:

```
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-3.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-16.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-7.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-11.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-18.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-4.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-10.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-0.bp to be created
ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-9.bp to be created
Exception caught
ERROR: SstReader did not find active Writer contact info in file "/gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-12.bp.sst".  Timeout or non-current SST contact file?
Exception caught
ERROR: SstReader did not find active Writer contact info in file "/gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-13.bp.sst".  Timeout or non-current SST contact file?
Exception caught
ERROR: SstReader did not find active Writer contact info in file "/gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-6.bp.sst".  Timeout or non-current SST contact file?
Exception caught
ERROR: SstReader did not find active Writer contact info in file "/gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-17.bp.sst".  Timeout or non-current SST contact file?
```
Any hint and guidance?

**Comment by eisenhauer** [comment]
Make sure the writer has specified the SST engine and make sure the same name is used in both the reader and writer open statements...  possible file name problem.

**Comment by abidmalikwaterloo** [comment]
@eisenhauer Thanks:
I am using 20 clients each dumping file for the reader. The following is one example:
```
/gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-18.bp.sst
```
So the file exists.  However, in the file I found the following information:
```
ADIOS2-SST v0
0x4731dd40:AAIAAJTJ8o3vZQAAATkCmNkHhgo=
```
Is this complete information?

The error message is coming from engine/sst/SstReader.cpp 
```
m_Input = SstReaderOpen(cstr, &Params,
#ifdef ADIOS2_HAVE_MPI
                            CommAsMPI(m_Comm)
#else
                            MPI_COMM_NULL
#endif
    );
    if (!m_Input)
    {
        throw std::runtime_error(
            "ERROR: SstReader did not find active "
            "Writer contact info in file \"" +
            m_Name + SST_POSTFIX +
            "\".  Timeout or non-current SST contact file?" + m_EndMessage);
    }

```
It looks like the n_Input is NULL.

**Comment by eisenhauer** [comment]
Yes, the contents of the SST contact information file is fine, and yes, that is where the exception is raised when SST fails to find the contact information file.  But what are the filenames that you specify in the open() statements on the read and write side?  They should be the same.  Maybe you have a postfix in one and not in the other?  You can set the environment variable SstVerbose=1 to get more info.

**Comment by eisenhauer** [comment]
Although actually, you're opening 20 concurrent streams?  Are some open's succeeding and others not?  Sorry, I was thinking this was a simple use-case.   If you're opening one independent stream from each writer (presumably after an MPI split that gives you a single node MPIComm and then trying to open them all (maybe on a single reader?), then this is a very atypical use of SST, and I probably need a lot more details to sort out what is going on.

**Comment by abidmalikwaterloo** [comment]
@eisenhauer I am attaching some detailed output
[adios2.pdf](https://github.com/ornladios/ADIOS2/files/3990130/adios2.pdf)
 with SstVerbose=1.

**Comment by eisenhauer** [comment]
Assuming that this output is temporally ordered, all the readers try to do their open() and eventually timeout without having a writer appear.  Then after they have all failed, the writers show up (towards the end of page 8).  Not having job script, or code or anything else I can't really guess what might be happening, but the writers not starting until the readers have all given up would seem to be the core of the problem.

**Comment by abidmalikwaterloo** [comment]
I am writing part of the script where I launch the reader and writer.

```
cd ${WORK_DIR}
#if true; then
echo ""
echo "==========================================="
echo "Launch Chimbuko parameter server"
echo "==========================================="
jsrun -n 4 -a 1  -c 2 -g 0  bin/app/hpserver 160 "${WORK_DIR}/parameters.txt" &

sleep 5



echo ""
echo "=========================================="
echo "Launch Application with anomaly detectors"
echo "=========================================="
# this is the reader
jsrun -n 20 -a 1  -c 2 -g 0  -b none bin/app/driver $BP_ENGINE $WORK_DIR/BP $BP_PREFIX \
     "${EXECUTION_PATH}" 4 ${AD_SIGMA} ${AD_WINSZ} ${AD_INTERVAL} &



### the following is the writer dumping the information
jsrun -n 20  -a 1 -c 2 -g 0  -b none ./nwchem 4pgs-1M-prepare-equil-md.nw

#wait $ps_pid

#sleep 60

cd $WORK_DIR
echo "BP size: `du -sh BP`"
echo "DB size: `du -sh db`"
echo "execution: `du -sh executions`"


```

**Comment by eisenhauer** [comment]
Is it possible that the writer is spending a lot of time doing other things before it establishes the output streams?  You can change the amount of time that the readers will wait before they timeout by setting the     engine parameter "OpenTimeoutSecs".  Its default value is 60 seconds...

**Comment by abidmalikwaterloo** [comment]
@eisenhauer Is this a system environment variable or adios library variable that I need to declare in the reader file (reader program)?

**Comment by eisenhauer** [comment]
ADIOS2 has gone in the direction of "engine parameters", which are (perhaps oddly) set in the IO before the engine is created, either programatically or via the ADIOS2 XML interface.  This is the programatic interface from the docs:

/** Signature */
/** Passing several parameters at once */
void SetParameters(const adios2:Params& parameters);
/** Passing one parameter key-value pair at a time */
void SetParameter(const std::string key, const std::string value);

/** Examples */
io.SetParameters( { {"Threads", "4"},
                    {"ProfilingUnits", "Milliseconds"},
                    {"MaxBufferSize","2Gb"},
                    {"BufferGrowthFactor", "1.5" }
                    {"FlushStepsCount", "5" }
                  } );
io.SetParameter( "Threads", "4 );

**Comment by abidmalikwaterloo** [comment]
@eisenhauer  I looked into the reader code.

```
ADParser::ADParser(std::string inputFile, std::string engineType)
    : m_engineType(engineType), m_status(false), m_opened(false), m_attr_once(false), m_current_step(-1)
{
    m_inputFile = inputFile;
    m_ad = adios2::ADIOS(MPI_COMM_SELF, adios2::DebugON);

    // set io and engine
    m_io = m_ad.DeclareIO("tau-metrics");
    m_io.SetEngine(m_engineType); // here we are setting the SST engine
    m_io.SetParameters({
        {"MarshalMethod", "BP"},
        {"DataTransport", "RDMA"}
    });

    // open file
    // for sst engine, is the adios2 internally blocked here until *.sst file is found?
    std::cout << "Trying to open the file" << m_inputFile << std::endl;
    // m_inputFile is the file reader is looking for. I checked. Its with out sst extension
/* ADIOS2 SST Engine waiting for contact information file /gpfs/alpine/scratch/amalik/csc299/MHPSERVER/nwchem-11-10-SST/BP/tau-metrics-3.bp to be created

Should it be with *.sst extension?
*/

    m_reader = m_io.Open(m_inputFile, adios2::Mode::Read, MPI_COMM_SELF);
    std::cout << " The file has been opened[check]"<< std::endl;

    m_opened = true;
    m_status = true;
}


```
Any comments will be appreciated. I am stuck here!

**Comment by eisenhauer** [comment]
I'm not sure exactly what to comment on here.  WRT the question in the comment, just make sure the m_inputFile is the same name, with our without extension as is the output file.  The m_io.SetParameters can be changed to add {"OpenTimeoutSecs", "300"} or however long you think you need to make the readers wait so that they don't give up before the writers create the files.  (That is maybe the problem?  That 60 seconds after reader open() the writers still haven't done their open and the readers give up?)

**Comment by eisenhauer** [comment]
Hi Abid, just checking in on status...   Anything I can help with?

**Comment by abidmalikwaterloo** [comment]
@eisenhauer Sorry for the late update. I was able to fix it. It was due to the resource deadlock. I was running readers and there were not enough resources for the writers. Therefore, the readers were waiting forever.
