### ISSUE TITLE
Python tests not found

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#194]
Not sure if related to issue #193 

Found PythonInterp: /usr/bin/python (found version "2.7.11") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Found PythonModule_mpi4py: /usr/lib/python2.7/dist-packages/mpi4py  

Installation prefix: /usr/local
  Features:
    Library Type: shared
    Build Type:   Debug
    Testing: ON
    Build Options:
      BZip2    : ON
      ZFP      : ON
      MPI      : ON
      DataMan  : ON
      ZeroMQ   : ON
      HDF5     : ON
      ADIOS1   : ON
      Python   : ON
      SysVShMem: ON

$ ls ./bin
globalArray_write         heatTransfer_write_a2h5    heatTransfer_write_hdf5  hello_bpFlushWriter  hello_datamanReader  joinedArray_write  reader_stepping          TestXMLConfig
heatTransfer_read_adios1  heatTransfer_write_adios1  heatTransfer_write_ph5   hello_bpTimeWriter   hello_datamanWriter  localArray_write   TestADIOSInterfaceWrite  values_write
heatTransfer_read_adios2  heatTransfer_write_adios2  hello_adios1Writer       hello_bpWriter       hello_hdf5Writer     reader_allsteps    TestHDF5WriteRead        writer_multiste

**Comment by chuckatkins** [comment]
It won't show up in bin but the test is still there.  Do you see the `PythonBPWrite` tests when you run `ctest -N` ?

**Comment by williamfgc** [comment]
Yes, it's:  Test #33: PythonBPWrite
