### ISSUE TITLE
Install.Setup CI tests currently failing

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#1941]
**Describe the bug**
Install.Setup tests are currently failing at CMake configure stage on GitHub Actions / linux (el7-intel18-openmpi-ohpc). See [PR outcome](https://github.com/ornladios/ADIOS2/pull/1930/checks?check_run_id=403677355)

**To Reproduce**
See PR #1930 #1931.

**Expected behavior**
Test should pass

**Desktop (please complete the following information):**
 - OS/Platform: linux (el7-intel18-openmpi-ohpc)

**Additional context**
Scalability of Test output is problematic. It's very difficult to jump through the text on a (Chrome) browser.

**Comment by chuckatkins** [comment]
Resolved by updating CI images
