### ISSUE TITLE
need a general test for SetMemorySelection in multiple engines

### ISSUE THREAD

**Issue by eisenhauer** [ornladios/ADIOS2#1954]
Just opening an issue for this as a reminder.  When #1866 is resolved (or sooner), we should make sure that there's an actual test for memory selections that can be run on multiple engines.  Currently the only place we have for such things is staging-common.

**Comment by caitlinross** [comment]
Maybe this one can be closed? It looks like #3591 made TestADIOSSelection so it could be tested with different engines, but not sure if there are more tests you have in mind for this.

**Comment by eisenhauer** [comment]
Well, we can probably close.  Not because of #3591, but because a different PR both added a procedure through which we can use testing/adios2/engine/bp tests in engine/staging-common, and imported TestBPWriteMemorySelectionRead.cpp into staging-common so we can use it with staging and file engines.  (Getting the MemorySelection feature implemented in more engines is another matter.)
