### ISSUE TITLE
DataMan with multiple writes

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1958]
I am trying to write 2 files with DataMan in a single process without success. I.e., as shown in the following log, I am trying to write two files (`18431_ch000101_s000.bp` and `18431_ch000101_s001.bp`) with two different DataMan port numbers but getting the following error:
```
>>> num_analysis: 2
>>> Writer dataman_port: 12400
>>> Writer opening ... 18431_ch000101_s000.bp
>>> Writer dataman_port: 12401
>>> Writer opening ... 18431_ch000101_s001.bp
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: binding zmq socket failed
[1]    72091 abort      python ./receiver.py --config config-mbp.json
```

If I write a single file, it works. I think using multiple instances of zeromq in a single process has some issue.
@JasonRuonanWang can you give any advice?

**Comment by JasonRuonanWang** [comment]
Can you try to specify a different port number for the second stream? For example replace 12401 with 12411 or 12421. One DataMan stream needs multiple ports.

**Comment by jychoi-hpc** [comment]
I see. After adding 10 ports apart between writers, it works now. Thanks.
