### ISSUE TITLE
Starting with ADIOS2

### ISSUE THREAD

**Issue by aruhela** [ornladios/ADIOS2#2000]
What is the recommended way to start with ADIOS2? 

Is there available any Video tutorial to get an overview and basic usage of it ?

**Comment by pnorbert** [comment]
Hi, we don't have a video tutorial but here is the PDF of our latest tutorial. 
[https://users.nccs.gov/~pnorbert/adios-tutorial-2.5.0.pdf](https://users.nccs.gov/~pnorbert/adios-tutorial-2.5.0.pdf)

**Comment by aruhela** [comment]
Thanks for sharing the tutorial.

**Comment by ax3l** [comment]
Maybe we can add the link to the latest tutorial in the manual. That's the first entry point for new users.

**Comment by caitlinross** [comment]
Closing since we now have [self-directed tutorial available on read the docs](https://adios2.readthedocs.io/en/latest/tutorials/overview.html)
