### ISSUE TITLE
adios_reorganize hangs when launched in MPMD mode

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#2008]
adios_reorganize hangs when launched with other applications (heatTransfer, gray-scott, etc.) in MPMD mode. For example, the following hangs:

```
mpirun -n 4 build/gray-scott simulation/settings-staging.json : \
       -n 1 adios_reorganize gs.bp reorg.bp SST '' BP4 '' 1
```

This is needed for the JAXA use case and worked fine in the past.

**Comment by keichi** [comment]
The hang is caused by`helper::CommFromMPI`, which calls a collective function `MPI_Comm_dup` on `MPI_COMM_WORLD`. The other applications are therefore forced to call `MPI_Comm_dup` as well.

https://github.com/ornladios/ADIOS2/blob/1b12fed4299f00973acbd65369946ab28a1c9ccc/source/utils/adios_reorganize/Reorganize.cpp#L55-L56

**Comment by bradking** [comment]
#2011 should fix this.  Its description and commit message include a detailed explanation of what happened.
