### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by HannoSpreeuw** [ornladios/ADIOS2#2038]
**Describe the bug**
These commands from bash:
`wget https://raw.githubusercontent.com/ornladios/ADIOS2/master/scripts/docker/images/ubuntu18.04/Dockerfile`
`docker build -t adios2_im .`

output
```
Cloning into 'ADIOS2'...
CMake Error at CMakeLists.txt:6 (cmake_minimum_required):
  CMake 3.12 or higher is required.  You are running version 3.10.2
```

**Expected behavior**
A succesful build of the Ubuntu Bionic Docker image with Adios2 installed.

**Desktop (please complete the following information):**
This is on Manjaro Linux 19.0.2.
Docker version 19.03.6-ce, build 369ce74a3c

**Additional context**
Can fix this by using 
```
# FROM ubuntu:18.04
FROM ubuntu:19.10
```
Also, the paths need to be fixed or very few Unix commands can be issued from within a shell in the container:
```
ENV PYTHONPATH="/usr/local/lib/python3.6/site-packages/:/opt/adios2/lib/python3.6/site-packages:${PYTHONPATH}"
ENV PATH="/opt/adios2/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/lib:/opt/zfp/lib:/opt/sz/lib:/opt/adios2/lib:${LD_LIBRARY_PATH}"
```
E.g. `ls` will not work without the addition of `:${PATH}`.

Please let me know if you will accept a PR for these changes.

**Comment by germasch** [comment]
A more localized fix might be to add this to the Dockerfile:

```
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
RUN apt-get update
RUN apt-get install -y cmake
```

This will just update cmake to the latest release, rather than updating the whole base distro. (Credit: https://apt.kitware.com/)

**Comment by HannoSpreeuw** [comment]
I could copy that into the Dockerfile instead of Ubuntu 19.10.

**Comment by germasch** [comment]
@chuckatkins ?
