### ISSUE TITLE
CI: el7-gnu8-openmpi-ohpc-static builder broken on master

### ISSUE THREAD

**Issue by bradking** [ornladios/ADIOS2#2044]
Cc: @chuckatkins @eisenhauer @JasonRuonanWang  

Several PRs are blocked by failures of the `Install.Make.Fortran` test on the `el7-gnu8-openmpi-ohpc-static` CI build.

One can use [this CDash query](https://open.cdash.org/index.php?project=ADIOS&date=2020-03-17&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=el7-gnu8-openmpi-ohpc-static&field2=buildname&compare2=63&value2=master&field3=buildstarttime&compare3=83&value3=2020-02-15&field4=buildstarttime&compare4=84&value4=2020-03-18) to see that the test passed on that build in `master` consistently until 2020-03-12 and has failed consistently ever since.

The first version that failed in the `master` branch builder was commit bada93f0f5fcdcbacf5fb665981f14450aeb2101.  That commit merged #2032 where the failure had been seen during CI, but that PR was able to be merged eventually.

**Comment by bradking** [comment]
#2036 was based on an older version of `master` that did not have the merge of #2032 and its CI passed.

**Comment by chuckatkins** [comment]
Debugging in #2043

**Comment by chuckatkins** [comment]
I'm to disable in #2046 to unblock CI, but I'm sporadically seeing the same typed of linker failures in the build as well: https://open.cdash.org/viewBuildError.php?buildid=6416407

So I'm trying to force a serial build to see if that reliably makes it pass.

**Comment by bradking** [comment]
Doing the build serially will avoid problems with too many `ld` processes running at once on large binaries (which may hit memory or time limits).  If that works, maybe we can set `Install.*` test properties to serialize them too.

**Comment by chuckatkins** [comment]
I believe this has been resolved in #2046 by forcing `-j1`.  It got things unstuck for the time being but it still feels like a red herring since the tests were already running serially.  I don't really have a better answer atm and I wish I could assert it's resolution more definitively.

All that being said, it seems to work for now so I'm closing this.
