### ISSUE TITLE
Python binding issues

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#2047]
I get the following error when I try to run gray-scott. This was on Mac 10.15.3 with Clang 11.0.0, and Python 3.7.7. Python was installed through homebrew and is the only Python3 installation on the machine. 

 ```
jason@iMac  ~/w/adiosvm/Tutorial/gray-scott   master  mpirun --oversubscribe -n 4 build/gray-scott simulation/settings-staging.json :          -n 1 build/pdf_calc gs.bp pdf.bp 100 : -n 1 python3 plot/pdfplot.py -i pdf.bp
Traceback (most recent call last):
  File "plot/pdfplot.py", line 3, in <module>
    import adios2
  File "/usr/local/lib/python3.7/site-packages/adios2/__init__.py", line 1, in <module>
    from .adios2 import *
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/adios2/adios2.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /usr/local/lib/python3.7/site-packages/adios2/adios2.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/adios2/adios2.so
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[50203,1],5]
  Exit code:    1
--------------------------------------------------------------------------
```

The following error is a compile error I got from compiling ADIOS2 with python3 on Ubuntu 19.10. It was a brand new VM installation, with everything (gcc 9.2.1 and libpython3-dev) installed through apt. Cmake in this case is not able to find the python3 installation automatically. I had to specify DPython_LIBRARIES and DPython_INCLUDE_DIR, but it still didn't work.

```
 jason@vm  ~/build/adios2  cmake ~/d/a2 -DPython_LIBRARIES=/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7.so -DPython_INCLUDE_DIR=/usr/include/python3.7m
-- Could NOT find Blosc (missing: BLOSC_LIBRARY BLOSC_INCLUDE_DIR) (Required is at least version "1.7")
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find ZFP (missing: ZFP_DIR)
-- Could NOT find SZ (missing: SZ_LIBRARY ZLIB_LIBRARY ZSTD_LIBRARY SZ_INCLUDE_DIR) 
-- Could NOT find MGARD (missing: MGARD_LIBRARY ZLIB_LIBRARY BLOSC_LIBRARY MGARD_INCLUDE_DIR) 
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) (Required is at least version "1.6.0")
-- Found MPI: TRUE (found version "3.1") found components:  C Fortran CXX 
-- Could NOT find ZeroMQ (missing: ZeroMQ_LIBRARY ZeroMQ_INCLUDE_DIR) (Required is at least version "4.1")
-- Could NOT find DataSpaces (missing: DATASPACES_VERSION DATASPACES_INCLUDE_DIR DATASPACES_LIBRARIES DSPACES_LIBRARY) (Required is at least version "1.8")
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS C) (found version "")
CMake Error at cmake/upstream/FindPython/Support.cmake:2068 (if):
  if given arguments:

    "_Python_INC_VERSION" "VERSION_EQUAL"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/upstream/FindPython.cmake:326 (include)
  cmake/FindPython.cmake:8 (include)
  cmake/DetectOptions.cmake:213 (find_package)
  CMakeLists.txt:130 (include)


-- Configuring incomplete, errors occurred!
See also "/home/jason/build/adios2/CMakeFiles/CMakeOutput.log".
See also "/home/jason/build/adios2/CMakeFiles/CMakeError.log".
 ✘ jason@vm  ~/build/adios2  
```

**Comment by chuckatkins** [comment]
It looks like there's a few issues with `FindPython` specifically related to `>= 3.7`.  I'm working on a fix.

**Comment by chuckatkins** [comment]
Okay, I believe you and @eisenhauer are having the same issue and from what I can tell it's traced back to a missing distutils package.  Can both of you verify that the python distutils package is installed, and if not, try to install it and see if that works?

I believe I can rework FindPython to not rely on it for introspection but it's in a fair number of places so it might take a bit given that I'll need to iterate some with upstream.

**Comment by eisenhauer** [comment]
Yes, python3-distutils was missing, and once it's installed configuration works.  

So, I'm guessing that python3.7 was installed as a dependency for something, but doesn't quite fully install python?

**Comment by chuckatkins** [comment]
Tracking the issue upstream: https://gitlab.kitware.com/cmake/cmake/issues/20502

**Comment by chuckatkins** [comment]
> So, I'm guessing that python3.7 was installed as a dependency for something, but doesn't quite fully install python?

`python3-distutils` is installed as a dependency with the `python3-dev` package, at least in `*buntu` so a vanilla runtime interpreter-only install won't have it.  Essentially all of the introspection information that `FindPython` gets from `distutils.sysconfig` can also be retrieved from the top-level `sysconfig` which seems to always be available.  I'm working on trying to transition `FindPython` to do just that.

**Comment by chuckatkins** [comment]
@JasonRuonanWang can you try #2070 and see if that fixes your issues?

**Comment by chuckatkins** [comment]
nm, still broken.  I'll let you know when to try it...

**Comment by chuckatkins** [comment]
Okay @JasonRuonanWang I believe #2070 is good to go now and fixes your issues.  Can you please confirm?

**Comment by JasonRuonanWang** [comment]
@chuckatkins I had a try and the Mac problem is still there. For the Ubuntu 19.10 problem, now I am not getting the error, but I couldn't configure cmake to build with python either. 

No matter what I do, it will show this:

-- Could NOT find Python (missing: Development NumPy) (found version "2.7.17")

I am 100% sure that I have installed numpy and I have exported /home/jason/.local/lib/python2.7/site-packages/numpy/core/include/numpy and /home/jason/.local/lib/python2.7/site-packages/numpy/core/include into CPATH. But it still says it cannot find numpy. Besides, I don't know what Development is. Is that also a python package that I need to install?

Then I tried to use Python3 by specifying -DPYTHON_EXECUTABLE=/usr/bin/python3 as written in the docs. But apparently this  PYTHON_EXECUTABLE does not work and it still finds python 2.7.17.

**Comment by JasonRuonanWang** [comment]
I figured that the Development thing might be the dev files for python, so I gave it another try by specifying these:

cmake .. -DCMAKE_INSTALL_PREFIX=/opt/adios2 -DPython_INCLUDE_DIRS=/usr/include/python2.7 -DPython_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython2.7.so

But I still get the same thing 

-- Could NOT find Python (missing: Development NumPy) (found version "2.7.17")

**Comment by JasonRuonanWang** [comment]
I also tried to specify DPython_INCLUDE_DIRS and DPython_LIBRARIES to use the Python3 dev files, but I still get the same thing.

**Comment by chuckatkins** [comment]
> I also tried to specify DPython_INCLUDE_DIRS and DPython_LIBRARIES to use the Python3 dev files, but I still get the same thing.

Those are explicitly set by the find model so you won't be able to set them via -D.  Do you have the python-dev package installed?

**Comment by JasonRuonanWang** [comment]
> > I also tried to specify DPython_INCLUDE_DIRS and DPython_LIBRARIES to use the Python3 dev files, but I still get the same thing.
> 
> Those are explicitly set by the find module so you won't be able to set them via -D. Do you have the python-dev package installed?

Yes.

 jason@vm  ~/src  sudo apt install libpython-dev libpython3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpython3-dev is already the newest version (3.7.5-1).
libpython-dev is already the newest version (2.7.17-1).
0 upgraded, 0 newly installed, 0 to remove and 97 not upgraded.
 jason@vm  ~/src 

**Comment by chuckatkins** [comment]
The error message is unfortunately misleading.  I suspect it can't find your numpy installation.  Do you have python 3-numpy installed?

**Comment by JasonRuonanWang** [comment]
> The error message is unfortunately misleading. I suspect it can't find your numpy installation. Do you have python 3-numpy installed?

Yes.

 jason@vm  ~  pip3 install numpy
Requirement already satisfied: numpy in ./.local/lib/python3.7/site-packages (1.18.2)
 jason@vm  ~  pip install numpy
Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages (1.16.6)
 jason@vm  ~ 

**Comment by chuckatkins** [comment]
Okay, so I've been testing it through the actual package manager, not pip.  I.e. `apt install python3-numpy` which does work.  I'll try it through pip.

**Comment by JasonRuonanWang** [comment]
> Okay, so I've been testing it through the actual package manager, not pip. I.e. `apt install python3-numpy` which does work. I'll try it through pip.

Okay, it worked for me now by installing numpy through apt. So the Ubuntu 19.10 problem can be closed. I am trying to look more into the Mac problem.

**Comment by JasonRuonanWang** [comment]
@chuckatkins Okay, now I have some more insights into the Mac problem. It seems to be only happening with macOS 10.15 Catalina. I have tried to compile your branch and the latest master on two old Macs, one running 10.14 Mojave and the other running 10.13 High Sierra. They both work fine. 

However, on the other two Macs that I have running 10.15 Catalina, I got the same error. You don't need to run any apps to re-produce it. You will see it simply by import adios2 in command line. 

 jason@iMac  ~/  python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import adios2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/adios2/adios2.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /usr/local/lib/python3.7/site-packages/adios2/adios2.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/adios2/adios2.so
>>> 
 jason@iMac  ~/w/adiosvm/Tutorial/gray-scott   master 

**Comment by germasch** [comment]
I've been spent some time yesterday fighting this, too, to no avail. This is MacOS Catalina, too (Last I did this on an older mac os, it worked with troubles).

cmake only seems to find the system python2:
```
-- Could NOT find Python (missing: Development NumPy) (found version "2.7.16")
```
I want it to use my macports installed python3:
```
kai@kais-mbp  ~/build/ADIOS2/build-mpi   pr2070  python
Python 3.7.6 (default, Dec 22 2019, 01:09:06)
[Clang 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils
>>> import numpy
>>> import mpi4py
>>>
```

I tried with master and #2070, same issue.

**Comment by JasonRuonanWang** [comment]
> I've been spent some time yesterday fighting this, too, to no avail. This is MacOS Catalina, too (Last I did this on an older mac os, it worked with troubles).
> 
> cmake only seems to find the system python2:
> 
> ```
> -- Could NOT find Python (missing: Development NumPy) (found version "2.7.16")
> ```
> 
> I want it to use my macports installed python3:
> 
> ```
> kai@kais-mbp  ~/build/ADIOS2/build-mpi   pr2070  python
> Python 3.7.6 (default, Dec 22 2019, 01:09:06)
> [Clang 11.0.0 (clang-1100.0.33.12)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import distutils
> >>> import numpy
> >>> import mpi4py
> >>>
> ```
> 
> I tried with master and #2070, same issue.

I found that if it automatically uses Python2 then it's mostly because your Python3 is not completely installed, for example, the dev files may be missing, or the numpy package may be missing. At least #2070 compiled for me on all my 5 machines, after I make sure the development library files of Python3 and numpy are installed correctly.

**Comment by NAThompson** [comment]
I've hit this issue as well:

```
ADIOS2/build$ cmake --version
cmake version 3.16.3
ADIOS2/build$ python --version
Python 3.8.2
ADIOS2/build$ pip3 freeze | grep numpy
numpy==1.17.2
ADIOS2/build$ cmake ../ -G Ninja
CMake Error at /usr/local/Cellar/cmake/3.16.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS NumPy) (found
  version "2.7.16")
```

**Comment by chuckatkins** [comment]
Does it work if you have numpy installed via Homebrew?

**Comment by NAThompson** [comment]
@chuckatkins : Just tried; no joy.

**Comment by chuckatkins** [comment]
@NAThompson how do you have python installed?  Is it via homebrew, macports, or something else?

**Comment by NAThompson** [comment]
IIRC I got it from python.org.

**Comment by germasch** [comment]
@chuckatkins 

So I went to debug my issue, and my first conclusion is: I'm very glad I don't have to write python find modules ;).

I had previously tried to set my python executable explicitly following this quote from further up:

> Then I tried to use Python3 by specifying -DPYTHON_EXECUTABLE=/usr/bin/python3 as written in the docs. But apparently this PYTHON_EXECUTABLE does not work and it still finds python 2.7.17.

And in fact it does say that in the adios2 docs, but one has to use `Python_EXECUTABLE` -- and with that everything works as expected on my macbook.

However, I thought it still should have worked without specifying the executable since it's in the path. So some more tracing what's going on in that find module later, I figured out this is what happened:

The find module start search for python from 3.9 backwards, and it ended up finding a `python3.8` which I had lying around. I didn't trace it from there, but I believe what happened is that because this python3.8 doesn't have numpy, it gave up on it, but also stopped trying going down the list to 3.7.

I think the behavior of the find module hence is probably actually fine.

 Maybe it'd be nice if it finds a version of python that doesn't have the requested components to continue searching, but I don't think it's clear that's the right thing. Also, maybe, if there's a `python` or `python3` in the path, it should prefer that to trying python3.9, python3.8, etc.

 But it's not clear that the above doesn't cause other troubles for other people. What definitely would be helpful, though, is to have some better messages that let you know why it failed. In particular when it actually found an an available python but then didn't find some of the requested components, it'd really be helpful if it said so.

**Comment by germasch** [comment]
Okay, so I spoke somewhat to soon. First, to be clear, the find module actually tries to give a helpful error message:
```
Could NOT find Python (missing: Development NumPy) (found version "2.7.16")
```
So it does say that it failed because the components are missing -- which they are, from version 2.7.16. However, I took that to mean that it didn't find python3 at all.

Second, after moving my python3.8 out of the way, things still don't work right. That's because the python3 it now finds is `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/bin/python3.7`, which appears to be a system installed python3 that I wasn't aware of. And so of course that one doesn't have the required components, either.

I'm not sure how it finds this one (it's not in the path or anything), and it does find it (and prefers it to the macports `python3.7` in the path) even with `-DPython_FIND_FRAMEWORKS=NEVER`.
