### ISSUE TITLE
Why is MPI_CXX required?

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#2057]
Why is MPI_CXX required? Is this related to CXX API of MPI or usability of MPI from C++ code?
On Rhea, this is not found, so I cannot configure adios:

```
-- Found MPI_C: /autofs/nccs-svm1_sw/rhea/.swci/0-core/opt/spack/20191017/linux-rhel7-x86_64/gcc-6.2.0/openmpi-3.1.4-6i3xptfa3r6joouympddcnja5njc3eda/lib/libmpi.so (found version "3.1") 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
-- Found MPI_Fortran: /autofs/nccs-svm1_sw/rhea/.swci/0-core/opt/spack/20191017/linux-rhel7-x86_64/gcc-6.2.0/openmpi-3.1.4-6i3xptfa3r6joouympddcnja5njc3eda/lib/libmpi_usempif08.so (found version "3.1") 
CMake Error at /autofs/nccs-svm1_sw/rhea/.swci/0-core/opt/spack/20191017/linux-rhel7-x86_64/gcc-4.8.5/cmake-3.15.2-4xbxfsztfb7z2qemxy2dgrsuabbdgifu/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /autofs/nccs-svm1_sw/rhea/.swci/0-core/opt/spack/20191017/linux-rhel7-x86_64/gcc-4.8.5/cmake-3.15.2-4xbxfsztfb7z2qemxy2dgrsuabbdgifu/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /autofs/nccs-svm1_sw/rhea/.swci/0-core/opt/spack/20191017/linux-rhel7-x86_64/gcc-4.8.5/cmake-3.15.2-4xbxfsztfb7z2qemxy2dgrsuabbdgifu/share/cmake-3.15/Modules/FindMPI.cmake:1684 (find_package_handle_standard_args)
  cmake/FindMPI.cmake:10 (include)
  cmake/DetectOptions.cmake:115 (find_package)
  CMakeLists.txt:130 (include)
```

Funny thing is, the shared libraries are there:
```
rhea-login2g:/autofs/nccs-svm1_sw/rhea/.swci/0-core/opt/spack/20191017/linux-rhel7-x86_64/gcc-6.2.0/openmpi-3.1.4-6i3xptfa3r6joouympddcnja5njc3eda/lib
$ ls -l libmpi_cxx.so*
lrwxrwxrwx 1 uamntr uamntr     21 Nov  8 16:05 libmpi_cxx.so -> libmpi_cxx.so.40.10.1
lrwxrwxrwx 1 uamntr uamntr     21 Nov  8 16:05 libmpi_cxx.so.40 -> libmpi_cxx.so.40.10.1
-rwxr-xr-x 1 uamntr uamntr 145600 Nov  8 16:05 libmpi_cxx.so.40.10.1
```

So the question could also be "why not find it?"

**Comment by pnorbert** [comment]
$ cmake --version
cmake version 3.15.2

**Comment by pnorbert** [comment]
Note, the build error was my fault by pointing to the wrong compiler. So I can build ADIOS on Rhea now. The question still holds for information purposes. Why do we have dependency on libmpi_cxx.so

**Comment by vicentebolea** [comment]
I have done some digging and we are pulling `MPI_CXX` in both: `bindings/CXX11/CMakeLists.txt` and `testing/install/CXX11/CMakeLists.txt`, However, there is not a instance in the source code that is using symbols defined at `mpicxx.h` header, so in those particular `CMakeLitsts.txt` it should be safe to remove it.

The other instance where this is used is at `cmake/adios2-config-common.cmake.in` which is packaged in our ADIOS installation. In this case, it pulls mpi_cxx when we do not have MPI_C compiler which is fine of course.

I will see If I can get rid of the MPI::MPI_CXX dependency of the first case. Expect a MR soon :)

**Comment by vicentebolea** [comment]
@pnorbert find the dependency dropped at #2783

**Comment by pnorbert** [comment]
Thanks a lot @vicentebolea
