### ISSUE TITLE
conda install fails due to unnecessary upper bound on Python version

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#2079]
```
$ python3 --version
Python 3.8.2
$ conda --version
conda 4.8.3
$ conda install -c williamfgc adios2-nompi
Found conflicts! Looking for incompatible packages.

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - adios2-nompi -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8
```

Where can we get rid of the upper bound on the Python version?

**Comment by williamfgc** [comment]
@NAThompson Not sure if anaconda supports python 3.8, [the latest is 3.7.7](https://www.anaconda.com/distribution/) . Is `3.8.2` your system's python?

**Comment by NAThompson** [comment]
> Is 3.8.2 your system's python?

Yeah; so you think this requirement that python version < 3.8.0a0 is coming from Anaconda?

**Comment by NAThompson** [comment]
Bah, those guys! Alright thanks man!
