### ISSUE TITLE
yaml-cpp import

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#2089]
Is it possible to reference ADIOS' internal yaml-cpp build in another project's CMake setup? For example, I'm working on the EFFIS workflow tool, which also uses yaml-cpp. The EFFIS install works OK if I use yaml-cpp version 0.6.3, which is the version ADIOS currently uses, but causes a segfault if EFFIS uses a different version of yaml-cpp. (yaml-cpp is nominally a PRIVATE link in EFFIS, but I see the same thing with PUBLIC or INTERFACE.)
 
Since EFFIS needs ADIOS, I was just going to pick up on what ADIOS had built if I could. It doesn’t seem to be built for this though, with how it’s only part of the BUILD_INTERFACE, and how it’s effectively private, i.e. without the yaml-cpp headers in the ADIOS header directory. I tried a hackish use of linking adios2::yaml-cpp in the EFFIS cmake, but that doesn't build (and I had to use the yaml-cpp header from the yaml-cpp repo, since it wasn’t in the ADIOS build output.)

**Comment by chuckatkins** [comment]
The way it's currently implemented, `yaml-cpp` isn't even an actual library file, it's source files are directly included in `libadios`, which also means we can't consume an externally provided one either.  We could transition it to a proper third-party library where we could then build our internal copy or consume an external one, but that wouldn't really address what you want.  Regardless of how it's implemented, adios's internal copies of third party libraries are explicitly for internal use only and not intended to be provided for direct consumption by anything else.

The best way to deal with what you want would be to allow adios to use either an internal or external version and then build both EFFIS and ADIOS with the same external yaml-cpp.

**Comment by suchyta1** [comment]
OK, that makes sense. Thanks for the info. I may attempt a PR to allow an external link, but for now I'll just use the matching version.

**Comment by williamfgc** [comment]
@suchyta1 the part that is interesting is the seg fault caused by the internal/private implementation. The internal yaml-cpp symbols (or any thirdparty in adios2) shouldn't be reachable, not even globally in the adios2 library. As an example of a similar situation, adios2 uses a fixed version of pugixml different from VTK's pugixml. Did you try running `ldd` on your dynamic executable/libraries? Are you using the same compiler for adios2 and effis/yaml-cpp? Does Effis work without adios2 using yaml-cpp other than 0.6.3?

**Comment by suchyta1** [comment]
@williamfgc Yes, I was thinking along the same line, and those are the kinds of things I'm looking into. I don't have anything enlightening yet.

**Comment by caitlinross** [comment]
This was taken care of in #2184
