### ISSUE TITLE
Lustre : Striping_Factor and Striping_Unit 

### ISSUE THREAD

**Issue by aruhela** [ornladios/ADIOS2#2095]
Are the Lustre Parameters like Striping_Factor and Striping_Unit supported in ADIOS2? If yes, can you provide an example on how to set them with bp4 XML configuration?

**Comment by pnorbert** [comment]
a) No, they are not supported at the moment as we decided early on to not bother with them. From the usage of ADIOS1 we learnt that
- users generally don't know how to set them
- on a close-to-full Lustre filesystem it is safer to just let Lustre decide what to do with the files.

Moreover, in BP4, the output is a directory and every single file in there is written by a single process, therefore striping is not needed to carefully orchestrate multi-process writing. Aggregation of data from multiple processes is handled by ADIOS in memory and does not rely on parallel-IO. 

Moreover, BP4 is designed for scalability via the number of files in the .bp/ directory, by choosing the number of files (SubStreams in the XML) to match the capability of the file system (the number of OSTs). 

Of course, there surely are circumstances where a user for a specific use case (e.g. modest number of processes but huge amount of data) could squeeze out better performance by tuning the striping option. 

b) Nevertheless, our decision of not supporting them is not final. We just have not implemented the Lustre control from ADIOS1 into ADIOS2 and it has not been a priority. 

c) However, we saw some patterns where Lustre's strategy of picking the OST for each individual file in the .bp/ directory is not optimal for performance, so we may want this control back. But that is not about striping settings but about selecting the target OST for each file.

d) We are interested to hear why would you want these options in ADIOS2.

**Comment by aruhela** [comment]
Thanks Norbert for detailed note.

I don't have any specific use-case but I was curious to know if my program written for HDF5 can be ported completely to ADIOS2.  Can you also let me know me if it is possible to define attributes for individual datasets rather at the file level in the bp4 configuration just like they are defined in HDF5?

Thanks,
Amit

**Comment by aruhela** [comment]
Thanks Norbert

**Comment by eisenhauer** [comment]
Closed as resolved...
