### ISSUE TITLE
BP3/4 on-disk file format

### ISSUE THREAD

**Issue by Zehvogel** [ornladios/ADIOS2#2101]
is there any documentation regarding the format/structure of a BP file available? I couldn't find any :(

**Comment by williamfgc** [comment]
@Zehvogel the files/directory structure exposed to users is documented in the user guide for [BP4](https://adios2.readthedocs.io/en/latest/engines/engines.html#bp4) and [BP3](https://adios2.readthedocs.io/en/latest/engines/engines.html#bp4]. If you're referring to the internal byte arrangement specs in BP3/BP4 I'd check with @pnorbert . There are a few papers in the literature for BP3 for the research community. Hardly ever users go to that level of detail, though. Hope this helps.
