### ISSUE TITLE
SST prints error messages

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#2141]
So I suspect I'll have to  condense my code down into a small example that reproduces the issue, but maybe this is something that rings a bell.

I have both a writer and a reader communicating via SST, both with 6 MPI processes each. I don't think I do anything unusual. On all but rank 0 on the reader  I get this "Read" error below. Other than the message, everything seems to actually work fine.

```
[1,2]<stdout>: bef begin_step
[1,4]<stdout>: bef begin_step
[1,5]<stdout>: bef begin_step
[1,0]<stdout>: bef begin_step
[1,1]<stdout>: bef begin_step
[1,3]<stdout>: bef begin_step
[1,1]<stderr>:[30678029a2d4:12987] Read -1, expected 32416, errno = 1
[1,2]<stderr>:[30678029a2d4:12988] Read -1, expected 32416, errno = 1
[1,3]<stderr>:[30678029a2d4:12991] Read -1, expected 32416, errno = 1
[1,4]<stderr>:[30678029a2d4:12996] Read -1, expected 32416, errno = 1
[1,5]<stderr>:[30678029a2d4:12997] Read -1, expected 32416, errno = 1
[1,4]<stdout>: aft begin_step
[1,4]<stdout>: aft variable_shape
```

Relevant piece of code from the reader:
```f90
    print *, '-- read setup.bp'
    call this%adios%open(setup_read, 'setup.bp', 'setup', &
         adios2_mode_read, comm)
    print *, 'bef begin_step'
    call setup_read%begin_step(adios2_step_mode_read)
    print *, 'aft begin_step'
    call setup_read%variable_shape('matrices', shape)
    print *, 'aft variable_shape'
```

I don't think the writer does anything too unusual:
```f90
    call this%adios%open(setup_write, 'setup.bp', 'setup', &
         adios2_mode_write, this%comm_cart_o%comm)
    call setup_write%define_attribute('nprocs', this%comm_cart_o%n_procs)
    call setup_write%define_variable('matrices', cmplx(0), &
         [gdisc%ni0, gdisc%ni0, gdisc%nky0*nz0, this%n_solvers])
    call setup_write%begin_step(adios2_step_mode_append)
```

The only thing that comes to mind, maybe, is that it defines the attribute and variable before the `begin_step()`.

This is with the 2.5.0 release.

**Comment by eisenhauer** [comment]
Hmm.  That error message doesn't look familiar.  I looked for strings like ", expected" that I would expect to be needed to generate this, and I don't see anything that matches anywhere in ADIOS source (including the thirdparty libs).  Can you maybe run with the SstVerbose environment variable set?  That might help us sort out where this is coming from...

**Comment by germasch** [comment]
Yeah, I had just assumed that the message was from ADIOS2/SST, but googling seems to indicate that it may be from openmpi (which would make sense in that I'm using openmpi as my MPI here). So let me try to look into that a bit more. (This is openmpi compiled by spack in a ubuntu container running on macos, so plenty of opportunity for something to go wrong that has nothing to do with ADIOS2).

**Comment by philip-davis** [comment]
Is this being run in a container, by any chance?

I think this is coming from OpenMPI, and perhaps the same issue that Axel
reported here:
https://github.com/open-mpi/ompi/issues/4948

**Comment by germasch** [comment]
Thanks, yes, that was exactly it -- nothing to do with ADIOS2. It's an OpenMPI issue running in a container, which, for the record, can be fixed using the workaround in the link @philip-davis mentioned above:
```
export OMPI_MCA_btl_vader_single_copy_mechanism=none
```
Thanks to both of you for the very quick help!
