### ISSUE TITLE
bpls misses an attribute on BP3 file

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#2152]
**Describe the bug**

`bpls` of ADIOS 1.13.1 shows an attribute in a BP3 file but `bpls` misses the same attribute in ADIOS2.

Also, I cannot programmatically read the "missing" attribute (but all other attributes).

**To Reproduce**
File from https://github.com/openPMD/openPMD-api/issues/726:
[thetaMode_00200.zip](https://github.com/ornladios/ADIOS2/files/4513104/thetaMode_00200.zip)

Attribute
```
  string              /openPMD                               attr
# ...
  double              /data/200/meshes/E/gridUnitSI          attr
```

**Expected behavior**
`/data/200/meshes/E/gridUnitSI` should be visible and readable in ADIOS2 as well.

**Desktop (please complete the following information):**
 - OS/Platform: 18.04
 - Build: GCC 9.3.0 with openPMD-api

**Additional context**
Part of https://github.com/openPMD/openPMD-api/issues/726

**Comment by guj** [comment]
@pnorbert 
I think you are more familiar with the BP3Deserializer than me. 
It seems BP3Deserializer::ParseMetadata() did not pick up any info of the attribute gridUnitSI()

While ADIOS1 read it in.

**Comment by pnorbert** [comment]
Diagnosis: in the adios 1.x BP3 files, the **vars length** and **attrs length** fields in the beginning of the variable/attribute index are not accurate (of the total sums of the individual lengths of variable/attribute entries), missing e.g.  the 4 byte-long individual entries and maybe more. With enough number of variables/attributes, the adios 2.x implementation of the parser relying on the reported length will miss the last variables/attributes. 

adios 1.x ignored these lengths and used the reported **count** of the variables/attributes. 

There is a very accurate calculation of the length of the pg/variable/attribute index from the size of the total index (buffer) and the individual pg/variable/attribute index pointers (that are stored in the minifooter). The PR is using these and this should be working accurately for both adios 1.x and adios 2.x.

**Comment by ax3l** [comment]
Thank you for the quick fix, Norbert. I tested the fix and this works superb for us now!
