### ISSUE TITLE
max buffer size in adios_reorganize

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#2169]
**Describe the bug**
Robert is trying to use adios_reorganzie to convert XGC bp files but getting the following error:
```
[xgc.3d.00002] ERROR: rank 0: write buffer size needs to hold about 1352554164bytes but max is set to 1073741824
```

I found in the `adios_reorganize.h` that max_write_buffer_size is fixed. Is there any way to change the limit?

We tried to give some options but didn't work.
```
adios_reorganize xgc.3d.00002.bp xgc.3d.00002.h5 BPFile ""  HDF5 "MaxBufferSize=2Gb"
```

**Comment by pnorbert** [comment]
Its a const in the source of adios_reorganize, the max size per process.
You can manually change this parameter in the source and rebuild in adios
for your special use case.

Or, maybe, run the reorganizer on more than one process?

**Comment by jychoi-hpc** [comment]
We changed the buffer size in the code and rebuilt. It worked. Thanks.

**Comment by rmchurch** [comment]
Rediscovered this today. Seems it should be offered as an input to the adios_reorganize call, or remove it completely and allow OOM to handle the error, its not defining any variable sizes, just throwing an error when the requested write or read buffer is larger than the current const of 1GB (which is pretty small for HPC no?)

**Comment by rmchurch** [comment]
I solve currently just by writing a small Python script:
```
import adios2 as ad
import h5py

def bp2h5(filein,fileout):  
  fa = ad.open(filein,'r')  
  fh = h5py.File(fileout,'w')  
  vars = fa.available_variables()  
  for i,(k,v) in enumerate(vars.items()):   
    kdata = fa.read(k)
    dset = fh.create_dataset(k,data=kdata)
  fa.close()
  fh.close()
```

**Comment by jychoi-hpc** [comment]
It looks like a good solution. It would be good if we can collect such scripts/functions. I have a similar one here: https://gist.github.com/jychoi-hpc/aca8e6fea0e27d3d15429ba56a841f6c
