### ISSUE TITLE
Is fuzzing interesting for ADIOS?

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#2177]
Clang and LLVM now ship with a fuzz testing tool:

```
clang++ -fsanitize=fuzzer,address foo.cpp
```

Would it be interesting to add a fuzzer to the `.bp` reader?

Of course I can see arguments on both sides; but would it allow us to find bugs faster if we had a few fuzz targets?

I ask mainly to see if anyone thinks this would be a cool skill to put in their toolkit.

**Comment by williamfgc** [comment]
@NAThompson I'm personally not familiar with fuzz targets. I'd like to know more if you don't mind elaborating about any potential benefits within the scope of adios.

**Comment by NAThompson** [comment]
Well, most common file formats are fuzzed. This is because they can be mutated by malicious actors and uploaded to content sharing sites in order to pwn them in some way.

[Here's](https://github.com/google/oss-fuzz/tree/master/projects) a list of projects which have submitted themselves to "continuous fuzzing".

I think ADIOS could benefit quite a bit from at least fuzzing releases; we'd undoubtedly find plenty of bugs, but the question is whether they are interesting or relevant. At this point, most will not be interesting, but if we (say) build a dashboard that allows upload then it becomes very relevant. And even if they aren't relevant bugs, we still get the ability to build software which gives very informative error messages to users to do things in unpredictable ways (I count myself among them!).

**Comment by williamfgc** [comment]
It's still not clear how fuzzing is different from other forms of testing. For the most part adios2 has functional and integration testing. An example would help. Keep in mind that libraries don't own the data they produce, so if the data is modified by a 3rd third party we can't guarantee much.
