### ISSUE TITLE
python writing error when numpy values are not contiguous in memory

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#2217]
**Describe the bug**
When tried to write a subset of a multi-dimensional numpy array, I got wrong numbers in the file.

**To Reproduce**
Here is a simple script to demonstrate this error:
```
from mpi4py import MPI
import numpy as np
import adios2

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

Nx = 2
Ny = 2
steps = 5

## Defining a large array
data = np.ones((Nx, Ny*steps))
for i in range(steps):
    data[:, Ny*i:Ny*i+Ny] += i
print (data)

count = [Nx, Ny]
start = [rank * Nx, 0]
shape = [size * Nx, Ny]

adios = adios2.ADIOS(comm)
IO = adios.DeclareIO("test")
IO.SetEngine("BP4")

var = IO.DefineVariable(
    "FloatArray", data[:,:Ny], shape, start, count, adios2.ConstantDims)

writer = IO.Open('hello.bp', adios2.Mode.Write)

for i in range(steps):
    print("Step", i)
    ## Writing a subset of data
    x = data[:,Ny*i:Ny*i+Ny]
    ## Writing all the same values
    print(x)
    writer.BeginStep()
    writer.Put(var, x, adios2.Mode.Sync)
    writer.EndStep()

writer.Close()
```
Basically, it writes a subset of values at each step.

**Expected behavior**
I expected all 1s, 2s, ..., 5s at each step. If I dump, I expected to see:
```
        step 0: 1 1 1 1
        step 1: 2 2 2 2 
        step 2: 3 3 3 3 
        step 3: 4 4 4 4 
        step 4: 5 5 5 5
```
But, I got mixed numbers:
``` bash
$ bpls -d -D hello.bp
File info:
  of variables:  1
  of attributes: 0
  statistics:    Min / Max 

  double   FloatArray  5*{2, 2} = 1 / 5
        step 0: 
          block 0: [0:1, 0:1] = 1 / 2
    (0,0)    1 1 2 2 
        step 1: 
          block 0: [0:1, 0:1] = 2 / 3
    (0,0)    2 2 3 3 
        step 2: 
          block 0: [0:1, 0:1] = 3 / 4
    (0,0)    3 3 4 4 
        step 3: 
          block 0: [0:1, 0:1] = 4 / 5
    (0,0)    4 4 5 5 
        step 4: 
          block 0: [0:1, 0:1] = 1 / 5
    (0,0)    5 5 1 1 

```
I think the main issue is that the subset values are not contiguous in the memory and Adios cannot distinguish this. I had a similar problem with Adios1 and a fix was to check and copy: https://github.com/ornladios/ADIOS/blob/20e8ac689fc03499ebd2fd2084d09c6ef8bef24d/wrappers/numpy/adios_mpi.pyx#L501

I don't know if Adios2 c++ binding can do a similar thing.

**Comment by pnorbert** [comment]
same issue as in #1705 

Right now, you can write the correct values only by passing a copy in the python script.
Thanks for the pointer to adios 1.x solution.

**Comment by jychoi-hpc** [comment]
Ok. We put such routine (to made a continuous numpy array) in our application for now. Thanks.
