### ISSUE TITLE
Make numpy mandatory for Python bindings

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#222]
Numpy is a mandatory dependency as it provides sizeof(T) and contiguous memory data (1D numpy arrays) needed by adios2 operations.

**Comment by ax3l** [comment]
Quick question: pybind11 can also pull in scipy dependencies for matrix binding/operations - you don't depend on those, right?

**Comment by williamfgc** [comment]
@ax3l for now we stick with their numpy support, http://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html ...that should give ADIOS2 enough coverage for Python applications. Unless, there is a strong case/reason for using scipy dependencies.

**Comment by ax3l** [comment]
@williamfgc all right, thanks and keep up the great work!
