### ISSUE TITLE
Crash on using SST with RDMA on Summit

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#2220]
**Describe the bug**
I built libfabric 1.8.1 and adios but got a crash when using SST with RDMA on Summit:

Here is my debugging screen shot:
![image](https://user-images.githubusercontent.com/3661063/81454897-835a3500-915b-11ea-81f3-8b67268117f1.png)

I don't know if this is related with this problem: I could not use the system default libfabric 1.7.0 since it gave very strange error. I built own libfabric 1.8.1 with no special option:
```bash
$ ./configure --prefix=$PREFIX  CC=/usr/bin/gcc
```

Any advice and help will be greatly appreciated. Thanks.

**Comment by eisenhauer** [comment]
This is likely related to recent changes in the control plane for which the RDMA data plane is not yet adapted.  I have submitted PR #2221 that should fix this.

**Comment by eisenhauer** [comment]
I've merged that PR, but it was correcting a clear issue, but please retry and let me know for sure it's fixed.

**Comment by jychoi-hpc** [comment]
Greg, thank you for the quick fix. It works for me.

**Comment by jychoi-hpc** [comment]
It worked in a small scale (8 summit nodes). With a larger case (48 summit nodes), there was no crash but it didn't move either. I got the following error:
``` 
[DELTAF:240] ADIOS2 SST Engine waiting for contact information file ../coupling/xgc.wdm.f0.1.bp to be created
[DELTAF:241] ERROR: SstReader did not find active Writer contact info in file "../coupling/xgc.wdm.f0.1.bp.sst".  Timeout or non-current SST contact file?
[DELTAF:241] adios2_open_new_comm
```

Can you think of any possibility of this problem?

**Comment by eisenhauer** [comment]
This is probably unrelated.  Is it possible, based upon how you are starting the reader and writer, for the reader to fine a .sst file leftover from a prior run?  That is the most common cause if this error.  (We try to remove .sst files on writer exit, when the info in them becomes invalid, but that isn’t always possible...)

**Comment by jychoi-hpc** [comment]
Thank you for the reply. I didn't have old SST files. Instead, I found that libfabric version made some differences.

It looks like  libfabric 1.8.1 is not working with adios2. After using  libfabric 1.6.2, it works now.

Thanks.

**Comment by eisenhauer** [comment]
Odd.  1.8.1 is supposedly the version that is working, at least on Cori...
