### ISSUE TITLE
flake8 checks python files for python2 syntax

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#2229]
Hello,
I cleaned python files according to python 3 syntax but now my commit does not go through the travis-CI because it uses flake8 in python 2 mode.
 
9.16s$ pip install --user flake8
install.7

0.67s$ git config --global clangformat.binary ${HOME}/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang-format

0.19s$ git reset --hard ${TRAVIS_PULL_REQUEST_SHA}

HEAD is now at 9812317 Merge branch 'python-checks' of https://github.com/dmitry-ganyushin/ADIOS2 into python-checks

The command "git reset --hard ${TRAVIS_PULL_REQUEST_SHA}" exited with 0.

1.25s$ ${TRAVIS_BUILD_DIR}/scripts/travis/run.sh

Running formatting tests

Checking formatting for commit range: fd83b6273b647db86a67d7457c57e23be84640d9 981231753c9384f0d4762733d905722481c16763

./source/utils/bp4dbg/bp4dbg.py:40: [E999] SyntaxError: invalid syntax

./source/utils/bp4dbg/adios2/bp4dbg/metadata.py:141: [E999] SyntaxError: invalid syntax

./source/utils/bp4dbg/adios2/bp4dbg/data.py:126: [E999] SyntaxError: invalid syntax

**Comment by chuckatkins** [comment]
ADIOS should be still supporting both python 2 and 3 so it needs to work for both.

**Comment by chuckatkins** [comment]
We can certainly add dropping python 2 support for after the release but it's a bit late in the game at this point for the 2.6 release.  I'm happy to make that call after 2.6 though.

**Comment by chuckatkins** [comment]
@dmitry-ganyushin is this okay to close or is it still problematic?

**Comment by dmitry-ganyushin** [comment]
For now It can be closed.
