### ISSUE TITLE
BP compatibility: 2.5.0 cannot read master data

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#2242]
An INCITE user of ours reports that a `double` attribute written with ADIOS2 `master` is not read with the same data type again in `v2.5.0`, which causes us read problems.

**Describe the bug**
A user writes an attribute with openPMD-api `master` with a `double` type via ADIOS2.
Reading with ADIOS2 `v2.5.0` does not re-identify the type.

**To Reproduce**
Are there unit tests in ADIOS2 that check if old BP4 files are represented well in reads of never versions of ADIOS2?

**Expected behavior**
Which compatibility guarantees do we have for both APIs and BP file format?

**Desktop (please complete the following information):**
 - OS/Platform: Summit (write) and Rhea (read) at OLCF
 - Build: parallel write from C++11 API in ADIOS2 `master` from source; serial read via ADIOS2 2.5.0 (conda-forge, C++17 build)

**Additional context**
This could be caused by newly introduced data types for attributes and complex. I tried to take care that enum types/numbers in the API stay the same, but am not sure if I succeeded or what is done on the BP level. #1909 Could also be any other type change introduced in ADIOS2 since 2.5.0.

I am basically writing this to avoid that a data incompatibility sneaks into the next stable release.

**Comment by williamfgc** [comment]
@ax3l thanks for reporting this. Is the user checking with `bpls` to verify the metadata is correct? Please let us know as this has a major impact. @chuckatkins @pnorbert are there plans for adding regression testing functionality among versions?

**Comment by ax3l** [comment]
Thanks, I am investigating this right now myself. I can read the data with `bpls -A -l` from 2.5.0 which makes me suspect I am having a logic issue on my side in openPMD. Will try to build a reproducer, the problems is currently on a 4 TByte data set ;-)

**Comment by chuckatkins** [comment]
Related #2255 and #2257

**Comment by ax3l** [comment]
Thanks a lot!
I found and fixed a parser issue on our side today and we switched all to `2.5.0` to keep the user going.

We saw an intermediate issue not being able to parse a `string` attribute from `master` in `2.5.0`, which I have not followed down yet. I'll have to repeat the read check just to make 100% it's not `master` related, but looks like #2255 would cover these cases generally, which is superb. Thanks already!

**Comment by ax3l** [comment]
The last issue was not `master` related as well but occured in a write in which a wiriting app failed. `bpls` still shows an attribute that was written by some of the ranks, but not all, but serial read-back fails. Interesting but incomplete data, so I have to handle this just more gracefully.
