### ISSUE TITLE
bpls option to print bp-version

### ISSUE THREAD

**Issue by Bella42** [ornladios/ADIOS2#2247]
Currently there seems to be no way of identifying whether the file is written as bp3 or bp4 besides the fact, that bp3 outputs a file and a directory while bp4 files are always directories.

Inspecting data with bpls is a very convenient feature. Especially analysing the metadata is quite helpful. 
However, the possibility to check the format version with bpls would be a useful addition.
For a self-describing data format like bp it seems that this information should be easily available and the distinction between the formats is not easy to spot when first coming in contact with ADIOS 2 or the bp format. So this change would allow newcomers to transition to this format more easily.

The effort to implement this feature could probably be limited to a couple of lines in the bpls.cpp.
Something like checking the existence of the ".dir" ending and setting the format version accordingly. Similar to the detection which engine to use.

Alternatively, this information could be written to the bp header with the respective engines and then extracted with bpls. However, this solution would probably require touching several spots where the header information is serialised and deserialised.

**Comment by chuckatkins** [comment]
I think this would be a great idea and not particularly difficult to implement.  We're about to hit a feature freeze for the 2.6.0 release though so it might be tough to get it on there in time.

@pnorbert?

**Comment by pnorbert** [comment]
I am not sure of the utility of this information. It is quite cumbersome for historical reasons that on the ADIOS2 side that there are engines called "BP3" and "BP4". The "File" (virtual) engine will open both files (and .h5) files automatically with the proper engine. 

From 2.6.0 and on, BP3 really exists for backward compatibility, to read back old data. BP4 gives more benefits (easier to manage, append supported, in situ streaming supported, and now burst buffer is supported). 

Learning from past mistakes in adios 1.x, now the BP directory contains files with the first 64 bytes properly identifying the dataset by each ADIOS2 release version. There is version 4 still in that header though that an engine checks for compatibility but users should not rely on.  
```
$ /opt/adios2/bin/bp4dbg data.bp/md.idx 
========================================================
    Index Table File: data.bp/md.idx
========================================================
----------------------------------------------------------------------------------------------------------------------
|        Version string            | Major | Minor | Patch | unused | Endian | BP version | Active |     unused      |
|          32 bytes                |   1B  |   1B  |   1B  |   1B   |   1B   |     1B     |   1B   |       25B       |
+--------------------------------------------------------------------------------------------------------------------+
| ADIOS-BP v2.5.0 Index Table      |   2   |   5   |   0   |        |  yes   |      4     |   no   |                 |
----------------------------------------------------------------------------------------------------------------------
```

Now that I wrote this down, maybe a utility to print just that header info would be nice?

**Comment by Bella42** [comment]
Printing just that header seems to be sufficient to me.
Having the possibility to check both the used ADIOS2 release version as well as the BP version would be very convenient. Thank you!

**Comment by pnorbert** [comment]
#2270 Addresses this request. Please open another issue if you have trouble using it.
