### ISSUE TITLE
Path in bp file name fails

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#230]
/path/to/file doesn't produce /path/to/file.bp.dir/file.bp.0

**Comment by williamfgc** [comment]
To do:
Add tests

**Comment by HaochengLIU** [comment]
@williamfgc 
Hi William, since I'm working on make BP tests able to run parallel, I can handle this issue.

**Comment by williamfgc** [comment]
Hi @HaochengLIU thanks for reminding me I had an open ticket. This should have been fixed in PR #231, we need to add more tests for names in the form: /path/a/b/c/file

**Comment by HaochengLIU** [comment]
Thanks @williamfgc , I've incorporated the OS path separator in PR #252 .
