### ISSUE TITLE
Over allocation at mode::defer  

### ISSUE THREAD

**Issue by guj** [ornladios/ADIOS2#2320]
**Describe the bug**
Buffer is expanded twice when running Put(mode::defer) + PerformPuts()

**To Reproduce**

In BP4Writer.cpp::PerformPuts(): 

1.  resize buffer at  line 66 
 
2. line 84, then calls PerformPutCommon, which calls PutSyncCommon, and buffer is expanded again there.  <<I believe the counting is not quite right here.>>

**Expected behavior**

**Desktop (please complete the following information):**
 - OS/Platform:  Any
 - Build: 2.6.0 (possibly earlier versions too)

**Additional context**
Here is what I see with 1 core, writing 3 variables, var1 & var2, var3, 80MB each. 
put(var1, var1_data, deferred) 
performPuts(var1) 
=> now, peak at BufferSTL.cpp::resize(), it shows m_Buffer is a bit over 80MB

put(var2, var2_data, deferred) 
performPuts(var2) 
=> now, peak at BufferSTL.cpp::resize(), it shows m_Buffer is a bit over 240MB, expecting it to be around 160MB!!

put(var3, var3_data, deferred) 
performPuts(var3) 
=> now, peak at BufferSTL.cpp::resize(), it shows m_Buffer is a bit over 430MB, expecting it to be around 240MB!!
looks like somewhere,  byte accounting is not done correctly. The pattern is the previous variables are double counted. 

**Following up**
Was the issue fixed? Please report back.

**Comment by chuckatkins** [comment]
Fixed by #2326
