### ISSUE TITLE
Cmake configuration fails when Fortran option is not set and when Fortran is not available

### ISSUE THREAD

**Issue by Bella42** [ornladios/ADIOS2#2340]
When trying to build ADIOS2, the cmake configuration fails. 
It seems there is a bug with Fortran when -DADIOS2_USE_Fortran is not set. 
The option detection works correctly and finds that there is no Fortran available.
However, I get the following error:
"CMake Error at /usr/share/cmake-3.17/Modules/CheckFortranSourceCompiles.cmake:132 (try_compile): Unknown extension ".F" for file"

This occured following the instructions in the documentation (https://adios2.readthedocs.io/en/latest/setting_up/setting_up.html#):
1. clone git
2. make build directory, change into it
3. call plain cmake without any options set -> "cmake ../ADIOS2"

I attached the complete cmake output I get.
- OS: Manjaro 20.0.3 Lysia
- kernel: 5.6.16-1-MANJARO
- gcc: 10.1.0
- adios2:  2.6.0.83
- cmake: 3.17.3

The error does not occur when -DADIOS2_USE_Fortran=OFF is set! Then, cmake runs as expected.

[cmake-output.txt](https://github.com/ornladios/ADIOS2/files/4794508/cmake-output.txt)

Edit: added CMakeCache.txt
[CMakeCache.txt](https://github.com/ornladios/ADIOS2/files/4796668/CMakeCache.txt)

**Comment by chuckatkins** [comment]
Could you also post your `CMakeCache.txt` from the build directory?  That should help with debugging the problem.

**Comment by Bella42** [comment]
Sure. I added it yesterday to the original issue. Do you need anything else for now?

**Comment by NAThompson** [comment]
I hit this today as well. As a workaround, I ran `cmake` twice, and the problem went away.

```
adios2/build$ rm -rf *
adios2/build$ cmake ../ -G Ninja
...
    RDMA Transport for Staging: Unconfigured
-- Configuring incomplete, errors occurred!
See also "/Users/4nt/ADIOS2/build/CMakeFiles/CMakeOutput.log".
See also "/Users/4nt/ADIOS2/build/CMakeFiles/CMakeError.log".
adios2/build$ cmake ../ -G Ninja
    RDMA Transport for Staging: Unconfigured
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/4nt/ADIOS2/build
```

The relevant error message from the failed CMake run is:

```
CMake Error at /usr/local/Cellar/cmake/3.17.0_1/share/cmake/Modules/CheckFortranSourceCompiles.cmake:132 (try_compile):
  Unknown extension ".F" for file

    /Users/4nt/ADIOS2/build/CMakeFiles/CMakeTmp/src.F

  try_compile() works only for enabled languages.  Currently these are:

    C CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.0_1/share/cmake/Modules/CheckFortranCompilerFlag.cmake:50 (CHECK_Fortran_SOURCE_COMPILES)
  cmake/DetectOptions.cmake:368 (check_fortran_compiler_flag)
  CMakeLists.txt:139 (include)


-- Performing Test ADIOS2_USE_Fortran_flag_argument_mismatch - Failed
```

**Comment by NAThompson** [comment]
I reran this using a new version of CMake, and I got the error message:

```
CMake Error at cmake/DetectOptions.cmake:140 (enable_language):
  The Ninja generator does not support Fortran using Ninja version

    1.9.0

  due to lack of required features.  Ninja 1.10 or higher is required.
```

So I ran:

```
brew upgrade ninja
```

and now everything works as expected.

@Bella42 : Are you using the Ninja generator?
