### ISSUE TITLE
[Discussion] RemoveVariables confusion

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#2366]
The documentation for `IO::RemoveVariable` states:

> Remove functions must be used with caution as they generate dangling Variable/Attributes pointers or references if they didn’t go out of scope.

I am confused by this; does the `IO` not have ownership of the data? If it does not own it, then shouldn't calling `RemoveVariable` be prohibited?

**Comment by NAThompson** [comment]
From a conversation with Norbert:

> staging read engines use this to clean out the IO group and fill it with new variables for the next step (InsituMPI).

**Comment by williamfgc** [comment]
```
adios2::Variable<double> var = io.DefineVariable<double>("to-be-dangled", ... );
io.RemoveVariable("to-be-dangled"); // io has ownership, so it can remove it
/// var is undefined (not even false) is dangling
```
