### ISSUE TITLE
Is Append mode supported?

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#2367]
In the [documentation](https://adios2.readthedocs.io/en/latest/components/components.html#opening-an-engine), it states that `adios2::Mode::Append` is under development. However, there are [unit](https://github.com/ornladios/ADIOS2/blob/003dc7eb4d54cb791f4a8a25af1ed1970a2a6bb3/testing/adios2/engine/bp/TestBPWriteAppendReadADIOS2.cpp#L326) tests for this mode, and it is exposed in the [Python interface](https://github.com/ornladios/ADIOS2/blob/master/bindings/Python/py11glue.cpp#L129). Yet the [comments](https://github.com/ornladios/ADIOS2/blob/master/bindings/CXX11/adios2/cxx11/IO.h#L255) say it is not supported.

Is append mode supported or not?

**Comment by pnorbert** [comment]
Yes, append mode is supported for BP4. The documentation is behind.
