### ISSUE TITLE
cmake error on Summit

### ISSUE THREAD

**Issue by lwan86** [ornladios/ADIOS2#2402]
I tried to build the latest master branch on Summit. 
I ran this cmake command:
cmake -DCMAKE_INSTALL_PREFIX=/ccs/home/lwan86/adios2-master-summit/install-dir ../ADIOS2/

 and got this error:

    RDMA Transport for Staging: Unconfigured
-- Configuring incomplete, errors occurred!

This is my environment:
Currently Loaded Modules:
  1) xl/16.1.1-5   2) spectrum-mpi/10.3.1.2-20200121   3) hsi/5.0.2.p5   4) xalt/1.2.0   5) lsf-tools/2.0   6) darshan-runtime/3.1.7   7) DefApps   8) python/3.7.0   9) cmake/3.17.3

**Comment by pnorbert** [comment]
That is not the error. Look higher up for messages like
```
CMake Error: Remove failed on file: /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/build.summit.master.gcc/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_7fbb4.dir/.nfs0000000000692a3100008b1c: System Error: Device or resource busy
```
Nowadays it takes up to a dozen tries to run cmake once successfully on NFS. You may want to move to GPFS.

**Comment by lwan86** [comment]
Okay. I'm closing this.

**Comment by germasch** [comment]
> That is not the error. Look higher up for messages like
> 
> ```
> CMake Error: Remove failed on file: /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/build.summit.master.gcc/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_7fbb4.dir/.nfs0000000000692a3100008b1c: System Error: Device or resource busy
> ```
> 
> Nowadays it takes up to a dozen tries to run cmake once successfully on NFS. You may want to move to GPFS.

I and others I know have also encountered this problem. I opened a ticket with OLCF about it, but the problem wasn't fixed. Maybe if enough other people complained, they'd address it? I, like others, have moved to GPFS, but then stuff gets purged after 90 days, which is not helpful...
