### ISSUE TITLE
Non-uniform adios2-config behavior

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#2403]
If we ask for Fortran flags from `adios2-config`, we obtain

```
$ adios2-config --fortran-flags
-DADIOS2_USE_MPI -I/usr/local/include/adios2/fortran
```

We can consume this directly in our `INCFLAGS` via

```make
INCFLAGS +=$(shell adios2-config --fortran-flags)
```

However, for the lib flags, we obtain:

```
$ adios2-config --fortran-libs
/usr/local/lib/libadios2_fortran_mpi.2.6.0.dylib /usr/local/lib/libadios2_fortran.2.6.0.dylib 
```

We cannot consume this via

```
LINKFLAGS +=$(shell adios2-config --fortran-libs)
```
and we have to implement a parser in our Makefile.

More uniform behavior would be:

```
$ adios2-config --fortran-libs
-L/usr/local/lib/ -ladios2_fortran_mpi  -ladios2_fortran
```

Note: The same behavior is observed when asking about the C-flags vs C libs, and cxx flags and cxx-libs.

**Comment by NAThompson** [comment]
@chuckatkins : Would you accept a PR that made this change?

**Comment by germasch** [comment]
Have you tried that this doesn't work as is? `-L` / `-l` is one option to link libraries, though somewhat error-prone if one might have multiple versions of libs in different paths. Passing the library including full path directly should work.

**Comment by NAThompson** [comment]
@germasch : I am astonished but indeed your suggestion works!
