### ISSUE TITLE
MPI-3 for Windows CI

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#2426]
It seems that the windows CI only supports MPI-2, which results in some of the SSC functionalities not being able to pass the Windows CI. Is there an easy way to upgrade the MPI version in the Windows build? If not then I have to use alternative MPI functions which disable some SSC functionalities just for passing the Windows CI...

**Comment by chuckatkins** [comment]
Our CI is using the Microsoft MPI implementation which provides a fill 2.2 implementation and a subset of 3.1.  Unfortunately there's not really a well maintained alternative for MPI on windows so MS-MPI is really it.  You can see the release notes regarding what should be supported (we're using 10.1.1)m https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi-release-notes .

If MS-MPI doesn't provide what you need for SSC then it's entirely reasonable to disable SSC on Windows.

**Comment by JasonRuonanWang** [comment]
Fair enough. Thanks for checking
