### ISSUE TITLE
Can't build VTK master with ADIOS2 v2.6.0

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#2449]
**Describe the bug**
[VTK master](https://gitlab.kitware.com/vtk/vtk) fails to build with adios2 v2.6.0 as a dependency with the following error:

```
Found MPI: TRUE (found version "3.1") found components: C
 Found MPI: TRUE (found version "3.1")
 CMake Error at /opt/adios2/2.6.0/lib/cmake/adios2/adios2-config-common.cmake:168 (add_library):
   add_library cannot create imported target "adios2::adios2" because another
   target with the same name already exists.
 Call Stack (most recent call first):
   /opt/adios2/2.6.0/lib/cmake/adios2/adios2-config.cmake:29 (include)
   IO/ADIOS2/Testing/Cxx/CMakeLists.txt:1 (find_package)

 Configuring incomplete, errors occurred!
 See also "/home/wgodoy/workspace/vtk-build/CMakeFiles/CMakeOutput.log".
 See also "/home/wgodoy/workspace/vtk-build/CMakeFiles/CMakeError.log".
```

**To Reproduce**
using `ccmake ../vtk` set:
- VTK_BUILD_TESTING               *OFF
- VTK_USE_MPI                           *ON
- VTK_MODULE_ENABLE_VTK_IOADIOS2  *YES
and type [c] Configure

**Expected behavior**
VTK should build with ADIOS2 as a dependency, works with v2.5.0

**Desktop (please complete the following information):**
 - OS/Platform: Ubuntu 18.04
 - gcc 8

**Comment by williamfgc** [comment]
@chuckatkins just letting you know as the above might affect future integrations with ParaView. Adding @bradking as he is the most knowledgeable on v2.6.0. Thanks!

**Comment by williamfgc** [comment]
@bradking thanks for the explanation. Is this something that should be fixed in adios2 or in VTK? I can always open an issue there. Thanks.

**Comment by bradking** [comment]
I've opened [VTK issue 18004](https://gitlab.kitware.com/vtk/vtk/-/issues/18004) for this.

**Comment by mathstuf** [comment]
The ADIOS2 config should check each target individually and not assume that just because one is missing, all of them are missing.

**Comment by bradking** [comment]
> The ADIOS2 config should check each target individually and not assume that just because one is missing, all of them are missing.

I disagree, but let's take this up over in the VTK issue.
