### ISSUE TITLE
Runtime error with compression: characteristic ID not supported when updating offsets

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#2461]
I am running the Gray-Scott code on Summit on 128 nodes. `L` in the settings-files.json is set to 4096.
The code has been modified so that it does not use the adios xml configuration file. The engine and compression are set directly in the code.
The engine is set to BP4 and SZ compression is applied to the U and V variables.

At runtime, the simulation reports the following error:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  ERROR: characteristic ID 11 not supported when updating offsets
```

No. of nodes: 128
No. of ranks: 4096 (32 ranks per node)
No. of time steps: 50
plotgap: 1
Total data written: 1 TB per timestep * 50 steps = 50 TB

The error seems to occur during the first timestep when about 320+ GB are written.

Using ADIOS master from July 17 with git hash cd005ecc6cb6abb6e6d93987d6dcf2ad75cdc3a5.
ADIOS was built using the existing SZ module on Summit v2.0.2.0

**Comment by pnorbert** [comment]
What is your simulation/settings.json content? I think compression only works if you have
```
    "adios_span": false,
    "adios_memory_selection": false,
```

**Comment by kshitij-v-mehta** [comment]
Yes, I have `adios_span` and `adios_memory_selection` set to false.

**Comment by kshitij-v-mehta** [comment]
I ran a test at a lower scale on 16 nodes with `L`=1024, but I get the same error.

**Comment by kshitij-v-mehta** [comment]
With L=1024 (16 GB per step), it fails on 16 (512 ranks) and 8 (256 ranks) nodes, but works with 4 nodes.

**Comment by kshitij-v-mehta** [comment]
I have set the no. of substreams = 128 , maybe that has an impact. Let me verify.

**Comment by kshitij-v-mehta** [comment]
Setting a different value for SubStreams causes this error. You can reproduce this at small scale on a desktop machine.

```
$> grep L settings-files.json
"L": 32,
```

Set no. of substreams to 1 in adios2.xml.

```
$ mpirun -np 2 ./gray-scott settings-files.json
...
Simulation at step 1 writing output step     1
terminate called after throwing an instance of 'std::invalid_argument'
  what():  ERROR: characteristic ID 11 not supported when updating offsets
```

**Comment by pnorbert** [comment]
I can reproduce the problem. Apparently aggregation and compression was never supported together.
