### ISSUE TITLE
engine.Close() is documented as optional, but it's not

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#2510]
In [this example](https://adios2.readthedocs.io/en/latest/components/components.html), the call to `engine.Close()` is commented out. In [this one](https://adios2.readthedocs.io/en/latest/api_high/api_high.html), the calls to the close method are listed as optional. The natural expectation from this is that the engine destructor calls `Close()`, if it hasn't already.

However, if we run this code:

```cpp
int main() {
    adios2::ADIOS adios;
    adios2::IO io = adios.DeclareIO("BPWriter");
    io.DefineAttribute<std::string>("foo", "bar");
    adios2::Engine eng = io.Open("test.bp", adios2::Mode::Write);

    //eng.Close();
}
```

with and without the call to `end.Close()`, we get different results:

```
$ bpls -Vv
blps: ADIOS file introspection utility

Build configuration:
ADIOS version: 2.6.0.504 (4b24a850)
C++ Compiler:  GNU 10.1.0
Target OS:     Darwin-18.7.0
Target Arch:   x86_64
$ # No close
$ bpls -lav test.bp
File info:
  of variables:  0
  of attributes: 0
  statistics:    Min / Max
$ # Call Close:
$ bpls -lav test.bp 
File info:
  of variables:  0
  of attributes: 1
  statistics:    Min / Max 

  string   foo   attr   = "bar"
```

**Comment by pnorbert** [comment]
Thanks for pointing this out. Close() is not optional, maybe it was in the very beginning when the example and doc was created. They need to be updated.

**Comment by williamfgc** [comment]
Yes, good catch. That's the compromise between not being fully C++ RAII + MPI library + unified API for serial and parallel code. I think the only place we don't need explicit Close is in the Python high-level API  `with-as`.

**Comment by caitlinross** [comment]
completed in #2521
