### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#2539]
Hi @KyleFromKitware,

just checking in: can you tell me the status of the Debian package support for ADIOS2, please?
This would be great for many of my integrations in our downstream software stack.

Cheers,
Axel

**Comment by KyleFromKitware** [comment]
Hi @ax3l,

The `dh-cmake` helper package was accepted into Debian unstable several months ago. Around that time, I filed RFS (requests for sponsorship) for ADIOS and its various dependencies, but did not get any responses. If there is still demand and funding for this, I will reach out to Alastair, the sponsor for `dh-cmake`, and ask if he'd be willing to sponsor ADIOS and friends, or find someone who is. (This would happen around the beginning of January, as I am about to take a vacation.)

**Comment by ax3l** [comment]
Hi @KyleFromKitware,

thank you for the update, this sounds like great progress. @pnorbert @sklasky, do you think this effort could be finalized?

**Comment by ax3l** [comment]
@KyleFromKitware it looks like a dependency, libevpath-dev, is not yet building.
If this is time consuimg, I would be fine to skip EVPATH for a first ADIOS2 Debian package and add support later, mainly because I am not using it and this can be fixed after onboarding:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960462

**Comment by williamfgc** [comment]
Hi All, just asking on the status of @KyleFromKitware work (thanks @KyleFromKitware, nice job!). Should we plan for our own repo and perhaps, expand also to rpms (I have some RHEL use cases)? The barrier of entry is pretty high without an active sponsor for debian or fedora's epel (unlike conda, spack, brew).

**Comment by ax3l** [comment]
@pnorbert do you think there is a chance to push this again?
Debian inclusion of ADIOS2 would be great and trickle down to Ubuntu et al.

**Comment by williamfgc** [comment]
@ax3l should we try snap (or maybe not)?  This is the debian [repo](https://gitlab.kitware.com/debian/adios2) in question.

**Comment by vicentebolea** [comment]
@scottwittenburg

**Comment by vicentebolea** [comment]
@drew-parsons has done a fantastic work maintain the adios2 package for debian, here is its repo https://salsa.debian.org/science-team/adios2

There is an ongoing issue with https://github.com/ornladios/ADIOS2/issues/4156 which is blocking him to update to 2.10.X. I would close this since we already have an adios2 package in debian/ubuntu
