### ISSUE TITLE
Conflict: Building serial examples fails with adios library built with MPI

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#2594]
**Describe the bug**
If the ADIOS2 library is built with MPI, I cannot build an example that has optionally mpi.h in it. This is because the adios include files will define the ADIOS2_HAVE_MPI macro. `adios2-config --cxx-flags -s` correctly omits the -DADIOS2_HAVE_MPI flag but then including adios2.h or adios2_c.h will get this macro. 

**To Reproduce**
Assuming adios2 is installed in /opt/adios2, 
1. Go to ADIOS2-Examples/source/cpp/hello-world
2. 
```
g++ -o hello-world `/opt/adios2/bin/adios2-config --cxx-flags -s` hello-world.cpp `/opt/adios2/bin/adios2-config --cxx-libs -s`
```
3.
```
hello-world.cpp:16:10: fatal error: mpi.h: No such file or directory
   16 | #include <mpi.h>
      |          ^~~~~~~
compilation terminated.
```

**Discussion**
ADIOS2-Examples were written when one to had to use separate parallel and serial builds of adios. They can still be built with either one, so technically, there is no bug if someone wants to build ADIOS2-Examples. However, the adios2-config flags for a serial build when we have a parallel build of adios, does not work in manual compile/Makefile **when** the application is prepared to be able to build serial or parallel.

**Comment by williamfgc** [comment]
Thanks @pnorbert , the agreement with @chuckatkins is that ADIOS2-Examples only supports tagged versions that match each adios2 release, see [here](https://github.com/ornladios/ADIOS2-Examples/tags) there is only v2.5.0. I'd be happy to help with updated release versions, but I can't commit in full.

**Comment by pnorbert** [comment]
Hi, @williamfgc this is not an issue with ADIOS2-Examples per se but with any examples we had prepared to be built both serial or parallel. The choice must match the adios build itself. Or we have to write separate serial and parallel examples. Or use a different macro and manually set that flag as users instead of relying on adios' flag.

**Comment by chuckatkins** [comment]
This should be an easy enough change to make the examples compatible with both.  When 2.6.0 introduced both serial and mpi libraries in the same build the feature macro ADIOS2_USE_MPI was introduced to signify which flavor of the library from a build is being used.  We can either have the example check the version and test HAVE vs USE based on that or alternatively (my preference) have the examples define their own USE_MPI macro.

**Comment by pnorbert** [comment]
Ah, my bad, I did not realize the examples used HAVE and adios2-config declares USE. So there is no problem here, I just need to modify the examples to use the ADIOS2_USE_MPI macro, which is adios2-config (and hence user choice) dependent.

However, ADIOSConfig.h always defines ADIOS2_USE_MPI to have a value

#ifndef ADIOS2_USE_MPI
#  define ADIOS2_USE_MPI 0
#endif

This is in conflict how adios2-config uses this macro (defined vs not-defined).

**Comment by chuckatkins** [comment]
USE was introduced in 2.6.0 so to maintain compatibility with 2.5.x it needs to be a bit craftier, hence either the version check or an independent USE definition for the apps, which is how an app would realistically do it instead of relying on a definition from a dependency.

**Comment by pnorbert** [comment]
I am talking about 2.7 and forward. adios 2.5 and the related examples are history. 
The adios2-config -m/-s flags are not usable since ADIOS2_USE_MPI is always defined if someone is including adios2.h from a parallel build. Either the ADIOSConfig.h has to be fixed and have the macro defined/not-defined or the adios2-config script has to be modified and define this macro with a value 0/1, resp.

Of course, for an app the easiest fix is just not to rely on adios2 macros but to use its own.

**Comment by pnorbert** [comment]
Okay, I was not focusing enough. Changing the examples to use
```
#if ADIOS2_USE_MPI
...
```

does work fine. So there is no problem here.

**Comment by chuckatkins** [comment]
> Okay, I was not focusing enough. Changing the examples to use
> 
> ```
> #if ADIOS2_USE_MPI
> ...
> ```
> 
> does work fine. So there is no problem here.

It works for current adios but not for 2.5
