### ISSUE TITLE
Is Adios2 supporting 32bit systems?

### ISSUE THREAD

**Issue by psychocoderHPC** [ornladios/ADIOS2#2597]
During my work on the blosc compression operator in ADIOS I spotted that buffer sizes are always of the type `size_t`.
`sizeof(size_t)` is `4` on 32bit system and `8` on 64bit systems.
Since ADIOS2 is internally using everywhere `size_t` it would mean that on a 32bit system you can only handle 4GiB memory.

My question is therefore if ADIOS2 aims to support 32bit systems?

**Comment by williamfgc** [comment]
@psychocoderHPC this was discussed in the past, see #1823 . Hope it helps.

**Comment by psychocoderHPC** [comment]
Thanks for linking my question to the old discussion. 
I will close this issue.
