### ISSUE TITLE
Fails to build with HDF5 1.12

### ISSUE THREAD

**Issue by yurivict** [ornladios/ADIOS2#2603]
**Describe the bug**
Fails to build with HDF5 1.12:
Log: http://package18.nyi.freebsd.org/data/121amd64-default-foo/2021-01-20_21h30m48s/logs/errors/adios2-2.7.0.log

Downstream bug report:  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252968

**Comment by guj** [comment]
Looks like your HDF5 is 1.12 but decided to use older version of H5O_getInfo. 

Would you mind edit the file HDF5Common.cpp,  at the 2  lines  in question (1495, 1551), replacing H5Pget_info(..)  to H5Pget_info3?

Hopefully this should pass the compiler. 
Thanks,

**Comment by guj** [comment]
If it works, we will put a patch in our code. Thanks.

**Comment by chuckatkins** [comment]
@guj whenever you make the patch, please base it off the `release_27` branch.  Even though it's going into `master`, this will allow it to be easily applied to the release by downstream package managers.
