### ISSUE TITLE
Write several fields with a loop in VTU XML

### ISSUE THREAD

**Issue by FabienSalmon** [ornladios/ADIOS2#2670]
When we do not know how many fields we will have to visualize, we often make a loop on the fields demanded by users.

To define them, we use the adios functions (among others) adios2_define_variable and adios2_put.

However, in the function adios2_put, we need to use different variable names every time, for instance :
```
adios2_put(engine, var, single_1, ierr)
adios2_put(engine, var, single_2, ierr)
```
etc.

Otherwise, the values are overwritten by the last defined variable. But, in a loop, it is not easily possible to use different names (for instance) :

```
do while condition
adios2_define_variable
**_calculations giving single_0_**
adios2_put(engine, var, single_0, ierr)
do loop
```

Here, we do not change the name of the variable single_0 for each iteration. But this fails to write a correct VTU XML file due to overwriting.

Therefore, could it be possible to define several variables with the same name in a personal code without overwriting previous variables?

Thank you

**Comment by williamfgc** [comment]
@FabienSalmon not sure if it helps your problem, but the `vtk.xml` attribute can be superseeded with a xml file inside the `.bp` directory called "vtk.xml" , see [2nd option in the docs](https://adios2.readthedocs.io/en/latest/ecosystem/visualization.html#saving-the-vtk-xml-data-model).

**Comment by FabienSalmon** [comment]
Thank you for your comment.

However, the problem stems from the definition of the variables inside the considered software code that uses adios2 output. 

We need to know the number of output fields before the calculation, name them such as var_1, var_2, etc, and after define them with adios functions. 

But for instance, if we have 50 fields to write, we do not want to create 50 variables, but only one, and overwrite it after each definition since it is easier. It seems that it is not possible so far.

At least, I do not find a way to do that and the provided examples in adios2 always define 5-6 variables at the beginning which assumes that we know the number of variables that we will write (which is not the case in real world).

**Comment by williamfgc** [comment]
@FabienSalmon what is the expectation when you say "overwrite"? Overall, adios2 just does what is told in terms of defining a variable and putting the data in the internal buffers, the last two are decisions made in the workflow consuming adios2. They can be invoke only when the intended variables are known. In general, adios2 Variables have 3 invariants once defined: name, type and number of dimensions in shape (or count if local). Also, `adios2_define_variable` is an operation in memory, without a `adios2_put` those defined variables are not written at all. If you could provide example code it would be help clarify. Hope it helps.

**Comment by FabienSalmon** [comment]
Thank you for the answer. I provide an example below

```
call adios2_begin_step(engine, ierr)
field => print_list%first
do while(associated(field))
   call adios2_define_variable(varArray, io, trim(field%label), adios2_type_real, &
                  1, adios2_null_dims, adios2_null_dims, count_dims, &
                  adios2_constant_dims, ierr)
   single_tmp=real(field%scalar,kind=4)
   call adios2_put(engine, varArray, single_tmp, ierr)
   
   field ==> print_list%next
end do
call adios2_end_step(engine, ierr)
```

This stores the last field in all written fields due to overwriting because single_tmp is updated each iteration. We would need another name like single_tmp2.

**Comment by williamfgc** [comment]
I have a few questions from the code snippet: 
1. Do you need to store all the variables? In a previous comment I see that you don't, but the code is doing that.
2. Are there extra conditions to decide if a variables must be written or not? Passing an if condition before adios interactions would do it.
3. Is this snippet inside a loop? begin_step and end_step are for I/O steps, if you put them inside the while loop the variables won't overwrite each other, but I'm not sure that's what you need.

It would be good if you could provide how you envision the final output product in terms of variables. Something that `bpls` would dump.

**Comment by FabienSalmon** [comment]
**1. Do you need to store all the variables? In a previous comment I see that you don't, but the code is doing that.**
Actually, I need to turn variables of rank 3 into variables of rank 1 (serialization). So I need to store them in intermediate variables such as single_tmp. I do not know if I understand well the question.

**2. Are there extra conditions to decide if a variables must be written or not? Passing an if condition before adios interactions would do it.**
No, I write everything that is in the loop condition.

**3. Is this snippet inside a loop? begin_step and end_step are for I/O steps, if you put them inside the while loop the variables won't overwrite each other, but I'm not sure that's what you need.**
Actually, it is what I wanted but it is not possible with unstructured meshes because I need to store variables for the mesh: vertices, connectivity, types. And when I put a begin_step and an end_step for each adios2_put, it fails. The mesh structure is not correctly stored by adios. I must use only one begin_step and one end_step and put everything between them. In our code, we also have the option of structured meshes, and here, we can use multiple begin_step/end_step for each variable (and thus we do not have the problem of this issue).

I am not at the lab this week-end, but the bpls info should look like the one in your website, but with several variables like that :

```
  uint32_t  NumOfElements       {4} = 1024 / 1024
  uint32_t  NumOfVertices       {4} = 1377 / 1377
  uint64_t  connectivity        [4]*{1024, 9} = 0 / 1376
  uint32_t  dimension           attr   = 3
  double    sol1                 [4]*{1377, 3} = -0.201717 / 1.19304
  double    sol2                 [4]*{1377, 3} = -0.101717 / 1.29304
  double    sol3                 [4]*{1377, 3} = -0.001717 / 1.39304
  ....
  uint32_t  types               scalar = 12
  double    vertices            [4]*{1377, 3} = -1.19304 / 8.20172
```

But I have 
```
...
  double    sol1                 [4]*{1377, 3} = -0.001717 / 1.39304
  double    sol2                 [4]*{1377, 3} = -0.001717 / 1.39304
  double    sol3                 [4]*{1377, 3} = -0.001717 / 1.39304
...
```

**Comment by germasch** [comment]
@FabienSalmon:
I think what you may need is
```fortran
call adios2_put(engine, varArray, single_tmp, adios2_mode_sync, ierr)
```
This may decrease performance, but it should make it work correctly.

**Comment by williamfgc** [comment]
@FabienSalmon I think I'm understanding the same thing as @germasch after seeing the intended output. The other option is to call `adios2_perform_puts` right after `adios2_put`, it's the same thing. `adios2_put` is deferred/lazy evaluation by default, so registered temp memory goes away (in your case gets overwritten). 

For unstructured mesh that doesn't change over time I usually just call corresponding `adios2_put` at the first step, `step == 0` (not `1` as in Fortran indexing). It's a common pattern.

```
call adios2_begin_step(engine, ierr)

call adios2_current_step(current_step, engine, ierr)
if current_step == 0 then
    ! only put variables once
    adios2_put(engine, ...)
! here in all steps
adios2_put(engine, ...)
call adios2_end_step(engine, ierr)
```
Hope this helps. Thanks for providing the extra info.

**Comment by FabienSalmon** [comment]
Ok thank you for your tips.

I will try that on monday

**Comment by FabienSalmon** [comment]
It works perfectly.

To sum up, I now use 

```
call adios2_put(engine, varArray, single_tmp, adios2_mode_sync, ierr)
```

and I only define the mesh structure at the first step.

Thanks for your help
