### ISSUE TITLE
adios build error on Cori with intel compiler

### ISSUE THREAD

**Issue by shahzebsiddiqui** [ornladios/ADIOS2#2692]
I am trying to install adios2 on Cori using the intel compiler with the e4s 21.02 stack. For this build i used the following variants `adios2@2.7.1 +hdf5 +dataman +dataspaces`

**Describe the bug**
The error can be described here: This is a comment from the spack.yaml you will need to look at the CDASH build. The project is located at https://software.nersc.gov/NERSC/e4s-2102/ if you need access i can grant it to you.
```
  # /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib/libm.so: error adding symbols: file in wrong format see https://cdash.spack.io/buildSummary.php?buildid=104952
```

**Desktop (please complete the following information):**
 - OS/Platform: Cori
 - Build:  intel/19.1.2.254 + cray-mpich/7.7.10

**Additional context**
I was able to install adios2 in e4s-20.10 with the default variants see https://github.com/spack/spack-configs/blob/master/NERSC/cori/e4s-20.10/spack.yaml#L14. This was using spack v0.15.4 to be specific the commit is documented in gitlab.ci file: https://github.com/spack/spack-configs/blob/master/NERSC/cori/e4s-20.10/.gitlab-ci.yml#L4. I suspect that adding the variants caused the issue so i will try to disable them and see if it works. Anyhow, i am not the expert in this tool, i try to enable sensible variants that should be enabled. I figured it may be worth installing adios2 on Cori. There is a spack gitlab pipeline documentation: https://docs.nersc.gov/applications/e4s/spack_gitlab_pipeline/ that can be useful if you want to do nightly build of your product.

**Comment by ax3l** [comment]
The problem likely came from `+dataspaces`.

**Comment by eisenhauer** [comment]
Will close as no longer relevant (@shahzebsiddiqui please re-open if necessary).  Unfortunate that this didn't get looked at a time, but it is an odd error, "libm.so "file is in the wrong format"?  Seems likely that this was machine or compiler specific and if those are no longer accessible, there's little followup that remains.
