### ISSUE TITLE
Where to ask questions?

### ISSUE THREAD

**Issue by eschnett** [ornladios/ADIOS2#2702]
I want to explore using ADIOS2 for the [Einstein Toolkit](https://einsteintoolkit.org). We are working on a new driver `CarpetX` based on [AMReX](https://github.com/AMReX-Codes/amrex), which uses block-structured AMR.

I have questions regarding
- what other (if any) packages use ADIOS2 with block structured AMR
- how to efficiently map block-structured AMR variable to ADIOS2 files
- how to best visualise the result (e.g. via [VisIt](https://wci.llnl.gov/simulation/computer-codes/visit)), i.e. whether this would require a new database plugin for VisIt

Is there a good venue to ask these questions?

**Comment by eschnett** [comment]
I am now examining [openPMD](https://github.com/openPMD) to structure ADIOS2 data.

**Comment by williamfgc** [comment]
> Is there a good venue to ask these questions?

GitHub issues is a good starting point. Good luck.  Also, [the docs](https://adios2.readthedocs.io/en/latest/ecosystem/visualization.html) have partial support for visualization of unstructured and image data using ParaView, but I don't know if that's exactly what you need.

**Comment by eschnett** [comment]
Thanks. No, I'm looking for block-structured AMR. But I hear that ParaView has beginning support for this (via openPMD).
