### ISSUE TITLE
JSON dependency not found on Windows

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#271]
@chuckatkins I got this error from the pull request checking. It compiles perfectly on Mac and Linux but apparently on Windows it cannot find the JSON header file.

Affected: PR #270 

C:\projects\adios2\source\adios2/toolkit/transportman/dataman/DataMan.h(15): fatal error C1083: Cannot open include file: 'json.hpp': No such file or directory [C:\projects\adios2build\build_visual-studio\source\adios2\adios2.vcxproj]

**Comment by chuckatkins** [comment]
This isn't a bug but a problem with the code in the reference PR.
