### ISSUE TITLE
C API doesn't allow defining local values

### ISSUE THREAD

**Issue by eschnett** [ornladios/ADIOS2#2723]
The C API ignores the argument `adios2_local_value_dim` to `adios2_define_variable`. When I define a local variable, it is written as global array instead.

The source code of `adios2_define_variable` does not mention the constant `adios2_local_value_dim`.

**Comment by williamfgc** [comment]
@eschnett is this still an issue? I see you closed it. Thanks!

**Comment by eschnett** [comment]
I was confused, the real issue is different. I have already opened a new issue.
