### ISSUE TITLE
adios2_attribute_data cannot be called for strings

### ISSUE THREAD

**Issue by eschnett** [ornladios/ADIOS2#2735]
I am trying to call `adios2_attribute_data` to obtain the value of a string attribute. I have looked at its implementation to find out how to call the function, and it seems there is no safe way to do so.

When called for a single string, the function apparently expects the `data` argument to be a `char*`, pointing to a pre-allocated buffer that is filled by the function. However, there doesn't seem to be a function to find out how large the buffer needs to be. The function returns a `size` value, but this is always `1`, indicating that there is only one string. I do not see a way to obtain the length of the string.

**Comment by germasch** [comment]
FWIW, a similar issue existed for other C API functions that return a string, and for those, there is a solution, though not a pretty one. #1230 has some fun reading...

**Comment by eschnett** [comment]
I find that this function does not even work when you allocate a sufficiently large buffer. It seems that the function writes the first bytes of the length of the string (instead of the string!) into the buffer.

**Comment by pnorbert** [comment]
I agree that there is no way to determine the string size in this case, but the function seems to work fine if you allocate a big enough buffer. Can you check again if it works properly for you?

There is a test in `testing/adios2/bindings/C/TestBPWriteTypes.cpp`, from line 206:

```
       adios2_bool result;
        char name[30];
        size_t name_size;
        adios2_type type;
        char type_str[30];
        size_t type_str_size;

        // single
        adios2_attribute *attrSingle =
            adios2_inquire_attribute(ioH, "strvalue");
        adios2_attribute_is_value(&result, attrSingle);
        EXPECT_EQ(result, adios2_true);

        adios2_attribute_name(name, &name_size, attrSingle);
        const std::string nameStrSingle(name, name_size);
        EXPECT_EQ(nameStrSingle, "strvalue");

        adios2_attribute_type(&type, attrSingle);
        EXPECT_EQ(type, adios2_type_string);

        adios2_attribute_type_string(type_str, &type_str_size, attrSingle);
        const std::string typeStrSingle(type_str, type_str_size);
        EXPECT_EQ(typeStrSingle, "string");

        char *dataSingle = new char[30]();
        size_t elements;
        adios2_attribute_data(dataSingle, &elements, attrSingle);
        const std::string dataSingleStr(dataSingle);
        EXPECT_EQ(dataSingleStr, "Hello Attribute");
        EXPECT_EQ(elements, 1);
        delete[] dataSingle;
```

This retrieves the string attribute `strvalue` properly, which is "Hello Attribute"

```
~/ADIOS2/build$ ctest -R Bindings.C.ADIOS2_C_API.ADIOS2BPWriteTypes.Serial
~/ADIOS2/build.debug$ ./bin/bpls -la testing/adios2/bindings/C/ADIOS2_C_API.ADIOS2BPWriteTypes.bp strvalue
  string    strvalue  attr   = "Hello Attribute"
```

**Comment by eschnett** [comment]
This code segfaults: <https://gist.github.com/eschnett/431a95e8d50b232dd589e83c240963cf>.

I write a string attribute array of length 1. When reading, it is presented as a value (non-array) attribute (`is_value=1`, `size=1`). Reading it as such segfaults.

I find that there is generally no way to distinguish between length-1 attribute arrays and attribute values when reading a file with the C API.

**Comment by eschnett** [comment]
My problems were due to a bug in my code. The bug was in writing (defining) the attributes.

I also found the constant `adios2_string_array_element_max_size`, which is presumably the one to use to allocate buffers.

**Comment by manauref** [comment]
@pnorbert 
is there still no good way to determine the size of a string attribute before reading it? I'd like to read in a string attribute without preallocating a buffer big enough (I don't know what big enough is in our application).
