### ISSUE TITLE
Unable to get detailed numpy type info into C++ code from dtype

### ISSUE THREAD

**Issue by chuckatkins** [ornladios/ADIOS2#276]
The `pybind11::dtype` object allows access to low-level type information via the `kind()` method, which maps to the `numpy.dtype.kind` python property.  This is only a coarse level of type information and is missing sizing.  For instance, `pybind11::dtype::of<float>().kind()` is equal to `pybind11::dtype::of<double>::kind()` because they are both floating point types.  The `numpy.dtype` class exposes more detailed information via the `type` property but that's not exposed in pybind11, thus leaving only the coarser level type-information.

**Comment by williamfgc** [comment]
They explain that we can restrict the types and make sure memory is contiguous (required by adios2), something I never implemented but we should:  http://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#arrays  . The way the type (hence size) is obtained is through returning the bool: `pybind11::isinstance<pybind11::array_t<T>>(array)`  yeah, I remember kind() wasn't helpful.

**Comment by chuckatkins** [comment]
Yes, but that's from an array which uses the type information, whereas if you just have the type object without an array, the detailed information is not available.   It is in python though as it's a trivial patch to pybind11 to expose it in the `pybind11::dtype` mappings.  I'm in the process of making the pr to pybind11 that addresses this specifically.

**Comment by chuckatkins** [comment]
taking a different approach so this is not necessary
