### ISSUE TITLE
Feature request: Julia bindings

### ISSUE THREAD

**Issue by rkube** [ornladios/ADIOS2#2802]
Hi,
any chance that bindings for [julia](https://julialang.org/) will be implemented in the future?

**Comment by eschnett** [comment]
I implemented Julia bindings in a Julia package https://github.com/eschnett/ADIOS2.jl, but calling the C API.

**Comment by williamfgc** [comment]
@rkube @eschnett we can safely close this issue. Thanks for the great effort 👍

**Comment by williamfgc** [comment]
duplicate of #426
