### ISSUE TITLE
BP serializers should ignore InitialBufferSize parameter in read-only mode

### ISSUE THREAD

**Issue by franzpoeschel** [ornladios/ADIOS2#2804]
**Describe the bug**
Currently, when specifying `InitialBufferSize`, reading BP-based engines will allocate the specified amount of memory and never use it. 

See [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3675) for measurements: This example loads a dataset with 16 steps from a BP4 dataset into memory, the diagrams show heap memory usage over time. The righthand diagram specifies `InitialBufferSize` as 32GB.

**To Reproduce**
Use any reading example, specify a large InitialBufferSize and observe heap memory usage.

**Expected behavior**
Two possible interpretations:
1. It's a user error. If the user specifies a buffer size, ADIOS will create a buffer, even if it's useless.
2. ADIOS should not create useless buffers. Users will sometimes copy-paste configurations between readers and writers, e.g. to guarantee that writer and reader in SST are set up correctly, so this will occur.

**Desktop (please complete the following information):**
 - ADIOS 2.7.1
 - Platform specifics should probably not matter further

**Comment by pnorbert** [comment]
Thanks for the report. This bug was fixed in #2800

**Comment by franzpoeschel** [comment]
Thank you for fixing this so fast! I can confirm that this solves the issue, memory usage on 2.7.1 and on master:
![Bildschirmfoto vom 2021-07-30 11-04-36](https://user-images.githubusercontent.com/14241876/127629751-d2dac4a5-211c-414e-8142-c5fe51815ca7.png)

**Comment by williamfgc** [comment]
@franzpoeschel yup, it's a bug. Thanks @pnorbert for the fix.
