### ISSUE TITLE
Spack & E4S: Add Compile & Smoke Test

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#2840]
Follow-up to #2836:

ECP E4S unit tests provide us with a unique opportunity to let system people test our compiled software against their MPI and compiler stacks. That's cool, because it's a ton of work for you to support all those systems and Spack packages formalize the whole testing process so we devs and system people speak the same language.

Here are two examples how this can look:
- https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openpmd-api/package.py#L134-L152
- https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/warpx/package.py#L139-L187

And this is the Spack file you need to update:
- https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/adios2/package.py

I can help/review, but would like you to take the lead as it's your product :)

cc @chuckatkins @pnorbert @williamfgc

**Comment by scottwittenburg** [comment]
@vicentebolea I've created a PR for this [here](https://github.com/spack/spack/pull/39970).

**Comment by vicentebolea** [comment]
@ax3l I think that this has been completed
