### ISSUE TITLE
Feature Request: Fortran API -  adios2_inquire_all_variables

### ISSUE THREAD

**Issue by MichaelLaufer** [ornladios/ADIOS2#2845]
We are adding ADIOS2 functionality into a Fortran application using the ADIOS2 Fortran API.  We are seeing an order of magnitude speedup for file writes [!], but are having issues during the implementation of the reader functionality.

In the reader part of the application, the number of variables as well as variable names that will be read are **not known at read time**, and there does not seem to be any way to ascertain the total available variables using the Fortran API.

It appears that this functionality is missing in the Fortran API, while it is available in the C++, C, Python and even Matlab bindings (using AvailableVariables/adios2_inquire_all_variables/file.Variables).

Can this be added to the Fortran bindings?

Many thanks

**Comment by pnorbert** [comment]
New subroutines are added in #2847 to retrieve the list of variable names and list of attribute names. These will be allocated, fixed length character arrays to accommodate the longest name, right-padded with spaces for shorter names. The list should be deallocated after use. 

```
type(adios2_io) :: ioRead
character(len=:), dimension(:), allocatable :: varnamelist, attrnamelist
integer :: nvars, nattrs, ierr
...

call adios2_available_variables(ioRead, nvars, varnamelist, ierr)
write(*,*) 'Number of variables = ', nvars
do i=1,nvars
     write(*,'("Var[",i2,"] = ",a12)') i, varnamelist(i)
end do
deallocate(varnamelist)

call adios2_available_attributes(ioRead, nattrs, attrnamelist, ierr)
write(*,*) 'Number of attributes = ', nattrs
do i=1,nattrs
     write(*,'("Var[",i2,"] = ",a20)') i, attrnamelist(i)
end do
deallocate(attrnamelist)
```

You need to call adios2_inquire_variable() to get the individual variable objects to examine them further.
Do these functions satisfy your needs?

**Comment by MichaelLaufer** [comment]
Thank you @pnorbert. Closing.
Looks exactly like what we need :)

**Comment by pnorbert** [comment]
@MichaelLaufer Unfortunately I used a Fortran 2008 feature to allocate the character array inside the subroutine, which does not work with our basic CI build using gfortran 4.8.5 under centos 7. I had to roll back and make a cumbersome F90 solution for this. The usage is more convoluted now:
- adios2_available_variables() / adios2_available_attributes() return a struct, and only tells number of variables/attributes and the length of the longest name in the list
- user has to allocate the character array
- adios2_retrieve_names() will fill the character array (and frees the internal C structure, and invalidates the struct)

```
character(len=4096), dimension(:), allocatable :: varnamelist
type(adios2_namestruct) :: namestruct

call adios2_available_variables(ioRead, namestruct, ierr)
if (ierr /= 0) stop 'adios2_available_variables returned with error'
if (.not.namestruct%valid) stop 'adios2_available_variables returned invalid struct'
write(*,*) 'Number of variables = ', namestruct%count
write(*,*) 'Max name length = ', namestruct%max_name_len
if (namestruct%count /= 14) stop 'adios2_available_variables returned not the expected 14'

allocate(varnamelist(namestruct%count))

call adios2_retrieve_names(namestruct, varnamelist, ierr)
if (ierr /= 0) stop 'adios2_retrieve_names returned with error'
if (namestruct%f2c /= 0_8) stop 'namestruct f2c pointer is not null after adios2_retrieve_names()'
if (namestruct%valid) stop 'namestruct is not invalidated after adios2_retrieve_names()'

do i=1,namestruct%count
     write(*,'("Var[",i2,"] = ",a12)') i, varnamelist(i)
end do
deallocate(varnamelist)
```

**Comment by MichaelLaufer** [comment]
Thanks @pnorbert! I have revised my code. Works jsut as advertised!
Closing.
