### ISSUE TITLE
#2815 and #2847 broke the master branch, which blocks all PRs

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#2855]
#2815 and #2847 broke the master branch, which blocks all PRs

**Comment by pnorbert** [comment]
fixing this with latest PR but now the docs build fails. Did the github automatic update of packages break our build?

**Comment by williamfgc** [comment]
@pnorbert the only difference is the funcpaserlib in the conda environment: 

[Pass](https://readthedocs.org/projects/adios2/builds/14656278/):
`Successfully installed blockdiag-2.0.1 commonmark-0.9.1 funcparserlib-0.3.6 readthedocs-sphinx-ext-2.1.4 recommonmark-0.7.1 sphinxcontrib-blockdiag-2.0.0 webcolors-1.11.1`

[Fail](https://readthedocs.org/projects/adios2/builds/14658449/):
`Successfully installed blockdiag-2.0.1 commonmark-0.9.1 funcparserlib-0.3.5 readthedocs-sphinx-ext-2.1.4 recommonmark-0.7.1 sphinxcontrib-blockdiag-2.0.0 webcolors-1.11.1`

error:   ```
File "/home/docs/checkouts/readthedocs.org/user_builds/adios2/conda/2849/lib/python3.7/site-packages/funcparserlib/lexer.py", line 80
    def match_specs(specs, str, i, (line, pos)):
                                   ^
SyntaxError: invalid syntax
```

**Comment by williamfgc** [comment]
I opened PR #2859 to see if it makes any difference

**Comment by pnorbert** [comment]
@williamfgc Thanks for the fix, the doc build in #2858 now passed

**Comment by williamfgc** [comment]
Thanks @pnorbert !
