### ISSUE TITLE
Building issue on NASA/Pleiades

### ISSUE THREAD

**Issue by liangwang0734** [ornladios/ADIOS2#2891]
**Describe the bug**
Building on the NASA/Pleiades with intel/gnu failed. Anyone has experience with this cluster? Do these I have to manualy locate the correct versions of headers/libraries? Can I go by by setting certain flags, disablign certain features?

**To Reproduce**
```bash
module load comp-intel/2018.3.222 mpi-sgi/mpt hdf5/1.8.18_mpt
git clone https://github.com/ornladios/ADIOS2.git ADIOS2
mkdir adios2-build && cd adios2-build

# I had to manually add the pthread flags and mpi flags some how.
CFLAGS="-pthread -lpthread -lmpi -lmpi++"  CXXFLAGS="-pthread -lpthread -lmpi -lmpi++" CC=icc CXX=icpc \
    /nasa/pkgsrc/sles12/2021Q1/bin/cmake \
    -DCMAKE_INSTALL_PREFIX=~/src/adios2-install \
    -DADIOS2_USE_MPI=ON \
    -DADIOS2_USE_HDF5=OFF \
    -DADIOS2_USE_Python=OFF \
    -DADIOS2_USE_Fortran=OFF \
    -DADIOS2_USE_SST=OFF \
    -DADIOS2_USE_SSC=OFF \
    -DADIOS2_USE_MHS=OFF \
    -DADIOS2_USE_PNG=OFF \
    -DADIOS2_USE_ZeroMQ=OFF \
    -DADIOS2_USE_BZip2=OFF \
    -DADIOS2_USE_Blosc=OFF \
    -DADIOS2_USE_ZFP=OFF \
    -DBUILD_TESTING=OFF \
    -DADIOS2_BUILD_EXAMPLES=OFF \
    ../ADIOS2
```
[CMakeError.log](https://gist.github.com/liangwang0734/82d1d0a07e75c2e57b67819906e8c772) and summary of errors:
```
-- Checking whether CXX compiler has environ in stdlib.h - no
-- Checking whether CXX compiler struct stat has st_mtimespec member - no
-- Looking for include file windows.h - not found
-- Looking for sockLib.h - not found
-- Looking for winsock.h - not found
-- Looking for hostlib.h - not found
-- Looking for sys/sockio.h - not found
-- Performing Test HAVE_FDS_BITS - Failed
```

**Expected behavior**
Success.

**Desktop (please complete the following information):**
 - OS/Platform: Pleaides
 - Build: icc (ICC) 18.0.3 20180410, cmake version 3.12.2, Git (current):
 ```git
commit f5fae3fbab6746d75d446b2283903bc0e2f6b727 (HEAD -> master, origin/master, origin/HEAD)
Merge: 523b403d3 a254376a0
Author: Jason Wang <jason.ruonan.wang@gmail.com>
Date:   Thu Sep 30 11:14:07 2021 -0500
```

**Additional context**

**Following up**
Was the issue fixed? Please report back.

**Comment by williamfgc** [comment]
@liangwang0734 thanks for reporting this. I worked with Pleiades more than a decade ago, so I might not be useful. Still, @chuckatkins it looks like the errors come from KWSys, I'll try to take a look.

**Comment by eisenhauer** [comment]
For clarification, did CMake somehow stop there?  Or are you seeing other problems?  The include files that you show as not found, are expected not to be found unless you're compiling on Windows.  Also, there is a test for the presence of the fds_bits field in the system fd_set structure.  The result is held in HAVE_FDS_BITS, but generally it's perfectly OK for that test to fail and that just results in HAVE_FDS_BITS not being defined and an #ifdef HAVE_FDS_BITS then causes some code (that uses fds_bits for verbose output) not to be included in the compile.  That is also fine. 

You seem to have disabled a lot of stuff.  If you further add -DADIOS2_USE_BP5=OFF, you should see much of this particular output disappear too.

**Comment by chuckatkins** [comment]
I suspect the additional flags in `CFLAGS` and `CXXFLAGS` is breaking things.  CMake should find `mpicc` from the `mpi-sgi/mpt` module ad extract the necessary compile and link flags on it's own.  Can you try it from a clean build directory without specifying any additional `CFLAGS` or `CSSFLAGS` env vars?

**Comment by liangwang0734** [comment]
Thank you all for immediate help. I will update my attempts one by one. I will disable bp5 for these attempts and entered a new shell.

First, no additional `CFLAGS` and `CXXFLAGS`.
- The errors are [here](https://gist.github.com/liangwang0734/057e563fdd27bc00f03aa39952fbaf47).
- Most failures are still there. (and also the older pthread undefined errors).
```
(pfe27)[adios2-build]$ module list
Currently Loaded Modulefiles:
  1) comp-intel/2018.3.222   3) mpi-sgi/mpt             5) hdf5/1.8.18_mpt
  2) mpi-hpe/mpt.2.17r13     4) szip/2.1.1
(pfe27)[adios2-build]$ CC=icc CXX=icpc /nasa/pkgsrc/sles12/2018Q3/bin/cmake  -DCMAKE_INSTALL_PREFIX=/home1/lwang12/src/adios2-install -DADIOS2_USE_HDF5=OFF -DADIOS2_USE_MPI=ON -DADIOS2_USE_Python=OFF -DADIOS2_USE_Fortran=OFF -DADIOS2_USE_SST=OFF -DADIOS2_USE_SSC=OFF -DADIOS2_USE_MHS=OFF -DADIOS2_USE_PNG=OFF  -DADIOS2_USE_ZeroMQ=OFF -DADIOS2_USE_BZip2=OFF -DADIOS2_USE_Blosc=OFF -DADIOS2_USE_ZFP=OFF -DBUILD_TESTING=OFF -DADIOS2_BUILD_EXAMPLES=OFF -DTHREADS_PREFER_PTHREAD_FLAG=ON -DDADIOS2_USE_BP5=OFF ../ADIOS2
```

**Comment by liangwang0734** [comment]
Sorry, I made a typo above. After disabling bp5, most of the errors are gone. The remaining ones are

- `pthread`, `KWSys` (`environ` not in `stdlib` and `struct stat has no member named 'st_mtimespec`

**Comment by chuckatkins** [comment]
The pthread undefined errors are not actually failures, just cmake trying to determine what threading libraries are implicit vs explicit.    There's a lot of things in the internal cmake logs that look like failures but are really just part of the normal system interrogation process.  What does the stdout look like?

**Comment by liangwang0734** [comment]
> The pthread undefined errors are not actually failures, just cmake trying to determine what threading libraries are implicit vs explicit. There's a lot of things in the internal cmake logs that look like failures but are really just part of the normal system interrogation process. What does the stdout look like?

- My interpretation is that the building process is treating the failed pthread, and other missing header issue as errors to fail the configuration.
- After disabling bp5, and add only flag `CFLAG="-lpthread", the only errors are now in `KWSys`.
- Now (without specifying `CXX=icpc`) the stdout looks like:
```
...
-- ADIOS2 ThirdParty: Configuring KWSys
..
-- Checking whether CXX compiler has environ in stdlib.h
-- Checking whether CXX compiler has environ in stdlib.h - no
-- Checking whether CXX compiler struct stat has st_mtimespec member - no
...
ADIOS2 build configuration:
  ADIOS Version: 2.7.1.772
  C++ Compiler : GNU 4.8.5 
    /usr/bin/c++

  Installation prefix: /home1/lwang12/src/adios2-install
        bin: bin
        lib: lib64
    include: include
      cmake: lib64/cmake/adios2

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: OFF
    Examples: OFF
    Build Options:
      Blosc     : OFF
      BZip2     : OFF
      ZFP       : OFF
      SZ        : OFF
      MGARD     : OFF
      PNG       : OFF
      MPI       : ON
      DataMan   : OFF
      DAOS      : OFF
      MHS       : OFF
      SSC       : OFF
      SST       : OFF
      BP5       : OFF
      DataSpaces: OFF
      ZeroMQ    : OFF
      HDF5      : OFF
      HDF5_VOL  : OFF
      IME       : OFF
      Python    : OFF
      Fortran   : OFF
      SysVShMem : ON
      Profiling : ON
      Endian_Reverse: OFF
      LIBPRESSIO: OFF
    RDMA Transport for Staging: Unconfigured
-- Configuring incomplete, errors occurred!
See also "/home1/lwang12/src/adios2-build/CMakeFiles/CMakeOutput.log".
See also "/home1/lwang12/src/adios2-build/CMakeFiles/CMakeError.log".
```
And the `CMakeError.log` contains only two `KWSys` errors  (`environ` not in stdlib` and `struct stat has no member named st_mtimespec`.

**Comment by liangwang0734** [comment]
After commenting out the relevant lines in `thirdparty/KWSys/adios2sys/CMakeLists.txt`, the `stdlib/environ` and  `st_mtimespec` errors are skipped. But I noticed there have always been an error not reported in the `CMakeError.log` but in stdout only.
```
-- ADIOS2 ThirdParty: Configuring perfstubs
CMake Error at thirdparty/perfstubs/perfstubs/CMakeLists.txt:16 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "perfstubs".
-- ADIOS2 ThirdParty: Configuring pugixml

-- ADIOS2 ThirdParty: Configuring nlohmann_json

-- ADIOS2 ThirdParty: Configuring yaml-cpp


ADIOS2 build configuration:
  ADIOS Version: 2.7.1.772
  C++ Compiler : GNU 4.8.5 
    /usr/bin/c++

  Installation prefix: /home1/lwang12/src/adios2-install
        bin: bin
        lib: lib64
    include: include
      cmake: lib64/cmake/adios2

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: OFF
    Examples: OFF
    Build Options:
      Blosc     : OFF
      BZip2     : OFF
      ZFP       : OFF
      SZ        : OFF
      MGARD     : OFF
      PNG       : OFF
      MPI       : ON
      DataMan   : OFF
      DAOS      : OFF
      MHS       : OFF
      SSC       : OFF
      SST       : OFF
      BP5       : OFF
      DataSpaces: OFF
      ZeroMQ    : OFF
      HDF5      : OFF
      HDF5_VOL  : OFF
      IME       : OFF
      Python    : OFF
      Fortran   : OFF
      SysVShMem : ON
      Profiling : ON
      Endian_Reverse: OFF
      LIBPRESSIO: OFF
    RDMA Transport for Staging: Unconfigured
-- Configuring incomplete, errors occurred!
See also "/home1/lwang12/src/adios2-build/CMakeFiles/CMakeOutput.log".
```

**Comment by chuckatkins** [comment]
Can you post the complete stdout without extra arguments?  I.e.
```
CC=icc CXX=icpc  FC=ifort /nasa/pkgsrc/sles12/2018Q3/bin/cmake  -DCMAKE_INSTALL_PREFIX=/home1/lwang12/src/adios2-install ../ADIOS2
```

**Comment by liangwang0734** [comment]
After disabling `Profiling` the last error on `perfstubs` is gone (though I really prefer to have profiling in the output bp folders).

At compiling stage, various `undefined reference` errors occurred because for some reason the mpi flags are not automatically picked up.

After manually setting mpi flags, now adios2 is compiled.

To summarize: 
```
CC=icc CXX=icpc CFLAGS="-lpthread -lmpi" CXXFLAGS="-lmpi -lmpi++" \
    /nasa/pkgsrc/sles12/2018Q3/bin/cmake  \
    -DCMAKE_INSTALL_PREFIX=/home1/lwang12/src/adios2-install \
    -DADIOS2_USE_HDF5=OFF -DADIOS2_USE_MPI=ON -DADIOS2_USE_Python=OFF -DADIOS2_USE_Fortran=OFF -DADIOS2_USE_SST=OFF -DADIOS2_USE_SSC=OFF -DADIOS2_USE_MHS=OFF -DADIOS2_USE_PNG=OFF  -DADIOS2_USE_ZeroMQ=OFF -DADIOS2_USE_BZip2=OFF -DADIOS2_USE_Blosc=OFF -DADIOS2_USE_ZFP=OFF -DBUILD_TESTING=OFF -DADIOS2_BUILD_EXAMPLES=OFF -DTHREADS_PREFER_PTHREAD_FLAG=ON -DADIOS2_USE_BP5=OFF -DADIOS2_USE_Profiling=OFF \
    ../ADIOS2
```
```
(pfe27)[ADIOS2]$ git diff
diff --git a/thirdparty/KWSys/adios2sys/CMakeLists.txt b/thirdparty/KWSys/adios2sys/CMakeLists.txt
index b0a854292..12e678dd8 100644
--- a/thirdparty/KWSys/adios2sys/CMakeLists.txt
+++ b/thirdparty/KWSys/adios2sys/CMakeLists.txt
@@ -428,24 +428,18 @@ if(KWSYS_USE_SystemTools)
     "Checking whether CXX compiler has setenv" DIRECT)
   KWSYS_PLATFORM_CXX_TEST(KWSYS_CXX_HAS_UNSETENV
     "Checking whether CXX compiler has unsetenv" DIRECT)
-  KWSYS_PLATFORM_CXX_TEST(KWSYS_CXX_HAS_ENVIRON_IN_STDLIB_H
-    "Checking whether CXX compiler has environ in stdlib.h" DIRECT)
   KWSYS_PLATFORM_CXX_TEST(KWSYS_CXX_HAS_UTIMES
     "Checking whether CXX compiler has utimes" DIRECT)
   KWSYS_PLATFORM_CXX_TEST(KWSYS_CXX_HAS_UTIMENSAT
     "Checking whether CXX compiler has utimensat" DIRECT)
   KWSYS_PLATFORM_CXX_TEST(KWSYS_CXX_STAT_HAS_ST_MTIM
     "Checking whether CXX compiler struct stat has st_mtim member" DIRECT)
-  KWSYS_PLATFORM_CXX_TEST(KWSYS_CXX_STAT_HAS_ST_MTIMESPEC
-    "Checking whether CXX compiler struct stat has st_mtimespec member" DIRECT)
   set_property(SOURCE SystemTools.cxx APPEND PROPERTY COMPILE_DEFINITIONS
     KWSYS_CXX_HAS_SETENV=${KWSYS_CXX_HAS_SETENV}
     KWSYS_CXX_HAS_UNSETENV=${KWSYS_CXX_HAS_UNSETENV}
-    KWSYS_CXX_HAS_ENVIRON_IN_STDLIB_H=${KWSYS_CXX_HAS_ENVIRON_IN_STDLIB_H}
     KWSYS_CXX_HAS_UTIMES=${KWSYS_CXX_HAS_UTIMES}
     KWSYS_CXX_HAS_UTIMENSAT=${KWSYS_CXX_HAS_UTIMENSAT}
     KWSYS_CXX_STAT_HAS_ST_MTIM=${KWSYS_CXX_STAT_HAS_ST_MTIM}
-    KWSYS_CXX_STAT_HAS_ST_MTIMESPEC=${KWSYS_CXX_STAT_HAS_ST_MTIMESPEC}
     )
   if(NOT WIN32)
     if(KWSYS_STANDALONE)
```

**Comment by chuckatkins** [comment]
Also try using the latest cmake binary, I think there have been some fixes I'm findmpi specifically for mpt.

https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.tar.gz

**Comment by williamfgc** [comment]
Also, I noticed the message appears in your config log which conflicts with trying to use `icpc`, maybe try loading a more recent gcc module?  It looks like cmake can't find POSIX headers somehow?

```
ADIOS2 build configuration:
  ADIOS Version: 2.7.1.772
  C++ Compiler : GNU 4.8.5 
    /usr/bin/c++
```

**Comment by liangwang0734** [comment]
I realized the system does have a newer version of `cmake 3.19.7`. After using that version, the configuration passed. But I still had to specify `CXXFLAGS="-lmpi -lmpi++"` to compile untile faild comping some examples.

I can try the cmake 3.21.3.

```
[ 39%] Building CXX object examples/basics/globalArray/CMakeFiles/globalArray_write_mpi.dir/globalArray_write.cpp.o
cd /home1/lwang12/src/adios2-build/examples/basics/globalArray && /nasa/intel/Compiler/2018.3.222/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc -DADIOS2_USE_MPI -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -I/home1/lwang12/src/ADIOS2/bindings/CXX11 -I/home1/lwang12/src/ADIOS2/source -I/home1/lwang12/src/adios2-build/source -isystem /nasa/hpe/mpt/2.17r13/include -lmpi -lmpi++ -O3 -DNDEBUG -std=gnu++11 -o CMakeFiles/globalArray_write_mpi.dir/globalArray_write.cpp.o -c /home1/lwang12/src/ADIOS2/examples/basics/globalArray/globalArray_write.cpp
/home1/lwang12/src/ADIOS2/examples/basics/globalArray/globalArray_write.cpp(50): error: more than one instance of constructor "adios2::ADIOS::ADIOS" matches the argument list:
            function "adios2::ADIOS::ADIOS(MPI_Comm={unsigned int}, bool)"
            function "adios2::ADIOS::ADIOS(bool)"
            argument types are: (enum <unnamed>)
      adios2::ADIOS adios(MPI_COMM_WORLD);
```

```
CXXFLAGS="-lmpi -lmpi++" CC=icc CXX=icpc  FC=ifort /nasa/pkgsrc/sles12/2021Q1/bin/cmake  -DCMAKE_INSTALL_PREFIX=/home1/lwang12/src/adios2-install ../ADIOS2
```
```
ADIOS2 build configuration:
  ADIOS Version: 2.7.1.772
  C++ Compiler : Intel 18.0.3.20180410 
    /nasa/intel/Compiler/2018.3.222/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc

  Fortran Compiler : Intel 18.0.3.20180410 
    /nasa/intel/Compiler/2018.3.222/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort

  Installation prefix: /home1/lwang12/src/adios2-install
        bin: bin
        lib: lib64
    include: include
      cmake: lib64/cmake/adios2
     python: lib/python3.8/site-packages

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: ON
    Examples: ON
    Build Options:
      Blosc     : ON
      BZip2     : ON
      ZFP       : OFF
      SZ        : OFF
      MGARD     : OFF
      PNG       : ON
      MPI       : ON
      DataMan   : OFF
      DAOS      : OFF
      MHS       : ON
      SSC       : ON
      SST       : ON
      BP5       : ON
      DataSpaces: OFF
      ZeroMQ    : OFF
      HDF5      : ON
      HDF5_VOL  : OFF
      IME       : OFF
      Python    : OFF
      Fortran   : ON
      SysVShMem : ON
      Profiling : ON
      Endian_Reverse: OFF
      LIBPRESSIO: OFF
    RDMA Transport for Staging: Unconfigured
-- Configuring done
-- Generating done
-- Build files have been written to: /home1/lwang12/src/adios2-build
```

**Comment by liangwang0734** [comment]
> Also, I noticed the message appears in your config log which conflicts with trying to use `icpc`, maybe try loading a more recent gcc module? It looks like cmake can't find POSIX headers somehow?
> 
> ```
> ADIOS2 build configuration:
>   ADIOS Version: 2.7.1.772
>   C++ Compiler : GNU 4.8.5 
>     /usr/bin/c++
> ```

Sorry, that was when I try to switch between gcc and intel. They errors are similar/same, I believe.
Anyway, now I could compile with almost everything disabled. After re-enabling everything, compiling failed at some examples. I will try the newest cmake as @chuckatkins suggested.

**Comment by liangwang0734** [comment]
Thank you all. @chuckatkins @williamfgc @eisenhauer 

After using the newest cmake 3.21.3:
- With intel compilers, I still have to specify mpi linkiing flags. With gnu compilers (mpicc), I don't have to specify mpi flags. This is a minor issue for me and perhaps is just an problem with the cluster configuration.
- However, with both intel (18.0.3/19.1.3) and gnu (4.8.5 and 9.3.0), the errors of ambiguity in the following two overloaded `adios2::ADIOS::ADIOS` constructors show up (in calls like `adios2::ADIOS adios(MPI_COMM_WORLD);`).
```
            function "adios2::ADIOS::ADIOS(MPI_Comm={unsigned int}, bool)"
            function "adios2::ADIOS::ADIOS(bool)"
```
- After disabling all examples and testing, everything else compiles. But the usage above seems to be a commonly used one.
  - This would be a separte issue though?
- My ubuntu desktop with gcc 10.x was able to compile the git head version.

**Comment by liangwang0734** [comment]
> Thank you all. @chuckatkins @williamfgc @eisenhauer
> 
> Maybe I can close this now, though there are still some issues.
> 
> After using the newest cmake 3.21.3:
> 
>     * With intel compilers, I still have to specify mpi flags. With gnu compilers (mpicc), I don't have to specify mpi flags. This is a minor issue for me and perhaps is just an problem with the cluster configuration.
> 
>     * However, with both intel (18.0.3/19.1.3) and gnu (4.8.5 and 9.3.0), the errors of ambiguity in the following two overloaded `adios2::ADIOS::ADIOS` constructors show up (in calls like `adios2::ADIOS adios(MPI_COMM_WORLD);`).
> 
> 
> ```
>             function "adios2::ADIOS::ADIOS(MPI_Comm={unsigned int}, bool)"
>             function "adios2::ADIOS::ADIOS(bool)"
> ```
> 
>     * After disabling all examples and testing, everything else compiles. But the usage above seems to be a commonly used one.
>       
>       * This would be a separte issue though?
> 
>     * My ubuntu desktop with gcc 10.x was able to compile the git head version.

I tried to compile my own adios2 program using flags returned from `bin/adios2-config --cxx-flags` and `bin/adios2-config --cxx-libs`.
- Both have some minor problem, perhaps irrelevant to this issue (the flag does not have `-I` before the include path; the linker does not have `-lmpi` which seems to be needed together with `-lmpi++` on this cluster.
- After manually fixing the problems above, I was able to compile my own adios program.
- The final way I used was intel compiler 19.1.3, cmake 3.21.3, disabling testing and examples (to skip the conflicting overloading issue).
```
  C++ Compiler : Intel 19.1.3.20200925 
    /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/bin/intel64/icpc

  Fortran Compiler : Intel 19.1.3.20200925 
    /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/bin/intel64/ifort

  Installation prefix: /home1/lwang12/src/adios2-install
        bin: bin
        lib: lib64
    include: include
      cmake: lib64/cmake/adios2
     python: lib/python3.8/site-packages

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: OFF
    Examples: OFF
    Build Options:
      Blosc     : OFF
      BZip2     : ON
      ZFP       : OFF
      SZ        : OFF
      MGARD     : OFF
      PNG       : ON
      MPI       : ON
      DataMan   : OFF
      DAOS      : OFF
      MHS       : ON
      SSC       : ON
      SST       : ON
      BP5       : ON
      DataSpaces: OFF
      ZeroMQ    : OFF
      HDF5      : ON
      HDF5_VOL  : OFF
      IME       : OFF
      Python    : OFF
      Fortran   : ON
      SysVShMem : ON
      Profiling : ON
      Endian_Reverse: OFF
      LIBPRESSIO: OFF
    RDMA Transport for Staging: Unconfigured
```

**Comment by williamfgc** [comment]
@liangwang0734 thank you for the extensive feedback. @chuckatkins time to bump minimum `cmake`?

**Comment by liangwang0734** [comment]
> @liangwang0734 thank you for the extensive feedback. @chuckatkins time to bump minimum `cmake`?

FYI, cmake 3.19.7 seems to work. Though I ended up using 3.21.3.

**Comment by chuckatkins** [comment]
@liangwang0734 I think this may be an oddity of the HPE MPT MPI implementation.  The default behavior of `mpicc` and other wrappers is to use gcc, regardless of the compiler loaded.  Can you try setting the environment variables:
```
$ export MPICC_CC=icc MPICXX_CXX=icpc MPIF90_F90=ifort
```
and then running the configure step with no additional `*FLAGS` variables set?  That should get the MPI compiler wrappers to use the correct underlying compilers and in turn hopefully extract the correct MPI usage flags.

**Comment by liangwang0734** [comment]
> @liangwang0734 I think this may be an oddity of the HPE MPT MPI implementation. The default behavior of `mpicc`, `mpic++`, and `mpif90` in MPT is to use `gcc`, regardless of the compiler module loaded. Can you try setting the environment variables:
> 
> ```
> $ export CC=icc CXX=icpc FC=ifort
> $ export MPICC_CC=icc MPICXX_CXX=icpc MPIF90_F90=ifort
> $ cmake ...
> ```
> 
> and then running the configure step with no additional `*FLAGS` variables set? That should get the MPI compiler wrappers to use the correct underlying compilers and in turn hopefully extract the correct MPI usage flags.

@chuckatkins Thank you. Yes, defining `MPICXX_CXX` etc works! However, I had to modify the `CC` definitions to
```
export CC=mpicc CXX=mpicxx FC=mpif90
```

Now, MPI seems to be correctly found and no `-lmpi -lmpi++` flags are required to compile anymore.
```
-- Found MPI_C: /nasa/hpe/mpt/2.17r13/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /nasa/hpe/mpt/2.17r13/bin/mpicxx (found version "3.1") 
-- Found MPI_Fortran: /nasa/hpe/mpt/2.17r13/bin/mpif90 (found version "3.1") 
```

Now, this is fully resolved. I actually noticed that this cluster's HPE MPI does not use the loaded intel compilers, but I wasn't aware of the `MPICXX_CXX` flags and my hack has always been manually specifying the flags...

**Comment by liangwang0734** [comment]
I created a [gist](https://gist.github.com/liangwang0734/394264b176b1f803d96a7ce30d6c782f) to keep track of my commands to build adios on Pleiades. Note that I still had to disable testing and examples due to this [issue](https://github.com/ornladios/ADIOS2/issues/2893).

**Comment by chuckatkins** [comment]
It's still broken if you have to use the mpicc wrappers directly.  What happens when you try to use icc etc. As the compiler with the MPICC_CC etc. set to use icc etc.?  The difference is important because it reflects how the adios2-config script gets generated.

**Comment by chuckatkins** [comment]
If you have a workaround that works for you now by using the wrappers as the regular compilers then that's great.  I'd still like to figure out the underlying issue though, although if you're willing to iterate a bit with me.  It might be easier to debug in the slack channel if you still have issues.  Email me out of band and we can work the problem there in slack if needed.

**Comment by liangwang0734** [comment]
> It's still broken if you have to use the mpicc wrappers directly. What happens when you try to use icc etc. As the compiler with the MPICC_CC etc. set to use icc etc.? The difference is important because it reflects how the adios2-config script gets generated.

If I just set `CC` and `MPICC_CC` to `icc`, etc., during `make`, `undefined reference` errors occur (couldn't fine `PMPI::Comm`, `MPI::Comm`, etc.

**Comment by liangwang0734** [comment]
> If you have a workaround that works for you now by using the wrappers as the regular compilers then that's great. I'd still like to figure out the underlying issue though, although if you're willing to iterate a bit with me. It might be easier to debug in the slack channel if you still have issues. Email me out of band and we can work the problem there in slack if needed.

Sorry, is there an official slack channel?

**Comment by chuckatkins** [comment]
Oh!  That's an easy fix!  We had to do something similar in vtk for MPT.  It basically just needs an extra define to deal with the MPT implementation to disable the c++ bindings when trying to use the c bindings.  Give me a few minutes and I can find it...

**Comment by chuckatkins** [comment]
> > It's still broken if you have to use the mpicc wrappers directly. What happens when you try to use icc etc. As the compiler with the MPICC_CC etc. set to use icc etc.? The difference is important because it reflects how the adios2-config script gets generated.
> 
> If I just set `CC` and `MPICC_CC` to `icc`, etc., during `make`, `undefined reference` errors occur (couldn't fine `PMPI::Comm`, `MPI::Comm`, etc.

This should fix that:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 79e911418..b7d078df9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -170,7 +170,7 @@ if(ADIOS2_HAVE_MPI)
   endif()
 
   # Workaround for MPI forcing the link of C++ bindings
-  add_definitions(-DOMPI_SKIP_MPICXX -DMPICH_SKIP_MPICXX)
+  add_definitions(-DOMPI_SKIP_MPICXX -DMPICH_SKIP_MPICXX -DMPI_NO_CPPBIND)
 endif()
 
 set(ADIOS2_CONFIG_OPTS
```

**Comment by chuckatkins** [comment]
> > If you have a workaround that works for you now by using the wrappers as the regular compilers then that's great. I'd still like to figure out the underlying issue though, although if you're willing to iterate a bit with me. It might be easier to debug in the slack channel if you still have issues. Email me out of band and we can work the problem there in slack if needed.
> 
> Sorry, is there an official slack channel?

Yep, adios2.slack.com .  We used it extensively in the first few years if initial development but it doesn't get much traffic these days.  It's still there though and can be a good place to iterate on things that need a lot of back and forth.

**Comment by liangwang0734** [comment]
@chuckatkins Yes, now with `export CC=icc CXX=icpc FC=ifort`, no `-lmpi` flags are needed (though, again, building tests/examples failed due to this [issue](https://github.com/ornladios/ADIOS2/issues/2893)).

**Comment by liangwang0734** [comment]
> > > If you have a workaround that works for you now by using the wrappers as the regular compilers then that's great. I'd still like to figure out the underlying issue though, although if you're willing to iterate a bit with me. It might be easier to debug in the slack channel if you still have issues. Email me out of band and we can work the problem there in slack if needed.
> > 
> > 
> > Sorry, is there an official slack channel?
> 
> Yep, adios2.slack.com . We used it extensively in the first few years of initial development when everything anyone was doing affected everyone else. It doesn't get much traffic these days bit it's still there and can be a good place to iterate on things that need a lot of back and forth.

Sorry for this irrelevant question: How can I join the slack channel? It seems to require invitation? Could you add me (liang.wang.phys@gmail.com)?

**Comment by liangwang0734** [comment]
While all but one minor [issue](https://github.com/ornladios/ADIOS2/issues/2893) have been fixed, I'd provide my usage results on Pleaides in case they are useful for the dev team as an unusual user case:

- Input data: 500k binary files (legacy vtk format), each contains a block of the global 3d array and 2 scalar variables, and 2 3-component variables. On a block ,the 3d variables are stored in the layout `nz*ny*nx*3`. Block locations and block IDs are not consecutive but can be computed.
- The first task is to merge them into bp files (for easier parallel reading using the ADIOS2 interface).
- Three methods
  - Merge each variable into a file. For 3-component variables, store the data in the `3*Nz*Ny*Nx` layout (in `DefineVariables`).
  - Merge each variable into a file. For 3-component variables, store the components into three separate `Variable`s but in the same file.
  - Merge each component into a file.
- Merging/writing timing for the three methods were similar, on the order of 700s for all variables (2048 cores, 74 nodes).
- However, later, when I read the generated data in parallel (1024 cores, 37 nodes), the speed in reading components of the 3-componet variables are very different: 900s, 1100s, 200s for the three methods.
  - The speed in reading the scalars are the same, on order of 200s.
  - The slow speed of the second method was surprising to me, as I thought it would be close to the third one. Maybe internally the different variables in the same bp file do not live on each's own consecutive space?

**Comment by williamfgc** [comment]
> Sorry, is there an official slack channel?

With GitHub issues you probably get more visibility and interactions. @chuckatkins I see [Discussions](https://github.com/ornladios/ADIOS2/discussions/landing) enabled. 

> Disclaimer: This is my first ADIOS2 attempt, my code is very likely under-performing. But I'm very happy to that the interface is so much simpler than vanilla HDF5 and the default result is also better (both read and write) without much tuning.

Glad to hear, a lot of effort was put in the API and architecture.

**Comment by chuckatkins** [comment]
> @chuckatkins Yes, now with `export CC=icc CXX=icpc FC=ifort`, no `-lmpi` flags are needed (though, again, building tests/examples failed due to this [issue](https://github.com/ornladios/ADIOS2/issues/2893)).

Excellent!  I'll push up a PR with the MPT fix, at least for this specific issue.
