### ISSUE TITLE
Links/aliases to existing resources (including those in external files)

### ISSUE THREAD

**Issue by liangwang0734** [ornladios/ADIOS2#2895]
HDF5 has a convenient feature to allow aliases to resources in an external file.

An [example](https://docs.h5py.org/en/stable/high/grouap.html#soft-links):
```py
myfile = h5py.File('foo.hdf5','w')
myfile['ext link'] = h5py.ExternalLink("otherfile.hdf5", "/path/to/resource")
```

Does ADIOS2 have a solution/workaround already?

**Why is this feature important?**
Sharing resources, particularly heavy binary data, among different .bp files reduces duplicate files in some scenarios, and helps users to create a universal interface for different needs.

**What is the potential impact of this feature in the community?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like and potential required effort**
Allow links/aliases to resources in external files. I don't know much about `adios2` internals, but this at least requires some string parsing and mechanism to safely/efficient access external resources without memory problem.

**Describe alternatives you've considered and potential required effort**

**Additional context**

**Comment by williamfgc** [comment]
The adios2 model is a bit different. Starts in memory with IO objects which in turn can open several engines, HDF5 starts with files. adios2 IO objects are "logical" containers of Variables, Attributes in memory. In principle, you could open two file engines with the same IO, but careful must be taken to avoid conflicts when reading. What adios2 doesn't have is the ability to cherry-pick like ExternalLink, just compose your workflow with different IO objects and retrieve appropriate Variables. Hope it helps.

**Comment by williamfgc** [comment]
Also, the ability to add "soft link" aliases is not supported in adios2, a workaround is to create a string attribute to map the variable names.that are soft linked. If implemented at the library level, it will have to be a special kind of entry like in HDF5.

**Comment by liangwang0734** [comment]
> The adios2 model is a bit different. Starts in memory with IO objects which in turn can open several engines, HDF5 starts with files. adios2 IO objects are "logical" containers of Variables, Attributes in memory. In principle, you could open two file engines with the same IO, but careful must be taken to avoid conflicts when reading. What adios2 doesn't have is the ability to cherry-pick like ExternalLink, just compose your workflow with different IO objects and retrieve appropriate Variables. Hope it helps.

Yes, this make sense. I will follow your suggestion and close this request. Thank you, @williamfgc
