### ISSUE TITLE
Missing description about the features in the documentation

### ISSUE THREAD

**Issue by JudithYi** [ornladios/ADIOS2#2921]
ADIOS2 offers nice features such as InSituMPI and CUDA support, but the introduction, description or/and technical details of them are missing in the documentation.

For instance, I have already tried the InSituMPI engine within one node or cross multiple nodes on the supercomputer. I used the MPMD to allow M writers and N readers in the in-situ processing. It leads to interesting results. But in the documentation, "InSitu MPI" is not listed in the "Available Engines" in "Interface Components". And in the "Supported Engines", it is still "Coming soon".

The new CUDA support allows ADIOS2 to receive the data from NVIDIA GPU device buffer and to write them out through the BP4 engine directly without copying the data to the CPU. But it is not introduced in the documentation yet.

Another nice feature missing description in the documentation is the "operator". With runtime configuration from "xml" file, operation such as compression can be done before writing out the data. But there is no introduction or description about these compressor and related parameters in the documentation.

I think with the documentations being updated with the development, ADIOS2 can attract more attentions.

**Comment by JasonRuonanWang** [comment]
InSituMPI was retired and the alternative SSC engine is documented. We have also added documentations for CUDA buffers too.
