### ISSUE TITLE
"redefinition of" errors compiling on Summit.

### ISSUE THREAD

**Issue by brtnfld** [ornladios/ADIOS2#2928]
**Describe the bug**
Compiling on Summit, I get the compilation error with current master and v2.7.1:

/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:409:22: error: redefinition of 'i'
            for (int i = 0; i < Info->VarCount; i++)
                     ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:394:22: note: previous definition is here
            for (int i = 0; i < Stream->WriterCohortSize; i++)
                     ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1124:14: error: redefinition of 'Dim'
    for (int Dim = 0; Dim < Dims; Dim++)
             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1096:14: note: previous definition is here
    for (int Dim = Dims - 1; Dim >= 0; Dim--)
             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1224:14: error: redefinition of 'Dim'
    for (int Dim = 0; Dim < Dims; Dim++)
             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1188:14: note: previous definition is here
    for (int Dim = 0; Dim < Dims; Dim++)
             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1408:30: error: redefinition of 'i'
                    for (int i = 0; i < DimCount; i++)
                             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1388:30: note: previous definition is here
                    for (int i = 0; i < LocalBlockID; i++)
                             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/cp_common.c:1401:18: error: redefinition of 'i'
        for (int i = 0; i < sizeof(CP_WriterResponseStructs) /
                 ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/cp_common.c:1389:18: note: previous definition is here
        for (int i = 0; i < sizeof(CP_DP_WriterArrayStructs) /
                 ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1799:14: error: redefinition of 'i'
    for (int i = 0; i < Info->VarCount; i++)
             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c:1784:14: note: previous definition is here
    for (int i = 0; i < Stream->WriterCohortSize; i++)
             ^
1 error generated.
Error while processing /ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/cp_common.c.
make[2]: *** [source/adios2/toolkit/sst/CMakeFiles/sst.dir/build.make:127: source/adios2/toolkit/sst/CMakeFiles/sst.dir/cp/cp_common.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
5 errors generated.
Error while processing /ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/ffs_marshal.c.
make[2]: *** [source/adios2/toolkit/sst/CMakeFiles/sst.dir/build.make:140: source/adios2/toolkit/sst/CMakeFiles/sst.dir/cp/ffs_marshal.c.o] Error 1
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/cp_reader.c:1465:14: error: redefinition of 'i'
    for (int i = 0; i < Stream->InternalMetaMetaCount; i++)
             ^
/ccs/home/brtnfld/packages/ADIOS2/source/adios2/toolkit/sst/cp/cp_reader.c:1452:14: note: previous definition is here
    for (int i = 0; i < Stream->InternalMetaMetaCount; i++)
             ^

**To Reproduce**

cmake -D ADIOS2_USE_HDF5=true \
..

make

**Desktop (please complete the following information):**
Summit:

Currently Loaded Modules:
  1) xl/16.1.1-10   2) spectrum-mpi/10.4.0.3-20210112   3) lsf-tools/2.0   4) hsi/5.0.2.p5   5) darshan-runtime/3.3.0-lite   6) xalt/1.2.1   7) DefApps   8) zlib/1.2.11   9) cmake/3.21.3

**Comment by brtnfld** [comment]
Sorry, I meant the conn_version field. I can use 1.12 if that is supported. There are also other changes that need to be made, so if you would like to wait until 1.13 is released that would be fine. I don't think there are any more changes to be made to the vol interface before the release, but that could change.

**Comment by guj** [comment]
Thanks. Please use 1.12 for now.

**Comment by JasonRuonanWang** [comment]
There have been many HDF5 related changes since this issue. Hopefully it has been solved. Otherwise please feel free to re-open.
