### ISSUE TITLE
ADIOS2_USE_CUDA option not in the docs 

### ISSUE THREAD

**Issue by sb15895** [ornladios/ADIOS2#2956]
I am currently using ADIOS2 on HPC systems. I had some errors with CUDA compilers saying "No CMAKE_CUDA_COMPILER could be found." I fixed this with adding -DADIOS2_USE_CUDA=OFF in my cmake command.

**Comment by vicentebolea** [comment]
@sb15895 ADIOS2 default behavior for ADIOS2_USE_CUDA is to enable it if it can find its toolkit, if it cannot it will simply not enable CUDA compilation.

If you are having issues with the configure script being halted when not finding nvcc something must be off.

Could you provide the output of the configure phase?

**Comment by JasonRuonanWang** [comment]
Generally if there is no cuda toolkit installed at all, cmake will turn off cuda automatically, not even trying to find the cuda compiler. This has been tested substantially. In your case one possibility is that there is some kind of cuda toolkit installation that cmake did find, but it's not quite working, possibly missing some path environmental variables so cmake couldn't find the nvcc compiler. In this case manually specifying -DADIOS2_USE_CUDA=OFF is the way to go, just like what you did. It's also possible that the cmake version you used is not very friendly with the cuda version. But without further information, it's hard for us to determine what's really behind it.
