### ISSUE TITLE
Build error for third party ATL library

### ISSUE THREAD

**Issue by jw447** [ornladios/ADIOS2#2967]
Hi,

I was trying to rebuild the ADIOS2 (v2.7.1) when I encountered this issue:

```
CMake Error at thirdparty/atl/atl/cmake_install.cmake:57 (file):
  file INSTALL cannot find
  "/gpfs/alpine/proj-shared/csc143/jwang/io_modeling/ADIOS2/adios2-build/lib64/libadios2_atl.so.2.2.1":
  No such file or directory.
Call Stack (most recent call first):
  thirdparty/atl/cmake_install.cmake:47 (include)
  thirdparty/cmake_install.cmake:53 (include)
  cmake_install.cmake:52 (include)
```

I was not encountered with such issue before so I'm not sure if the upstream ATL library has been updated.

The build script used for building is as follows:

```
#!/bin/bash

module load cmake/3.18.4
module load gcc/9.3.0
module load openmpi/4.0.4
module load python/3.7-anaconda3
module load cuda/11.0.2

mkdir -p adios2-build && cd adios2-build

cmake -DADIOS2_USE_MPI=ON \
        -DADIOS2_USE_BZip2=OFF \
        -DADIOS2_USE_HDF5=ON \
        -DADIOS2_USE_Python=ON \
        -DADIOS2_USE_Fortran=OFF \
        -DADIOS2_USE_ZFP=ON \
        -DADIOS2_USE_SZ=ON \
        -DSZ_LIBRARY=$SZ_LIBRARY \
        -DZSTD_LIBRARY=$ZSTD_LIBRARY \
        -DSZ_INCLUDE_DIR=$SZ_INCLUDE_DIR \
        -DHDF5_ROOT=$HDF5_ROOT \
        -DHDF5_C_INCLUDE_DIR=$HDF5_C_INCLUDE_DIR \
        -DHDF5_FIND_DEBUG=ON \
        -DADIOS2_USE_MGARD=OFF \
        -DADIOS2_BUILD_EXAMPLES=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_TESTING=ON \
        -DCMAKE_INSTALL_PREFIX=/gpfs/alpine/proj-shared/csc143/jwang/io_modeling/ADIOS2/adios2-build/ ../

make -j 16
make install
```

I'd appreciate if you could point me to some fix.

Thanks,

**Comment by eisenhauer** [comment]
What host?  It's not clear from the snippet that you posted if there was an actual failure in building ATL (preventing the atl.so file from being generated), or if it might be a cmake problem in finding the successfully built library for installation.  Attaching the complete log might help sort that out.

**Comment by jw447** [comment]
I'm building on Andes at ORNL. The complete log is attached as follows. It would seem that libadios2_atl.so.2.2.1 is not found in the build/lib64 directory.

[build_andes.log](https://github.com/ornladios/ADIOS2/files/7647152/build_andes.log)

**Comment by williamfgc** [comment]
@jw447 Not sure, but looks like your build and installation directory point at the same location on Andes. Please try a different installation directory other than the build of that's the case.

**Comment by jw447** [comment]
Thanks, @williamfgc that seems to be a fix.
