### ISSUE TITLE
error compiling with gcc11

### ISSUE THREAD

**Issue by chi86** [ornladios/ADIOS2#2976]
Compiling with gcc-11.2.0 reported:

> In file included from ADIOS2-2.7.1/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.cpp:17:
> ADIOS2-2.7.1/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h:34:20: error: ‘std::shared_ptr’ has not been declared
>    34 |     void Send(std::shared_ptr<std::vector<char>> buffer);
>       |                    ^~~~~~~~~~
> ADIOS2-2.7.1/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h:34:30: error: expected ‘,’ or ‘...’ before ‘<’ token
>    34 |     void Send(std::shared_ptr<std::vector<char>> buffer);
>       |                              ^
> ADIOS2-2.7.1/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h:35:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
>    35 |     std::shared_ptr<std::vector<char>> Receive();
>       |          ^~~~~~~~~~
> ADIOS2-2.7.1/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h:17:1: note: ‘std::shared_ptr’ is defined in header  ‘<memory>’; did you forget to ‘#include <memory>’?
>    16 | #include <thread>
>   +++ |+#include \<memory\>
>    17 | 
> ...

by adding, as proposed in the error message "#include \<memory\>" at line 17 in "ADIOS2-2.7.1/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h" fixed the issue.

Best
Chris

**Comment by pnorbert** [comment]
Thanks for the report. This is already fixed in the master branch with commit https://github.com/ornladios/ADIOS2/commit/8d04bda12988ac4190780e1d75bedaf3e510d32c
