### ISSUE TITLE
adios_steps is brocken in the C binding

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#2980]
The adios_steps function  does not return the number of steps in a file; it returns alltimes 0. 
Platform:
Ubuntu 18.04, gcc 10.3.0
ADIOS 2.7.1.862

**Comment by williamfgc** [comment]
@dmitry-ganyushin does it work on the C++ API? That would be a good starting point.

**Comment by JasonRuonanWang** [comment]
@dmitry-ganyushin From my side it's working fine. I tested it with the following writer in C++ and reader in C. Please provide a code to reproduce it if you still have the problem. Or you can take my code and try reproducing the problem based on it. 

```
// writer.cpp
#include <vector>
#include <adios2.h>
int main(int argc, char *argv[])
{
    std::vector<double> myData = {
        0.0001, 1.0001, 2.0001, 3.0001, 4.0001, 5.0001, 6.0001, 7.0001, 8.0001, 9.0001,
        1.0001, 2.0001, 3.0001, 4.0001, 5.0001, 6.0001, 7.0001, 8.0001, 9.0001, 8.0001,
        2.0001, 3.0001, 4.0001, 5.0001, 6.0001, 7.0001, 8.0001, 9.0001, 8.0001, 7.0001,
        3.0001, 4.0001, 5.0001, 6.0001, 7.0001, 8.0001, 9.0001, 8.0001, 7.0001, 6.0001,
        4.0001, 5.0001, 6.0001, 7.0001, 8.0001, 9.0001, 8.0001, 7.0001, 6.0001, 5.0001,
        5.0001, 6.0001, 7.0001, 8.0001, 9.0001, 8.0001, 7.0001, 6.0001, 5.0001, 4.0001,
        6.0001, 7.0001, 8.0001, 9.0001, 8.0001, 7.0001, 6.0001, 5.0001, 4.0001, 3.0001,
        7.0001, 8.0001, 9.0001, 8.0001, 7.0001, 6.0001, 5.0001, 4.0001, 3.0001, 2.0001,
        8.0001, 9.0001, 8.0001, 7.0001, 6.0001, 5.0001, 4.0001, 3.0001, 2.0001, 1.0001,
        9.0001, 8.0001, 7.0001, 6.0001, 5.0001, 4.0001, 3.0001, 2.0001, 1.0001, 0.0001,
    };
    adios2::ADIOS adios;
    auto io = adios.DeclareIO("TestIO");
    auto varDouble = io.DefineVariable<double>("varDouble", {10,10}, {0,0}, {10,10}, adios2::ConstantDims);

    auto engine = io.Open("hello.bp", adios2::Mode::Write);
    for(int i=0; i<10; ++i)
    {
        engine.BeginStep();
        engine.Put<double>(varDouble, myData.data());
        engine.EndStep();
    }
    engine.Close();
    return 0;
}
```

```
// reader.c
#include <adios2_c.h>
#include <cstdio>
int main(int argc, char **argv)
{
    MPI_Init(&argc, &argv);
    adios2_adios *adios = adios2_init(MPI_COMM_WORLD, adios2_debug_mode_on);
    adios2_io *io = adios2_declare_io(adios, "Read");
    adios2_engine *e = adios2_open(io, "hello.bp", adios2_mode_read);
    size_t steps=0;
    adios2_steps(&steps, e);
    printf("steps = %lu\n", steps);
    MPI_Finalize();
    return 0;
}
```

```
# output 
steps = 10
```

**Comment by dmitry-ganyushin** [comment]
I set the read engine as a FileStream:

adios2_error adiosErr = adios2_set_engine(file->ioH, "FileStream");

Should not it work for that case?

**Comment by eisenhauer** [comment]
Generally Steps() isn't a reasonable thing to ask a streaming engine...   SST doesn't override the default implementation, so it will throw an exception.  FileStream is a version of bp4 and instead returns m_MetadataSet.StepsCount, which probably isn't set right for streaming.  BP5 doesn't implement streaming-through-file yet.  We should probably decide whether or not 0, 1 or exception is the right thing to do for streaming engines and make them all consistent.

**Comment by JasonRuonanWang** [comment]
> I set the read engine as a FileStream:
> 
> adios2_error adiosErr = adios2_set_engine(file->ioH, "FileStream");
> 
> Should not it work for that case?

Greg gave the perfect answer. The concept *stream* in ADIOS2 means real streams, i.e. something working regardless previous steps or status. So it's reasonable to assume that typical implementations will ignore outdated steps and only process the latest available step if you use anything streaming.
