### ISSUE TITLE
 Feature request: Wildcard (*) support for "io name" in adios2 XML 

### ISSUE THREAD

**Issue by MichaelLaufer** [ornladios/ADIOS2#2985]
**Why is this feature important?**
Currently when using the XML for adios2 configuration, the distinct IO name must be specified. 
It would be helpful if a wildcard could be used to apply the same configuration parameters for multiple IO's.

**What is the potential impact of this feature in the community?**
I believe that this feature could help porting current codes to use ADIOS2 where the natural IO name would be the file name, which may change between subsequent runs (e.g CFD_out_5s.bp, CFD_out_15s.bp etc.). Being able to use a wildcard expression (e.g CFD_out*) could reduce the manual user intervention that would be needed to edit XMLs.

**Is your feature request related to a problem? Please describe.**
Yes, I am porting WRF to support ADIOS2 for I/O, where the filename, as well as number of output files are not easily known at the beginning of the run (using a single IO for all outputs does not match the current WRF usage model, so multiple IOs are needed). A feature like this will greatly increase the usability for the user. 

**Describe the solution you'd like and potential required effort**
 Wildcard (*) support for "io name" in adios2 XML. I assume some implementation of pattern matching with regex should do the trick, but I have not looked at the implementation details. I would appreciate input on the implementation complexity of the feature.

**Describe alternatives you've considered and potential required effort**
Alternatively, an option to apply a set of parameters for **ALL** IO names could also provide a partial but helpful solution (e.g io name="\_\_ALL\_\_").
The other option, at the main application level, is to add a secondary set of global ADIOS2 parameters in main application config that is then programmatically applied for all  the outputs, but this feels a bit superfluous, and may introduce some corner cases that will break intended functionality.

**Comment by williamfgc** [comment]
@MichaelLaufer out of curiosity. Why are the multiple files needed (one per step, I guess)?  In a way it defeats the purpose of adios streaming APIs. Perhaps, an opportunity to rethink I/O in your app to avoid potential bottlenecks. Still

**Comment by MichaelLaufer** [comment]
@williamfgc The application has a "frames_per_outfile" runtime parameter  which allows for X outputs to be outputted (appended) to a single outfile. When this parameter is set to the number of total outputs in the run (manually, in a Fortran namelist), my implementation will indeed utilize the begin_step/end_step adios2 paradigm. 
BUT this is not the default behavior in this legacy application, and I must also support the multiple file approach.

**Comment by pnorbert** [comment]
If you have always one file opened for writing, you can reuse the same IO
object. E3SM/Scorpio and XGC does similarly, packing N steps/frames into
one file but create multiple files during the run.

**Comment by MichaelLaufer** [comment]
Thanks @pnorbert, i did not realize that the same IO object can be reused. I will try to consolidate to a single IO object.
Assuming that is the case,  I agree, this feature should not be needed.
Closing for now.
Thanks!
