### ISSUE TITLE
Pass decompress parameters to ADIOS when reading back data

### ISSUE THREAD

**Issue by guj** [ornladios/ADIOS2#3008]
**Why is this feature important?**
- So that client can pass parameters to desired decompressor and improve performance. 
**What is the potential impact of this feature in the community?**
- This will help improve the read time
**Is your feature request related to a problem? Please describe.**
- This request is from decompressing with blosc.  And it applies to all other decompressors. 
**Describe the solution you'd like and potential required effort**
-  I would like to see a way to let blocs use multiple threads when decompress data. 
**Describe alternatives you've considered and potential required effort**
- At least use the same number of compression threads would do.

**Comment by ax3l** [comment]
Thanks for looking into this!
We asked for this because we like to use this with blosc in read workflows.

cc @franzpoeschel @psychocoderHPC so you also get updates

**Comment by JasonRuonanWang** [comment]
I am trying to add it but I am not sure how blosc decompressor takes the parameter. It looks to me that the blosc decompression API does not take any parameters. Can anyone show me an example or something that makes blosc decompress some data using a parameter?

**Comment by ax3l** [comment]
Hi,

Thanks for working on this.

It can definitely do it, see benchmarks here:
https://www.blosc.org/pages/blosc-in-depth/

Looking at the examples, I think you just set:
  blosc_set_nthreads(nthreads);
and then do your decompression.
https://github.com/Blosc/c-blosc/blob/master/examples/multithread.c

Axel

**Comment by JasonRuonanWang** [comment]
The following line can be added in the reader code to enable blosc threads, once #3014 is merged.

        myVariable.AddOperation("blosc",{{"nthreads","8"}});

in which myVariable is an ADIOS2 variable object that is obtained from IO

        auto myVariable = myIO.InquireVariable<double>("myVariable");

**Comment by guj** [comment]
Thanks @JasonRuonanWang
