### ISSUE TITLE
support for fixed length arrays as data types for Variables?

### ISSUE THREAD

**Issue by cwsmith** [ornladios/ADIOS2#3058]
Hello,

Do [`Variables`](https://adios2.readthedocs.io/en/latest/components/components.html#data-types) support only a single fixed width type (e.g., `DefineVariable<int8_t>(...)`) or are fixed length arrays (possibly of multiple dimensions) of fixed width types supported (e.g., `DefineVariable<int8_t[2]>(...)`)?

Thank you.

**Comment by williamfgc** [comment]
@cwsmith at some point we discussed adding "compound types" or "structs", but the effort didn't justify the application in HPC for the performance scope of adios. There is added overhead tracking offsets and non-contiguous memory access. Either having two separate variables, or managing the offsets at the application level is your best bet. Hope it helps.

**Comment by cwsmith** [comment]
Thank you @williamfgc .  That answers my question.  I appreciate the quick response.
