### ISSUE TITLE
CMake doesn't detect missing Python.h 

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#306]
Python-dev is required by PyBind11. Compilation fails even when numpy and mpi4py are installed. This is not detected by cmake.
```
workspace/ADIOS2/thirdparty/pybind11/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
```

**Comment by chuckatkins** [comment]
This looks like a bug in the pybind11 FindPythonLibsNew code.  It explicitly searches for the python libraries and headers but assumes they are always found and doesn't actually check if they are or not.  I'll fix the issue upstream and backport the patch

**Comment by chuckatkins** [comment]
Rather than deal w/ it upstream, they seem pretty tied to their implementation so if we just fix it on the ADIOS side then the correct libs and dirs will propagate accordingly to bybind11.
