### ISSUE TITLE
Reading varying size tilmestep variable in Python

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#3093]
Hi. I am trying to read a varying size tilmestep data in Python without success. 

Initially, I tried the step-by-step reading example: `https://adios2.readthedocs.io/en/latest/api_high/api_high.html?highlight=step%20by%20step#python-read-step-by-step-example`
I need to read data step by step.

Instead, I like to read a variable directly at specific tilmestep. Reading step-by-step cannot be a reasonable solution if there are lots of time steps. In XGC, now we have many datasets in varying size. 

Another issue is that it looks like there is no function to get the size at specific tilmestep.

Can anyone give any advice?

An example data is here: `/gpfs/alpine/proj-shared/csc143/jyc/summit/su461_d3d_lowB_for_GB_small/xgc.escaped_ptls.bp`

**Comment by pnorbert** [comment]
Which GCC version do you build ADIOS2 with that works with python/anaconda?

**Comment by jychoi-hpc** [comment]
`gcc/9.1.0`

**Comment by pnorbert** [comment]
That does not work for me, even though I just built adios2 with gcc/9.1.0
```
summit:pnorbert@login2:/gpfs/alpine/proj-shared/csc143/jyc/summit/su461_d3d_lowB_for_GB_small
$ which python3
/sw/summit/python/3.8/anaconda3/2020.07-rhel8/bin/python3
summit:pnorbert@login2:/gpfs/alpine/proj-shared/csc143/jyc/summit/su461_d3d_lowB_for_GB_small
$ python3
Python 3.8.3 (default, Jul  2 2020, 16:32:18)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import adios2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/build.summit.master.gcc/lib/python3.8/site-packages/adios2/__init__.py", line 1, in <module>
    from .adios2 import *
ImportError: /autofs/nccs-svm1_sw/summit/python/3.8/anaconda3/2020.07-rhel8/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/build.summit.master.gcc/lib/python3.8/site-packages/adios2/adios2.cpython-38-powerpc64le-linux-gnu.so)
>>>
```

**Comment by jychoi-hpc** [comment]
I found I was using a nompi version of adios python built with `gcc/6.4.0`. You can use mine as follows:
```
module load python

module use -a /gpfs/alpine/world-shared/csc143/jyc/summit/sw/modulefiles
module load adios2-nompi/devel
```

I am getting the same error with `gcc/9.1.0`.

**Comment by jychoi-hpc** [comment]
Here is my python code to demonstrate the problem I have:
```
import adios2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.tri as tri

def adios2_get_shape(f, varname):
    nstep = int(f.available_variables()[varname]["AvailableStepsCount"])
    shape = f.available_variables()[varname]["Shape"]
    lshape = None
    if shape == "":
        ## Accessing Adios1 file
        ## Read data and figure out
        v = f.read(varname)
        lshape = v.shape
    else:
        lshape = tuple([int(x.strip(",")) for x in shape.strip().split()])

    return (nstep, lshape)

## want to read data at step 50
istep = 50

## Reading step-by-step
print (">>> step-by-step")
with adios2.open("xgc.escaped_ptls.bp", "r") as fh:
    for fstep in fh:
        print ("Step:", fstep.current_step())
        if fstep.current_step() == istep:
            nstep, count = adios2_get_shape(fstep, 'iphase')
            start = [0,]*len(count)
            iphase = fstep.read("iphase", start=start, count=count)
            print (fstep.current_step(), iphase.shape)

## Reading directly at a specific step
print (">>> low-level")
ad = adios2.ADIOS()
IO = ad.DeclareIO("escaped_ptls")
reader = IO.Open("xgc.escaped_ptls.bp", adios2.Mode.Read)
var = IO.InquireVariable("iphase")

## Not working
# shape = ## don't know how to get shape at a specific step
# var.SetShape(shape)
# var.SetSelection(([0,]*len(shape), shape))
# var.SetStepSelection([istep, istep+1])
# iphase = np.zeros(shape, dtype=np.float32)
# reader.Get(var, iphase)
# reader.PerformGets()
# print ("iphase.shape:", iphase.shape)

reader.Close()

```

**Comment by jychoi-hpc** [comment]
By the way, I found a workaround for the `GLIBCXX_3.4.26` not found error.  Need to use LD_PRELOAD=/sw/summit/gcc/9.1.0-alpha+20190716/lib64/libstdc++.so
```
module load gcc/9.1.0

module use -a /gpfs/alpine/world-shared/csc143/jyc/summit/sw/modulefiles
module load adios2/devel

LD_PRELOAD=/sw/summit/gcc/9.1.0-alpha+20190716/lib64/libstdc++.so jsrun -n 1 python -c "import adios2; print(adios2.__file__)"

```

**Comment by dmitry-ganyushin** [comment]
[jychoi-hpc](https://github.com/jychoi-hpc), It looks like this part is not fully documented. Please see an example
https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/bindings/python/TestBPSelectSteps.py

**Comment by jychoi-hpc** [comment]
It is not working for me.

First of all, the example doesn't show how to get a shape information at a specific timestep.

Second of all, even if I provide a prior knowledge, I got an error:
```
Traceback (most recent call last):
  File "/Users/jyc/project/XGC_analysis/test.py", line 36, in <module>
    reader.Get(var, iphase)
ValueError: [Mon Mar 14 18:14:13 2022] [ADIOS2 EXCEPTION] <Toolkit> <format::bp::BP4Deserializer> <InitVariableBlockInfo> : offset 5 from steps start 5 in variable iphase is beyond the largest available step = 9, check Variable SetStepSelection argument stepsCount (random access), or number of BeginStep calls (streaming), in call to Get
```
Here is my test code:
```
import adios2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.tri as tri

def adios2_get_shape(f, varname):
    nstep = int(f.available_variables()[varname]["AvailableStepsCount"])
    shape = f.available_variables()[varname]["Shape"]
    lshape = None
    if shape == "":
        ## Accessing Adios1 file
        ## Read data and figure out
        v = f.read(varname)
        lshape = v.shape
    else:
        lshape = tuple([int(x.strip(",")) for x in shape.strip().split()])

    return (nstep, lshape)

## want to read data at step 5
istep = 5

## Reading directly at a specific step
print (">>> low-level")
ad = adios2.ADIOS()
IO = ad.DeclareIO("escaped_ptls")
reader = IO.Open("xgc.escaped_ptls.bp", adios2.Mode.Read)
var = IO.InquireVariable("iphase")

## Not working
# shape = ## don't know how to get shape at a specific step
var.SetSelection(([0,0], [10,11]))
var.SetStepSelection([istep, istep+1])
iphase = np.zeros([10,11], dtype=np.float32)
reader.Get(var, iphase)
reader.PerformGets()
print ("iphase.shape:", iphase.shape)

reader.Close()

```

**Comment by jychoi-hpc** [comment]
I overlooked param_string. I got the second part working (i.e., assuming that I know prior knowledge of shape/size).

But, still I don't know how to get a shape/size at a specific step. 

Here is a working version for the second part:
```
istep = 5
selected_steps = [istep, ]

## Reading directly at a specific step
print (">>> low-level")
ad = adios2.ADIOS()
IO = ad.DeclareIO("escaped_ptls")
param_string = ",".join([str(i) for i in selected_steps])
IO.SetParameter("xgc.escaped_ptls.bp", param_string)
reader = IO.Open("xgc.escaped_ptls.bp", adios2.Mode.Read)
var = IO.InquireVariable("iphase")

## Not working
# shape = ## don't know how to get shape at a specific step
var.SetSelection(([0,0], [10,11]))
var.SetStepSelection([0, len(selected_steps)])
iphase = np.zeros([len(selected_steps),10,11], dtype=np.float32)
reader.Get(var, iphase)
reader.PerformGets()
print ("iphase.shape:", iphase.shape)

reader.Close()
```

**Comment by pnorbert** [comment]
@jychoi-hpc  https://adios2.readthedocs.io/en/latest/api_full/api_full.html#variable-class
There is a Shape(int step) function for a variable. Can you try that?

**Comment by dmitry-ganyushin** [comment]
That works for Summit:
``>>> ad = adios2.ADIOS()                                                                                         
>>> IO = ad.DeclareIO("escaped_ptls")
>>> reader = IO.Open("/gpfs/alpine/proj-shared/csc143/jyc/summit/su461_d3d_lowB_for_GB_small/xgc.escaped_ptls.bp", adios2.Mode.Read)
>>> reader
<adios2.adios2.Engine object at 0x7fffa3fcbe30>
>>> var = IO.InquireVariable("iphase")
>>> var
<adios2.adios2.Variable object at 0x7fffa22fc730>
>>> var.       
var.AddOperation(       var.SelectionSize(      var.Shape(              var.StepsStart(
var.BlockID(            var.SetBlockSelection(  var.ShapeID(            var.Type(
var.Count(              var.SetSelection(       var.Sizeof(             
var.Name(               var.SetShape(           var.Start(              
var.Operations(         var.SetStepSelection(   var.Steps(              
>>> var.Shape
var.Shape(    var.ShapeID(  
>>> var.Shape(0)
[9955349, 11]
>>> var.Shape(1)
[10372291, 11]
>>> var.Shape(2)
[10354332, 11]
``
