### ISSUE TITLE
C++20 libraries that include the `adios2.h` header fail to compile (GCC 11)

### ISSUE THREAD

**Issue by garth-wells** [ornladios/ADIOS2#3146]
The header files `bindings/CXX11/adios2/cxx11/Attribute.h` and `bindings/CXX11/adios2/cxx11/Variable.h` contain declarations that are not valid C++20. Libraries compiled with C++20 and which include these files (typically indirectly via `adios2.h`) fail to compile with GCC 11.2.  The issue is discussed at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97202.

The simple changes in #3145 fix the issue.

**Comment by chuckatkins** [comment]
Fixed
