### ISSUE TITLE
HDF5 API checks are wrong

### ISSUE THREAD

**Issue by eschnett** [ornladios/ADIOS2#3149]
This code
```
#if H5_VERSION_GE(1, 11, 0)
    herr_t ret = H5Oget_info(m_FileId, &oinfo, H5O_INFO_ALL);
#else
    herr_t ret = H5Oget_info(m_FileId, &oinfo);
#endif
```
in the file `source/adios2/toolkit/interop/hdf5/HDF5Common.cpp` checks the HDF5 API in the wrong way: it checks only the HDF5 version to find out which API to use. Instead, it should also check the macros `H5_USE_110_API` or similar, or it should set the respective macros to select a particular HDF5 API.

**Comment by ax3l** [comment]
cc HDF5 component contributor @guj 
cc release manager @chuckatkins

**Comment by guj** [comment]
Thanks for pointing out. I added extra checks.

**Comment by JasonRuonanWang** [comment]
Fix merged. Please re-open if the issue still exists.
