### ISSUE TITLE
v2.8.0: adiosLog.h (MSVC)

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#3150]
**Describe the bug**
I am trying to deploy ADIOS 2.8.0 via conda-forge.
https://github.com/conda-forge/adios2-feedstock/pull/44

It does not build with MSVC.

**To Reproduce**
Please see link.

Error:
```
CompressBZIP2.cpp
%SRC_DIR%\source\adios2/helper/adiosLog.h(24): error C2059: syntax error: 'constant'
%SRC_DIR%\source\adios2/helper/adiosLog.h(24): error C3805: 'constant': unexpected token, expected either '}' or a ','
%SRC_DIR%\source\adios2\operator\compress\CompressBZIP2.cpp(81): warning C4267: '+=': conversion from 'size_t' to 'unsigned int', possible loss of data
```

**Expected behavior**
Build.

My guess is that `ERROR` is also defined as a macro in a stdlib:
https://github.com/ornladios/ADIOS2/blob/v2.8.0/source/adios2/helper/adiosLog.h#L24

See:
https://stackoverflow.com/a/10191253/2719194

**Desktop (please complete the following information):**
 - OS/Platform: Windows (on CI via Azure Pipelines in conda-forge)
 - Build:
   - MSVC 19.16.27045.0

**Additional context**
Conda-Forge deployment (WIP): https://github.com/conda-forge/adios2-feedstock/pull/44

CC file author @JasonRuonanWang
CC release manager @chuckatkins

**Comment by chuckatkins** [comment]
Fixed

**Comment by ax3l** [comment]
x-ref: via #3153
