### ISSUE TITLE
Can Python binding get data through SST engine from C/C++ put?

### ISSUE THREAD

**Issue by halehawk** [ornladios/ADIOS2#3175]
Can Python binding get data through SST engine from C/C++ put? I tried a python binding get from C/C++ put by SST engine, but I keep get the following:
  File "helloBPReader.py", line 50, in <module>
  File "helloBPReader.py", line 50, in <module>
    bpFileReader.Get(var_get, myArray, adios2.Mode.Sync)
    bpFileReader.Get(var_get, myArray, adios2.Mode.Sync)
    bpFileReader.Get(var_get, myArray, adios2.Mode.Sync)
ValueError: ERROR: found null pointer for variable, in call to Engine::Get a numpy array

    bpFileReader.Get(var_get, myArray, adios2.Mode.Sync)
ValueError: ERROR: found null pointer for variable, in call to Engine::Get a numpy array

Is there any special in Python binding get() to retrieve the data? Or it cannot contact C/C++ get() data by SST at all? Many thanks!

**Comment by williamfgc** [comment]
@halehawk it should as that's part of the tutorial. SST is a streaming engine, so you can only consume data one step at a time (. Take a look at the [gray-scott example](https://github.com/ornladios/ADIOS2-Examples/tree/master/source/cpp/gray-scott#analysis-example-how-to-run) for a functional starting point for a Python streaming reader (plot) from a C++ streaming producer (simulation).

**Comment by pnorbert** [comment]
Note, that you need to call InquireVariable within each step, as the var_get variable object expires in EndStep. 

And then, if the variable is not present in a given step, you cannot read it either, naturally.

**Comment by halehawk** [comment]
@pnorbert I did call InquireVariable before BeginStep() and still got this null pointer error.

**Comment by pnorbert** [comment]
You need to call it _after_  BeginStep and use it before EndStep.

**Comment by JasonRuonanWang** [comment]
Looks like this is solved. Staging reader engines only get writer metadata after calling BeginStep(), before which the reader does not know what variables exist. So at this point InquireVariable returning nullptr is an expected behavior.
