### ISSUE TITLE
BP5 Append Mode with AppendAfterSteps option creates unreadable files

### ISSUE THREAD

**Issue by franzpoeschel** [ornladios/ADIOS2#3225]
Hey together, the BP5 `AppendAfterSteps` option does not work for me on the current ADIOS2 release (2.8.0):

**Describe the bug**

* Use a BP5 file
* Append to it with `adios2::Mode::Append` and delete some of the last steps with the `AppendAfterSteps` option
* Use `bpls` to try reading the file

In my tests, `bpls` cannot read the file after this

**To Reproduce**
Use the following BP5 file with 6 steps. (If it's relevant: It has been created by appending to the same BP5 file two times)
[sample.zip](https://github.com/ornladios/ADIOS2/files/8754455/sample.zip)

Append to it with the following C++ code:

```c++
#include <adios2.h>

int main( int argsc, char ** argsv )
{
    adios2::ADIOS adios;
    auto IO = adios.DeclareIO("asdf");
    IO.SetParameter("AppendAfterSteps", "-3");
    auto engine = IO.Open("append_groupbased.bp5", adios2::Mode::Append);

    engine.BeginStep();
    auto var = IO.DefineVariable<int>("somevariable", {5}, {0}, {5});
    int data[] = {0,1,2,3,4};
    engine.Put(var, data);
    engine.EndStep();
    engine.Close();
}
```

```CMake
cmake_minimum_required(VERSION 3.12.0)

project(adios2_append)
find_package(ADIOS2 REQUIRED)

add_executable(adios2_append adios2_append.cpp)
target_link_libraries(adios2_append PRIVATE adios2::cxx11)
```

After this:
```
> bpls append_groupbased.bp5/
Failed to open with BPFile engine: [Mon May 23 12:19:55 2022] [ADIOS2 EXCEPTION] <Engine> <BP5Reader> <ParseMetadataIndex> : Current ADIOS2 BP5 Engine only supports version 5.2, found 5.0 version

Failed to open with HDF5 engine: [Mon May 23 12:19:55 2022] [ADIOS2 EXCEPTION] <Engine> <HDF5ReaderP> <HDF5ReaderP> : Invalid HDF5 file found


Error: Could not open this file with any ADIOS2 file reading engines
```

**Expected behavior**

No error, behavior as in documentation

**Desktop (please complete the following information):**
 - OS/Platform: `nvidia/cuda:11.6.0-devel-ubuntu20.04` container, `g++ (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0`, x64 Intel processor
 - Build: Debug build, v2.8.0 git tag

**Additional context**
–

**Following up**
Was the issue fixed? Please report back.

**Comment by pnorbert** [comment]
It is a known issue. Fix is in the release_28 branch already

**Comment by franzpoeschel** [comment]
I noticed that the issue only occurs on the master branch, so it seems to have been reintroduced somehow. v2.8.3 is working fine.

**Comment by pnorbert** [comment]
The error message indicates this issue. We have a minor version in the BP5 format, now 5.2 in master.
