### ISSUE TITLE
Build error on Summit: undefined reference to `void adios2::helper::CUDAMinMax`

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#3257]
I am getting an error on Summit during compilation of v2.8.1
```[ 31%] Linking CXX executable ../../../../../bin/sst_conn_tool
../../../../../lib64/libadios2_core.so.2.8.1: undefined reference to `void adios2::helper::CUDAMinMax<long double>(long double const*, unsigned long, long double&, long double&)'
```

Compiler used: PGI 20.4
CUDA version: 11.0.3

Modules loaded:

```
  1) hsi/5.0.2.p5
  2) xalt/1.2.1
  3) DefApps
  4) cmake/3.23.1
  5) python/3.7-anaconda3
  6) git-lfs/2.11.0
  7) pgi/20.4
  8) spectrum-mpi/10.4.0.3-20210112
  9) nsight-compute/2021.2.1
 10) nsight-systems/2021.3.1.54
 11) cuda/11.0.3
 12) hypre/2.22.0-cpu
 13) lsf-tools/2.0
 14) amgx/2.1.0-1
 15) netcdf-fortran/4.4.5
 16) git/2.35.1
```

The configure log and build log are attached.
[build.txt](https://github.com/ornladios/ADIOS2/files/8960768/build.txt)
[config.txt](https://github.com/ornladios/ADIOS2/files/8960769/config.txt)

**Comment by vicentebolea** [comment]
@kshitij-v-mehta there has been many changes in the CUDA support in ADIOS2 can you check if this still occurs in the current master.

Thanks!

**Comment by anagainaru** [comment]
It still occurs but only with PGI, I am working on this
