### ISSUE TITLE
Compatibility with ZFP 1.0

### ISSUE THREAD

**Issue by minrk** [ornladios/ADIOS2#3303]
**Describe the bug**

[ZFP 1.0](https://github.com/LLNL/zfp/releases/tag/1.0.0) is out this week, but cmake rejects it (possibly correctly) as incompatible with the desired target of 0.5.1:

```
CMake Error at cmake/DetectOptions.cmake:94 (find_package):
Could not find a configuration file for package "ZFP" that is compatible
with requested version "0.5.1".

The following configuration files were considered but not accepted:
  $PREFIX/lib/cmake/zfp/zfp-config.cmake, version: 1.0.0
Call Stack (most recent call first):
 CMakeLists.txt:165 (include)
```

**To Reproduce**
1. install zfp 1.0
2. try to configure adios2 with `-DADIOS2_USE_ZFP=ON`
3. see `Could not find a configuration file for package "ZFP" that is compatible`

**Expected behavior**

Build succeeds.

**Desktop (please complete the following information):**
 - OS/Platform: Ubuntu 20.04
 - Build: cmake 3.23, zfp 1.0.0

**Additional context**

Building on [conda-forge](https://github.com/conda-forge/adios2-feedstock)

**Following up**

**Comment by ax3l** [comment]
Thanks for reporting this.
@pnorbert let us know what the status on compatibility for this is.

@chuckatkins if compatible, could you please relax the CMake compat. check in ADIOS2?

**Comment by chuckatkins** [comment]
I believe this is actually a zfp bug.  It should be defining the compatibility rules in it's generated zfp-config.cmake.  I'll take a closer look though when I get a chance.

**Comment by ax3l** [comment]
You are right, they intentionally declare major releases as breaking:
https://github.com/LLNL/zfp/blob/develop/zfp-config-version.cmake.in

**Comment by chuckatkins** [comment]
> You are right, they intentionally declare major releases as breaking: https://github.com/LLNL/zfp/blob/develop/zfp-config-version.cmake.in

Okay, so looking at this a little deeper, the version compatibility test in `zfp-config-version.cmake` is reasonable since there are some api breakages in `1.0.0`, just not the ones adios uses   We do need to change the header paths we use for `>= 1.0.0`.  So it's a pretty straightforward change on our end.  I'll get a pr up for it.
