### ISSUE TITLE
Count and SelectionSize are not updated at new step for variable sized 1D global array

### ISSUE THREAD

**Issue by lyon-fnal** [ornladios/ADIOS2#3311]
When reading a file with multiple steps and a 1D global array that has a different size in each step, the `Count` and `SelectionSize` are not updated at a new step. `Shape` is updated. This leads to an ADIOS2 exception if the array in a step is smaller than the previous step (out of bounds). This can be solved by calling `SetSelection` and setting the count equal to the shape to read the whole array in the step, but needing this call to `SetSelection` is not obvious from the documentation.

**To Reproduce**
I have a Julia program [Gist](https://gist.github.com/lyon-fnal/c615d5edc8dceb34d2283f576f35a327#file-mwe_stepsandarraycount-jl) that is a minimum-working-example. Note that ADIOS2.jl uses the C API.

The output is...
```
Step 0: Shape is 200, Start is 0, Count is 200, selection_size is 200
Step 1: Shape is 100, Start is 0, Count is 200, selection_size is 200
[Fri Aug 12 18:25:19 2022] [ADIOS2 ERROR] <Helper> <adiosSystem> <ExceptionToError> : adios2_end_step: [Fri Aug 12 18:25:19 2022] [ADIOS2 EXCEPTION] <Toolkit> <format::bp::BP4Deserializer> <SetVariableBlockInfo> : selection Start Dims(1):[0] and Count Dims(1):[200] (requested) is out of bounds of (available) Shape Dims(1):[100] , when reading global array variable anArray in step 2, in call to Get
```

**Expected behavior**
It would be nice if `Count` and `SelectionSize` were updated by default to the correct size of a global array in the step. That way ADIOS2 would "do the right thing" by default and not lead to an exception. I note that if `SetSelection` is called, then that selection is kept for all subsequent steps. So my suggestion here would break this behavior (unless you can tell if the user called `SetSelection` in the past and then not reset start and count). Perhaps a better solution is to have a note in the documentation that says one must call `SetSelection` to read arrays that change size for each step (or if it is there, make it more obvious :-)

**Desktop (please complete the following information):**
- Mac and Linux

Thanks!

**Comment by williamfgc** [comment]
@lyon-fnal try moving `inquire_variable` inside the `begin_step/end_step` region. Adios2 is step based, so each step can redefine its own set of variables. The latter is a truly streaming API for that can be used with SST.

**Comment by lyon-fnal** [comment]
Hi @williamfgc!  I'm afraid moving the `inquire_variable` within the `begin_step/end_step` didn't help. Same behavior as before.

**Comment by williamfgc** [comment]
@lyon-fnal thanks for confirming this and providing code. I'll try to follow up to see if it's an issue with the library or the bindings. We have test for variables changing shape [here](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/engine/bp/TestBPChangingShape.cpp). 

> It would be nice if Count and SelectionSize were updated by default to the correct size of a global array in the step

Taking a second look, Count and SelectionSize are user decisions and they might be intended not to change (e.g. we always want the first N elements, regardless of the changing shape). It's probably a design decision as "correct" depends on the user. Shape is the one that should be updated as it's a property of the variable when written. Let me know if this makes sense. Thanks!

**Comment by lyon-fnal** [comment]
Yes, I think I'm coming to the same realization as you ... start and count are user decisions. How about I'll open a PR early next week with an update to the documentation (maybe the `advice.rst` file) that explains this. 

Overall, I'm finding the documentation to be really great - but it's missing a few little things like this. I have a feeling that my use case is somewhat unusual (e.g. most examples I see are for fixed sized arrays - not variable sized ones like mine). 

Thanks again! I'll close this issue.

**Comment by williamfgc** [comment]
@lyon-fnal thanks! You're absolutely right, the docs can always be improved and contributions are always welcome! There is always rough edges that come from very specific cases. I appreciate your insight on this.
