### ISSUE TITLE
Question: SST with MPI dataplane requires MPI_THREAD_MULTIPLE?

### ISSUE THREAD

**Issue by cwsmith** [ornladios/ADIOS2#3323]
Is MPI_THREAD_MULTIPLE required for getting 'good' performance with SST using the MPI dataplane?  I hit this warning and figured I should ask:

https://github.com/ornladios/ADIOS2/blob/f3b207575983bcdafd8ce7860e6027e45ccffd22/source/adios2/toolkit/sst/dp/mpi_dp.c#L272-L278

@vicentebolea I'm tagging you here and in a related PR since I saw you had changes in this code recently.  Sorry for the noise if it isn't your area.

**Comment by eisenhauer** [comment]
Vicente is the right guy, but the deal is that it is required in order to use the MPI dataplane _at all_ in SST.  SST uses a background thread for network handling, so if you also use MPI in the main program, you have to have MPI_THREAD_MULTIPLE enabled so that MPI runs in a thread-safe manner.

**Comment by cwsmith** [comment]
Great.  Thank you.
