### ISSUE TITLE
support multiple read request for one variable

### ISSUE THREAD

**Issue by guj** [ornladios/ADIOS2#335]
Need to support multiple selection in the Variable class
so it is possible to schedule multiple GetDefered() requests on that variable.

Right now client has to union different selections or do GetSync()
if they want to read data from 2 different boundingboxes for the same variable

**Comment by pnorbert** [comment]
We need an example for this. It should work this way:
var.SetSelection()
engine.GetDeferred()
var.SetSelection()
engine.GetDeferred()
engine.PerformGets()

**Comment by eisenhauer** [comment]
Let me add that we need the same thing with PutDeferred() on the write side...   (And Norbert, I would encourage a test and not just an example!   (You probably meant example in the looser sense, but just to clarify...))

**Comment by williamfgc** [comment]
Closing this as this is supported at user API level by bpfile in sync and deferred modes in master.
