### ISSUE TITLE
Staging pipeline error with SST in gray-scott tutorial pipeline

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#3353]
Master branch and ADIOS2-Examples, the gray-scott pipeline does not work properly with SST: the python script claims mismatched versions. 

The adios2-gray-scott to gsplot.py pipeline does not work:
```
~/Software/ADIOS2-Examples/build/install/share/adios2-examples/gray-scott$ mpirun -n 4 ../../../../bin/adios2-gray-scott settings-files.json : -n 1 python3 ./gsplot.py -i gs.bp
MPI init without MPI_THREAD_MULTIPLE (Externally initialized:true)
Simulation writes data using engine type:              SST
IO parameters:  
    AsyncWrite = false
    NumAggregators = 1
    OpenTimeoutSecs = 60.0
    QueueFullPolicy = Discard
    QueueLimit = 1
    RendezvousReaderCount = 0
========================================
grid:             64x64x64
restart:          no
steps:            1000
plotgap:          10
F:                0.01
k:                0.05
dt:               2
Du:               0.2
Dv:               0.1
noise:            1e-07
output:           gs.bp
adios_config:     adios2.xml
process layout:   2x2x1
local grid size:  32x32x64
========================================
Simulation at step 10 writing output step     1
Simulation at step 20 writing output step     2
Simulation at step 30 writing output step     3
Simulation at step 40 writing output step     4
 * An invalid message of type "ReaderRegister" has been received on an incoming connection.
 * In ADIOS2/SST this likely means a version mismatch between stream participants.
 * Please ensure that all writers and readers are built with the same version of ADIOS2.

```

A pipeline between gray-scott and pdf-calc runs fine. 
`~/Software/ADIOS2-Examples/build/install/share/adios2-examples/gray-scott$ mpirun -n 4 ../../../../bin/adios2-gray-scott settings-files.json : -n 1 ../../../../bin/adios2-pdf-calc gs.bp pdf.bp 100 `

Another pipeline with adios2_reorganize_mpi and pdfplot.py runs fine. 
`~/Software/ADIOS2-Examples/build/install/share/adios2-examples/gray-scott$ mpirun -n 4 /opt/adios2/bin/adios2_reorganize_mpi pdf.bp reorg.bp BP5 "" SST "" : -n 1 python3 ./pdfplot.py -i reorg.bp`

**Comment by pnorbert** [comment]
Even the reorganize - gsplot.py pipeline works fine although this is very very similar to the one not working properly:
`~/Software/ADIOS2-Examples/build/install/share/adios2-examples/gray-scott$ mpirun -n 4 /opt/adios2/bin/adios2_reorganize_mpi gs.bp reorg.bp BP5 "" SST "" : -n 1 python3 ./gsplot.py -i reorg.bp`

**Comment by pnorbert** [comment]
Note that the gray-scott -- pdf-calc -- pdfplot.py also have the same issue, so the problem is not tied to the gsplot.py script itself

**Comment by eisenhauer** [comment]
I will try to recreate, but running with the environment variable CMDataVerbose=1 might produce helpful output.

**Comment by pnorbert** [comment]
```
~/Software/ADIOS2-Examples/build/install/share/adios2-examples/gray-scott$ mpirun -n 4 ../../../../bin/adios2-gray-scott settings-files.json : -n 1 python3 ./gsplot.py -i gs.bp
MPI init without MPI_THREAD_MULTIPLE (Externally initialized:true)
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
Simulation writes data using engine type:              SST
IO parameters:  
    AsyncWrite = false
    NumAggregators = 1
    OpenTimeoutSecs = 60.0
    QueueFullPolicy = Discard
    QueueLimit = 1
    RendezvousReaderCount = 0
========================================
grid:             64x64x64
restart:          no
steps:            1000
plotgap:          10
F:                0.01
k:                0.05
dt:               2
Du:               0.2
Dv:               0.1
noise:            1e-07
output:           gs.bp
adios_config:     adios2.xml
process layout:   2x2x1
local grid size:  32x32x64
========================================
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
Simulation at step 10 writing output step     1
Simulation at step 20 writing output step     2
Simulation at step 30 writing output step     3
CM - Writing record of type ReaderRegister
CM - record type ReaderRegister, contents are:
  writer_ID = 94711587856864 ,writer_response_condition = 2 ,ReaderCohortSize = 1 ,SpecPreload = 1 ,CP_ReaderInfo = 0x55a08b7e4230 0x55a08b7e3660 CP_ReaderInfo = ContactInfo = "AAIAAJTJ8o2xnAAAATkCmAEAAH8=",reader_ID = 94148022220832 ,,,DP_ReaderInfo = 
R e 

  ****  Warning **** CM record dump truncated
  To change size limits, set CMDumpSize environment variable.

=======
CM - Total write size is 192 bytes data + 0 bytes attrs
 * An invalid message of type "ReaderRegister" has been received on an incoming connection.
 * In ADIOS2/SST this likely means a version mismatch between stream participants.
 * Please ensure that all writers and readers are built with the same version of ADIOS2.
Simulation at step 40 writing output step     4
```

**Comment by pnorbert** [comment]
The warning is there in the good run (gray-scott -- pdf-calc) as well, but the reader picks up the record
```
CM - Writing record of type ReaderRegister
CM - record type ReaderRegister, contents are:
  writer_ID = 94866286907872 ,writer_response_condition = 2 ,ReaderCohortSize = 1 ,SpecPreload = 1 ,CP_ReaderInfo = 0x5582a7427300 0x5582a7427f30 CP_ReaderInfo = ContactInfo = "AAIAAJTJ8o1HiwAAATkCmAEAAH8=",reader_ID = 94019639766256 ,,,DP_ReaderInfo = ,,,,
=======
CM - Total write size is 173 bytes data + 0 bytes attrs
CM - Receiving record of type ReaderRegister, FFSformat 0x7f1918002240
CM - Found incoming cm_format 0x5647c7574590, matching FFSformat 0x7f1918002240
CM - record type ReaderRegister, contents are:
  writer_ID = 94866286907872 ,writer_response_condition = 2 ,ReaderCohortSize = 1 ,SpecPreload = 1 ,CP_ReaderInfo = 0x7f1918001e60 0x7f1918001e68 CP_ReaderInfo = ContactInfo = "AAIAAJTJ8o1HiwAAATkCmAEAAH8=",reader_ID = 94019639766256 ,,,DP_ReaderInfo = ,,,,
=======
CM - Finish processing - record of type ReaderRegister
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
EVPath Version 4.2.4 -- Mon Dec  4 16:21:33 EST 2017
Simulation at step 10 writing output step     1
CM - Writing record of type WriterResponse
CM - record type WriterResponse, contents are:
  WriterResponseCondition = 2 ,WriterCohortSize = 4 ,WriterConfigParams = 0x5647c74bff98 WriterConfigParams = MarshalMethod = 1 ,verbose = 1 ,RegistrationMethod = 0 ,StepDistributionMode = 0 ,DataTransport = "evpath",WANDataTransport = NULL ,,,QueueLimit = ,

  ****  Warning **** CM record dump truncated
  To change size limits, set CMDumpSize environment variable.
```

**Comment by pnorbert** [comment]
SstVerbose=5: why is the reader in python selecting mpi dataplane?
```
Reader 0 (0x55f243779450): Sst set to use sockets as a Control Transport
DP Reader 0 (0x55f243779450): Considering DataPlane "evpath" for possible use, priority is 1
DP Reader 0 (0x55f243779450): Considering DataPlane "mpi" for possible use, priority is 100
DP Reader 0 (0x55f243779450): Selecting DataPlane "mpi", priority 100 for use
Reader 0 (0x55f243779450): Looking for writer contact in file gs.bp.sst, with timeout 60 secs
Param -   RendezvousReaderCount=0
DP Reader 0 (0x55f243779450): MPI dataplane reader initialized, reader rank 0
Reader 0 (0x55f243779450): Waiting for writer response message in SstReadOpen("gs.bp")
 * An invalid message of type "ReaderRegister" has been received on an incoming connection.
Reader 0 (0x55f243779450): finished wait writer response message in read_open
RuntimeError: [Thu Sep 29 07:06:30 2022] [ADIOS2 EXCEPTION] <Engine> <SstReader> <SstReader> : SstReader did not find active Writer contact info in file "gs.bp.sst".  Timeout or non-current SST contact file?
```

The mpi priority is -100 in the C++ reader:
```
eader 0 (0x55b4292fecf0): Sst set to use sockets as a Control Transport
DP Reader 0 (0x55b4292fecf0): Considering DataPlane "evpath" for possible use, priority is 1
DP Reader 0 (0x55b4292fecf0): Considering DataPlane "mpi" for possible use, priority is -100
DP Reader 0 (0x55b4292fecf0): Selecting DataPlane "evpath", priority 1 for use
```

**Comment by eisenhauer** [comment]
Hmm...  Will dig into this this morning.

**Comment by pnorbert** [comment]
Changing gray-scott to use MPI_THREAD_MULTIPLE makes SST pick MPI as default transport and then everything works. So it's that the python mpi4py is probably threaded by default

**Comment by pnorbert** [comment]
Or setting explicitly the DataTransport to WAN works as well. So it's the default policy that is causing problems when a "normal" C++ code is connecting to a Python/mpi4py code.

**Comment by pnorbert** [comment]
https://github.com/ornladios/ADIOS2-Examples/pull/67 now initializes MPI with threads in gray-scott. So the default transport will be MPI on both sides. Nevertheless this is still an issue for any app that uses MPI_Init(), or on systems where python mpi4py is non-threaded by default, even new gray-scott (could not confirm)

**Comment by eisenhauer** [comment]
I'm not sure we want the MPI data transport to be the default in any circumstances until we know a bit more about it.  I.E. performance, stability, etc...  But I'm not sure how this relates to the 'invalid message' error.  A disconnect in the defaults for data planes shouldn't produce that...

**Comment by pnorbert** [comment]
agree, making it default on the state of the individual application is not the best idea. It will not work when two apps have different MPI init levels and one will not be able to figure it out what went wrong.

**Comment by eisenhauer** [comment]
Ha, nevermind.  I know how that produces an "invalid message" error.  Let me at least get on a fix where this gives a more reasonable error message.  Then we can sort out what do do about data plane priorities...

**Comment by eisenhauer** [comment]
Should be addressed by #3356.  At least it will cause ADIOS to generate a more reasonable error message.  Still have to address the issue of different data planes being chosen.

**Comment by vicentebolea** [comment]
@eisenhauer was this fixed in #3356?

**Comment by eisenhauer** [comment]
"Fixed" might not be the right word.  The root of this problem was that two different builds of ADIOS had different default data planes and when they tried to connect the resulting error didn't have any obvious relationship with that problem.   #3356 added protocol where the reader gets info about what dataplane the writer selected earlier and tries to load that, failing with an error if it cannot.  That improves the situation slightly by adding a better error.  Really doing better, like doing a negotiation between reader and writer to see what planes they have in common, or maybe reconsidering the DP priorities based on measured performance requires more.  So, we could probably close this and open an issue that says that more directly.

**Comment by vicentebolea** [comment]
> So, we could probably close this and open an issue that says that more directly. 

@eisenhauer sounds good :+1:.

The feature of negotiating the DP between two ADIOS2 instances is a more involved task. I Agree that it grants its own issue.is a more developed. I wrote an issue to formalize this at #3479
