### ISSUE TITLE
data exchange between codes using SST engine, the same verstion of ADIOS2 with different compilers

### ISSUE THREAD

**Issue by jycheng1989** [ornladios/ADIOS2#3362]
I have two Fortran codes need data exchange using SST engine via ADIOS2 in Crusher. But these two codes are compiled with different compilers. One is using Cray compiler and another one is using AMD compiler. Both ADIOS2 use 2.8.1 but are compiled with different compilers. The error information shows that

' In ADIOS2/SST this likely means a version mismatch between stream participants.
 Please ensure that all writers and readers are built with the same version of ADIOS2.'

Can any setup solve the problem? Or I have to use the same compiler to couple these two codes.

**Comment by eisenhauer** [comment]
Hi. We've recent discovered that this error pops up when the two different instances of ADIOS end up selecting different DataTransports in the SST data plane layer.  A pull request that at least gives a better error message when this happens just got merged with GitHub master days ago.  You might try using master, or simply using the DataTransport engine parameter to actively control which data plane gets selected.

**Comment by jycheng1989** [comment]
> Hi. We've recent discovered that this error pops up when the two different instances of ADIOS end up selecting different DataTransports in the SST data plane layer. A pull request that at least gives a better error message when this happens just got merged with GitHub master days ago. You might try using master, or simply using the DataTransport engine parameter to actively control which data plane gets selected.

Thanks. Let me try the master version.

**Comment by pnorbert** [comment]
Does it work now?
