### ISSUE TITLE
SST_HAVE_MPI always off  in source/adios2/toolkit/sst/dp/dp.c

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3442]
> There are two #ifdef SST_HAVE_MPI blocks in source/adios2/toolkit/sst/dp/dp.c that don't get activated in my builds any more, and I find no place in the build system where that macro would be activated.

This is correct, I accidentally introduced this regression in #3407

_Originally posted by @vicentebolea in https://github.com/ornladios/ADIOS2/issues/3439#issuecomment-1404804753_

**Comment by pnorbert** [comment]
Please fix this a.s.a.p. The tutorial on Feb 8 needs this feature. Thanks
