### ISSUE TITLE
‘adios2_init_config' c binding is deprecated, and missing alternative MPI initialiser for C binding in the docs

### ISSUE THREAD

**Issue by sb15895** [ornladios/ADIOS2#3454]
I am writing a benchmarking library using C comparing ADIOS2, MPI and HDF5. For ADIOS2, I am using a config file and writing using the BP4 and the BP5 format. However, the recent updates have deprecated the adios2_init_config function
![image](https://user-images.githubusercontent.com/21076259/215793934-ea4847d5-4987-4219-b867-75f5db78f146.png)

The function to replace this initialiser does not appear to be mentioned in the read the docs. I am guessing that adios2_config_mpi should be the replacement function, but I am not completely sure. If there is any advice, I would be very interested. 

Thank you

**Comment by dmitry-ganyushin** [comment]
Although the function is documented, the build system of documentation ignores it,
```
/**
 * Starting point for MPI apps. Creates an ADIOS handler allowing a runtime
 * config file.
 * MPI collective and it calls MPI_Comm_dup and MPI_Bcast to pass the
 * configFile contents
 * @param config_file runtime configuration file in xml format
 * @param comm defines domain scope from application
 * @return success: handler, failure: NULL
 */
adios2_adios *adios2_init_config_mpi(const char *config_file, MPI_Comm comm);
```
Probably because ADIOS2_USE_MPI is not set for the C preprocessor at the time of doc build.

**Comment by vicentebolea** [comment]
@dmitry-ganyushin should we close this since the related PR that you authored has been merged?

**Comment by dmitry-ganyushin** [comment]
Completed
