### ISSUE TITLE
SST with MPI plane on Frontier 

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#3456]
When I attempt to use MPI in SST for XGC — GEM coupling, I'm encountering an error on Frontier. When I have a chance, I will try to running it on Crusher, and see if that reproduces the error. 

Here is the error log, which is occurring in XGC:

> MPICH ERROR [Rank 0] [job id 1267839.0] [Tue Jan 31 15:16:32 2023] [frontier01774] - Abort(673264166) (rank 0 in comm 0): Fatal error in PMPI_Comm_connect: Invalid port, error stack:
> PMPI_Comm_connect(125).........: MPI_Comm_connect(port="tag#0$connentry#0024CC21$", MPI_INFO_NULL, root=0, MPI_COMM_SELF, newcomm=0x7fe7ffff69b8) failed
> MPID_Comm_connect(192).........:
> MPIDI_OFI_mpi_comm_connect(662):
> (unknown)(): Invalid port
> 
> aborting job:
> Fatal error in PMPI_Comm_connect: Invalid port, error stack:
> PMPI_Comm_connect(125).........: MPI_Comm_connect(port="tag#0$connentry#0024CC21$", MPI_INFO_NULL, root=0, MPI_COMM_SELF, newcomm=0x7fe7ffff69b8) failed
> MPID_Comm_connect(192).........:
> MPIDI_OFI_mpi_comm_connect(662): 
> (unknown)(): Invalid port
> srun: error: frontier01774: task 0: Exited with exit code 255 
> srun: launch/slurm: _step_signal: Terminating StepId=1267839.0
> slurmstepd: error: *** STEP 1267839.0 ON frontier01774 CANCELLED AT 2023-01-31T15:16:33 ***
> srun: error: frontier02670: tasks 48-55: Terminated
> srun: error: frontier02556: tasks 40-47: Terminated
> srun: error: frontier02428: tasks 32-39: Terminated
> srun: error: frontier01902: tasks 8-15: Terminated
> srun: error: frontier02300: tasks 24-31: Terminated
> srun: error: frontier02814: tasks 56-63: Terminated
> srun: error: frontier02031: tasks 16-23: Terminated
> srun: error: frontier01774: tasks 1-7: Terminated
> srun: Force Terminated StepId=1267839.0
> 

It looks as if at least the first sender-receiver between GEM-XGC rendezvous'ed correctly, (unless it isn't using `RendezvousReaderCount: 1`, but I haven't set anything for that parameter myself explicitly) because I have two `.sst` files, not just one. XGC is reading, and so what I believe is going on, is that XGC is failing when it tries to read the first step from the first exchange with GEM. GEM doesn't crash and ends up hanging because XGC isn't progressing.

**Comment by vicentebolea** [comment]
Possibly related #3439

**Comment by vicentebolea** [comment]
This is related to problems with the cray-mpich library in Frontier/Crusher. You need to allocate the job with the following flags:

```
salloc ... --network=single_node_vni,job_vni
```

Also you will need to have at least 2 ranks per MPI domain. There are some scalability issues being resolved at #3588
