### ISSUE TITLE
Support for Variable with SetMemorySelection from GPU writer

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#3478]
Provide capability to support `Variable::SetMemorySelection` from GPU allocated data

**Why is this feature important?**
The gray-scott ADIOS2 Example can be ported to GPUs and Kokkos (for C++) as implemented in the recently added Julia version [GrayScott.jl](https://github.com/ornladios/ADIOS2-Examples/tree/master/source/julia/GrayScott.jl). When saving the data, the ghost cells must be removed using `Variable::SetMemorySelection` 

**What is the potential impact of this feature in the community?**
Allow saving only the relevant parts of a GPU-allocated variable, just like it's done on CPU system RAM allocated variables

**Is your feature request related to a problem? Please describe.**
No, more of a new feature not currently supported

**Describe the solution you'd like and potential required effort**
It's probably more likely to do the clipping and memory copies on CPU memory (as it's now) to avoid increasing GPU memory occupancy.

**Describe alternatives you've considered and potential required effort**
None

**Additional context**
GPU backend are still needed in the C++/Python version of gray-scott

**Comment by anagainaru** [comment]
@williamfgc we are working towards this. There will be several changes to the GPU backend for the v2.9.0 release that will make this possible. I'll keep you posted.

**Comment by anagainaru** [comment]
Tested and solved the problems for this in #3539
