### ISSUE TITLE
Example Plugin Engine: [ADIOS2 EXCEPTION] <Helper> <adiosType> <CheckForNullPtr> : found null pointer for variable in call to Engine::Get

### ISSUE THREAD

**Issue by tybulut** [ornladios/ADIOS2#3492]
**Describe the bug**
On top of mater on github repository, compiled from source code on Debian Linux.
examplePluginEngine_write  succeeds
examplePluginEngine_read fails with:

variable does not exist
Engine "TestPlugin" destroyed without a prior Close().
This may have negative consequences.
Invalid argument exception, STOPPING PROGRAM
[Mon Feb 20 16:14:26 2023] [ADIOS2 EXCEPTION] <Helper> <adiosType> <CheckForNullPtr> : found null pointer for variable in call to Engine::Get

**To Reproduce**
A minimal reproducible example is preferred.
Or Steps to reproduce the behavior:
1. Built latest git master branch
2. Run examplePluginEngine_read
3. Run examplePluginEngine_write
4. See error on terminal

**Expected behavior**
Success on terminal:
data was read correctly!

**Desktop (please complete the following information):**
 - OS/Platform: Debian 11.6
 - Build 
ADIOS2 build configuration:
  ADIOS Version: 2.9.0
  C++ Compiler : GNU 10.2.1 
    /usr/bin/c++

  Fortran Compiler : GNU 10.2.1 
    /usr/bin/f95

  Installation prefix: /media/src/york.ac.uk/usr
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/adios2
     python: lib/python3.9/site-packages

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: ON
    Examples: ON
    Build Options:
      BP5       : ON
      DataMan   : OFF
      DataSpaces: OFF
      HDF5      : ON
      HDF5_VOL  : OFF
      MHS       : ON
      SST       : ON
      CUDA      : OFF
      Fortran   : ON
      MPI       : ON
      Python    : OFF
      Blosc2    : OFF
      BZip2     : ON
      LIBPRESSIO: OFF
      MGARD     : OFF
      PNG       : OFF
      SZ        : OFF
      ZFP       : OFF
      DAOS      : OFF
      IME       : OFF
      O_DIRECT  : ON
      Sodium    : OFF
      Catalyst  : OFF
      SysVShMem : ON
      UCX       : OFF
      ZeroMQ    : OFF
      Profiling : ON
      Endian_Reverse: OFF
      GPU_Support: OFF
      AWSSDK    : OFF
    RDMA Transport for Staging: Unconfigured
-- Configuring done

**Additional context**
None

**Following up**

**Comment by caitlinross** [comment]
I was able to reproduce. I thought this example was being used in one of the CI tests, so I'll need to also figure out why either it's not being run or the error isn't being reported by CI.

**Comment by tybulut** [comment]
I verified / tested the PR#3499 successfully on my setup. Thanks!
