### ISSUE TITLE
ADIOS2 unknown type in C API

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#3507]
Adios types in C API defined as following:
```typedef enum
{
    adios2_type_unknown = -1,

    adios2_type_string = 0,
    adios2_type_float = 1,
    adios2_type_double = 2,
    .... 
} adios2_type;
```

I bumped into a problem with a C compiler here because the statement 
```assert (4 > adios2_type_unknown);```
fails. I can speculate that a C compiler translates enum into unsigned one byte integer type, and -1 is translated to 255.
One could fix it by changing the unknown type value to 255.

**Comment by eisenhauer** [comment]
Compilers are free to use an unsigned char to implement an enum type, which here would be the same as you changing that -1 to 255.  The problem is with the assertion that it is using > to test for something when that relationship may vary with the implementation.  Maybe the assertion can be rewritten so that it operates correctly regardless of the compiler's choice of implementation?  Restricting it to the use of =, or just using comparatives on the non-negative enums would be sufficient.

**Comment by dmitry-ganyushin** [comment]
In C++11 one can force ```int``` type for enums,
```
typedef enum: int
{
    minus_one = -1,
    minus_two = -2
};
```
 but this syntax does not work for GNU C-compiler.

**Comment by eisenhauer** [comment]
Can I ask where you bumped into this problem?  There isn't an assert like this in ADIOS, so I assume it's abstracted from some other circumstance?  I still tend to think that the answer is to fix the usage, not change the enum.

**Comment by dmitry-ganyushin** [comment]
In the scorpio library
https://github.com/E3SM-Project/scorpio/blob/5a542f0f87ebe039306e900278991c7b41bcf57a/src/clib/pio_darray.c#L2664

**Comment by eisenhauer** [comment]
That piece of code is fundamentally broken.
```
            if (vdesc_adios2->adios_type_size == 0)
                vdesc_adios2->adios_type_size = get_adios2_type_size(vdesc_adios2->adios_type, NULL);
            assert(vdesc_adios2->adios_type_size > adios2_type_unknown);
```
For one thing, the assert is comparing a size to a type enumeration value.  That doesn't even make sense.  If you wanted to change this to something that both worked and made sense change it to something like this:
```
            if (vdesc_adios2->adios_type_size == 0) {
                assert((int)vdesc_adios2->adios_type > (int) adios2_type_unknown);
                vdesc_adios2->adios_type_size = get_adios2_type_size(vdesc_adios2->adios_type, NULL);
            }
```
That is, you force those type values to be int before the comparison (and do it before you call get_adios2_type_size() using the value you're doing an assertion on).  Although if you wanted to be truely safe you could simply use a not equal operator:  `assert(vdesc_adios2->adios_type != adios2_type_unknown);`
