### ISSUE TITLE
Make BP5 work on Windows

### ISSUE THREAD

**Issue by eisenhauer** [ornladios/ADIOS2#3532]
EVPath, which is a requirement for SST and BP5 (because of FFS), hasn't been completely ported to Visual Studio, so BP5 doesn't build in CI on Windows and our default engine remains BP4 on those platforms.   This needs to be address so that we have a consistent default file engine across all platforms.

**Comment by vicentebolea** [comment]
@eisenhauer was this resolved?

**Comment by eisenhauer** [comment]
Mostly...  BP5 is now enabled, but SST is not.  Maybe leave it open as a reminder. But we do have a consistent file format default across all platforms.

**Comment by vicentebolea** [comment]
I See, moving this to the next patch release (or minor release)

**Comment by vicentebolea** [comment]
@eisenhauer I wonder if this was already completed?

**Comment by eisenhauer** [comment]
Same answer as July unfortunately.  I've made progress with SST, but there's some threading bug I can't quite sort out and this has fallen on my priority list.

**Comment by pnorbert** [comment]
need a new issue for SST
