### ISSUE TITLE
Use ccache in CI builds

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3548]

**Comment by scottwittenburg** [comment]
Working on this in #3705.

**Comment by vicentebolea** [comment]
@scottwittenburg I believe that this is done, shall we close it?

**Comment by scottwittenburg** [comment]
Yes, I have seen that workflows on `master` are populating the cache, and also that PR workflows are restoring from it and get good hit rates, so let's close.  We can always open a new issue to fix anything that might come up with ccache.
