### ISSUE TITLE
Does VTK's ADIOS2 VTX reader support mesh caching over timesteps?

### ISSUE THREAD

**Issue by stgeke** [ornladios/ADIOS2#3565]

**Comment by williamfgc** [comment]
@stgeke if your mesh is only written on step 0 and nowhere else (unchanged), then it's already in memory see this [line](https://gitlab.kitware.com/vtk/vtk/-/blob/master/IO/ADIOS2/VTX/schema/vtk/VTXvtkVTU.cxx#L162). So it's more of a question of how your mesh data was stored in the BP format, if it evolves and it's stored in BP VTX would read it. Hope it helps.

**Comment by williamfgc** [comment]
@stgeke any follow up? Let me know if we can close this.
