### ISSUE TITLE
Got undefined reference to `cod_yylex' when compiling ADIOS2

### ISSUE THREAD

**Issue by halehawk** [ornladios/ADIOS2#3572]
Hi,
I got undefined reference to `cod_yylex' when compiling ADIOS2/thirdparty/ffs main branch.
The error log is attached.
I used gust at UCAR, it is amd x86_64 cluster with modules:
1) ncarenv/23.03 (S)   4) ncarcompilers/0.8.0   7) cray-mpich/8.1.25
  2) craype/2.7.20       5) hdf5/1.12.2           8) cuda/11.7.1
  3) gcc/12.2.0          6) netcdf/4.9.1          9) cmake/3.25.2
Building scanner with flex 2.6.3
Building parser with bison 3.8.2
I didn't have this kind of error on casper.ucar before. So I suppose this error shall relate with craype or flex, bison.
Also if I commented out the following redefined macros (display some here, not all) in ~/ADIOS2_main/build/thirdparty/ffs/ffs/lex.yy.c, I can get rid of the above error.
    #define yy_create_buffer yy_create_buffer
    #define yy_delete_buffer yy_delete_buffer
    #define yy_scan_buffer yy_scan_buffer

Could you please help me to solve this problem?
[error.log](https://github.com/ornladios/ADIOS2/files/11115287/error.log)

**Comment by eisenhauer** [comment]
I'm investigating a bit, first in an environment with the same versions of flex and bison.  The ffs package has pre-processed source code outputs from flex and bison so we can build if those are not found.  One possible thing to try would be to make sure that flex and bison were not found so that we'd default to those versions.  Then again if this is really an issue with craype, that wouldn't help.   Give me a little while to see if I can figure out what might be going on.

**Comment by eisenhauer** [comment]
Well, building with the same versions of bison and flex don't reproduce the problem.  However, I'd like to followup on this:

> Also if I commented out the following redefined macros (display some here, not all) in ~/ADIOS2_main/build/thirdparty/ffs/ffs/lex.yy.c, I can get rid of the above error.
> #define yy_create_buffer yy_create_buffer
> #define yy_delete_buffer yy_delete_buffer

There are #defines similar to this in cod.y, which means that they appear in cod.tab.c and redefine things there and in cod.lex.c which is #included there.  But they look like this:
```
#define yy_flex_debug cod_yy_flex_debug
#define yy_create_buffer cod_yy_create_buffer
#define yy_delete_buffer cod_yy_delete_buffer

```
and include `#define yylex cod_yylex`, which produces the cod_yylex symbol that you're not getting defined.  Can you verify what you are seeing and where?  Maybe attach those files from the build directory?

**Comment by halehawk** [comment]
Thanks! Here is a tar ball of the build files, hope it help.
[ffs_build.tar.gz](https://github.com/ornladios/ADIOS2/files/11124347/ffs_build.tar.gz)

**Comment by halehawk** [comment]
Great, thanks a lot. I don't know how to avoid cmake looking for flex. I
will try to ask our admin to install flex 2.6.4 first.

**Comment by halehawk** [comment]
I set find_package(FLEX 2.6.4 REQUIRED) in thirdparty/ffs/ffs/CMakeLists.txt and -DFLEX_EXECUTABLE=/usr/bin/flex (which is 2.6.4) for cmake, it won't give cod_yylex error any more.

**Comment by eisenhauer** [comment]
Sounds good.  I'm not sure there's anything defensive we should do in ADIOS to protect against the flex bug, so at least for now I'll just close this issue.  Please let us know if you have further problems.
