### ISSUE TITLE
DAOS/DFS build is brocken

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#3589]
If I am trying to use DAOS/DFS with the current master commit 240690a4720d175847af043c09792505f3042dfc, transport library "daos" is not recognized. Before it was possible to set it up with transport parameter as
```<parameter key="Library" value="daos">``` 
in xml config file.
The cmake ADIOS2_USE_DAOS is not helping.

**Comment by eisenhauer** [comment]
I assume that you've checked to see if ADIOS2_HAVE_DAOS is true in the final config.h and have stepped through to where this is happening.  What's going on?

**Comment by dmitry-ganyushin** [comment]
cmake could not detect DAOS due to node misconfiguration.
