### ISSUE TITLE
Compilation error with ADIOS1=ON

### ISSUE THREAD

**Issue by dingwentao** [ornladios/ADIOS2#360]
I encountered a compilation issue when I build ADIOS2 with ADIOS1=ON. Here are the error messages:
[ 31%] Building CXX object source/adios2/CMakeFiles/adios2.dir/__/__/bindings/C/adios2/adios2_c_adios.cpp.o
[ 32%] Building CXX object source/adios2/CMakeFiles/adios2.dir/__/__/bindings/C/adios2/adios2_c_glue.cpp.o
[ 32%] Building CXX object source/adios2/CMakeFiles/adios2.dir/__/__/bindings/C/adios2/adios2_c_io.cpp.o
[ 33%] Building CXX object source/adios2/CMakeFiles/adios2.dir/__/__/bindings/C/adios2/adios2_c_engine.cpp.o
[ 34%] Building CXX object source/adios2/CMakeFiles/adios2.dir/__/__/bindings/C/adios2/adios2_c_variable.cpp.o
[ 34%] Building CXX object source/adios2/CMakeFiles/adios2.dir/__/__/thirdparty/pugixml/pugixml/src/pugixml.cpp.o
[ 35%] Linking CXX shared library ../../lib/libadios2.so
/home/dtao/adios-1.13.0/lib: file not recognized: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libadios2.so.2.1.0] Error 1
make[1]: *** [source/adios2/CMakeFiles/adios2.dir/all] Error 2
make: *** [all] Error 2

I installed AIDOS-1.13.0 in /home/dtao/adios-1.13.0 successfully and configure ADIOS2 by using the command: cmake -DCMAKE_INSTALL_PREFIX=/opt/adios2/2.0.0/gnu/openmpi -DADIOS1_LIBRARY=/home/dtao/adios-1.13.0/lib -DADIOS1_INCLUDE_DIR=/home/dtao/adios-1.13.0/include ../source

ADIOS2 build configuration:
  ADIOS Version: 2.1.0
  C++ Compiler : GNU 4.8.5
    /usr/bin/c++

  Installation prefix: /opt/adios2/2.0.0/gnu/openmpi
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/adios2

  Features:
    Library Type: shared
    Build Type:   Debug
    Testing: ON
    Build Options:
      BZip2    : OFF
      ZFP      : OFF
      MPI      : ON
      DataMan  : ON
      SST      : OFF
      ZeroMQ   : OFF
      HDF5     : OFF
      **ADIOS1   : ON**
      Python   : OFF
      Fortran  : OFF
      SysVShMem: ON

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dtao/adios2/build

However, if I turn ADIOS1 off, ADIOS2 can be compiled successfully. 
....
[ 38%] Building CXX object source/adios2/CMakeFiles/adios2.dir/__/__/thirdparty/pugixml/pugixml/src/pugixml.cpp.o
[ 39%] Linking CXX shared library ../../lib/libadios2.so
[ 39%] Built target adios2
Scanning dependencies of target bpls2
[ 40%] Building CXX object source/utils/CMakeFiles/bpls2.dir/bpls2/main.cpp.o
[ 41%] Building CXX object source/utils/CMakeFiles/bpls2.dir/bpls2/BPLS2.cpp.o
...
[100%] Linking CXX executable ../../../bin/TestXMLConfig
[100%] Built target TestXMLConfig

Anyone could help me with this issue?

**Comment by scottwittenburg** [comment]
I think you need to supply the path to a library file as the value for `ADIOS1_LIBRARY`, rather than simply the path to the directory containing that library.

**Comment by pnorbert** [comment]
Please do not use ADIOS1_LIBRARY.
Use ADIOS1_DIR=/home/dtao/adios-1.13.0 in your current checkout. This is
changing to be ADIOS1_ROOT in the release coming up by 12/31. You can
access the latest code in the 'release' branch.

**Comment by dingwentao** [comment]
Hi Nobert,

Thanks for your reply!
However, it seems I am unable to build with AIDOS1=ON when I use ADIOS1_DIR option. Please see the following commands:
$ cmake -DCMAKE_INSTALL_PREFIX=/opt/adios2/2.0.0/gnu/openmpi -DADIOS1_DIR=/home/dtao/adios-1.13.0 -DADIOS1_INCLUDE_DIR=/home/dtao/adios-1.13.0/include ../source

...
-- Could NOT find ADIOS1 (missing: ADIOS1_LIBRARY) (Required is at least version "1.12.0")
...

    Build Options:
      BZip2    : OFF
      ZFP      : OFF
      MPI      : ON
      DataMan  : ON
      SST      : OFF
      ZeroMQ   : OFF
      HDF5     : OFF
      **ADIOS1   : OFF**
      Python   : OFF
      Fortran  : OFF
      SysVShMem: ON

I am currently using the updated ADIOS2 in the master branch. 
Thanks for your help!

**Comment by dingwentao** [comment]
Hi Scott,

Which file should I pass to ADIOS1_LIBRARY? I tried ADIOS1_LIBRARY=/home/dtao/adios-1.13.0/lib/libadios.a, but it also had an issue.
Linking CXX shared library ../../lib/libadios2.so
/usr/bin/ld: /home/dtao/adios-1.13.0/lib/libadios.a(libadios_a-adios.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/dtao/adios-1.13.0/lib/libadios.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libadios2.so.2.1.0] Error 1
make[1]: *** [source/adios2/CMakeFiles/adios2.dir/all] Error 2

Here are the files in my ADIOS1 library directory.
$ ls /home/dtao/adios-1.13.0/lib
libadios.a   libadiosf_nompi.a     libadiosf_v1.a    libadiosread.a   libadiosreadf_nompi.a libadiosreadf_v1.a    libskel.a libadiosf.a  libadiosf_nompi_v1.a  libadios_nompi.a  libadiosreadf.a libadiosreadf_nompi_v1.a  libadiosread_nompi.a  python

Thanks!

**Comment by scottwittenburg** [comment]
Based on the comment from @pnorbert, it seems you should no longer use the `ADIOS1_LIBRARY` argument.  I'm just guessing now, but I wonder if you should build shared libraries for ADIOS1 before attempting to link ADIOS2 against it.

**Comment by pnorbert** [comment]
I am configuring it this way, setting the path in an environment variable
ADIOS1_DIR=/opt/adios/  \
cmake ...  -DADIOS2_USE_ADIOS1=ON  ...

I am not sure if passing the path in a -Dxxx option works. Also not the
other flag is ADIOS2_USE_ADIOS1 not simply ADIOS1.

**Comment by scottwittenburg** [comment]
Hi @pnorbert.  Just fyi, you can pass a path in a -D option.  For example:

```console
cmake -DADIOS1_DIR:Path=/home/scott/projects/adios1 ...
```

**Comment by pnorbert** [comment]
Indeed, and even this works now in the release branch (not using that
strange :Path thingy there)

cmake   -DADIOS2_USE_ADIOS1=ON   -DADIOS1_ROOT=/opt/adios/

**Comment by dingwentao** [comment]
The problem is solved!!
Thanks a lot for your great help.
The ticket can be closed.
