### ISSUE TITLE
BPFile reader misses last step in streaming mode

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#363]
If I run the heat transfer producing N output steps (initial condition + the number of requested steps), then the reader will only process N-1 steps.

_$ mpirun -n 2 ./bin/heatTransfer_write_adios2 /home/adios/work/ADIOS2/examples/heatTransfer/heat_bpfile.xml heat.bp 2 1 5 6 1 1_
Step 1:
Total runtime = 0.00218892s

_$ bpls -lav heat.bp -d -n 6 -f "%6.2g"_
File info:
  **of groups:     2**
  of variables:  1
  of attributes: 0
  of meshes:     0
  time steps:    0 - 1
  file size:     632 bytes
  bp version:    3
  endianness:    Little Endian
  statistics:    Min / Max / Avg / Std_dev

  double   T     2*{10, 6} = -3.6591 / 3.1591 / null  / null 
    (0,0,0)         1      1    2.7      1  -0.73      1
    (0,1,0)      -1.9   -1.9   -0.2   -1.9   -3.7   -1.9
    (0,2,0)       1.4    1.4    3.2    1.4   -0.3    1.4
    (0,3,0)       1.4    1.4    3.2    1.4   -0.3    1.4
    (0,4,0)      -1.9   -1.9   -0.2   -1.9   -3.7   -1.9
    (0,5,0)         1      1    2.7      1  -0.73      1
    (0,6,0)      -1.9   -1.9   -0.2   -1.9   -3.7   -1.9
    (0,7,0)       1.4    1.4    3.2    1.4   -0.3    1.4
    (0,8,0)       1.4    1.4    3.2    1.4   -0.3    1.4
    (0,9,0)      -1.9   -1.9   -0.2   -1.9   -3.7   -1.9
    (1,0,0)       1.2    1.2    1.5   0.81   0.12   0.87
    (1,1,0)      0.31  -0.32   0.37  -0.67   -1.7 -0.032
    (1,2,0)       1.1    1.1    1.8   0.76  -0.28   0.72
    (1,3,0)       1.1    1.1    1.8   0.76  -0.28   0.72
    (1,4,0)      0.31  -0.32   0.37  -0.67   -1.7 -0.032
    (1,5,0)      0.23   0.18   0.87  -0.17   -1.2  -0.12
    (1,6,0)      0.31  -0.32   0.37  -0.67   -1.7 -0.032
    (1,7,0)       1.1    1.1    1.8   0.76  -0.28   0.72
    (1,8,0)       1.1    1.1    1.8   0.76  -0.28   0.72
    (1,9,0)      0.71  0.076   0.42  -0.27  -0.96   0.37

_$ mpirun -n 1 ./bin/heatTransfer_read /home/adios/work/ADIOS2/examples/heatTransfer/heat_bpfile.xml heat.bp 1 1_
gndx       = 10
gndy       = 6
rank 0 reads 2D slice 10 x 6 from offset (0,0)
Processing step 0
_There should be another step "Processing step 1" here_

_$ cat data.0_
rank=0 size=10x6 offsets=0:0 step=0
 time   row   columns 0...5

                0        1        2        3        4        5
--------------------------------------------------------------
    0    0        1        1      2.7        1    -0.73        1
    0    1     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9
    0    2      1.4      1.4      3.2      1.4     -0.3      1.4
    0    3      1.4      1.4      3.2      1.4     -0.3      1.4
    0    4     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9
    0    5        1        1      2.7        1    -0.73        1
    0    6     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9
    0    7      1.4      1.4      3.2      1.4     -0.3      1.4
    0    8      1.4      1.4      3.2      1.4     -0.3      1.4
    0    9     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9

**Comment by williamfgc** [comment]
@pnorbert you can try moving the break condition until the end of the while loop in heatRead.cpp:Line 89.    BeginStep is detecting that reading the last step has been reached, but it doesn't reach the Get functions. 

``` while (true)
        {
            adios2::StepStatus status =
                bpReader.BeginStep(adios2::StepMode::NextAvailable, 10.0f);
            if (status != adios2::StepStatus::OK)
            {
                break;
            }
       ....
       } //end of while loop
```

To: 
```
 while (true)
        {
            adios2::StepStatus status =
                bpReader.BeginStep(adios2::StepMode::NextAvailable, 10.0f);
            if (status != adios2::StepStatus::OK)
            {
                break;
            }
             ....
            if (status != adios2::StepStatus::OK)
            {
                break;
            }
       
       } //end of while loop
```

**Comment by pnorbert** [comment]
The example is fine. BeginStep should return OK when the last step is
reached because there is still a valid step to read. It should return
errors only when it is called beyond the last step. All the other engines
work with this logic.

**Comment by eisenhauer** [comment]
Assuming that m_BP3Deserializer.m_MetadataSet.StepsCount is the actual count of steps in the file, then this conditional in BPFileReader.cpp is probably the problem:

    if (m_CurrentStep >= m_BP3Deserializer.m_MetadataSet.StepsCount - 1)
    {
        status = StepStatus::EndOfStream;
    }

Current step starts at 0, and is incremented prior to this, which I think makes status == EndOfStream one too early.

**Comment by williamfgc** [comment]
@pnorbert I just did a PR to accommodate this
@eisenhauer yes, that's the one!
Thanks!

**Comment by pnorbert** [comment]
Yes, this PR fixes this bug. Thanks.
