### ISSUE TITLE
Want function to get ADIOS2 library version at run time

### ISSUE THREAD

**Issue by eschnett** [ornladios/ADIOS2#3630]
I would like to have a function (in the C API) that returns the ADIOS2 version number. This will allow the Julia wrapper to inquire the current version by calling the C API (or reading a global variable), and make run-time decisions based on this, e.g. whether certain functionality is available.

A C `#define` would not be good enough because these are not available in a shared library.

**Comment by pnorbert** [comment]
Please see #3633 and comment

**Comment by ax3l** [comment]
@pnorbert I would like the same function for C++ please (if there is none already).
