### ISSUE TITLE
Undeclared identifier `uint`

### ISSUE THREAD

**Issue by eschnett** [ornladios/ADIOS2#3638]
I am configuring ADIOS2 2.9.0 with HDF5 1.14.0 on Windows. This leads to an undefined identifier error in line 40 of file `source/h5vol/H5VolUtil.h`: `uint` is not defined.

**Comment by eisenhauer** [comment]
Yeah, uint is not guaranteed to be available across all compilers.  You might edit that to be "unsigned int" in the short term.  (Or add a typedef, since it also appears in H5VolUtil.c as well.) @guj ?  I guess we're not doing windows builds with HDF5?

**Comment by guj** [comment]
Thanks for spotting this. size_t would be enough. I will put a PR on it.

**Comment by ax3l** [comment]
@eschnett did you furthermore encounter
```
D:\bld\adios2-split_1685654832661\work\source\h5vol\H5VolReadWrite.c(19): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
```
? #3649

**Comment by eschnett** [comment]
I don't recall seeing that error. I am using a patch that replaces `uint` with `unsigned`, and everything is working fine then.
