### ISSUE TITLE
2.9.0: OSX Python Pickle Issue

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#3646]
**Describe the bug**
This is a Python regression in 2.9.0, first seen by @liangwang0734 in https://github.com/conda-forge/adios2-feedstock/pull/71

This seems to be partly a regression from https://github.com/ornladios/ADIOS2/commit/a0d458676f7e6c6296a3b4176c2f08004efe2905 possibly due to the [change](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) in multiprocessing on OS X since Python 3.8. Searching the error `TypeError: cannot pickle '_io.TextIOWrapper' object` gives a bunch of discussions.

cc @vicentebolea - thank you for offering to help with this

**To Reproduce**
Build and test ADIOS2 as in https://github.com/conda-forge/adios2-feedstock/pull/71

**Desktop (please complete the following information):**
 - OS/Platform: OSX x86_64 for CPython 3.8-3.11 (all)
 - Build: **LLVM** Clang 14, CMake (latest), shared build

**Additional context**
This bug prevents us from releasing a new ADIOS2 release on conda-forge.

**Comment by ax3l** [comment]
ping @dmitry-ganyushin 

Issue is in https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/engine/dataman/TestDataMan1D.py with macOS

**Comment by ax3l** [comment]
@dmitry-ganyushin we suspect this is from a0d458676f7e6c6296a3b4176c2f08004efe2905

**Comment by dmitry-ganyushin** [comment]
I am looking into that. It is only OSX specific? I made a fast test with python 3.9.16 ubuntu, everything is fine.

**Comment by dmitry-ganyushin** [comment]
Python 3.11.3 + Ubuntu is fine

**Comment by pnorbert** [comment]
@vicentebolea Can we please have ZeroMQ, DataMan, HDF5 and some compression library on for the macos tests?

**Comment by dmitry-ganyushin** [comment]
Fixed

**Comment by ax3l** [comment]
Thanks a lot, @dmitry-ganyushin!
