### ISSUE TITLE
No output file after writing reported to have finished (deferred mode?)

### ISSUE THREAD

**Issue by liangwang0734** [ornladios/ADIOS2#3674]
Hi, this is perhaps a naive question:

In some of our tests with 60k cores, each is responsible for writing data ~ 1MB.

The adios2 writing calls seem to have finished, but no actual data is written (no .bp folder created) if my substream number if small, or 0 (i.e., one file per node).

I suspect this is caused by the "deferred mode"? If yes, how can I configure this, hopefully through the XML config file?

Also, for such writing needs, what is a better strategy (or how to test and look for one)?

**Comment by eisenhauer** [comment]
Hmm.   Well, the short answer is no, this isn't the result of deferred mode.  On the writer side that mode basically allows ADIOS the freedom to grab the data anytime between Put and EndStep (as opposed to requiring it to be consumed during Put) and shouldn't affect actually moving stuff to disk, creating the ADIOS directory structure, etc.  Actually, the directory structure should be created in file Open, so something is going seriously wrong here, though just what I don't have an immediate guess for.  (I can tell you that you don't want to run with a small substream number like one file per rank at 60K ranks.  Whatever filesystem you are working on will not appreciate 60K parallel file creations...)

**Comment by liangwang0734** [comment]
Thank you @eisenhauer 

If I set substream up to the core number, I do get the BP folders created and data files inflated.

In the case with no actual files written, I should examine my code and perhaps work with the system operator, but do you have any suggestions where to look on both Adios side and system side?

Thank you for your reply.

**Comment by pnorbert** [comment]
Is this BP4 or BP5? Do you get results if you use BP5 with
EveryoneWritesSerial aggregation strategy and setting aggregation ratio or
number of aggregators aggressively (less files then number of nodes)?

Open is launching a thread by default to call Posix open on each process,
you can turn that off with AsyncOpen.

Open is also cascaded I think so there is a message sent from rank to rank
during the opening process. Did your code get stuck, or finished but had no
files on disk?

**Comment by liangwang0734** [comment]
@pnorbert , thank you for the details!

We are using BP4. If it is not too hard to switch to BP5, I can try (does it just work by changing the option in the xml config file, assuming Adios itself was built with BP5?)

The writing passed without complaining (actually it spent close-to-expected time hanging but then went through).

I need a bit more time to check your other comments.

**Comment by pnorbert** [comment]
Yes, just change the engine name. The default aggregation is one file per
node with TwoLevelShm strategy which cannot do less files than that. So you
need the other aggregation strategy to produce less number of files.
