### ISSUE TITLE
BP5 output in release_28

### ISSUE THREAD

**Issue by liangwang0734** [ornladios/ADIOS2#3678]
Sorry for asking a question about a past release (release_28). In the following test, the BP4 output is fine, but the BP5 is empty as seen by the adios2 python interface (conda version v2.8.3).

Unfortunately, for now, we are stuck with release 28 but would like to use BP5 (which has a clear performance advantage in some of our tests).

Any suggestions are appreciated:

```c++
#include <adios2.h>

int main () {
  auto dbl = std::vector<double>{1., 2., 3., 4., 5.};
  
  auto my_adios = adios2::ADIOS {};

  const std::vector<std::string> engine_names = {"BP4", "BP5"};

  for (auto engine_name : engine_names)
  {
    auto my_io = my_adios.DeclareIO(engine_name);
    my_io.SetEngine(engine_name);
    auto my_var = my_io.DefineVariable<double>("dbl", {5}, {0}, {5});
    auto mode = adios2::Mode::Write;
    auto writer = my_io.Open("test-" + engine_name + ".bp", mode);
    writer.BeginStep();
    writer.Put<double>(my_var, dbl.data());
    writer.EndStep();
    writer.Close();
  }
}
```

**Comment by liangwang0734** [comment]
The python script and result looks like:

```python
import adios2
print(adios2.__version__)

for filename in [
    'test-BP4.bp/',
    'test-BP5.bp/',
]:
    fp = adios2.open(filename, 'r')
    print(fp)
    print(fp.available_variables())
    print(fp.available_attributes())
    print("")
```
```
2.8.3
<adios2.file named 'test-BP4.bp/' and mode 'r'>
{'dbl': {'AvailableStepsCount': '1', 'Max': '5', 'Min': '1', 'Shape': '5', 'SingleValue': 'false', 'Type': 'double'}}
{}

<adios2.file named 'test-BP5.bp/' and mode 'r'>
{}
{}
```

**Comment by eisenhauer** [comment]
I can't look at the moment, but the problem here is likely due to python defaulting to a streaming-mode read, which for BP5 requires BeginStep before any variables are visible.  (BP4 loads all variables in Open(), a behavior that is problematic for very large files, so BP5 only does that if you open the file with ReadRandomAccess mode, which in Python is string "rra" rather than "r".  So you could probably fix python behaviour by either changing the open mode to "rra", or by introducing the Begin/EndStep pairs you use in C++.  (But not both.  For BP5, Begin/EndStep are used in streaming mode only.)

**Comment by liangwang0734** [comment]
@eisenhauer thank you for the tip! The Python problem in my Issue has been solved after using "rra". And following your suggestions, the problem in my c++ code has also been fixed.

Still, the failure in my c++ BP5 tests was a little strange to me: I missed the begen/emdStep mistakenly, then the first bp5 output files needs "rra" mode in Python to read, but the subsequent files were ok with the "r" mode in Python; I guess somehow the stream mode was turned on silently turned on for the subsequent files (though I always close the writer after each file output).

**Comment by anagainaru** [comment]
If you add `fpBeginStep()` and `fp.EndStep()` surrounding your inquiry, your code will work with "r" as well

**Comment by liangwang0734** [comment]
@anagainaru thank you for the suggestions.

Yes it works now. I will close the issue as resolved.
