### ISSUE TITLE
Add Libcurl in some of our Github builds

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3694]

**Comment by vicentebolea** [comment]
@scottwittenburg lets do this after merging #3631 

cc @dmitry-ganyushin

**Comment by vicentebolea** [comment]
@dmitry-ganyushin do you still need this?

**Comment by scottwittenburg** [comment]
The package manager makes us pick a TLS backend, as described in not very much detail [here](https://everything.curl.dev/get/linux#ubuntu-and-debian).  Which version of `libcurl-dev-` do we want?

```console
# apt-get install libcurl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl-dev is a virtual package provided by:
  libcurl4-openssl-dev 7.68.0-1ubuntu2.19
  libcurl4-nss-dev 7.68.0-1ubuntu2.19
  libcurl4-gnutls-dev 7.68.0-1ubuntu2.19
You should explicitly select one to install.
```

**Comment by vicentebolea** [comment]
Since he will be using Python libcurl as well maybe openssl?

**Comment by scottwittenburg** [comment]
@vicentebolea @dmitry-ganyushin Let me know what you want to do here.  If "Python libcurl" refers to a specific python package, let me know which one, and I can look into it.  Or I can just go with the openssl version of libcurl4 (`libcurl4-openssl-dev`) and hope for the best.
