### ISSUE TITLE
Add muparser in some of our Builds

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3695]

**Comment by vicentebolea** [comment]
@guj @lizdulac do we still need this?

**Comment by guj** [comment]
My code is in my "queryDerived" branch.  I put in a version of muParser in the toolkit/query/. So no need to import it.  This branch is not merged to master yet. Before Liz finishes her parser, It can serve as a backup if Scott wants a demo.  

So short answer is no need to add muparser in any builds.  Whether to merge this branch to master is up to you.

**Comment by anagainaru** [comment]
Liz's version will not use muParser but her own grammar. I assume we'll want to use the same to parse @guj expression from the XML eventually so I don't think we'll need muParser in our builds
