### ISSUE TITLE
SST with GPU support

### ISSUE THREAD

**Issue by anagainaru** [ornladios/ADIOS2#3706]
The file engines are capable of receiving GPU buffers in their Put/Get calls. SST/SSC should also be able to do this. 

Even though SST is using the same Serializer, there is something missing that is making it seg fault when receiving CUDA buffers. This needs to be fixed if there is a bug or implemented if there is something missing.

**Comment by eisenhauer** [comment]
BP5 file and SST both use the same serializer, but they pass in different BufferV subclasses.  SST requires a contiguous data buffer (for RDMA registration), so there is a memcpy in MallocV::AddToVec().  Presumably something that needs to be tweaked for CUDA buffer support.

**Comment by anagainaru** [comment]
Great, thanks for the explanation. I did not have time to look more into why it didn't work. After the AHM I was optimistic it might just directly work :) I'll look at this in the near future and keep you posted
