### ISSUE TITLE
check engine type

### ISSUE THREAD

**Issue by liangwang0734** [ornladios/ADIOS2#3719]
Hi, in the C++ interface, what is the routine to find out the engine type?

PS: In my case, I set the engine to `BP5` for my output in the XML file but got an error that shows `BP4Writer::EndStep` is called.
(I've checked the validity of the XML file by setting the engine in the XML file to an invalid value like BPx and then it gives an error, indicating that the XML file is indeed picked up).

The debug trace relevant to adios2 can be found [here](https://gist.github.com/liangwang0734/654c5d4e4b6e32509be6feac68b31e41).

**Comment by eisenhauer** [comment]
The Engine::Type() method returns what you want:

     * From ADIOS2 engine type: "bpfile", "sst", "dataman", "insitumpi", "hdf5"
     * @return engine type as lower case string
     */
    std::string Type() const;

**Comment by eisenhauer** [comment]
(I'm not sure what to think about the trace, but lets take this one step at a time...)

**Comment by liangwang0734** [comment]
Thanks @eisenhauer That helped me a lot!

And, it turned out that the engine type in our test DOES change during the simulation.

Sorry that I don't have a minimum example yet to reproduce the problem; but my understanding of our code is that we store an and `adios2::IO` object `io_` and an `adios2::Engine` object `engine_` in a class.
When doing an output with the `io_name_`, say, "checkpoint", we do the following
- `io_ = ad.DeclareIO(io_name_)` 
-  `engine_ = io_.open(filename, mode)` 
- when done, call `engine_.Close()` and `ad_.RemoveIO(io_name_)`

It appears to me that only the first iteration gets the correct engine type from the XML file. The subsequent iterations fall back to the default `BP4`.

I wonder if this is due to some lifetime logic in adios2? Note that in our case, for different checkpoint filenames, the `io_name_` is the same ("checkpoint"), thus we declared and removed io instances of the same `io_name_` repeatedly.

**Comment by liangwang0734** [comment]
I'll make another issue for the change of engine issue. So closing this one.

**Comment by liangwang0734** [comment]
@eisenhauer sorry, a follow-up question: is the following way to set and check engine/parameters correct:

```c++
  io_ = ad.DeclareIO(io_name_);
  io_.SetEngine("BP5");
  io_.SetParameter("SubStreams", "0");
  auto params = io_.Parameters();
  std::cout << "Substreams = " << params["SubStreams"] << std::endl;
```

**Comment by eisenhauer** [comment]
Sorry for the delayed response, but yes, that's the right way to set and check engine parameters.
