### ISSUE TITLE
Fix code scanning alert - No space for zero terminator

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3771]
Tracking issue for:
- [ ] https://github.com/ornladios/ADIOS2/security/code-scanning/36

**Comment by eisenhauer** [comment]
I understand why it the detector might be worried, given the first line, but given the 2nd it's more obviously spurious...
```
            CMContactString = malloc(strlen(Writer0Contact)); /* at least long enough */
            sscanf(Writer0Contact, "%p:%s", WriterFileID_p, CMContactString);

```

**Comment by vicentebolea** [comment]
Apparently the `%s` format specifier in scanf functions will inject a null character at the end of the string.

**Comment by vicentebolea** [comment]
But yeah CMContactString allocate as large as Writer0Contact however its used size is less than Writer0Contact as you showed. Yep, indeed spurious
