### ISSUE TITLE
BPFile writer aborting on Titan

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#379]
$ aprun -n 1 ./heatTransfer_write_adios2 ./heat_bpfile.xml heat.bp 1 1 5 6 1 1
Step 1:
Total runtime = 0.00466585s

It segfaults when gathering global metadata. In this example, the subfile is readable, but at larger runs, they are also invalid BP files somehow. 

(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000004f3f6c in __gthread_equal (__t1=0, __t2=0) at /opt/gcc/4.9.3/snos/include/g++/x86_64-suse-linux/bits/gthr-default.h:680
#2  0x00000000004fcffc in std::operator== (__x=..., __y=...) at /opt/gcc/4.9.3/snos/include/g++/thread:84
#3  0x00000000004fd0e9 in std::thread::joinable (this=0xe16ea0) at /opt/gcc/4.9.3/snos/include/g++/thread:162
...
#20 0x00000000004f81b3 in adios2::format::BP3Serializer::DeserializeIndicesPerRankThreads (this=0xe11790, serialized=...)
    at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/source/adios2/toolkit/format/bp3/BP3Serializer.cpp:781
#21 0x00000000004f7a2f in adios2::format::BP3Serializer::AggregateMergeIndex (this=0xe11790, indices=...)
    at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/source/adios2/toolkit/format/bp3/BP3Serializer.cpp:652
#22 0x00000000004f5548 in adios2::format::BP3Serializer::AggregateCollectiveMetadata (this=0xe11790)
    at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/source/adios2/toolkit/format/bp3/BP3Serializer.cpp:234
#23 0x00000000004d2109 in adios2::BPFileWriter::WriteCollectiveMetadataFile (this=0xe11750)
    at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/source/adios2/engine/bp/BPFileWriter.cpp:200

**Comment by williamfgc** [comment]
@pnorbert let me know if this fixes the issue. As far as I remember, I needed to pass 2 additional parameters on Titan for using threads, number of NUMA threads and MPI processes per node to avoid thread overflow on a single node (might be the case here).

**Comment by pnorbert** [comment]
The PR fixed this, but there is the same problem in the reader:

#1  0x00000000004f4bb4 in __gthread_equal (__t1=0, __t2=0)
    at /opt/gcc/4.9.3/snos/include/g++/x86_64-suse-linux/bits/gthr-default.h:680
...
#19 0x000000000054c581 in std::async<**adios2::format::BP3Deserializer::ParseVariablesIndex**(const adios2::BufferSTL&, adios2::IO&)::<lambda(adios2::IO&, const std::vector<char>&, std::size_t)>&, std::reference_wrapper<adios2::IO>, std::reference_wrapper<const std::vector<char, std::allocator<char> > >, long unsigned int&>(std::launch, adios2::format::BP3Deserializer::<lambda(adios2::IO&, const std::vector<char, std::allocator<char> >&, std::size_t)> &) (
    __policy=std::async, __fn=...) at /opt/gcc/4.9.3/snos/include/g++/future:1581
#20 0x000000000054b302 in adios2::format::BP3Deserializer::ParseVariablesIndex (this=0xef4ad8, bufferSTL=..., io=...)
    at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/source/adios2/toolkit/format/bp3/BP3Deserializer.cpp:314
#21 0x0000000000549d51 in adios2::format::BP3Deserializer::ParseMetadata (this=0xef4ad8, bufferSTL=..., io=...)
    at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/source/adios2/toolkit/format/bp3/BP3Deserializer.cpp:39
#22 0x000000000058d5c9 in adios2::InSituMPIReader::BeginStep (this=0xef4a40, mode=adios2::NextAvailable, 
    timeoutSeconds=10) at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/source/adios2/engine/insitumpi/InSituMPIReader.cpp:178
#23 0x000000000040bd61 in main (argc=5, argv=0x7fffffff5828)
    at /ccs/proj/e2e/pnorbert/ADIOS/ADIOS2/examples/heatTransfer/read/heatRead.cpp:92

**Comment by williamfgc** [comment]
Of course, I forgot the read side. Please check PR #381

**Comment by williamfgc** [comment]
@pnorbert is this issue solved? If so, can we close it?

**Comment by pnorbert** [comment]
This issue is fixed.
