### ISSUE TITLE
Add unit tests for zero-sized reads

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3792]
We want to have a test that performs a zero-sized read of a block in variable with and without compression. We can do this based on some of our simplest read/write tests.

Taken from:

              @pnorbert @vicentebolea @anagainaru generally, shall we add a general test to ADIOS2 for zero-write blocks with and w/o compression? This is a pretty common corner case for us and can easily break :)
              
_Originally posted by @ax3l in https://github.com/ornladios/ADIOS2/issues/3459#issuecomment-1696047949_

**Comment by vicentebolea** [comment]
Related: https://github.com/ornladios/ADIOS2/issues/3460

**Comment by ax3l** [comment]
Related: #3542

ping @pnorbert @anagainaru https://github.com/ornladios/ADIOS2/issues/3460#issuecomment-1696052751

**Comment by anagainaru** [comment]
Sorry @ax3l I somehow did not see this until now.
Just so that it's clear what exactly this corner case is, the test should write data where some blocks are empty (using and not using compression)?

**Comment by vicentebolea** [comment]
@spyridon97 was originally assigned to this task as it was a good introduction for him how to write a "Simple" test. However, he is now busy with other tasks. I do not have cycles this week for adios2. @anagainaru feel free to re-assign you if you want to take it.

**Comment by anagainaru** [comment]
I'll finish this tomorrow, for some reason the test I made does not fail before the fix :) so I need to double check what I'm doing wrong. If I can't finish I'll re-assign this back.
