### ISSUE TITLE
Add Tutorial section at the ADIOS2 readthedocs

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3793]
We want to have an tutorial sections at the ADIOS2 readthedocs adios2.readthedocs.io/.

We want the following sections

- 00 Hello world; read/write (low level API C++)
- 01 Reading the ADIOS2 files (From python) 
- 02 Variables usage (Low level API C++)
- 03 Attributes (Low level API C++)
- 04 Operators (Low level API C++)

The source code of the tutorial should be the skeleton code and its solution and should be hosted at: https://github.com/ornladios/ADIOS2-Examples/tree/master/source

More info at the ADIOS2-examples readthedocs https://adios2-examples.readthedocs.io/en/latest/

**Comment by vicentebolea** [comment]
@spyridon97 we also want each tutorial to use its own standalone `cmakelists.txt`. We can do this one in a later iteration it makes thing more difficult.

ref #3795

**Comment by spyridon97** [comment]
Note for developer: Also update fides documentation to not use ADIOS2-examples

**Comment by spyridon97** [comment]
After discussing we are gonna use the following examples for the tutorials

1. HelloWorld
   1. examples/hello/helloWorld/hello-world.cpp
2. Read/Write files
   1. examples/hello/bpWriter/bpWriter.cpp
   2. examples/hello/bpReader/bpReader.cpp
3. Attributes:
   1. examples/hello/bpAttributesWriter.cpp
4. Operators
   1. examples/hello/bpWriter/bpSZ.cpp
5. Variables types:
   1. examples/basics/GlobalArrayND/globalArrayNDWrite.cpp
   4. examples/basics/JoinedArray/JoinedArrayWrite.cpp
   5. examples/basics/localArray/localArrayRead/Write.cpp

if any of them have python alternatives, they will be also attached.

**Comment by spyridon97** [comment]
Also the draft MR that @vicentebolea created is https://github.com/ornladios/ADIOS2/pull/3791.

**Comment by vicentebolea** [comment]
> * examples/basics/GlobalArrayND/globalArrayNDWrite.cpp
> 
> * examples/basics/JoinedArray/JoinedArrayWrite.cpp
> 
> * examples/basics/localArray/localArrayRead/Write.cpp

Great @spyridon97, this sounds good, Please note that Scott really wants a python example/tutorial for read/write an adios2 file. We can append this in the tutorial 2.
