### ISSUE TITLE
Possible Issue with adios2 v.2.9.1 python module

### ISSUE THREAD

**Issue by PhysicsDan** [ornladios/ADIOS2#3831]
Hello,

**Describe the bug**
Unable to read data from adios2 file produced from WarpX PIC code when using 2.9.1

**To Reproduce**
1) Data is produced via WarpX pic code which uses adios2 v2.9.1 to store the data. Adios2 is installed via conda forge.
2) Using `bpls` I can see the data is correctly written to the file.
3) Using the `available_variables` function from `adios2` python module returns an empty list (Note: Previously worked in v. 2.8.3)
```
import adios2

fp = adios2.open("myfile.py", "r")
print(fp.available_variables())
```
Note: `openpmd-api` also correctly can see the contents of the file.

**Expected behavior**
I should see the same variables that are displayed when running `bpls`

**Desktop (please complete the following information):**
 - OS/Platform: CentOS
 - Build adios2 nompi_py311hc31d2c9_102

**Additional context**

Thanks

**Following up**

**Comment by anagainaru** [comment]
Hey Dan, adios 2.9 is when BP5 became the default engine. For BP5 you have to inspect variables within steps, you can no longer do this before BeginStep. Could you trying modifying your code and see if it works?

**Comment by PhysicsDan** [comment]
Hi Ana, 
Apologies for the late reply! Yes thanks I had missed that change - all working now.
Thanks for the help
