### ISSUE TITLE
make ADIOS2_HAVE_MPI_CLIENT_SERVER as an option

### ISSUE THREAD

**Issue by guj** [ornladios/ADIOS2#3836]
ranjansv@gatech.edu 
is configuring ADIOS on Cambridge nodes with their gcc and mpich.

It so turns out the test ADIOS2_HAVE_MPI_CLIENT_SERVER
hang during cmake.

Is it possible  to have an option to disable this  or give it a timeout?

**Comment by guj** [comment]
@eisenhauer @vicentebolea

**Comment by vicentebolea** [comment]
@guj `ADIOS2_HAVE_MPI_CLIENT_SERVER` is already an option. The user can manually enabled/disabled it with: `-DADIOS2_HAVE_MPI_CLIENT_SERVER=ON/OFF`.

However, the hanging part should be resolved by adding a timeout. I will work on it.

Thanks for reporting.
