### ISSUE TITLE
DESTDIR not used if CMAKE_INSTALL_PREFIX is absolute directory

### ISSUE THREAD

**Issue by td-mpcdf** [ornladios/ADIOS2#3837]
**Describe the bug**
The DESTDIR variable given to make install is used for installation but the post-installation script does not account for it if the CMAKE_INSTALL_PREFIX is given as absolute path. This changed from earlier versions (2.7.1 works).

**To Reproduce**
cmake -build -DCMAKE_INSTALL_PREFIX=/my/installation
make -C build
make -C build install DESTDIR=${HOME}

**Expected behavior**
Installation should be done into ${HOME}/my/installation which works correctly.
After the installation step, the `generate-adios2-config.sh` is called which does not account for the DESTDIR variable and complains about a missing adios2-config.cmake file.

**Desktop (please complete the following information):**
 - OS/Platform: SLES15
 - Build  with defaults

**Additional context**

**Following up**
Was the issue fixed? Please report back.

**Comment by vicentebolea** [comment]
This was resolved in #3850
