### ISSUE TITLE
Build using spack with Kokkos dependency

### ISSUE THREAD

**Issue by hr87** [ornladios/ADIOS2#3854]
I am trying to build Adios 2.9.0 with Spack. I do not see a Kokkos option to turn on Kokkos support. 

I am trying to use ADIOS2 in a project that relies on Kokkos views. Building and managing the ADIOS 2 dependency with spack is easier than manual builds.

**Comment by anagainaru** [comment]
Thank for bringing this up, I'll check with @vicentebolea 
 I've always just installed from source.
