### ISSUE TITLE
Slack link not working

### ISSUE THREAD

**Issue by hr87** [ornladios/ADIOS2#3863]
I want to join the Adios2 slack to ask questions about using Adios2 with Kokkos. The link on the github front page is broken, it points to spack[.]io.

When I go to adios2.slack.com, there is a workspace there. Not sure if that is the right one. If it is, I cannot join, I get No account found from slack.

**Comment by eisenhauer** [comment]
Honestly, the ADIOS slack is moribund.  You might have better luck posting to the "discussions" tab here on Github.

**Comment by eisenhauer** [comment]
And I'll take it as an action item to remove that link.  That nobody ever noticed that it pointed to spack rather than slack is perhaps an indication of how useful it was.

**Comment by hr87** [comment]
Ok, posted my question here: https://github.com/ornladios/ADIOS2/discussions/3864

**Comment by eisenhauer** [comment]
Closed as resolved with slack link deleted.
