### ISSUE TITLE
MPI_Comm_dup in IO Open hangs on Mac and Linux

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#388]
The ./bin/hello_bpReaderHeatMap* examples show this behavior. Removing MPI_Comm_dup, and from Engine destructor, fixes the issue.

**Comment by pnorbert** [comment]
The bug is in the example. ADIOS object is created with MPI_COMM_WORLD. 
Then only rank 0 calls Open, without a communicator, which therefore will inherit the communicator from the ADIOS object. 
How about requiring a communicator in Open to avoid this easy mistake?
