### ISSUE TITLE
Cannot install ADOS2 with UCX support

### ISSUE THREAD

**Issue by cbontoiu** [ornladios/ADIOS2#3923]
**Describe the bug**
Cannot install ADOS2 with UCX support

**To Reproduce**
My installation command is

```
cd .. && sudo rm -r adios2-build && sudo mkdir adios2-build  && cd adios2-build && sudo cmake -DCMAKE_INSTALL_PREFIX=/usr/local/adios-2.9.2 ../ADIOS2-2.9.2 \
-DCMAKE_C_COMPILER=/usr/local/openmpi-5.0/bin/mpicc -DCMAKE_CXX_COMPILER=/usr/local/openmpi-5.0/bin/mpicxx \
-DADIOS2_USE_MPI=ON \
-DADIOS2_USE_MGARD=OFF \
-DADIOS2_USE_HDF5=OFF \
-DADIOS2_USE_IME=OFF \
-DADIOS2_USE_ZeroMQ=OFF \
-DADIOS2_USE_Fortran=OFF \
-DADIOS2_USE_Python=OFF \
-DADIOS2_BUILD_EXAMPLES=OFF \
-DADIOS2_USE_UCX=ON \
-DUCX_LIBRARIES=/usr/local/ucx-1.15/lib \
-DUCX_DIR=/usr/local/ucx-1.15/lib/ucp/api \
-DADIOS2_USE_SZ=ON \
-DSZ_LIBRARY=/usr/local/sz/lib \
-DZSTD_LIBRARY=/usr/local/sz/lib \
-DSZ_INCLUDE_DIR=/usr/local/sz/include \
-DADIOS2_USE_BZip2=ON \
-DADIOS2_USE_Blosc2=ON \
-DBlosc2_DIR=/usr/local/c-blosc2-2.11/lib/cmake/Blosc2 \
-DBLOSC2_LIBRARY=/usr/local/c-blosc2-2.11 \
-DBLOSC2_INCLUDE_DIR=/usr/local/c-blosc2-2.11 \
-DADIOS2_USE_PNG=ON && sudo make -j 32 && sudo make install -j 32
```

I get this error:
```
home/quasar/Software/ADIOS2-2.9.2/source/adios2/toolkit/sst/dp/ucx_dp.c:34:10: fatal error: ucp/api/ucp.h: No such file or directory
   34 | #include <ucp/api/ucp.h>
```

but that header is present in my UCX directory: ```/usr/local/ucx-1.15/include/ucp/api/```

How can I make it available to ADIOS, please?

**Desktop (please complete the following information):**
 - OS/Platform: Ubuntu 21
 - Build gcc-11.4

![2023-11-16_07-56](https://github.com/ornladios/ADIOS2/assets/7108691/3aaa0974-60a8-40a3-8d71-dba14a1811c3)

**Comment by eisenhauer** [comment]
Have you tried -DUCX_DIR=/usr/local/ucx-1.15/ ?  I think CMake will add the /include to the UCX_DIR in order to look for the include files.

**Comment by cbontoiu** [comment]
Hi @eisenhauer, 

Thanks for your help. That seemed to work but I have now another issue:

```
[ 36%] Linking CXX shared library ../../lib/libadios2_core.so
/usr/bin/ld: /usr/local/lib/libbz2.a(bzlib.o): warning: relocation against `stdout@@GLIBC_2.2.5' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libbz2.a(bzlib.o): relocation R_X86_64_PC32 against symbol `BZ2_crc32Table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [source/adios2/CMakeFiles/adios2_core.dir/build.make:2254: lib/libadios2_core.so.2.9.2] Error 1
make[1]: *** [CMakeFiles/Makefile2:3005: source/adios2/CMakeFiles/adios2_core.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Any idea, please?

**Comment by eisenhauer** [comment]
It looks like CMake has found only a static BZip library (/usr/local/lib/libbz2.a) and it can't use that to build the adios shared library.  If you don't absolutely need bzip, you can change your -DADIOS2_USE_BZip2=ON to be OFF instead.  Alternatively, you might convert the whole build to static (but you may well find that some other dependency has been installed with only dynamic libraries.)

**Comment by cbontoiu** [comment]
Thanks @eisenhauer Indeed I didn't need ```BZip``` and I was able to bypass this issue. All good now and I will close this thread.
