### ISSUE TITLE
BP5 + operator for local array

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#3987]
Apparently, BP5 does not support operators for local arrays, neither for writing nor reading.

**Comment by eisenhauer** [comment]
Hmmm.  No tests for that anywhere?  From a quick glance at BP5 serializer, they should be supported for everything that's not a single value, but maybe there's a non-obvious problem.

**Comment by eisenhauer** [comment]
Well, the logic for operator block sizing is missing on the read side for the Local case in GenerateReadRequests...  Might be more stuff, but it's where I'm starting.

**Comment by eisenhauer** [comment]
Quick PR submitted.  It needs better test cases, but if you have one, give this a go.

**Comment by pnorbert** [comment]
Fixed by #3989
