### ISSUE TITLE
BPFile writer with heat transfer: missing data in BP file 

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#401]
Data is 0 where it should not be. Bug present in VM as well as on Titan. 

$ mpirun -n 1 ./bin/heatTransfer_write_adios2 ../examples/heatTransfer/heat_bpfile.xml heat1.bp 1 1 100 100 10 10

$ bpls -l heat1.bp
  double   T     11*{100, 100} = -6.40663 / 7.19752 / null  / null 

$ bpls -l heat1.bp -d T -n 100 > T1.txt
$ less -S T1.txt
steps 3, 5, 7, 8, 9 have lots of zeros in the data

The statistics looks fine:

$ bpls -l heat1.bp -D
  double   T     11*{100, 100} = -6.40663 / 7.19752 / null  / null 
        step  0: 
          block 0: [ 0:99,  0:99] = -6.40663 / 7.19752/ N/A / N/A 
        step  1: 
          block 0: [ 0:99,  0:99] = -5.52777 / 5.90105/ N/A / N/A 
        step  2: 
          block 0: [ 0:99,  0:99] = -4.93104 / 5.05211/ N/A / N/A 
        step  3: 
          block 0: [ 0:99,  0:99] = -4.47786 / 4.49254/ N/A / N/A 
        step  4: 
          block 0: [ 0:99,  0:99] = -4.09603 / 4.09298/ N/A / N/A 
        step  5: 
          block 0: [ 0:99,  0:99] = -3.78051 / 3.80745/ N/A / N/A 
        step  6: 
          block 0: [ 0:99,  0:99] = -3.52656 / 3.60721/ N/A / N/A 
        step  7: 
          block 0: [ 0:99,  0:99] = -3.30453 / 3.44875/ N/A / N/A 
        step  8: 
          block 0: [ 0:99,  0:99] = -3.11012 / 3.31992/ N/A / N/A 
        step  9: 
          block 0: [ 0:99,  0:99] = -2.94833 / 3.22147/ N/A / N/A 
        step 10: 
          block 0: [ 0:99,  0:99] = -2.80852 / 3.13586/ N/A / N/A 

The variable size is 100x100 above. The bug is not present with 10x10.

**Comment by williamfgc** [comment]
@pnorbert can we try switching Threads to 1 in the config files?  I wonder if the memcpy gets affected by this, it is definitely a bug I need to double-check. For some reason std::copy wasn't working with threads so I needed to demote to std::memcpy. Thanks!

**Comment by pnorbert** [comment]
On Titan this was run with 1 thread.
Did it work for you on the VM with a single thread? I did not try that
combo.

**Comment by williamfgc** [comment]
I reproduce this on my Mac, I'll try to debug on my Linux box. Thanks.

**Comment by pnorbert** [comment]
This works now.
