### ISSUE TITLE
Spack not pulling Kokkos dependency

### ISSUE THREAD

**Issue by hr87** [ornladios/ADIOS2#4022]
**Describe the bug**
When building with spack, and requesting the kokkos interface, Spack does not pull in the Kokkos dependency.

**To Reproduce**
```
spack install adios2@2.9.2 +kokkos +python %gcc@12.2.0
```

gives this error message when building adios2:
```
1 error found in build log:
     44    -- Looking for BZ2_bzCompressInit - found
     45    -- Found ZFP: /vast/projects/tbiifp/env/spack/opt/spack/linux-rhel8-haswell/gcc-12.2.0/zfp-0.5.5-43ewgzglgpjbc6lfzbgjc646ep7piz5a/lib64/cmake/zfp/zfp-config.cmake (found suitable version "0.5.5", minimum required is "0.5.3")
     46    -- Performing Test ADIOS2_HAVE_ZFP_CUDA
     47    -- Performing Test ADIOS2_HAVE_ZFP_CUDA - Failed
     48    -- Found SZ: /vast/projects/tbiifp/env/spack/opt/spack/linux-rhel8-haswell/gcc-12.2.0/sz-2.1.12.5-jcauxmougcxfa3woi64533ccwlmm3ftl/lib64/libSZ.so
     49    -- Found PNG: /vast/projects/tbiifp/env/spack/opt/spack/linux-rhel8-haswell/gcc-12.2.0/libpng-1.6.39-cpgosnzjtmplduqhjwfkpnfx7634f4uk/lib64/libpng.so (found suitable version "1.6.39", minimum required is "1.6.0")
  >> 50    CMake Error at cmake/DetectOptions.cmake:208 (find_package):
     51      By not providing "FindKokkos.cmake" in CMAKE_MODULE_PATH this project has
     52      asked CMake to find a package configuration file provided by "Kokkos", but
     53      CMake did not find one.
     54
     55      Could not find a package configuration file provided by "Kokkos" (requested
     56      version 3.7) with any of the following names:
```

If I load kokkos before trying to build adios2, it works
```
spack load kokkos@4.0.01 %gcc@12.2.0
spack install adios2@2.9.2 +kokkos +python %gcc@12.2.0
```

If I specify kokkos as a dependency, somehow spack then pulls in petsc after installing Kokkos and petsc fails.
```
spack install adios2@2.9.2 +kokkos +python ^kokkos@4.0.01 %gcc@12.2.0
```

**Expected behavior**
Spack will install and load the correct Kokkos version, Kokkos version should be able to specify via dependency option

**Desktop (please complete the following information):**
 - LANL Darwin

**Additional context**
Spack version: 0.22.0.dev0 (d9528819a3e9404ff85943fcc027187b29059230)

**Comment by vicentebolea** [comment]
@hr87 Please report this in the https://github.com/spack/spack repository, we contribute to that package there and I also contribute sometimes to the kokkos one.

**Comment by suchyta1** [comment]
When I look at the adios2 package in Spack, I don't think there's a depency `when` that is just `+kokkos`, without `+rocm`, `+cuda`, or `+sycl`. I suspect if you do a `spack spec` on the install, it won't have Kokkos in the dependency build tree. I'll investigate further.

**Comment by suchyta1** [comment]
It works just to add `depends_on("kokkos@3.7:", when="+kokkos")` in addition to the others at the top of the file. But in my opinion, it might make sense not to make the ADIOS2 package explicitly a `ROCmPackage` or to have a `+sycl` variant, and just figure it out based on whatever `kokkos` dependency is requested. (It should be a `CudaPackage` though since it can use Cuda without Kokkos.) One might argue that it'd be harder to understand this way for people who don't know a lot about Spack, though. And strictly speaking, I suppose you could give ADIOS a Kokkos with ROCm, but not care about that ROCm support from ADIOS' Kokkos.

**Comment by vicentebolea** [comment]
@suchyta1 thanks for the insights.

> But in my opinion, it might make sense not to make the ADIOS2 package explicitly a ROCmPackage

The reason of this, is that the user needs to specify the GPU Architecture when using adios2+kokkos+rocm. A workaround is to have the user install kokkos first and later install adios2, the problem with it is that we can not expect our users to follow that.

I opened a PR in spack with the changes commented here: https://github.com/spack/spack/pull/42621

**Comment by suchyta1** [comment]
Yeah, you can do like with `spack install adios2 ^ kokkos +cuda cuda_arch=70`

**Comment by vicentebolea** [comment]
I believe that this was fixed at https://github.com/spack/spack/pull/42621. Please reopen this if you still observe this issue.
