### ISSUE TITLE
CI: All-Static builds (Linux/macOS/Win)

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#4025]
Downstream, it makes sense for some deployments (e.g., PyPA/pip of openPMD-api) to build an all-static ADIOS2 builds with all-static dependencies.

This often breaks in ADIOS2 #4019 #3898 #3716 #2747 #2454 #2316 #2576 #1810 ...

Could we add a CI entry for each Linux/macOS/Win that:
- builds all ADIOS2 dependencies as static
- builds ADIOS2 as static
- does smoke tests?

Currently, we only have three static Linux builds in CI. I am not sure they also test dependencies like C-Blosc2 (static!).

For our use case, covering `serial` is sufficient.

Note: we definitely want to keep shared builds for the same combinations too (esp. Windows DLL exports are tricky and need coverage).

**Comment by vicentebolea** [comment]
I believe that his has been fixed in #4037 and #4041
