### ISSUE TITLE
*.f90 files vs. *.F90 files

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#4032]
I am wondering if there is any special reason that we have both *.f90 and *.F90 files fortrran files in the repo?

**Comment by pnorbert** [comment]
We need .F90 if the file contains C style macros and headers (i.e. # character). The capital letter is commonly understood by Fortran compilers to call the pre-processor on them before compiling.

**Comment by eisenhauer** [comment]
For future reference, stackoverflow is a great place to learn this kind of thing.

**Comment by eisenhauer** [comment]
Close this as answered.
