### ISSUE TITLE
Reader for local variables fails

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#409]
Interprets shape[0] = 0, when shape should be empty for local variables

**Comment by pnorbert** [comment]
A local value is actually defined as 1D array at writing with a special dimension size:
```
 // 3. Local value, varying across processes
  adios2::Variable<int> &varProcessID =
            io.DefineVariable<int>("ProcessID", {adios2::LocalValueDim});
```
`constexpr size_t LocalValueDim = MaxSizeT - 2;`

At reading it should show as 1D array, and Shape[0] should be the number of writers.
