### ISSUE TITLE
PG name should be the IO object's name

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#411]
void BP3Serializer::PutProcessGroupIndex()
line 55    const std::string name(std::to_string(m_RankMPI));

In ADIOS1 the name of the PG comes from the user given name, which is used in the XML to identify a group. This name is the same for all writers. Currently ADIOS2 just uses the rank for the name, which makes the PGs have different names although they belong together. 

I found one place where this apparently matters: adios 1.x's old read api, and the plotter tool using that api. It does not find the variables in the file. The PG naming issue may or may not cause this issue but in debugging I found looping over the many groups with zero variables instead of just getting one group with a variable.

**Comment by williamfgc** [comment]
Good one!
