### ISSUE TITLE
Missing Conda files for Linux x86_64 with MPI

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#4110]
I am trying to install ADIOS 2.9.2 via Conda on Frontier, and I see that there is no binary for Linux x86_64 with MPI enabled.
[https://anaconda.org/conda-forge/adios2/files?version=2.9.2](https://anaconda.org/conda-forge/adios2/files?version=2.9.2)

**Comment by pnorbert** [comment]
Add this as a reminder for the 2.10 release to look out for this issue

**Comment by vicentebolea** [comment]
@kshitij-v-mehta in page 3 you can find the x86_64 binaries (https://anaconda.org/conda-forge/adios2/files?page=3&version=2.9.2)

Note that they are named linux-64

**Comment by vicentebolea** [comment]
Closing this as this appears to be resolved. Please re-open if you find that is not the case. Thanks for reporting this!
