### ISSUE TITLE
Python only reads partial data in 3D array

### ISSUE THREAD

**Issue by hr87** [ornladios/ADIOS2#4159]
**Describe the bug**
I have a file with a 3D variable. `bpls` gives the correct dimensions of the array (129, 16, 33). 
However, when I read the variable with a python script, the shape of the variable is suddenly (129, 16, 15). I confirmed that python only reads in the last 15 values of the last dimension, skipping the first 18.

The file is written from a single MPI process, the read is in serial.  

**To Reproduce**
I can provide an example file
1. Read data in with python
2. Compare shape of high-D variable

**Expected behavior**
Python reading in the whole variable, not only half

**Desktop (please complete the following information):**
 - LANL Darwin
 - Adios 2.9.2, gcc 12,2,0, python 3.11.5

**Comment by pnorbert** [comment]
Strange! Can you please provide the example file and the python commands you are issuing?

**Comment by hr87** [comment]
Can you send an email to hrhammer at lanl.gov, then I can send you the file.

**Comment by hr87** [comment]
Turns out, I missed something when debugging. It was my fault, works as expected, when I created the small example.
