### ISSUE TITLE
MATLAB Bindings Won't Properly Read "ADIOS-BP Version 5.2 Little Endian" BPs

### ISSUE THREAD

**Issue by tomgade09** [ornladios/ADIOS2#4212]
**Describe the bug**
MATLAB bindings will not properly read `ADIOS-BP Version 5.2 Little Endian - ADIOS v2.9.2` BPs.  When attempting to read v5.2 BPs produced on Linux with library v.2.9.2, on MacOS (using v.2.10.1) file opens successfully, but no variables are able to be detected or read; on Linux (Perlmutter), using v2.9.2 to both write and read the BP, when using the MATLAB bindings, `adiosopenc` segfaults and MATLAB crashes.  `ADIOS-BP Version 4 Little Endian - ADIOS v2.8.3` BPs are able to be read successfully on both platforms.

There doesn't appear to be any way to pass options to `adiosopenc` that specifies version of BP (nor would that necessarily be desirable if working with multiple versions of BPs).

BPLS on both platforms correctly identifies variables in the BP and is seemingly able to read data by producing min/max/avg values that look correct.

**To Reproduce**
1. Create BP file using a version of ADIOS2 that produces v5.2 BP files
2. Attempt to use MATLAB bindings in linux or MacOS
3. Observe segfault on `adiosopenc` call in `adiosopen.m`

**Expected behavior**
`adiosopenc` should be able to detect variables in BP files of any version.

**Desktop (please complete the following information):**
 - OS/Platform: MacOS, Linux (Perlmutter)
 - Build: BPs produced by ADIOS 2.9.2, read by 2.9.2 (Linux), 2.10.1 (MacOS)

**Comment by eisenhauer** [comment]
Unfortunately this is a known problem that was corrected in December 2023.  Reader-side matlab bindings won't work with BP5 for any anything without this fix, which was discovered after the 2.9.2 release.  The only options are to stick with BP4 or to use a 2.10 release on the reader side.

**Comment by tomgade09** [comment]
Thanks.  Is there anything special I would have to do on a 2.10 release?  Seems as if MacOS isn't detecting any of the variables in the bp.  The struct that's returned from `adiosopenc` doesn't list any variables.  I'll give 2.10 a shot on Perlmutter

**Comment by tomgade09** [comment]
I see.  The MATLAB bindings have one commit since my last one.  I'll have to recompile the c portion of the bindings.  Let me give it a shot quick.

**Comment by tomgade09** [comment]
Looks like that works on MacOS and I'm assuming it will work on Linux as well.  I updated the library (through brew) without recompiling the bindings - didn't notice anything had changed there.  Call it user error.  This can be closed.  Thanks for the help.
