### ISSUE TITLE
begin_step gets blocked when meshes become bigger.

### ISSUE THREAD

**Issue by abhishek1297** [ornladios/ADIOS2#4218]
We are encountering an issue with our heat PDE solver where each time step is sent to the server for processing. Our data is being transmitted as a 1D array instead of a 2D array using SST EVPATH engine.

When using ADIOS with a client setup of 4 ranks and server with 1 rank and a 500x500 mesh to send, each client rank successfully sends its respective local data to the server rank for processing. However, when we increase the mesh size to 1000x1000, the first call to `begin_step()` on the server side gets blocked, despite no explicit errors being reported. The clients and server open the engine on the file as expected. Interestingly, if we reduce the client ranks to 1, the program works again without issues.

I am aware that `begin_step()` involves some collective operations, but debugging is challenging due to the lack of apparent errors. Is it a deadlock due to lack of resources ? Although, I am testing the code with a single client and a single server which shouldn't consume too many resources.

Could you help identify what might be causing the issue when communicating larger arrays?
I am sharing `SstVerbose=5` tails below with a deadlock afterwards.

## SST logs tail client
```
Writer 0 (0xb13ce0): Stream "engines/melissa.sid-0" waiting for 1 readers
Writer 0 (0xb13ce0): Beginning writer-side reader open protocol
Writer 1 (0x15f6fc0): Beginning writer-side reader open protocol
Writer 3 (0x1a08b00): Beginning writer-side reader open protocol
Writer 2 (0x1345830): Beginning writer-side reader open protocol
DP Writer 0 (0xb13ce0): Received contact info "AAIAAJTJ8o39xgAAATkCmAowEKw=", RD_Stream 0x1f29f40 for Reader Rank 0
Writer 0 (0xb13ce0): Setting SpeculativePreload ON for new reader
DP Writer 2 (0x1345830): Received contact info "AAIAAJTJ8o39xgAAATkCmAowEKw=", RD_Stream 0x1f29f40 for Reader Rank 0
Writer 2 (0x1345830): Setting SpeculativePreload ON for new reader
DP Writer 1 (0x15f6fc0): Received contact info "AAIAAJTJ8o39xgAAATkCmAowEKw=", RD_Stream 0x1f29f40 for Reader Rank 0
Writer 1 (0x15f6fc0): Setting SpeculativePreload ON for new reader
DP Writer 3 (0x1a08b00): Received contact info "AAIAAJTJ8o39xgAAATkCmAowEKw=", RD_Stream 0x1f29f40 for Reader Rank 0
Writer 3 (0x1a08b00): Setting SpeculativePreload ON for new reader
Writer 0 (0xb13ce0): My oldest timestep was 0, global oldest timestep was 0
Writer 2 (0x1345830): My oldest timestep was 0, global oldest timestep was 0
Writer 1 (0x15f6fc0): My oldest timestep was 0, global oldest timestep was 0
Writer 1 (0x15f6fc0): Finish writer-side reader open protocol for reader 0x160f540, reader ready response pending
Writer 3 (0x1a08b00): My oldest timestep was 0, global oldest timestep was 0
Writer 3 (0x1a08b00): Writer 2 (0x1345830): Finish writer-side reader open protocol for reader 0x135e430, reader ready response pending
Finish writer-side reader open protocol for reader 0x1a21270, reader ready response pending
Writer 0 (0xb13ce0): Finish writer-side reader open protocol for reader 0xb2c9d0, reader ready response pending
Writer 0 (0xb13ce0): (PID 193b, TID 7f0f37f8aa80) Waiting for Reader ready on WSR 0xb2c9d0.
Writer 0 (0xb13ce0): Reader Activate message received for Stream 0xb2c9d0.  Setting state to Established.
Writer 0 (0xb13ce0): Parent stream reader count is now 1.
Writer 0 (0xb13ce0): Reader ready on WSR 0xb2c9d0, Stream established, Starting 0 LastProvided 0.
Writer 1 (0x15f6fc0): Finish opening Stream "engines/melissa.sid-0"
Writer 3 (0x1a08b00): Finish opening Stream "engines/melissa.sid-0"
Writer 2 (0x1345830): Finish opening Stream "engines/melissa.sid-0"
Writer 0 (0xb13ce0): Finish opening Stream "engines/melissa.sid-0"
```
## SST logs tail server
```
Reader 0 (0x2193e90): Writer is using Minimum Connection Communication pattern (min)
DP Reader 0 (0x2193e90): Received contact info "Writer Rank 0, test contact", WS_stream 0xb2c350 for WSR Rank 0
DP Reader 0 (0x2193e90): Received contact info "Writer Rank 1, test contact", WS_stream 0x1610af0 for WSR Rank 1
DP Reader 0 (0x2193e90): Received contact info "Writer Rank 2, test contact", WS_stream 0x135f7c0 for WSR Rank 2
DP Reader 0 (0x2193e90): Received contact info "Writer Rank 3, test contact", WS_stream 0x1a227e0 for WSR Rank 3
Reader 0 (0x2193e90): Sending Reader Activate messages to writer
Reader 0 (0x2193e90): Finish opening Stream "engines/melissa.sid-0", starting with Step number 0
DEBUG:melissa.server.base_server:Rank 0>> Decoded launcher messages [<melissa.launcher.message.JobUpdate object at 0x7fbfeb257610>]
INFO:melissa.server.base_server:Rank 0>> Connection established with sim-id=0 in  0.178 sec.
Reader 0 (0x2193e90): Wait for next metadata after last timestep -1
Reader 0 (0x2193e90): Waiting for metadata for a Timestep later than TS -1
Reader 0 (0x2193e90): (PID 1920, TID 7fc00d1c5740) Stream status is Established
```

**Comment by eisenhauer** [comment]
Hmm...  Which dataplane are you using?  (This would have been earlier in the trace output.).  Just FYI, I'm focusing on your client (which is an SST writer).  Both sides seem to have made it through the Open() handshake, and your server (SST reader) looks like it is waiting on metadata from the first timestep.  So presumably what is going on is that the writer (client) somehow hasn't gotten to the point of producing a timestep.  Aside from registering the data with the dataplane (which may or may not produce trace output, depending upon which data plane), there aren't any trace points early in SST's writer-side ProvideTimestep routine, which is what happens in CloseStep().  So it might be that we're blocking in our first internal MPI collective, but I think the first thing to sort out is whether or not all of your 4 mpi writer ranks are calling BeginStep and then EndStep().  There are no tracepoints in BeginStep, so we won't know about that, and we won't get to EndStep() tracepoints unless all ranks are calling EndStep().   Does this work with a single rank on the client side?

**Comment by abhishek1297** [comment]
[reader.log](https://github.com/user-attachments/files/16058408/reader.log)
[writers.log](https://github.com/user-attachments/files/16058410/writers.log)

Though, we want to use it with RDMA. I got the issue first with RDMA dataplane on a cluster with fabrics and omnipath. I moved to our local cluster to ensure everything is correct. So, I set the sst transport to evpath. But, it is exactly the same issue.

> Does this work with a single rank on the client side?
Yes. It does the handshake and starts sending all the timesteps.

What I don't understand is, if it works for 500x500, What could possibly change on larger meshes? The first metadata handshake should still be the same with different values, right?

In fact, I just tested by gradually increasing the mesh size to 505x505, beyond which, this deadlocks.

**Comment by eisenhauer** [comment]
> [reader.log](https://github.com/user-attachments/files/16058408/reader.log) [writers.log](https://github.com/user-attachments/files/16058410/writers.log)
> 
> Though, we want to use it with RDMA. I got the issue first with RDMA dataplane on a cluster with fabrics and omnipath. I moved to our local cluster to ensure everything is correct. So, I set the sst transport to evpath. But, it is exactly the same issue.
> 
> > Does this work with a single rank on the client side?
> > Yes. It does the handshake and starts sending all the timesteps.
> 
> What I don't understand is, if it works for 500x500, What could possibly change on larger meshes? The first metadata handshake should still be the same with different values, right?
> 
> In fact, I just tested by gradually increasing the mesh size to 505x505, beyond which, this deadlocks.

I don't know.  So the additional logs let me know that you're using the EVPath data plane.  The first thing that you should see in EndStep() is something like this:
DP Writer 3 (0x157808e50): ProvideTimestep, registering timestep 0, data 0x157809b60, fprint 3463442540779c5e
DP Writer 0 (0x13e80a910): ProvideTimestep, registering timestep 0, data 0x13e80c290, fprint 9e2849852b542132
DP Writer 1 (0x149205f60): ProvideTimestep, registering timestep 0, data 0x14900b7a0, fprint d08384454066dd96
DP Writer 2 (0x151609610): ProvideTimestep, registering timestep 0, data 0x141617c60, fprint c74373e5407153fa

This is the data plane printing out that it has received the timestep.  That's pretty much the first thing that happens in SST EndStep(), so that it's not happening makes me think that maybe your code isn't getting to EndStep. Can you put an output line in your code that would show that each rank is about to call EndStep()

**Comment by abhishek1297** [comment]
After printing, The issue seems to be coming befor the calls to adios api. Closing this issue. Thanks for your help.
