### ISSUE TITLE
GathervArrays does not support gathering...

### ISSUE THREAD

**Issue by pgrete** [ornladios/ADIOS2#4237]
I'm seeing the following error popping up when scaling up our simulation:

```
[AbstractIOHandlerImpl] IO Task CLOSE_FILE failed with exception. Clearing IO queue and passing on the exception.
terminate called after throwing an instance of 'std::_Nested_exception<std::runtime_error>'
  what():  [Thu Jul 11 16:26:37 2024] [ADIOS2 EXCEPTION] <Helper> <adiosComm> <GathervVectors> : ERROR: GathervArrays does not support gathering more than 2^31 elements. Here it was tasked with 3280349184 elements
```
This happens, for example, when reading a BP5 file with 2048 ranks (which was successfully written by 512 ranks before (and can also be successfully read by those 512 ranks).

I suspect an attribute with a large string (we store the input parameter file of our simulation as an attribute) to be the culprit, but I wasn't fully able to successfully confirm this suspicion.

So my question is: How can I most efficiently debug the issue at scale?
I didn't info infos on a logging mechanism or similar in the docs.

And related: Is there a way to print the data size with bpls? 3280349184 / 2048 is an integer so it might help to find some attribute with that size to narrow it down.

Thanks!

**Comment by eisenhauer** [comment]
If I were guessing from your description is sounds like you are stressing BP5's ability to gather metadata.  Some of the characteristics of BP5 that make it more efficient at scale, unfortunately put pressure on metadata size in the first timestep.  BP5Writer takes steps to minimize this problem, but it can't be completely eliminated.  That said, let me ask a quick question about your application.  Are you writing attributes on all ranks?  Or only on rank 0?   (Attributes from all ranks are merged after being gathered, so writing duplicate attributes on non-zero ranks adds unnecessary pressure to metadata.).
