### ISSUE TITLE
Engine BP5Writer does not support BeginStep

### ISSUE THREAD

**Issue by stgeke** [ornladios/ADIOS2#4318]
Not sure why I get this exception
```
[ADIOS2 EXCEPTION] <Core> <Engine> <ThrowUp> : Engine BP5Writer does not support BeginStep
```
Any pointers? All example using BP5 seem to use `BeginStep/EndStep`

**Comment by eisenhauer** [comment]
Yes, that is quite strange.    That "does not support" bit comes from the Engine parent class, and gets thrown whenever an actual engine (all subclassed from the Engine parent class) doesn't override one of the methods of the parent class.  But BP5Writer does override BeginStep, as I think all the engines do.  So I'd suspect that something has gone seriously wrong with your build in some way.  You might do make clean and start over, but if that doesn't help lets us know what platform you're building on, compiler, etc.

**Comment by eisenhauer** [comment]
I'm going to close this pending more information.
