### ISSUE TITLE
Is BP5 supported by Paraview's Adios VTX reader?

### ISSUE THREAD

**Issue by stgeke** [ornladios/ADIOS2#4320]
I guess it does but even latest Paraview (5.13-RC2) lists only:

![image](https://github.com/user-attachments/assets/41b44138-4473-4213-9c61-17f67bef9ebf)

**Comment by mohrmarc** [comment]
Testing this shows that the VTXReader also works with BP5 starting from at least ParaView 5.12.1. Don't have 5.12.0 anymore to check and 5.11.1 did not. See also https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10152 in this regard.

**Comment by eisenhauer** [comment]
Sounds like tings are resolved WRT Paraview using BP5.  Please reopen this or create an issue with vtk if not.
