### ISSUE TITLE
BP5 engine: errors with multiple adios2_put calls and multiple operations when compression is enabled

### ISSUE THREAD

**Issue by dqwu** [ornladios/ADIOS2#4390]
### Description
When using the BP5 engine in ADIOS2 with compression enabled, errors occur in two scenarios:
- When calling adios2_put twice on a scalar (0D) variable.
- When attempting to add multiple operations to a non-scalar variable.

### Working Code Example
```
#include <adios2_c.h>

int main()
{
    adios2_adios *adios = adios2_init_serial();
    adios2_io *bpIO = adios2_declare_io(adios, "BP5WriterWithComp");
    adios2_set_engine(bpIO, "BP5");

    adios2_engine *bpWriter = adios2_open(bpIO, "Blosc_compression.bp", adios2_mode_write);

    size_t count = 1;
    adios2_variable *var = adios2_define_variable(bpIO, "1d_var", adios2_type_int32_t, 1, NULL, NULL, &count, adios2_constant_dims_true);

    adios2_operator *op = adios2_define_operator(adios, "Blosc2Lossless", "blosc");

    size_t operation_index;
    adios2_add_operation(&operation_index, var, op, "compressor", "zstd");

    int val = 10;
    adios2_put(bpWriter, var, &val, adios2_mode_sync);

    val = 20;
    adios2_put(bpWriter, var, &val, adios2_mode_sync);

    adios2_close(bpWriter);
    adios2_finalize(adios);

    return 0;
}
```
Result: runs as intended with no errors.

### Variation 1: Changing to Scalar (0D) Variable
```
#include <adios2_c.h>

int main()
{
    adios2_adios *adios = adios2_init_serial();
    adios2_io *bpIO = adios2_declare_io(adios, "BP5WriterWithComp");
    adios2_set_engine(bpIO, "BP5");

    adios2_engine *bpWriter = adios2_open(bpIO, "Blosc_compression.bp", adios2_mode_write);

    adios2_variable *var = adios2_define_variable(bpIO, "0d_var", adios2_type_int32_t, 0, NULL, NULL, NULL, adios2_constant_dims_false);

    adios2_operator *op = adios2_define_operator(adios, "Blosc2Lossless", "blosc");

    size_t operation_index;
    adios2_add_operation(&operation_index, var, op, "compressor", "zstd");

    int val = 10;
    adios2_put(bpWriter, var, &val, adios2_mode_sync);

    val = 20;
    adios2_put(bpWriter, var, &val, adios2_mode_sync);

    adios2_close(bpWriter);
    adios2_finalize(adios);

    return 0;
}

```
Error:
`[ADIOS2 ERROR] <Helper> <adiosSystem> <ExceptionToError> : adios2_put: ... BP5 does not support adding operators after the first Put()`

### Variation 2: Adding an additional operation (clevel = 5)
```
#include <adios2_c.h>

int main()
{
    adios2_adios *adios = adios2_init_serial();
    adios2_io *bpIO = adios2_declare_io(adios, "BP5WriterWithComp");
    adios2_set_engine(bpIO, "BP5");

    adios2_engine *bpWriter = adios2_open(bpIO, "Blosc_compression.bp", adios2_mode_write);

    size_t count = 1;
    adios2_variable *var = adios2_define_variable(bpIO, "1d_var", adios2_type_int32_t, 1, NULL, NULL, &count, adios2_constant_dims_true);

    adios2_operator *op = adios2_define_operator(adios, "Blosc2Lossless", "blosc");

    size_t operation_index;
    adios2_add_operation(&operation_index, var, op, "compressor", "zstd");
    adios2_add_operation(&operation_index, var, op, "clevel", "5");

    int val = 10;
    adios2_put(bpWriter, var, &val, adios2_mode_sync);

    val = 20;
    adios2_put(bpWriter, var, &val, adios2_mode_sync);

    adios2_close(bpWriter);
    adios2_finalize(adios);

    return 0;
}

```
Error:
`[ADIOS2 ERROR] <Helper> <adiosSystem> <ExceptionToError> : adios2_put: ... BP5 does not support multiple operators`

Note: If we remove the second adios2_put call, the error is gone.

### Observed Behavior
Errors occur when:
- Using a scalar variable with multiple adios2_put calls.
- Attempting to add multiple operations to a non-scalar variable written with multiple adios2_put calls.

### Questions
- Are these errors expected behavior?
- For Variation 1, is it possible for the BP5 engine to support scalar variables with multiple adios2_put calls?
- For Variation 2, is it possible for the BP5 engine to support multiple operations on a variable written with multiple adios2_put calls?

**Comment by eisenhauer** [comment]
Hmm.   WRT variation 1, operators were introduced with compression in mind, so I don't think anyone thought about applying them to scalar variables.  At the moment I can't think of a solid use case for operators on scalars, so my view would be that we should throw an error message, but it should be a different one.  Given a use case I might think differently.

WRT 2, I'm not sure how the multiple puts comes in to the multiple operators question, but let me tell you what the constraints are.  First, we require that operators be defined before the first put() so there is no ambiguity.  I.E. any data the reader finds later will have had the operator applied to it.  You can do multiple Put()s to any array variable, this is true operator or not.  Each Put() is either a different "local" block or could be to a different region of a global array.  Right now, all the ADIOS engines are limited to a single operator per variable.  That could change given a solid use case, but it would require non-trivial changes to ADIOS internals.  Now, that said, I'm not sure I understand your code.  Is "clevel" really meant to be a parameter, as opposed to an operator itself?  If so, that's done differently (with parameters).  Can you clarify?

**Comment by dqwu** [comment]
> Hmm. WRT variation 1, operators were introduced with compression in mind, so I don't think anyone thought about applying them to scalar variables. At the moment I can't think of a solid use case for operators on scalars, so my view would be that we should throw an error message, but it should be a different one. Given a use case I might think differently.
> 
> WRT 2, I'm not sure how the multiple puts comes in to the multiple operators question, but let me tell you what the constraints are. First, we require that operators be defined before the first put() so there is no ambiguity. I.E. any data the reader finds later will have had the operator applied to it. You can do multiple Put()s to any array variable, this is true operator or not. Each Put() is either a different "local" block or could be to a different region of a global array. Right now, all the ADIOS engines are limited to a single operator per variable. That could change given a solid use case, but it would require non-trivial changes to ADIOS internals. Now, that said, I'm not sure I understand your code. Is "clevel" really meant to be a parameter, as opposed to an operator itself? If so, that's done differently (with parameters). Can you clarify?

My goal is to specify additional compression parameters (like clevel=5 for compression level or shuffle=bit) for the compressor. I originally attempted to apply these by making multiple calls to adios2_add_operation, like this:
```
adios2_add_operation(&operation_index, var, op, "compressor", "zstd");
adios2_add_operation(&operation_index, var, op, "clevel", "5");
adios2_add_operation(&operation_index, var, op, "shuffle", "bit");
```

However, given the constraint on a single operator per variable, my current workaround is to limit it to just the compressor type, as shown here:
`adios2_add_operation(&operation_index, var, op, "compressor", "zstd");`

This approach works but leaves the compression level and shuffle at their default values, which restricts flexibility. Is there a recommended way to apply these additional options (like clevel=5 or shuffle=bit) without adding extra adios2_add_operation calls?

**Comment by eisenhauer** [comment]
Ah, I see.  So, yes, this is some weirdness with the C api (as opposed to C++).    In C++, the equivalent call to adios2_add_operation takes a list of parameters. Parameter lists aren't easily represented in C, so we allow only a single parameter (key and value) in the add_operation call, but there is an additional call:

adios2_error adios2_set_operation_parameter(adios2_variable *variable, const size_t operation_id,
                                            const char *key, const char *value)
I don't see that this is something we mention in the documentation or used in examples, which we clearly need to correct, but you should be able to call adios2_set_operation_parameter() multiple times for multiple parameters.

**Comment by dqwu** [comment]
> Ah, I see. So, yes, this is some weirdness with the C api (as opposed to C++). In C++, the equivalent call to adios2_add_operation takes a list of parameters. Parameter lists aren't easily represented in C, so we allow only a single parameter (key and value) in the add_operation call, but there is an additional call:
> 
> adios2_error adios2_set_operation_parameter(adios2_variable *variable, const size_t operation_id, const char *key, const char *value) I don't see that this is something we mention in the documentation or used in examples, which we clearly need to correct, but you should be able to call adios2_set_operation_parameter() multiple times for multiple parameters.

Thank you for your suggestion! I will use adios2_set_operation_parameter() to apply additional compression options in my code.

**Comment by eisenhauer** [comment]
OK, I've verified that this is actually in the documentation, it's just in the doxygen-generated part, so not immediately obvious.  I'm going to close this, pending further questions.
