### ISSUE TITLE
CircleCI timeout staging test

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#449]
CircleCI timeouts on the staging-common/TestStagingMPMD test in the gcc-openmpi build. This test has 4 separate cases. Even the short ones (SingleStep and MultiStep) timeout at 300 seconds. I can run those under 10s on my VM with 2 CPU cores, forcing to run with 16 MPI tasks to have the full test (12 params). The other two (SlowWriter, SlowReader) run longer, right now under 40 seconds on my VM.

**Comment by williamfgc** [comment]
Just translating the failed PR to an issue, so we won't forget

**Comment by chuckatkins** [comment]
Fixed
