### ISSUE TITLE
Corrupted data in first output step in some cases of multi-block writing

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#478]
The standalone test program PerfManyVars exhibits this problem as well as its test counterpart TestManyVars (if those parameters are uncommented in the source that causes this problem).

The test writes multiple variables multiple blocks per process and multiple timesteps, the it reads them back and check the data value by value. At some limit of variables x blocks, there will be corrupted blocks in the output (a write problem). This only happens for the first output step; the test is always good for any other steps with any combo.  Known examples that exhibit the problem: 8 x 9, and 5 x 15. Note that 8x8 works and none of 8xN, N>=9 works.

```
$ ./bin/PerfManyVars 8 9 2 
fmt=[v%1.1d]
varname[0]=v0
varname[7]=v7
-- Define variables.
[rank=000, line 273]: Write step 0 to many_vars.bp
[rank=000, line 280]:   Write block 0, value 0 to many_vars.bp
[rank=000, line 280]:   Write block 1, value 1 to many_vars.bp
[rank=000, line 280]:   Write block 2, value 2 to many_vars.bp
[rank=000, line 280]:   Write block 3, value 3 to many_vars.bp
[rank=000, line 280]:   Write block 4, value 4 to many_vars.bp
[rank=000, line 280]:   Write block 5, value 5 to many_vars.bp
[rank=000, line 280]:   Write block 6, value 6 to many_vars.bp
[rank=000, line 280]:   Write block 7, value 7 to many_vars.bp
[rank=000, line 280]:   Write block 8, value 8 to many_vars.bp
[rank=000, line 295]:   Write time for step 0 was  0.004 seconds
[rank=000, line 273]: Write step 1 to many_vars.bp
[rank=000, line 280]:   Write block 0, value 10000 to many_vars.bp
[rank=000, line 280]:   Write block 1, value 10001 to many_vars.bp
[rank=000, line 280]:   Write block 2, value 10002 to many_vars.bp
[rank=000, line 280]:   Write block 3, value 10003 to many_vars.bp
[rank=000, line 280]:   Write block 4, value 10004 to many_vars.bp
[rank=000, line 280]:   Write block 5, value 10005 to many_vars.bp
[rank=000, line 280]:   Write block 6, value 10006 to many_vars.bp
[rank=000, line 280]:   Write block 7, value 10007 to many_vars.bp
[rank=000, line 280]:   Write block 8, value 10008 to many_vars.bp
[rank=000, line 295]:   Write time for step 1 was  0.002 seconds
[rank=000, line 366]: Read and check data in many_vars.bp
[rank=000, line 377]:   Check variable definitions... many_vars.bp
[rank=000, line 387]:   Time to check all vars' info:  0.000 seconds
[rank=000, line 390]:   Check variable content...
[rank=000, line 410]:     Step 0 block 0: value=0
[rank=000, line 410]:     Step 0 block 1: value=1
[rank=000, line 410]:     Step 0 block 2: value=2
[rank=000, line 410]:     Step 0 block 3: value=3
[rank=000, line 410]:     Step 0 block 4: value=4
[rank=000, line 410]:     Step 0 block 5: value=5
[rank=000, line 410]:     Step 0 block 6: value=6
[rank=000, line 410]:     Step 0 block 7: value=7
[rank=000, line 410]:     Step 0 block 8: value=8
[rank=000, line 421]: ERROR: v6[0] step 0 block 8: wrote 8 but read 0
[rank=000, line 421]: ERROR: v7[0] step 0 block 8: wrote 8 but read 0
[rank=000, line 435]:   Read time for step 0 was  0.008s
[rank=000, line 410]:     Step 1 block 0: value=10000
[rank=000, line 410]:     Step 1 block 1: value=10001
[rank=000, line 410]:     Step 1 block 2: value=10002
[rank=000, line 410]:     Step 1 block 3: value=10003
[rank=000, line 410]:     Step 1 block 4: value=10004
[rank=000, line 410]:     Step 1 block 5: value=10005
[rank=000, line 410]:     Step 1 block 6: value=10006
[rank=000, line 410]:     Step 1 block 7: value=10007
[rank=000, line 410]:     Step 1 block 8: value=10008
[rank=000, line 435]:   Read time for step 1 was  0.007s
```

Source code is in testing/adios2/performance/manyvars, a C code for the standalone program, C++ code for the test where the combos can be added to break the test.

**Comment by williamfgc** [comment]
Thanks @pnorbert this is a good catch. Let me see what's going on.

**Comment by williamfgc** [comment]
The interesting thing is that the metadata min/max 0/8 is correct for v6 and v7

**Comment by williamfgc** [comment]
@pnorbert I noticed that ldim1 and ldim2 are set to a fix value of 5.  Switching ldim1 to 1 would solve the problem as it scales with MPI Size. What happens is that we are trying to fit a 5x5 (25) data pointer (count) into a 1x5 (5) intended size (based on offset). This is from setting the offset in Line 282, 283 to start[2]:   
``` 
block0 offset = {0,0}, 
block1 offset = {0,5},
block2 offset = {0,10},
...
}
```

On a side note, I don't know if adios can identify memory overlapping cases. It's actually a good thing we show that results are not accurate.

**Comment by pnorbert** [comment]
Ah, so the test is not correct? Global size should be MPI_size * 5 x 5, or
vice versa, I don't remember. And offsets calculated so that there are no
overlaps.

BTW, overlapping blocks as well as unwritten parts of a global array are
allowed in adios. For overlapping blocks, it is 'undefined' which values
will be delivered at reading. For unwritten pieces we return zero, although
this should be some user defined FillValue.

**Comment by pnorbert** [comment]
The test works as intended. 5x5 blocks put into a  numproc*5 by nblocks*5
global array. That is a 2D array with 2D decomposition.

```
$ mpirun -np 2 ./bin/PerfManyVars 1 3 1
$ bpls -l many_vars.bp -D
  integer  v0    {10, 15} = 0 / 12 / null  / null
        step 0:
          block 0: [0:4,  0: 4] = 0 / 0/ N/A / N/A
          block 1: [0:4,  5: 9] = 1 / 1/ N/A / N/A
          block 2: [0:4, 10:14] = 2 / 2/ N/A / N/A
          block 3: [5:9,  0: 4] = 10 / 10/ N/A / N/A
          block 4: [5:9,  5: 9] = 11 / 11/ N/A / N/A
          block 5: [5:9, 10:14] = 12 / 12/ N/A / N/A

```

**Comment by williamfgc** [comment]
@pnorbert you're right. My bad, I am still getting confused by the memory contiguous aspect between offsets....shouldn't be only 5 memory contiguous elements between {0,0} and {0,5}?

**Comment by pnorbert** [comment]
Yes, there are only 5 elements between those offsets. Note that the 2D
decomposition logically splits the 5x5 block into 5 separate rows. The very
first blocks spans from "0,0" to "4,4", the second block from "0,5" to
"4,9".

**Comment by williamfgc** [comment]
@pnorbert I think you just hit the jackpot. This is a bug in which for those magic numbers (8 9) the buffer needed to be reallocated at block 8 var 6 when writing metadata in data (something really rare). I was checking capacity for reallocation which was big enough, while the size was too small. This is solved with one line of code to enforce a reserve (expensive) before a resize (cheap) to set the memory to zero (secure). Before this change the buffer was growing as a power of 2 (STL gnu default) no matter what.

**Comment by chuckatkins** [comment]
Is this related to the ` BPWriteReadAsStreamTestADIOS2.ADIOS2BPWriteRead1D8` test failure?

https://open.cdash.org/testDetails.php?test=641932952&build=5324003
