### ISSUE TITLE
Build failure on Ubuntu VM and Summitdev

### ISSUE THREAD

**Issue by philip-davis** [ornladios/ADIOS2#500]
I am seeing the following build error on both Summitdev and a Ubuntu VM.

```
CMake Error at thirdparty/EVPath/EVPath/CMakeLists.txt:262 (file):
  file failed to open for reading (No such file or directory):

    /ccs/home/pdavis/summit/ADIOS2.main/ADIOS2/cmake/GOOD_MEMLOCK_LIMIT.c
```
I'm using cmake 3.9.2 on Summit and 3.10.1 on the VM. My VM does have the ibverbs library. To me, it looks like the CMAKE_SOURCE_DIR has changed/should change for EVPath when nested in ADIOS, but I don't know enough about CMake be confident of that.

Not sure what other output would be useful. I can provide cmake logs, etc, if those would help.

**Comment by philip-davis** [comment]
@chuckatkins

**Comment by chuckatkins** [comment]
Thanks for the bug report.  I'll fix it asap
