### ISSUE TITLE
SST/EVPath not compiling on Mac with clang compiler

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#508]
[ 23%] Building C object thirdparty/EVPath/EVPath/CMakeFiles/EVPath.dir/evp.c.o
In file included from /Users/wfg/workspace/ADIOS2/thirdparty/EVPath/EVPath/evp.c:7:
/usr/local/include/memory.h:4:10: fatal error: 'cstdlib' file not found
#include <cstdlib>
         ^

CMake configuration:
```
ADIOS2 build configuration:
  ADIOS Version: 2.1.0
  C++ Compiler : AppleClang 8.0.0.8000042 
    /Library/Developer/CommandLineTools/usr/bin/c++

  Fortran Compiler : GNU 5.4.0 
    /usr/local/bin/gfortran

  Installation prefix: /usr/local
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/adios2
     python: lib/python2.7/site-packages

  Features:
    Library Type: shared
    Build Type:   Debug
    Testing: ON
    Build Options:
      BZip2    : ON
      ZFP      : ON
      SZ       : OFF
      MPI      : ON
      DataMan  : ON
      SST      : ON
      ZeroMQ   : ON
      HDF5     : OFF
      ADIOS1   : ON
      Python   : ON
      Fortran  : ON
      SysVShMem: ON

-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   atl

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/wfg/workspace/build
```

**Comment by eisenhauer** [comment]
This is probably a bad installed /usr/local/include/memory.h
http://gnu-autoconf.7623.n7.nabble.com/Error-message-for-memory-h-td20177.html

**Comment by eisenhauer** [comment]
The package is an older version of zfp apparently.  Jason ran into this a while ago.  It's been fixed in newer zfp releases.

**Comment by eisenhauer** [comment]
@chuckatkins Unrelated to the memory.h issue, notice the CMake Warning here.  Something related to this was why the MACOSX_RPATH stuff was in the prior versions of GTkorvo cmake.  Not sure what the proper fix should be.  I'm also seeing this in my OSX dev environment with CMake 3.10.2

**Comment by eisenhauer** [comment]
Compilation failure is likely due a poorly-designed locally-installed package.  No ADIOS2 issue.
