### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#536]
Building on Titan from the latest head (that includes #535 ) with gcc 4.9.3.
`make -j8` gives
```
[ 36%] Linking CXX shared library ../../lib/libadios2.so
/usr/bin/ld: /lustre/atlas/proj-shared/csc249/CSC249ADCD01/software/titan.gnu/gcc-4.9.3/adios-develop/lib/libadios_nompi.a(libadios_nompi_a-adios.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```

Configured as 
`cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/adios2/installation/ -DADIOS2_USE_DataMan=OFF -DADIOS2_USE_HDF5=OFF -DADIOS2_USE_Fortran=ON -DCMAKE_BUILD_TYPE=Release ../`

Loaded modules:
```
Currently Loaded Modulefiles:
  1) eswrap/1.3.3-1.020200.1280.0
  2) craype-network-gemini
  3) craype/2.5.13
  4) cray-mpich/7.6.3
  5) craype-interlagos
  6) lustredu/1.4
  7) xalt/0.7.5
  8) git/2.13.0
  9) module_msg/0.1
 10) modulator/1.2.0
 11) hsi/5.0.2.p1
 12) DefApps
 13) gcc/4.9.3
 14) cray-libsci/16.11.1
 15) udreg/2.3.2-1.0502.10518.2.17.gem
 16) ugni/6.0-1.0502.10863.8.28.gem
 17) pmi/5.0.12
 18) dmapp/7.0.1-1.0502.11080.8.74.gem
 19) gni-headers/4.0-1.0502.10859.7.8.gem
 20) xpmem/0.1-2.0502.64982.5.3.gem
 21) dvs/2.5_0.9.0-1.0502.2188.1.113.gem
 22) alps/5.2.4-2.0502.9774.31.12.gem
 23) rca/1.0.0-2.0502.60530.1.63.gem
 24) atp/2.1.1
 25) PrgEnv-gnu/5.2.82
 26) python/3.5.1
 27) cudatoolkit/7.5.18-1.0502.10743.2.1
 28) papi/5.5.1.3
 29) cmake3/3.9.0
 30) fastbit/svn
 31) m4/1.4.16
 32) autoconf/2.69
 33) automake/1.14
```

**Comment by chuckatkins** [comment]
There's a mismatch in how ADIOS1 was built and how ADIOS2 is being built.  Try explicitly calling `export CC=cc CXX=CC FC=ftn` before configuring from a clean build directory.  That will ensure your building with the CrayPE wrappers instead of vanilla gcc.

**Comment by pnorbert** [comment]
It also seems that that adios1 install was not built with the -fPIC flag.
Make sure you add this flag to CFLAGS before configuring adios1.

**Comment by kshitij-v-mehta** [comment]
Thanks. The build succeeds now. I noticed that I had an adios1 install in my path. It was built without -fPIC. I removed it and added `export CC=cc CXX=CC FC=ftn`, and the build is now successful.

**Comment by kshitij-v-mehta** [comment]
It looks like mainly the error was due to the buggy adios1 install that was getting picked up.
