### ISSUE TITLE
Re-opening the same engine

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#550]
Can I re-open the same engine to write data? For example, is the following allowed?

```
call adios2_init(...)
call adios2_declare_io(io_obj,...)

do i=1,4
    call adios2_open(engine, io_obj, "restart", adios2_mode_write,...)
    !! declare variable and write data
    call adios2_close(engine,...)
end do
```

For the second iteration of the 'do' loop above, 'adios2_open' results in `ADIOS2 open with new MPI_Comm: ERROR: IO Engine with name restart already created, in call to Open.`

Does this mean a file can only be opened once?
I am trying to write a checkpoint-restart file. At every iteration, the file must be overwritten with new data.

**Comment by williamfgc** [comment]
this is my bad, close should release the resource, but I kept it for my own profiling. I will fix this. For now just create 4 IOs as a workaround. You can put those in a container/array and operate by index. Just like we do when reading.

**Comment by kshitij-v-mehta** [comment]
On a similar note, it looks like an IO object must be declared only once as there is no way to destroy/close the object. You cannot have this:

```
do i=1,4
    call restart()
end do

subroutine restart()
    call adios2_declare_io(adios2_io_restart, adios2_handle, "test_restart", ierr)
    ...
end subroutine
```

**Comment by williamfgc** [comment]
yeah, IOs should be unique through the scope of the adios object/handler. It becomes a debug nightmare if we are that flexible. A new adios object/handler can be created for that purpose. In your case, you can move declare_io outside restart and pass them as arguments of as part of a module.

**Comment by kshitij-v-mehta** [comment]
Also, variables are associated with IO objects, and it becomes tricky if variables are allowed to be redefined at every timestep, as users could potentially redefine the same variable totally differently.

The only caveat here is that subroutines have to be modified to accept a timestep argument, so that variables are defined when timestep==1. I think this was a constraint with adios1 as well, iirc.

Anyway, thanks for the help.

**Comment by williamfgc** [comment]
Adios doesn't have a timestep per-se. These are logical IO abstract steps that each application will provide a meaning.... timestep, sections, iteration (eg steady state problems) http://adios2-adaptable-io-system-version-2.readthedocs.io/en/latest/api/api.html#engines

**Comment by kshitij-v-mehta** [comment]
p.s. creating a new IO object at every iteration works fine for checkpoint-restart files where data is overwritten at every iteration. However, for those files where timesteps need to be appended, I observed that creating a new IO object in every iteration results in losing timestep information. In this case, keeping a single IO object and keeping the engine open for the duration of the program is the way to go. Just fyi.

**Comment by williamfgc** [comment]
Append mode is not supported, yet. Now Open/Close in adios2 is conforming to POSIX IO (so C, Fortran, Python, C++ fstream) open/close than in adios1, doing a single open and a single close means the resouce is alive through the run. BeginStep and EndStep will replace the open/close in adios1.

**Comment by kshitij-v-mehta** [comment]
Ok, to make sure I understand .. doing an 'endstep' does not mean that timestep is available for some process to read (e.g. an analysis process). Only doing a 'close' ensures that data is available for reading. Is that correct?

**Comment by williamfgc** [comment]
You can always define an IO variable later in the run, as long as it is not conflicting. Steps are an Engine concept, not a variable per-se. Timestep is an application concept when solving transient problems, it is not related to IO per-se.

**Comment by williamfgc** [comment]
Steps are logical...this is how you IO is performed. Simulation "timestep" belong to the simulation. For example, most checkpoint/restarts only have one IO step, but they might belong to timestep "10". Treat adios steps as abstractions, they are NOT timesteps.

**Comment by williamfgc** [comment]
EndStep will be the equivalent of "\n" + flush in a text file. The data is available by default, but like in any IO library, before close the system IO resource is still in open state.

**Comment by kshitij-v-mehta** [comment]
I understand that adios timesteps are abstractions :-)
I am trying to understand when data is available for an external process to read. If you have an analysis application that is waiting for data from a simulation, is data guaranteed to be available when 'endstep' is called, or is it available when 'close' is called? How should a simulation 'publish' data for someone else to read?

**Comment by williamfgc** [comment]
It is just like in a text file.... adios2 step=line (logical, unrelated to timestep), adios2 EndStep = \n + flush,  adios2 open = system open, adios2 close = system close. Publication in text files is at flush or close, so in adios2 is at EndStep or at Close. But flush is not a final call, while close is an absolute final.

**Comment by eisenhauer** [comment]
Hey Kshitij...  I think your question really only makes sense for streaming, for example for SST, endstep is the equivalent to publish.  For files I don't think ADIOS has ever really supported reading a file while it is being written.  So you have to wait for Close.

**Comment by williamfgc** [comment]
ADIOS2 underlying file IO transport library is unbuffered POSIX IO on Linux/Mac, and C++ fstream in Windows with explicit flushes at write. We do non-blocking (without O_EXCL) file open https://github.com/ornladios/ADIOS2/blob/master/source/adios2/toolkit/transport/file/FilePOSIX.cpp, so at EndStep or at Close, if the data is in disk then data written up to that point is available. adios1 is the same under hood, or any file IO library depending on POSIX IO for that matter. What we don't support is opening a file to write and read from the same engine. @kshitij-v-mehta it's perfectly fine to have an engine writing and a second one reading, but like any other file IO library, data can be added until Close. That's the beauty of separating the OSI layers in ADIOS2, we can always try different transport interfaces.

**Comment by williamfgc** [comment]
@kshitij-v-mehta you can always wait for append mode to be added, but the end result will be a sync write and read which might kill performance. In any case, at EndStep the metadata file is available, while the data files keep on growing. We still enable control for multiple step buffering since flushing data at every EndStep might kill performance.

**Comment by kshitij-v-mehta** [comment]
Looks like this bug still exists with the latest adios2 d75f53b3c5e1863c0d466cada7e6f65ac8554b98

**Comment by williamfgc** [comment]
@kshitij-v-mehta you will see a referenced pull request from a branch that addresses the issue before making it to master. After the CI passes I will merge it into master.
