### ISSUE TITLE
Python feature requests

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#560]
William, Norbert, and I have been starting to consider Python ease of use, and are opening the conversation about Python enhancements. A couple things I see that could make things simpler:

1. Introspection: The ability to return a "file object" that has a list of the variables, their sizes, etc.
2. Default selections: When reading, if the user doesn't give bounds it just tries to return the whole array.

Python users, feel free to add to the discussion...

**Comment by williamfgc** [comment]
adding @kshitij-v-mehta @jychoi-hpc @JasonRuonanWang @pnorbert

**Comment by williamfgc** [comment]
3. Add configFile.xml option to Python high-level API

**Comment by suchyta1** [comment]
I've noticed that there doesn't seem to be a way to get attributes from the Python bindings. Something like InquireAttribute() seems natural in the low level API, as an analog to InquireVariable().

**Comment by williamfgc** [comment]
@suchyta1 please take a look at PR #672  the python test (testing/adios2/bindings/pythonTestBPWriteReadTypes.py) for types will show the added functionality. Use the IO AvailableAttributes function to get the attribute elements, not InquireAttribute. Thanks!

**Comment by williamfgc** [comment]
I will close this for now. For new requests please open a new issue. Thanks!
