### ISSUE TITLE
Python high-level API multiple step selection dimensions

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#573]
@williamfgc 

Using the same source from Issue #571 with the [heat transfer example](https://github.com/suchyta1/pyDIOS/tree/master/heat-transfer), I print the return dimensions of the numpy array from python, when I try to return multiple time steps from the data. To make testing this faster,  I've attached my bp file, so you can just run the reading part of the [job script](https://github.com/suchyta1/pyDIOS/blob/master/heat-transfer/job.sh) (use group='bpfile' and comment out the mpirun line).

I did a small run, where I've written 4 time steps of 200 x 200 global size. I try to get all the steps, so I expect (4, 200, 200) shaped array.  But what is returned is (800, 800) = (4x200, 4x200), which does not equal the expected number of total elements.

[data.zip](https://github.com/ornladios/ADIOS2/files/1939095/data.zip)

**Comment by williamfgc** [comment]
@suchyta1 great catch. This is a bug that goes deep in the C++11 engine. For now just reader one step at a time, or assign new numpy arrays to each step. Sorry for the inconvenience.

**Comment by williamfgc** [comment]
@suchyta1 please try the latest master. Let me know if the issue still exist.

**Comment by williamfgc** [comment]
@suchyta1 do the python tests work?   Is this the seg fault for large data or small datasets?

**Comment by suchyta1** [comment]
@williamfgc Good idea of what to check. No, the python tests no longer pass. I see some seg faults. In these tests, what seems to cause the seg fault is running with multiple MPI processes. If I try more than one, it crashes. If I use a single process, it doesn't crash, and passes.

**Comment by williamfgc** [comment]
@suchyta1 can you try from a fresh installation? It's strange, 'cause if it's in master it means all the CI tests passed in different platforms using MPI.   You can control the number of MPI processes for ctest with `cmake -DMPIEXEC_MAX_NUMPROCS:STRING=4 ../path/to/ADIOS2`  . Thanks!

**Comment by williamfgc** [comment]
@suchyta1 I disabled the fix for reading multiple steps. I need a more robust solution. The adiosvm cases should work with the latest master. Thanks!

**Comment by suchyta1** [comment]
I think I had something messed up with my build when the more basic unit tests weren't passing. I checked with master and it's indeed fine.

**Comment by williamfgc** [comment]
@suchyta1 can you check if reading multiple steps is working for you with the latest master? I just did a pull requests with tests. Thanks!

**Comment by suchyta1** [comment]
Again, I got way back logged on checking these, but yes it seems good.
