### ISSUE TITLE
Fortran to C dimensions swapping not handled in SST

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#576]
In a Fortran to C staging, the C reader should get the dimensions in C order, because that's how it uses the read selections, then the actual reads should be converted back to Fortran dimension order. 

To recreate the problem, use adiosvm Tutorial/heat2d which has Fortran and C++ codes. In fortran/ directory, edit adios2.xml to use BPFile or SST for the SimulationOutput as needed.

BPFile run:
```
Tutorial/heat2d/fortran$ mpirun -n 1 ./simulation/heatSimulation_adios2 sim 1 1 4 5   1 1 
Using BPFile engine for output
Process decomposition  : 1 x 1
Array size per process : 4 x 5
Number of output steps : 1
Iterations per step    : 1
Simulation step    0: initialization
Total runtime =  0.002s
```

Notice that the Fortran array size is 4 x 5. bpls, as a C tool, will show you this in C order, i.e., 5 x 4

```
Tutorial/heat2d/fortran$ bpls -D sim.bp T
  double   T     {5, 4}
        step 0: 
          block 0: [0:4, 0:3]
```

Run the analysis C++ code:
```
Tutorial/heat2d/fortran$ mpirun -n 1 ../cpp/heatAnalysis sim.bp a.bp 1 1
Using BPFile engine for input
Using BPFile engine for output
gndx       = 5
gndy       = 4
rank 0 reads 2D slice 5 x 4 from offset (0,0)
Analysis step 0 processing simulation step 0

Tutorial/heat2d/fortran$ bpls -D a.bp 
  double   T     {5, 4}
        step 0: 
          block 0: [0:4, 0:3]
  double   dT    {5, 4}
        step 0: 
          block 0: [0:4, 0:3]

```
Notice that the reader sees a 5 x 4 array and reads accordingly, then writes out a 5 x 4 C array to the a.bp file. 

SST run (use SST for SimulationOutput in adios2.xml)
```
Tutorial/heat2d/fortran$ mpirun -n 1 ./simulation/heatSimulation_adios2 sim 1 1 4 5 1 1 : -n 1 ../cpp/heatAnalysis sim.bp sst.bp 1 1
Using SST engine for output
Process decomposition  : 1 x 1
Using SST engine for input
Using BPFile engine for output
Array size per process : 4 x 5
Number of output steps : 1
Iterations per step    : 1
Simulation step    0: initialization
gndx       = 4
gndy       = 5
rank 0 reads 2D slice 4 x 5 from offset (0,0)
Analysis step 0 processing simulation step 0
Total runtime =  0.073s
```

Notice that the C++ reader thinks it reads a 4 x 5 array, but C readers should see 5 x 4.  The output of the C++ application has the wrong order:

```
Tutorial/heat2d/fortran$ bpls -D sst.bp T
  double   T     {4, 5}
        step 0: 
          block 0: [0:3, 0:4]
```

**Comment by eisenhauer** [comment]
@pnorbert This should be repaired now.

**Comment by eisenhauer** [comment]
Closing, as this has been supported (and tested) since mid-June.
