### ISSUE TITLE
Inappropriate compile-time conditional in testing (source of current failures on RaspPi, etc.)

### ISSUE THREAD

**Issue by eisenhauer** [ornladios/ADIOS2#622]
The test TestBPWriteReadAttributesADIOS2.cpp has #ifdef's that test OS and platform defines when they should probably be testing a compiler characteristic (do I use long or long long to get a 64-bit value) instead.

#if defined(_WIN32) || defined(__APPLE__)
        ASSERT_EQ(attr_i64->m_Type, "long long int");
#else
        ASSERT_EQ(attr_i64->m_Type, "long int");
#endif

**Comment by williamfgc** [comment]
@eisenhauer which compiler characteristic?

**Comment by eisenhauer** [comment]
I didn't look at this in enough detail to fix it, but it looks like what you're trying to return here is what type you use to get a 64-bit integer.  I.E. "long long int" or "long int".  That isn't a property of an OS or platform, but of the compiler.  Generally here I'd ask CMake to test and define type sizes as C preprocessor defines, add them to ADIOSConfig.h, and check SIZEOF_LONG_LONG and SIZEOF_LONG here rather than WIN32 and APPLE.

**Comment by chuckatkins** [comment]
Ideally we would be able to move away from "natural" integer types to fixed width integer types for actual data values, which will be agnostic to os, compiler, and platform. It's fairly involved though so something to stick on the Todo list...'

**Comment by williamfgc** [comment]
Actually "long long int" and "long int"  is indeed a property of the OS or platform. It's sufficient to read the documentation alignment https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os. Compilers adapt to the platform requirements. OSX and Windows have long consider long int = int 32-bit integers, long long int is for 64-bit integers. On Linux long int and long long int are both 64-bit. I am going to close this until a better solution can be provided and tested.

**Comment by pnorbert** [comment]
Why do we close tickets that are bugs and are not solved yet?
