### ISSUE TITLE
performance drops significantly when writing 10,000 variables using adios2 bp engine at each step

### ISSUE THREAD

**Issue by lwan86** [ornladios/ADIOS2#625]
I was testing the miniapp code under my branch https://github.com/lwan86/ADIOS2-Examples/tree/miniapp. When writing 10,000 variables at each step, using adios2 bp engine suffers from significant performance degradation compared to using adios1 engine.

This issue can be reproduced on both ubuntu VMs and macbook laptops.

**Comment by lwan86** [comment]
I've tested the newest code on my mac.  There is some improvement, but it is still slower than adios1.

**Comment by williamfgc** [comment]
@lwan86 how are you running the adios1 engine? are you generating metadata at every step? If so, can you rerun using the latest master? Thanks!

**Comment by lwan86** [comment]
@williamfgc I just pulled the latest master and tested again (both adios1 and adios2 are generating metadata at every step). adios2 bp engine is still slower than adios1, but the performance difference is reduced.

**Comment by lwan86** [comment]
@williamfgc I did my own profiling and it shows that function call in BP3Serializer.cpp **AggregateMergeIndex(m_MetadataSet.VarsIndices)** takes the most of the time. Specifically, inside this function call, these three functions are slow:

1. const std::unordered_map<std::string, std::vector<SerialElementIndex>> nameRankIndices =
            DeserializeIndicesPerRankThreads(gatheredSerialIndices)
2. m_Metadata.Resize(position + gatheredSerialIndicesPosition +
                              m_MetadataSet.MiniFooterSize,
                          ", in call to AggregateMergeIndex BP3 metadata")
3. MergeSerializeIndices(nameRankIndices)

**Comment by lwan86** [comment]
After enabling the optimization option during compilation, adios2 is faster than adios1 engine.
