### ISSUE TITLE
Metadata in subfiles is missing

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#629]
The metadata per subfile needs to be written to the end of the subfile (as in adios1). 
The option for writing the global metadata file is independent from this. 
bpmeta is using these pieces of metadata sections to construct the global metadata file if that is missing. 

There may be another option to turn this off but only when the global metadata file is created. Otherwise the data will be unreadable (unless one is willing to run bprecover on each subfile manually)

**Comment by williamfgc** [comment]
@pnorbert @jychoi-hpc I just merged so we can test XGC with the latest master, and then apply bpmeta. I'll keep this open in case there are issues.

**Comment by williamfgc** [comment]
Closing this as no new issue is reported
