### ISSUE TITLE
Linker error when building with ZFP:OFF on Mac using clang 9.1.0 and gfortran 8.1.0

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#634]
I was trying to build using the default configuration on Mac, and I don't have ZFP installed in anywhere on my machine. CMake automatically turned off ZFP because it does not find ZFP library but I still got this linker error complaining about ZFP library missing. 

[ 58%] Linking Fortran executable ../../../bin/hello_bpWriter_f
ld: file not found: @rpath/libzfp.0.dylib for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [bin/hello_bpWriter_f] Error 1
make[1]: *** [examples/hello/bpWriter/CMakeFiles/hello_bpWriter_f.dir/all] Error 2
make: *** [all] Error 2

**Comment by williamfgc** [comment]
@JasonRuonanWang I can't reproduce, do you have a hanging adios2 compilation somewhere else?

**Comment by JasonRuonanWang** [comment]
@williamfgc This was from a few commits ago and I can't reproduce it with the latest master either on my home computer. I will have a look tomorrow on my work laptop and let you know. Thanks.

**Comment by JasonRuonanWang** [comment]
Cannot reproduce any more.
