### ISSUE TITLE
Python API segfault with reading arrays

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#675]
I have a test code in Python that reads variables from a BP file. Reading the first array works fine, but reading the second array leads to a crash due to `*** glibc detected *** python3: munmap_chunk(): invalid pointer: 0x0000000000b78450 ***`.

Test code is on Titan as `/lustre/atlas/world-shared/csc143/kmehta/gtc/python-analysis/test_reader.py`. This uses a slightly older version of ADIOS2. `source.sh` provides this information.

**Comment by williamfgc** [comment]
@kshitij-v-mehta please try the low-level Python APIs (ADIOS, IO, Engine, Variable, etc.). This is still using the single object higher-level API that does the allocation in C++ and passes it to Python.

**Comment by williamfgc** [comment]
@kshitij-v-mehta I committed a fix in the latest master, can you try again and verify that this works? Thanks!

**Comment by kshitij-v-mehta** [comment]
Thanks, it works.
