### ISSUE TITLE
Linking library error with SST and Ascent (Mac)

### ISSUE THREAD

**Issue by stevenwalton** [ornladios/ADIOS2#679]
I have no errors installing ascent when I install adios2 with `ADIOS2_USE_SST=OFF` but when I have SST enabled and add the libraries (using `target_link_libraries(ascent_mpi PRIVATE "-lmpi -L${ADIOS2_DIR}/lib -ladios2 -ladios2_dill -ladios2_atl -ladios2_enet -ladios2_ffs -ladios2_sst")`) to my CMakeLists.txt I get the following error during make

```
[ 20%] Linking CXX shared library ../lib/libascent_mpi.dylib
ld: library not found for -ladios2_dill
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libascent_mpi.dylib] Error 1
make[1]: *** [ascent/CMakeFiles/ascent_mpi.dir/all] Error 2
make: *** [all] Error 2
```
If I rearrange the libraries I will get the first library in the ld error message.

I am running on High Sierra 10.13.4 and on a mac book air

**Comment by williamfgc** [comment]
@chuckatkins @eisenhauer can we have a cmake example on how to link adios2 with sst underlying libraries in an external application (e.g. ascent?)? Thanks!

**Comment by stevenwalton** [comment]
@chuckatkins forgive my naivety with cmake, but how would I implement this? I was assuming something like.

(I can make this a new issue, but I think we had a small discussion about this during the summer when things were different. )

```
if(ENABLE_ADIOS2)
   find_package(adios2 REQUIRED)
   target_link_libraries(ascent_mpi PRIVATE adios2::adios2)
endif()
```
and then adding to the cmake build options `ADIOS2_DIR=path/to/adios2-install-dir`. That leads to the same error I had before with 
```
CMake Error at CMakeLists.txt:176 (find_package):
  By not providing "Findadios2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "adios2", but
  CMake did not find one.

  Could not find a package configuration file provided by "adios2" with any
  of the following names:

    adios2Config.cmake
    adios2-config.cmake

  Add the installation prefix of "adios2" to CMAKE_PREFIX_PATH or set
  "adios2_DIR" to a directory containing one of the above files.  If "adios2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/walton/Programming/ORNL/ascent-adios2/build/CMakeFiles/CMakeOutput.log".
```
Where `adios2-install-dir` contains `bin include lib share` and are accessible by the standard user permissions.

That's why I made that `FindADIOS2.cmake` file and placed it into `adios2-install-dir/etc`. Adding that builds. I did remember that William said you had some other way for me to connect to Ascent. Am I on the right path?

**Comment by chuckatkins** [comment]
@stevenwalton When using `<PackageName>_DIR` variables, you can use then as either environment variables or CMake variables, but the behavior is different.  If using as a CMake variable via `-D` then it needs to be set to the directory containing the package config file, so in this case `-DADIOS2_DIR=/path/to/adios2-install-dir/lib/cmake/adios2` for the install tree or `-DADIOS2_DIR=/path/to/adios2-build-dir` to directly use a build tree.  However, if using `<PackageName>_DIR` as an environment variable and not a CMake variable, then you can set it to either the config directory (as in the case of the CMake var) or the install prefix.

 It's confusing, I know, how the `<PackageName>_DIR` variables work but unfortunately it's a long-standing behavior of CMake unlikely to change due to backwards compatibility.

**Comment by chuckatkins** [comment]
It's case sensitive.  CMake is searching for <Package Name>Config.cmake. Try changing `find_package(adios2)` to `find_package(ADIOS2)`

**Comment by stevenwalton** [comment]
Maybe we need to be a little more explicit. I don't actually know why there is `adios2_DIR`. In ascent if I do `grep -R adios2_DIR src/cmake` I find nothing (but I do when searching `ADIOS2_DIR`). The only time I do find `adios2_DIR` is 

Ascent links together third party libraries, named `SetupTHIRDPARTYLIBRARYNAME.cmake`

So here's my `SetupADIOS2.cmake` file. Maybe you can tell me where I'm going wrong.
```
if(NOT ADIOS2_DIR)
    MESSAGE(FATAL_ERROR "ADIOS2 support needs explicit ADIOS2_DIR")
endif()

MESSAGE(STATUS "Looking for ADIOS2 using ADIOS2_DIR = ${ADIOS2_DIR}")

set(ADIOS2_ROOT ${ADIOS2_DIR})
set(ENV{ADIOS2_ROOT} ${ADIOS2_ROOT})

find_package(ADIOS2 REQUIRED)
set(ADIOS2_FOUND TRUE)

if(NOT ADIOS2_FOUND)
    message(FATAL_ERROR "ADIOS2_DIR ${ADIOS2_DIR} is not a path to a valid ADIOS2 install")
endif()

blt_register_library(NAME adios2
                     INCLUDES ${ADIOS2_INCLUDE_DIRS}
                     LIBRARIES ${ADIOS2_LIBRARIES} )
```
I am unsure how to get it to recognize ADIOS2. I have even added the line
```
include(${ADIOS2_DIR}"/lib/cmake/adios2/ADIOS2Config.cmake")
```

**Comment by chuckatkins** [comment]
So, typically the _DIR and _ROOT variables are not set by the consuming project.  The CMake code would typically be something like this:

```cmake
option(FOO_ENABLE_ADIOS2 "Enable ADIOS2 support." OFF)
if(FOO_ENABLE_ADIOS2)
 find_package(ADIOS2 REQUIRED)
endif()
```
The package exports for ADIOS2 already create the imported target so to consume it after its found:
```cmake
add_library(foo ...)
if(FOO_ENABLE_ADIOS2)
  target_link_libraries(foo PRIVATE adios2::adios2)
endif()
```
Then when configuring:
```bash
$ cmake -DADIOS2_ROOT=/path/to/adios2-install -DFOO_ENABLE_ADISO2=ON /path-to/foo-source
```
Note that the `<PackageName>_ROOT` only works CMake >= 3.11 (maybe 3.12?).  Otherwise you need to use `<PackageName>_DIR.  Regardless though, the consuming project (in this case ascent) should only be calling `find_package(ADIOS2)` and not mucking around with `ADIOS2_ROOT` or `ADIOS2_DIR` CMake or env vars.  Those are intended to be set by the user.

**Comment by stevenwalton** [comment]
That doesn't quite work for me, and I am confused. I do have a working `CMakeLists.txt` for building *only* adios2 programs. Could I use this as a template for linking with ascent?

If so, how would I handle `target_link_libraries`?

```cmake
cmake_minimum_required(VERSION 3.6)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_COMPILER "mpicxx")
set(CMAKE_CC_COMPILER  "mpicc")

set(ADIOS2_DIR "~/Programming/ORNL/adios2-install/lib/cmake/adios2")

find_file(ADIOS2_CONFIG
          NAME adios2-config
          PATHS ${ADIOS2_DIR})
if(ADIOS2_CONFIG)
    message("Found 'adios2-config': ${ADIOS2_CONFIG}")
endif(ADIOS2_CONFIG)

set(ADIOS2_ROOT_DIR ${ADIOS2_CONFIG} --prefix)
set(ADIOS2_LIBRARIES ${ADIOS2_ROOT_DIR}/lib)
set(ADIOS2_INCLUDE_DIRS ${ADIOS2_ROOT_DIR}/include)
include_directories($ENV{LD_LIBRARY_PATH})

execute_process(COMMAND ${ADIOS2_CONFIG} --libs
                OUTPUT_VARIABLE ADIOS2_LINKERFLAGS
                RESULT_VARIABLE ADIOS2_CONFIG_RETURN
                OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND ${ADIOS2_CONFIG} --cxxflags
                OUTPUT_VARIABLE ADIOS2_CXXFLAGS
                RESULT_VARIABLE ADIOS2_CONFIG_RETURN
                OUTPUT_STRIP_TRAILING_WHITESPACE)
            
find_package(MPI REQUIRED)
find_package(ADIOS2 REQUIRED)

set(ADIOS2_FLAGS ${ADIOS2_LINKERFLAGS} ${ADIOS2_CXXFLAGS})

add_executable(rOverSST rOverSST.cpp)
add_executable(wOverSST wOverSST.cpp)
target_link_libraries(rOverSST adios2::adios2 ${ADIOS2_FLAGS})
target_link_libraries(wOverSST adios2::adios2 ${ADIOS2_FLAGS})

```

If not, maybe it would help if you looked at where I'm at. Here's a link to what [used to work](https://github.com/stevenwalton/ascent/blob/develop/src/cmake/thirdparty/SetupADIOS2.cmake) but that involved me creating a `FindADIOS2.cmake` file and placing that into `adios2-install/etc`

```cmake
cmake_minimum_required(VERSION 2.8.5)

set(OPTLIST "--libs")
set(ADIOS2_FOUND TRUE)

find_file(ADIOS2_CONFIG
    NAME adios2-config
    PATHS $ENV{ADIOS2_ROOT}/bin $ENV{ADIOS2_DIR}/bin $ENV{INSTALL_PREFIX}/bin $ENV{PATH})

if(ADIOS2_CONFIG)
    message(STATUS "Found 'adios2-config': ${ADIOS2_CONFIG}")
else(ADIOS2_CONFIG)
    set(ADIOS2_FOUND FALSE)
    message(STATUS "Can NOT find 'adios2-config' - set ADIOS2_ROOT, ADIOS2_DIR or INSTALL_PREFIX, or check your PATH")
endif(ADIOS2_CONFIG)

if(ADIOS2_FOUND)
    execute_process(COMMAND ${ADIOS2_CONFIG} ${OPTLIST}
                    OUTPUT_VARIABLE ADIOS2_LINKFLAGS
                    RESULT_VARIABLE ADIOS2_CONFIG_RETURN
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT ADIOS2_CONFIG_RETURN EQUAL 0)
        set(ADIOS2_FOUND FALSE)
        message(STATUS "Can NOT execute 'adios2-config' - check file permissions")
    endif()

    # find ADIOS2_ROOT_DIR
    execute_process(COMMAND ${ADIOS2_CONFIG} --prefix
                    OUTPUT_VARIABLE ADIOS2_ROOT_DIR
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT IS_DIRECTORY "${ADIOS2_ROOT_DIR}")
        set(ADIOS2_FOUND FALSE)
        message(STATUS "The directory provided by 'adios2-config --prefix' does not exist: ${ADIOS2_ROOT_DIR}")
    endif()
endif(ADIOS2_FOUND)

if(ADIOS2_USE_STATIC_LIBS)
    # carfully: we have to restore the original path in the end
    set(_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
    set(CMAKE_FIND_LIBRARY_SUFFIXES .a)
endif()

if(ADIOS2_FOUND)
    # ADIOS2 headers
    list(APPEND ADIOS2_INCLUDE_DIRS ${ADIOS2_ROOT_DIR}/include)

    # check for compiled in dependencies, recomve ";" in ADIOS2_LINKFLAGS (from cmake build)
    string(REGEX REPLACE ";" " " ADIOS2_LINKFLAGS "${ADIOS2_LINKFLAGS}")
    message(STATUS "ADIOS2 linker flags (unparsed): ${ADIOS2_LINKFLAGS}")

     set(ADIOS2_LIBRARY_DIRS "")
    string(REGEX MATCHALL " -L([A-Za-z_0-9/\\.-]+)" _ADIOS2_LIBDIRS " ${ADIOS2_LINKFLAGS}")
    foreach(_LIBDIR ${_ADIOS2_LIBDIRS})
        string(REPLACE " -L" "" _LIBDIR ${_LIBDIR})
        list(APPEND ADIOS2_LIBRARY_DIRS ${_LIBDIR})
    endforeach()

    message(STATUS "ADIOS2 DIRS to look for libs: ${ADIOS2_LIBRARY_DIRS}")

    # parse all -lname libraries and find an absolute path for them
    string(REGEX MATCHALL " -l([A-Za-z_0-9\\.\\-\\+]+)" _ADIOS2_LIBS " ${ADIOS2_LINKFLAGS}")
    foreach(_LIB ${_ADIOS2_LIBS})
        string(REPLACE " -l" "" _LIB ${_LIB})

        # find static lib: absolute path in -L then default
        find_library(_LIB_DIR NAMES ${_LIB} PATHS ${ADIOS2_LIBRARY_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)

        # found?
        if(_LIB_DIR)
            message(STATUS "Found ${_LIB} in ${_LIB_DIR}")
            list(APPEND ADIOS2_LIBRARIES "${_LIB_DIR}")
        else(_LIB_DIR)
            set(ADIOS2_FOUND FALSE)
            message(STATUS "ADIOS2: Could NOT find library '${_LIB}'")
        endif(_LIB_DIR)

        # clean cached var
        unset(_LIB_DIR CACHE)
        unset(_LIB_DIR)
    endforeach()

    #add libraries which are already using cmake format
    string(REGEX MATCHALL "/([A-Za-z_0-9/\\.\\-\\+]+)\\.([a|so]+)" _ADIOS2_LIBS_SUB "${ADIOS2_LINKFLAGS}")
    foreach(foo ${_ADIOS2_LIBS_SUB})
    if (EXISTS ${foo})
        message("Appending: ${foo}")
        list(APPEND ADIOS2_LIBRARIES "${foo}")
    endif()
    endforeach(foo)

    # add the version string
    execute_process(COMMAND ${ADIOS2_CONFIG} --version
                    OUTPUT_VARIABLE ADIOS2_VERSION
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
    
endif(ADIOS2_FOUND)

# unset checked variables if not found
if(NOT ADIOS2_FOUND)
    unset(ADIOS2_INCLUDE_DIRS)
    unset(ADIOS2_LIBRARIES)
endif(NOT ADIOS2_FOUND)


# restore CMAKE_FIND_LIBRARY_SUFFIXES if manipulated by this module ###########
if(ADIOS2_USE_STATIC_LIBS)
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES})
endif()

# handles the REQUIRED, QUIET and version-related arguments for find_package
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ADIOS2
    REQUIRED_VARS ADIOS2_LIBRARIES ADIOS2_INCLUDE_DIRS
    VERSION_VAR ADIOS2_VERSION
)
```

**Comment by williamfgc** [comment]
HI @stevenwalton , @chuckatkins is referring to the fact that you shouldn't need any of the boilerplate to link adios2. Just follow: https://adios2.readthedocs.io/en/latest/using/using.html   ADIOS2_ROOT should be passed to cmake as an argument . 
`cmake -DADIOS2_ROOT=/your/adios2-installation ....`   or (your build if doing development)  

From that point, you can use the adios2::adios2 target for dependencies on cmake `target_link_libraries`. If this minimal approach doesn't work, then there is a bug.

**Comment by chuckatkins** [comment]
You're close.  A couple of things:
```bash
-DCMAKE_INSTALL_PREFIX=../../ascent-install -DADIOS2_ROOT=../../adios2-install
```
CMake typically want's full paths to be specified rather than relative paths so ADIOS2_ROOT should be `$PWD/../../adios2-install` instead.

```bash
Policy CMP0074 is not set
```
That's the key here.  In the top level CMake for ascent, you'll want to add something like:
```cmake
if(POLICY CMP0074)
  cmake_policy(SET CMP0074 NEW)
endif()
```
If not then you'll need to use `-DADIOS2_DIR=$PWD/../../adios2-install/lib/cmake/adios` or set the env `ADISO2_DIR` to the install prefix.

**Comment by stevenwalton** [comment]
We can close this. There was that the proper target was hiding somewhere else (lots of cmake files). 

It does look like I was able to do it the proper way now. Thanks guys, sorry for the frustration.
