### ISSUE TITLE
SST from Fortran Error

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#691]
I'm trying to use SST in coupling XGC and GENE. I've largely gotten it working, but am running into a situation where I can do several successful steps, but then get a failure "at some point".

The way this works, is each stage of the coupling GENE opens a differently named file, and then XGC reads it. And that runs in a loop. In this example, the first 4 stages ran correctly, but when it get's to the fifth I get an error:
```
ADIOS2 open with new MPI_Comm: ERROR: SstReader did not find active Writer contact info in file "../coupling/density_2_core_00005.bp.sst".  Non-current SST contact file?
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DENORMAL
```
I'm not sure if it always fails on the 5th -- I haven't done anything comprehensive to check. If I run with files instead of SST, it runs OK. If there's anything else that's of use, I can try to get more details about the error.

@eisenhauer

**Comment by eisenhauer** [comment]
Is it possible that there are .sst postfix files that remain after some kind of unsuccessful termination of the writer program?  Generally the "SstReader did not find active Writer contact info in file" means that the reader found a file of the appropriate name, but upon reading the SST contact information in that file, there was no longer an active process serving that information.  Perhaps between runs remove everything matching "*.sst"?  If you do this and still get a problem, set the environment variable SstVerbose and we can look at that.

**Comment by suchyta1** [comment]
@eisenhauer I delete everything in the `coupling/` directory at the start of the run, so there isn't anything still sitting there pre-run.

I'm turning on SstVerbose=1, and I'll see what I get.

**Comment by suchyta1** [comment]
This time, the run looked kind of different. It got to phase 4 and hangs, without any explicit error messages. I attached the logs.
[GENE-log.txt](https://github.com/ornladios/ADIOS2/files/2138434/GENE-log.txt)
[XGC-log.txt](https://github.com/ornladios/ADIOS2/files/2138435/XGC-log.txt)

**Comment by suchyta1** [comment]
To add a little more detail to my previous messages about how the coupling proceeds, in each stage, both XGC and GENE each do a read and write. First GENE writes density data, which XGC consumes. Then XGC writes some potential data, which GENE consumes. It is that process that runs in a loop.

**Comment by eisenhauer** [comment]
Is this all done with the default Sst engine parameters?  I.E. rendezvous readers=1 and queue limit = 0 (unlimited)?
One concern here is that unlike file-based transports, Sst is more synchronous.  For example, with BP, the writing side can do an open/write/close and roll on without worrying about a reader.  While on the reader side, the open() will block until the file is there, but then roll on without delay.  With SST, the open() on the writer side is going to block until the reader does an open() too.  Then the reader side blocks until the writer does the write.   And the writer side blocks on close() until all the readers actually consume all the data and themselves do close() or advance().  Maybe this just all works out, but maybe not.  It's more likely to just work out if the communication graph is a DAG.  But this communication graph is specifically cyclic, and it looks like there's more than one stream involved (edge?, core?).   The upshot is that there may be potential for application-level deadlock because of the different semantics down below.  I'm still trying to sort out what might be happening from the logs, but something to consider...

**Comment by pnorbert** [comment]
I understand that this is an error, but the coupling should be done with
one fixed filename to make the connection once.

The new BP metadat format is going tp support this mode through files as
well.

**Comment by suchyta1** [comment]
All the defaults are indeed used. I think the process should "work" because everything with density has to happen, then everything with field, and so forth. So GENE sends density, and won't continue until XGC receives. After that GENE just basically instantly goes to waiting for potential data until XGC is ready to send it. Then XGC sends it and both can continue. Everything is synchronous, and we've run it with P2P memory exchange like this before. 

Doing everything from the same filename would be easy enough to try to change to. It's just the way it was here for irrelevant historical reasons. Though, I wasn't entirely sure what the correct thing to do was with the same file name. Does the "file" cease to exist after the write close occurs? And then subsequent steps just make a new step 0. Or is there somehow appending steps going on so more than one would be available? (I'm using append for the step mode.)

**Comment by suchyta1** [comment]
Thinking about this, it's probably ok to only open once at the first stage, then at each stage start a new step, write/read, and end the step, and only close once at the very end. I just hadn't done it that way, b/c that approach doesn't work with files.

**Comment by eisenhauer** [comment]
Doing one filename and multiple opens/closes would be bad.  (Then I would understand how you might have stale file data, and there would be no efficiency improvement over multiple filenames.)  Doing one open and multiple begin/end steps would be the way to go.   There is no append step mode for SST...

**Comment by suchyta1** [comment]
I think it was understood from Norbert's comment, but for clarity if anyone
didn't follow: so far I've had a different filename each step, but I'll
also try the single filename with single open and see how that goes.

**Comment by suchyta1** [comment]
I was way behind following up on these issue, but I'm no longer seeing this one either.

**Comment by eisenhauer** [comment]
Cool.  Closing then.
