### ISSUE TITLE
Compile error on CompressSZ

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#705]
I don't understand why this is not compiling. Ubuntu 16.10 VM, gcc 6.2.0, latest master, SZ is ON:

[ 27%] Building CXX object source/adios2/CMakeFiles/adios2.dir/operator/compress/CompressSZ.cpp.o
/home/adios/work/ADIOS2/source/adios2/operator/compress/CompressSZ.cpp: In member function ‘virtual std::size_t adios2::core::compress::CompressSZ::Decompress(const void*, std::size_t, void*, const Dims&, std::__cxx11::string, const Params&) const’:
/home/adios/work/ADIOS2/source/adios2/operator/compress/CompressSZ.cpp:369:51: error: ‘GetTotalSize’ was not declared in this scope
     size_t dataSizeBytes = GetTotalSize(dimensions) * typeSizeBytes;
                                                   ^
/home/adios/work/ADIOS2/source/adios2/operator/compress/CompressSZ.cpp:369:51: note: suggested alternative:
In file included from /home/adios/work/ADIOS2/source/adios2/helper/adiosFunctions.h:16:0,
                 from /home/adios/work/ADIOS2/source/adios2/operator/compress/CompressSZ.cpp:19:
/home/adios/work/ADIOS2/source/adios2/helper/adiosMath.h:30:8: note:   ‘adios2::helper::GetTotalSize’
 size_t GetTotalSize(const Dims &dimensions) noexcept;
        ^~~~~~~~~~~~
source/adios2/CMakeFiles/adios2.dir/build.make:1214: recipe for target 'source/adios2/CMakeFiles/adios2.dir/operator/compress/CompressSZ.cpp.o' failed
make[2]: *** [source/adios2/CMakeFiles/adios2.dir/operator/compress/CompressSZ.cpp.o] Error 1

**Comment by williamfgc** [comment]
@pnorbert the namespace helper:: is needed for `helper::GetTotalSize` it helps understand where functions come from. I never touched SZ since this is from Jong's hackathon project. I am working on operators interface and buffering right now.

**Comment by williamfgc** [comment]
Closing this since SZ support is now in master.
