### ISSUE TITLE
engine%type is always BPFile

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#706]
No matter what the engine is, this fortran structure member is always BPFile:

        call adios2_open (bp_writer, io, filename, adios2_mode_write, adios2_err)
        ! For information purposes only:
        if (rank == 0) then
            print '("Using ",a, " engine for output")', bp_writer%type
        endif

```
adios@adiosVM:~/work/adiosvm/Tutorial/heat2d/fortran$ mpirun  -n 12 simulation/heatSimulation_adios2 heat       4  3   40  50   10  1000 : -n   3 ../cpp/heatAnalysis heat.bp analysis.bp    3  1 
Process decomposition  : 4 x 3
Array size per process : 40 x 50
Number of output steps : 10
Iterations per step    : 1000
Simulation step    0: initialization
Using BPFile          engine for output
```

**Comment by williamfgc** [comment]
@pnorbert this is using the xml config I assume...then, it is a bug in the Fortran API

**Comment by pnorbert** [comment]
Yes, this is the heat transfer example after fixing the F90 source,
replacing the adios2_io_engine_type() function with this.

**Comment by williamfgc** [comment]
@pnorbert @suchyta1 this should be fixed on master, please let me know. Thanks!

**Comment by pnorbert** [comment]
Yes this update fixed it, thanks.
