### ISSUE TITLE
Get Version number

### ISSUE THREAD

**Issue by stevenwalton** [ornladios/ADIOS2#707]
Can I get a function that passes back the version number?

**Comment by williamfgc** [comment]
@stevenwalton since this is a very specific case, I think directly including `adios2/ADIOSConfig.h` will give you access to the compile-time definitions: 

```#define ADIOS2_VERSION_MAJOR 2
#define ADIOS2_VERSION_MINOR 2
#define ADIOS2_VERSION_PATCH 0
#define ADIOS2_VERSION       2.2.0
```

**Comment by williamfgc** [comment]
On a 2nd thought you don't need to adios2/ADIOSConfig.h , it's already included in adios2.h
