### ISSUE TITLE
C and Fortran API name clash

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#713]
aiods2_advance_step has multiple definitions, found while working with the C bindings on hPIC code.

**Comment by williamfgc** [comment]
@suchyta1 @jychoi-hpc can you verify that this fix solved the name clash problem? Thanks!

**Comment by suchyta1** [comment]
Yes, it worked for me.

**Comment by williamfgc** [comment]
Great, thanks @suchyta1 ! Closing this.
