### ISSUE TITLE
`type 11 not supported` for variable of type `adios2_type_complex_dp`

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#719]
I am running an example that contains a variable of type complex(kind=8).
At runtime, I get the following error:
`ADIOS2 end_step: ERROR: type 11 not supported in BP3 Metadata Merge`.
Variable was declared as `adios2_type_complex_dp`.

This is on a local machine with gcc 6.3.0. ADIOS2 version is from master with last commit 8984e168452ade27fae89918b86bd872a84d4e47 .

**Comment by williamfgc** [comment]
Moving this to #785
