### ISSUE TITLE
DataMan test failing

### ISSUE THREAD

**Issue by tneuroth** [ornladios/ADIOS2#728]
`$ ctest -VV -R DataMan
UpdateCTestConfiguration  from :/home/tn0/repos/A2-BUILD/DartConfiguration.tcl
Parse Config file:/home/tn0/repos/A2-BUILD/DartConfiguration.tcl
 Add coverage exclude regular expressions.
 Add coverage exclude: .*/thirdparty/.*
 Add coverage exclude: .*/testing/.*
 Add coverage exclude: .*/examples/.*
SetCTestConfiguration:CMakeCommand:/usr/local/bin/cmake
UpdateCTestConfiguration  from :/home/tn0/repos/A2-BUILD/DartConfiguration.tcl
Parse Config file:/home/tn0/repos/A2-BUILD/DartConfiguration.tcl
Test project /home/tn0/repos/A2-BUILD
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 108
    Start 108: DataManTest.WriteRead1DSubscribe

108: Test command: /home/tn0/repos/A2-BUILD/bin/TestDataMan "--gtest_filter=DataManTest.WriteRead1DSubscribe"
108: Test timeout computed to be: 1500
108: Note: Google Test filter = DataManTest.WriteRead1DSubscribe
108: [==========] Running 1 test from 1 test case.
108: [----------] Global test environment set-up.
108: [----------] 1 test from DataManTest
108: [ RUN      ] DataManTest.WriteRead1DSubscribe
108: unknown file: Failure
108: C++ exception with description "ERROR: this version of ADIOS2 didn't compile with ZMQ library, in call to Open
108: " thrown in the test body.
108: [  FAILED  ] DataManTest.WriteRead1DSubscribe (2 ms)
108: [----------] 1 test from DataManTest (2 ms total)
108: 
108: [----------] Global test environment tear-down
108: [==========] 1 test from 1 test case ran. (2 ms total)
108: [  PASSED  ] 0 tests.
108: [  FAILED  ] 1 test, listed below:
108: [  FAILED  ] DataManTest.WriteRead1DSubscribe
108: 
108:  1 FAILED TEST
1/1 Test #108: DataManTest.WriteRead1DSubscribe ...***Failed    0.07 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.09 sec

The following tests FAILED:
	108 - DataManTest.WriteRead1DSubscribe (Failed)
Errors while running CTest`

**Comment by williamfgc** [comment]
@JasonRuonanWang DataMan tests should only run if adios2 was compiled with ZMQ.

**Comment by JasonRuonanWang** [comment]
I have fixed the issue and merged into the master. Please check and let me know there is still problems.
