### ISSUE TITLE
shared library problem on Mac

### ISSUE THREAD

**Issue by BarrySmith** [ornladios/ADIOS2#743]
When I build master on Mac (with the latest Mac OS and Xcode all up to date), and try to link against adios2.dylib I get the linker unable to find libadios2_atl.2.dylib

Poking around a little bit I noticed

$ otool -L arch-darwin-c-debug/lib/libadios2_sst.dylib 
arch-darwin-c-debug/lib/libadios2_sst.dylib:
        @rpath/libadios2_sst.2.dylib (compatibility version 2.0.0, current version 2.2.0)
        @rpath/libadios2_evpath.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libadios2_ffs.1.dylib (compatibility version 1.0.0, current version 1.5.2)
        libadios2_atl.2.dylib (compatibility version 2.0.0, current version 2.2.1)
        /usr/local/opt/mpich/lib/libmpi.12.dylib (compatibility version 14.0.0, current version 14.1.0)
        /usr/local/opt/mpich/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)

I think this is wrong because there is no @rpath/ in front of libadios2_atl.2.dylib are perhaps the shared libraries not being built correctly with cmake on the Mac?

Any suggestions?

**Comment by BarrySmith** [comment]
The same cmake commands and process work fine for Linux so I think this is an issue specific to the Mac.

**Comment by williamfgc** [comment]
Hi @BarrySmith, please try adding the lib directory under adios2 installation to DYLD_LIBRARY_PATH on MAC. You're right, we have seen different runtime behaviors on Mac and Linux.

**Comment by BarrySmith** [comment]
@williamfgc Thanks for your quick response. @chuckatkins  Setting DYLD_LIBRARY_PATH does allow the code to run successfully. 

But this is not a very attractive approach for automatic builds, testing etc (for security reasons Apple doesn't pass environmental variables like this through scripts which breaks our tests). Note that ONLY the single library libadios2_atl.2.dylib  is missing the @rpath/ prefix that it should have while the other libraries, such as @rpath/libadios2_sst.2.dylib do have the @rpath/ prefix thus I suspect something hinky with the cmake code that builds the adios2 libraries.

**Comment by eisenhauer** [comment]
Would you please test this with the current master.  I believe that the situation may be improved:
bash-3.2$ otool -L ~/lib/libadios2_sst.dylib 
/Users/eisen/lib/libadios2_sst.dylib:
	@rpath/libadios2_sst.2.dylib (compatibility version 2.0.0, current version 2.2.0)
	@rpath/libadios2_evpath.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libadios2_ffs.1.dylib (compatibility version 1.0.0, current version 1.6.0)
	@rpath/libadios2_atl.2.dylib (compatibility version 2.0.0, current version 2.2.1)
	/opt/local/lib/openmpi-mp/libmpi.40.dylib (compatibility version 41.0.0, current version 41.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
bash-3.2$

The issue seems to have been that the third-party atl project allowed a lower version of CMake than the other projects.  I.E. it required only better than 2.8 rather than better than 3.0.  This requirement specification apparently has unexpected side effects, setting policy defaults in CMake rather than just rejecting too-old versions of CMake.  So, even if you used CMake > 3.0, it would behave more like CMake 2.8 when building ATL, and that version of CMake didn't by default do the right thing with OSX RPATHs.

**Comment by BarrySmith** [comment]
The fix resolved the problem for me. Thanks
