### ISSUE TITLE
ClipContiguousMemory bug for compressed data

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#768]
The ClipContiguousMemory function does not seem to do the correct thing for compressed data. 

For example, I write a variable for shape = {5,5}, start = {0,0}, count = {5,5}, which is 

0.00  0.01  0.02  0.03  0.04  
0.05  0.06  0.07  0.08  0.09  
0.10  0.11  0.12  0.13  0.14  
0.15  0.16  0.17  0.18  0.19  
0.20  0.21  0.22  0.23  0.24  

And I read for start = {1, 1}, and count = {2,2} on the reader side. If I don't use compression, I got the correct result:

0.06  0.07  
0.11  0.12  

If I use compression, I got incorrect results: 

0.00  0.01  
0.05  0.06  

This happens with both BPFile engine and SST engine using BP marshaling.

**Comment by JasonRuonanWang** [comment]
It seems that when an operator is added, the ClipContiguousMemory function always copies data from the first element of the input BP buffer. It misses an offset.

**Comment by williamfgc** [comment]
Thanks @JasonRuonanWang I am missing the extra clipping from the block start to the intersection start.
