### ISSUE TITLE
'adios2-config --libs' displays incorrect list of libraries

### ISSUE THREAD

**Issue by swatisgupta** [ornladios/ADIOS2#770]
Result of "adios2_config --libs" is
{ADIOS_INSTALL_DIR}/lib -ladios2 -L/usr/lib64 **-ldataman** -lbz2

The correct output should be 
{ADIOS_INSTALL_DIR}/lib -ladios2 -L/usr/lib64 -lbz2 

If SST is enabled it should be
{ADIOS_INSTALL_DIR}/lib -ladios2 -L/usr/lib64 -lbz2 -ladios2_sst -ladios2_evpath -ladios2_enet -ladios2_dill -ladios2_ffs -ladios2_dill  -ladios2_atl

**Comment by williamfgc** [comment]
@eisenhauer @chuckatkins can you document how to link with the sst external dependencies?  I still don't understand the added complexity to the developer.

**Comment by jychoi-hpc** [comment]
Is there any update on this? I am getting this problem too.

**Comment by chuckatkins** [comment]
Fixed by #1081
