### ISSUE TITLE
Heat transfer example crashes with SST on Titan

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#778]
Hi, I'm having trouble running the heat transfer example with SST engine on Titan. The example crashes after a dozens of timesteps. I'm using the current master of ADIOS2 (237f1be25b65035a1f1b5944b276461befd624c9).

Command

```
aprun -n 64 ./heatTransfer_write_adios2 ./heat_sst.xml foo 8 8 1000 1000 100 100 : -n 16 ./heatTransfer_read ./heat_sst.xml foo.bp bar 4 4
```

Config XML file (same as `examples/heatTransfer/heat_sst_ffs.xml`)

```
<?xml version="1.0"?>
<!-- Config XML file fo the
     - heatTransfer_write_adios2
     - heatTransfer_read
     executables in build/bin -->

<adios-config>

    <!--====================================
           Configuration for the Writer
        ====================================-->

    <io name="writer">
        <engine type="SST">
            <parameter key="MarshalMethod" value="FFS"/>
        </engine>
    </io>


    <!--======================================
           Configuration for the Reader Input
        ======================================-->

    <io name="readerInput">
        <engine type="SST">
            <parameter key="MarshalMethod" value="FFS"/>
        </engine>
    </io>


    <!--=======================================
           Configuration for the Reader output
        =======================================-->

    <io name="readerOutput">
        <engine type="BPFile">
        </engine>
    </io>

</adios-config>
```

stdout
https://gist.github.com/keichi/73e4974403cd3f2dc5f4f8f3e0c4e1b9

stderr (SstVerbose=1)
https://gist.github.com/keichi/9e5b9891e5124f9771c063acdb5976b5

**Comment by williamfgc** [comment]
Might be related to #710

**Comment by chuckatkins** [comment]
@williamfgc @eisenhauer Is this safe to close now?

**Comment by williamfgc** [comment]
@chuckatkins Titan is gone, but I'd let@eisenhauer address the identification and solution for the issue.

**Comment by eisenhauer** [comment]
This is really ancient now, and we've made a lot of changes to address scalability with a variety of applications.  I don't think there's a path forward for this particular issue at this point.  So closing...
