### ISSUE TITLE
Inconsistency between the documentation and implemetation for ON/OFF option

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#791]
I found a minor inconsistency between the documentation and implementation.

The [documentation](https://adios2-adaptable-io-system-version-2.readthedocs.io/en/latest/engines/engines.html#bpfile) for the BPFile engine says string `ON` or `OFF` should be used to enable/disable Profile or CollectiveMetadata.

However, the implementation does not accept uppercase `ON`/`OFF`, but only lowercase `on`/`off` or camelcase `On`/`Off`. 

For example, if I put the following line in my XML,

```
<parameter key="CollectiveMetadata" value="OFF"/>
```

I see the following error message:

```
ERROR: IO SetParameters profile invalid value, valid: CollectiveMetadata On or Off in call to Open
```

The corresponding method in the source code is https://github.com/ornladios/ADIOS2/blob/ab1a2e45dda32235158e67091ee37b40cb27ad84/source/adios2/toolkit/format/bp3/BP3Base.cpp#L310

**Comment by williamfgc** [comment]
Thanks @keichi , I am working on updating the docs right now.

**Comment by pnorbert** [comment]
This should not be fixed in the documentation. We need all options in all adios be processed case-insensitive. Do we have a helper function to return a lower case string of a string that can be used everywhere? I think I just used std::transform myself in every place.

**Comment by keichi** [comment]
@williamfgc I've built the current master and confirmed it is fixed now. Thanks!
