### ISSUE TITLE
Zeros in multiple time steps when no Close is called and Flush is (BPFIle)

### ISSUE THREAD

**Issue by stevenwalton** [ornladios/ADIOS2#794]
Working with the Ascent program I am unable to call `adiosWriter.Close()` and a few issues have been brought up because of this case. I have found that when writing to BPFiles that the first time step correctly writes, but each subsequent `BeginStep()/EndStep()` pair is called that the data does not get written. 

This currently does not affect SST or DataMan and #757 fixed the issues for HDF5.

When writing toy examples I can not reproduce the problem and I do not get it when I use small vectors within Ascent. It appears that vector sizes need to be quite large to reproduce this error. 

If `adiosWriter.Close()` is called, this is not an issue.

**Comment by stevenwalton** [comment]
I have tried to replicate the issue in a simple 1D case and can reproduce the behavior. I used similar vector sizes to that in Ascent (274625, or 65^3)
```
#include <iostream>
#include <vector>

#include <adios2.h>
#include <mpi.h>

int main(int argc, char **argv)
{
    MPI_Init(&argc, &argv);
    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    adios2::ADIOS adios(MPI_COMM_WORLD, adios2::DebugON);
    std::vector<double> v(274625,1);

    adios2::IO IO = adios.DeclareIO("writerIO");
    IO.SetEngine("bpfile");

    adios2::Engine writer = IO.Open("timesteps_test.bp", adios2::Mode::Write, MPI_COMM_WORLD);
    std::size_t vsize = v.size();
    std::vector<std::size_t> o(vsize,0);
    adios2::Variable<double> myVec;
    myVec = IO.DefineVariable<double>("vector",
                                      {size * vsize},
                                      {0},
                                      {vsize});
    
    for ( auto i = 0; i < 50; ++i )
    {
        writer.BeginStep();
        writer.Put(myVec, v.data());
        writer.PerformPuts();
        writer.EndStep();
        writer.Flush();  // MUST BE HERE TO REPRODUCE!!!!
    }
    MPI_Finalize();
    return 0;
    //writer.Close();

}
```
The interesting thing is the `Flush()` **MUST** exist for the code to reproduce. And that would explain why I didn't have this issue before. It must have popped up after I implemented the fix with #757 .

**Comment by chuckatkins** [comment]
@williamfgc @pnorbert is this related to #1752 and MPI_Finalize being called while adios still has some cleanup work to do?

**Comment by williamfgc** [comment]
@chuckatkins actually, this is an early design decision that's always open for discussion. `Close` must be called to ensure we release I/O resources. We are not following RAII strictly in the low-level C++ API for I/O system resources.

**Comment by eisenhauer** [comment]
Closing this as outdated.  BP5 (current default engine) doesn't show this problem and it throws a warning about possible corruption when destroying an engine object without a prior close.
