### ISSUE TITLE
Attributes associating with a variable

### ISSUE THREAD

**Issue by guj** [ornladios/ADIOS2#795]
This ticket is opened as William's request.

This is the HDF way:
1) create attr:
    input: parent_id, attrname
2) write attr
3) open attr
4) delete attr
5) find attr (input object_id) 
Note: 
(relative path can be used but it has to lead to an *existing* object. same as "ls path" on unix)

For ADIOS,  in order to support var & attribute association,  we need to:
a) assign association
b) retreive assocation

So I suggest we need to add these in IO:
- DefineAttr([var], attrname, ...)
- InqAttr([var]) 

[var] can be a var object or a valid var name.  Basically it needs to refer to an valid var.

So internally, it might be useful to add a collection of attrs to the Variable class for the new functions to return.

Please let me know when these functionalities are ready.  This would be what the inteoperability milestone will achieve.  Of course we are limiting the attributes to be 1D for now. And not sharing attributes between variables.

**Comment by williamfgc** [comment]
@guj @pnorbert @jychoi-hpc added check for variable existence and default "/" separator in Fortran.

**Comment by williamfgc** [comment]
@guj @pnorbert can we close this?

**Comment by guj** [comment]
Yes, I think so - Junmin

**Comment by guj** [comment]
William checked in code already
