### ISSUE TITLE
heat2d with SST hangs on Titan as it scales

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#813]
I am trying to run heat2d with SST on Titan. With a small number of processes (say, 4 heat2d processes and 4 analysis processes), it works. 

However, with an increased setting (64 head2d and 64 analysis), it hangs. Here is my aprun command:
```
aprun \
   -n 64 simulation/heatSimulation_adios2 heat 8 8 600 300 10 600 :\
   -n 64 analysis/heatAnalysis_adios2_stream heat.bp
```

I think this problem is related with my previous problem (a variant of heat2d in which not all processes writes, available on Titan: /lustre/atlas2/csc143/proj-shared/jyc/titan/adios2-heat2d)

**Comment by keichi** [comment]
This might be the same problem I'm having (#778).

**Comment by jychoi-hpc** [comment]
Is there any update? I just tried again today on Titan but got the following error lines:
```
[ANAL:96] Reader 38 (0x1363900): Connection failed in CP_sendToPeer! Contact list was:
[ANAL:112] Reader 53 (0x1363900): Connection failed in CP_sendToPeer! Contact list was:
```

**Comment by jychoi-hpc** [comment]
With 1024 writers and 1024 readers, I got the following error:
```
[HEAT:0] Cannot accept socket connection: Too many open files
```
I am wondering if `ulimit -n` can help here.

**Comment by eisenhauer** [comment]
That sounds like you are running out of file descriptors, which is expected to happen at some point with TCP/IP (and why we want RUDP).   You can try ulimit -n, but there may also be limits to how big you can make that.  Either at the OS configuration level, or compiled into the kernel (those limits might be gone now, but they used to be a very hard limit).

**Comment by chuckatkins** [comment]
Seems to be resolved.  Although the scaling issue would likely be mitigated by #1778
