### ISSUE TITLE
Occasional failure of SstKillReaders test.

### ISSUE THREAD

**Issue by eisenhauer** [ornladios/ADIOS2#829]
Creating this issue as a way to let everyone know this is being worked on.  The SstKillReaders test starts a long-running writer (server) application and then spawns and kills readers over a span of time.  At the end, we shut down the writer normally and expect any remaining readers to shut down normally.  It appears that sometimes there is a timing problem that prevents a reader from getting properly established.  The writer still shuts down cleanly, but that stuck reader raises an exception saying that it couldn't properly establish a stream (which is also OK in general, but shouldn't be happening here). 
This seems to happen only on readers that try to join an in-progress stream, so the other tests haven't been showing this issue.  If you have a PR that is held up because this test happened to fail, you can just trigger another build and hopefully you'll get lucky.   (One way:  "git commit --amend --no-edit ; git push -f" )  I'll sort this out as soon as I can.

**Comment by chuckatkins** [comment]
@eisenhauer is this resolved now?

**Comment by eisenhauer** [comment]
Yeah, we can probably close it at least for now.  I hadn't yet out of an abundance of caution.  But I haven't seen anything that looks like the heisen-bug failure mode for a couple of days now.  So, closing.
