### ISSUE TITLE
Memory leak when using SST with FFS marshaling

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#836]
When I run the heat transfer example with SST engine and FFS marshaling, the reader is terminated by the OOM killer after a few hundred timesteps. If I use BP marshaling, there is no memory leak, and the workflow can run for thousands of timesteps.

I did some memory debugging with DDT, and it seems that the memory allocated in `IssueReadRequests()` is not freed.

https://github.com/ornladios/ADIOS2/blob/752a618fe3ae9881f989b77c2ad309c6ebde6ab9/source/adios2/toolkit/sst/cp/ffs_marshal.c#L683-L684

**Comment by eisenhauer** [comment]
Please check with current master branch.  I've merged a fix...

**Comment by keichi** [comment]
@eisenhauer I confirmed the memory leak is fixed on current master. Thanks!

**Comment by keichi** [comment]
You might want to remove this printf or use `CP_verbose()` instead?

https://github.com/ornladios/ADIOS2/blob/4580d9d0a1951fd49e279197c4d29e6821581674/source/adios2/toolkit/sst/cp/ffs_marshal.c#L344

**Comment by eisenhauer** [comment]
Whoops!  Part of the problem was that there was a global free routine not being called.  That bit of debugging info slipped through.  I’ll do another PR to kill it.

**Comment by keichi** [comment]
Thanks, closing this issue now.
