### ISSUE TITLE
Brusselator SST performance issue

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#842]
Analysis code using SST is much slower with this example than to read from files. Same issue on VM and on Titan.

``` 
$ mpirun -n 16 ./simulation/Brusselator bru.bp 32 32 32 100 1
$ time mpirun -n 4 ./analysis/norm_calc bru.bp a.bp 0
```
```
VM: 
           BP     SST/FFS     SST/BP
         0.7s        14s         19s
```

Titan, with 256^3, 100 steps, 64 writers + 64 readers:
File based: a few minutes
SST based: does not finish within an hour. Also steps are slowing down visibly.

**Comment by keichi** [comment]
Profiling results on Titan

![screen shot 2018-09-07 at 11 28 15](https://user-images.githubusercontent.com/791283/45228435-296fe080-b291-11e8-82e2-ab6975acd54e.png)
