### ISSUE TITLE
GTC set selection is backwards

### ISSUE THREAD

**Issue by dpugmire** [ornladios/ADIOS2#855]
but in set selection.
Trying to read in C++ from the GTC output (which is done in fortran)

DIMS: [32 3 38315]
terminate called after throwing an instance of 'std::invalid_argument'
  what():  ERROR: selection Start Dims(3):[0, 0, 0] and Count Dims(3):[1, 1, 500] (requested) is out of bounds of available Shape Dims(3):[38315, 3, 32] , when reading variable coordinates, in call to Get

**Comment by williamfgc** [comment]
@dpugmire thanks for confirming this works now, I just modified a couple of tests to get the 2D and 3D Fortran writer and C++ reader on the same page. Thanks!
