### ISSUE TITLE
Setting engine to SST results in an xgc variable "time" changing types from double to float

### ISSUE THREAD

**Issue by tneuroth** [ornladios/ADIOS2#856]
Setting the engine to SST results in an xgc variable "time" changing type from double to float. Then when trying to read it there is a crash,

munmap_chunk(): invalid pointer: 0x00002aab3ea503ad ***

**Comment by pnorbert** [comment]
Notes:
- This is the xgc.particles.bp output of XGC. 
- "time"is a double scalar written only by rank 0. It is defined on every processor though in the IO object. 
- Fortran writer, C++ reader
- io.VariableType("time") returns a string saying it is a float variable
- io.InquireVariable<float>("time) returns successfully
- engine.Get() will crash

**Comment by eisenhauer** [comment]
I'm hopeful that this is now fixed.  Please try with current master.

**Comment by eisenhauer** [comment]
I believe that this was fixed a few weeks ago.  If not, please resubmit.
