### ISSUE TITLE
InSituMPI writer ignores FixedSchedule parameter

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#862]
When using the In-situ MPI engine, the writer sends the metadata even if `FixedSchedule` is true.

I noticed `FixedSchedule` is checked in `void InSituMPIReader::InitParameters()`, but not in 
 `void InSituMPIWriter::InitParameters()`.

**Comment by pnorbert** [comment]
You need to call engine.FixedSchedule() on both sides. If the read pattern
changes, or the write layout changes, metadata is going to be exchanged at
every step.
And I don't think we have this function in the Fortran API, so...

**Comment by williamfgc** [comment]
To do: 
1) Remove it as a runtime parameter in XML InsituMPI reader
2) Add Fortran API call

**Comment by keichi** [comment]
As a minor side note, we should update `examples/hello/insituMPI/hello_insitu.xml` too.

**Comment by keichi** [comment]
Closing issue as we will work on this in #871
