### ISSUE TITLE
String array attribute leads to segfault in C API

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#895]
The conversion routine from char** to string vector in 
adios2_c_io.cpp:296-310  adios2_define_variable_attribute() 
is faulty. A test code in C

char *strarray[] = {"first", "second", "third", "fourth"};
adios2_define_attribute(ioH, "strarray", adios2_type_string_array, strarray, 4);

leads to segmentation fault. The incoming const void * pointer should be cast to const char **
then there is a constructor for string vectors for char**, or a simple loop over the pointer can be used.

**Comment by williamfgc** [comment]
This should be fixed.

**Comment by pnorbert** [comment]
This is fixed.
