### ISSUE TITLE
Short writes are not treated correctly in FilePOSIX transport

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#905]
Currently, ADIOS2 aborts when POSIX write() writes fewer bytes than requested. Short writes are explicitly allowed in the POSIX specification and need to be treated correctly (repeat write() until no unwritten data is left).

https://github.com/ornladios/ADIOS2/blob/ebb0c217e51ce415e066c5cab3c9b71b53271bf5/source/adios2/toolkit/transport/file/FilePOSIX.cpp#L81-L101

**Comment by keichi** [comment]
This is causing occasional aborts on my application.

**Comment by williamfgc** [comment]
@keichi is this aborting or throwing an exception. If it throws an exception is it the one triggered by if (static_cast<size_t>(writtenSize) != size) ? Any compelling reason why size and writtenSize are not the same for each write?

**Comment by williamfgc** [comment]
@keichi this is what `man 2 write` says:

`The number of bytes written may be less than count if, for example, there is insufficient space on the  under‐lying  physical  medium, or the RLIMIT_FSIZE resource limit is encountered (see setrlimit(2)), or the call was interrupted by a signal handler after having written less than count bytes.  (See also pipe(7).)`

**Comment by keichi** [comment]
Hmm so writing less shouldn't be allowed except under those conditions?

Relevant thread from the Lustre mailing list:
https://groups.google.com/forum/#!topic/lustre-discuss-list/-wFgIIQ6PDk

**Comment by eisenhauer** [comment]
@keichi you are right.  The write() call should be in a loop that handles the situation where the write is short but not erroneous.

**Comment by eisenhauer** [comment]
A loop around the write() call is standard practice because returning a short write is explicitly allowed by the specification.  Intro class example here: https://www.cs.uky.edu/~raphael/programming.html

**Comment by keichi** [comment]
Here's my fix, I'm testing it on Titan now. I'm also testing FileStdio transport and FileFStream transport if the same problem occurs.

**Comment by williamfgc** [comment]
@eisenhauer that doesn't guarantee data integrity at scale on HPC systems, not surprised as it's intro material. @keichi thanks for testing, I wonder about the failure rates on Titan and if fstream is taking care of it internally, in the docs it says nothing about it.

**Comment by eisenhauer** [comment]
No guarantees unless you read back what you wrote, but ya gotta do the loop or you won't even get that far...
