### ISSUE TITLE
ctest cannot launch MPMD tests on Cori with Slurm 

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#912]
The MPMD tests (SST, InsituMPI) cannot run on Cori because the launch syntax is different from what cmake generates. See 
https://www.nersc.gov/users/computational-systems/cori/running-jobs/advanced-running-jobs-options/
Search for MPMD.
`srun --multi-prog ./mpmd.con`
Currently we get errors for each test:
`srun: fatal: Job steps that span multiple components of a heterogeneous job are not currently supported`

**Comment by JasonRuonanWang** [comment]
Now we know that running MPMD is not a simple thing. It's pretty common that on a big machine, people have to write a several thousand line job description file to run MPMD, and once the job scheduler breaks, it can take a year to recover. So we are probably not expecting ADIOS2 tests will contain knowledge how to manage this anyway.
