### ISSUE TITLE
LockDefinitions() in Python bindings

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#931]
I think `LockDefinitions()` is missing from the glue layer in the Python bindings. I was trying to test that out in some of my code, but when I try to call the method from an `IO` object that has been opened into into an engine for reading, the method isn't there. @williamfgc @keichi @pnorbert 

<img width="833" alt="screen shot 2018-10-15 at 3 14 41 pm" src="https://user-images.githubusercontent.com/3419552/46973065-2e912e00-d08e-11e8-94e7-b678507598ff.png">

**Comment by keichi** [comment]
@williamfgc Thanks, the glue code for Python was incomplete.
