### ISSUE TITLE
Fortran bindings step count

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#962]
I've written a simple Fortran program to read a BPFile. This file has a single step, but calls to `adios2_current_step` are returning values larger than one if I call `adios2_begin_step` with `adios2_step_mode_next_available` more than once. Also the step status always seems to return 0, which isn't especially surprising I suppose, given the `begin_step` behavior, but I was expecting `begin_step` wouldn't behave this way. `bpls` and `adios2_variable_steps` tell me there is only a single step in the file.

I've pasted the Fortran program code in here, as well as zipped my job run script and `.bp` file.

[fortran-debug.zip](https://github.com/ornladios/ADIOS2/files/2523085/fortran-debug.zip)

```fortran
!read.F90

recursive subroutine file_seek(filename, step, varname)
    use mpi
    use adios2

    character(len=*), intent(in) :: filename, varname
    integer, intent(in) :: step

    integer :: ierr, i, rank, comm, berr
    integer(kind=8) :: my_step, current_step, total_steps
    logical :: found

    type(adios2_variable) :: varid
    type(adios2_engine) :: engine
    type(adios2_io) :: io
    type(adios2_adios) :: adios

    rank = -1
    found = .false.
    my_step = -1
    comm = mpi_comm_world

    call mpi_comm_rank(comm, rank, ierr)
    call adios2_init(adios, comm, adios2_debug_mode_on, ierr)
    call adios2_declare_io(io, adios, "read", ierr)
    call adios2_open(engine, io, trim(filename), adios2_mode_read, comm, ierr)

    do while (.true.)
        call adios2_begin_step(engine, adios2_step_mode_next_available, berr)

        call adios2_current_step(current_step, engine, ierr)
        call adios2_inquire_variable(varid, io, trim(varname), ierr)
        call adios2_variable_steps(total_steps, varid, ierr)

        if (rank == 0) then
            write (*, "('filename: ', A, ',  Total steps: ', I0, ',  current step: ', I0, ',  wanted step: ', I0, ',  Begin err: ', I0)") trim(filename), total_steps, current_step, step, berr
        end if

        if (ierr == 0) then
            my_step = my_step + 1
        else
            exit
        end if

        if (my_step == step) then
            found = .true.
            exit
        end if

        call adios2_end_step(engine, ierr)
    end do

    if (.not.found) then

       call adios2_close(engine, ierr) 
        call adios2_remove_all_variables(io, ierr)
        call file_seek(trim(filename), step, trim(varname))
    end if

end subroutine file_seek

program debug
    use mpi
    character(len=256) :: filename, steps_str, varname
    integer :: i, ierr, steps, stat

    call getarg(1, filename)
    call getarg(2, steps_str)
    call getarg(3, varname)
    read(steps_str, *, iostat=stat) steps

    call mpi_init(ierr)
    do i=0, steps-1
        call file_seek(trim(filename), i, "data")
    end do
    call mpi_finalize(ierr)

end program debug

```

``` bash
#job.sh
mpif90 -g -ffree-line-length-none -I$(adios2-config --prefix)/include/fortran/ $(adios2-config --libs) -ladios2_f read.F90 -o read
filepath="density.bp"
varname="data"

bpls $filepath
mpirun -n 1 ./read $filepath 4 $varname

rm ./read
```
With output:
```
./job.sh
  double   data  {8, 210943}
  int      nphi  scalar
filename: density.bp,  Total steps: 1,  current step: 0,  wanted step: 0,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 0,  wanted step: 1,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 1,  wanted step: 1,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 0,  wanted step: 2,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 1,  wanted step: 2,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 2,  wanted step: 2,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 0,  wanted step: 3,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 1,  wanted step: 3,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 2,  wanted step: 3,  Begin err: 0
filename: density.bp,  Total steps: 1,  current step: 3,  wanted step: 3,  Begin err: 0
```

**Comment by pnorbert** [comment]
The BeginStep syntax has changed. You need to get status from there and
exit the loop on that status.
call adios2_begin_step(fh, adios2_step_mode_next_available, -1.0, istatus,
ierr)

See example:
https://github.com/pnorbert/adiosvm/blob/master/Tutorial/heat2d/fortran/analysis/heatAnalysis_adios2_stream.F90

 do
        call adios2_begin_step(fh, adios2_step_mode_next_available, -1.0,
istatus, ierr)
        if (ierr /= 0) then
            print '(" Failure when trying to get next step: ",a)',
streamname
            exit
        endif
        if (istatus == adios2_step_status_end_of_stream) then
            ! Stream has terminated, no more steps are available
            exit
        endif

**Comment by williamfgc** [comment]
Hi @suchyta1 I sent an email about the API changes a while back about changes to sync the C and Fortran bindings. ierr and status are separated just like in MPI_Irecv (which is what BeginStep is, a receiver in read mode) as they signal two different things. Please follow what @pnorbert posted. I am asking for everyones' patience in the API changes, which are in the latests stages, but this is typical in that weird stage between a release candidate and a release. Thanks!

**Comment by suchyta1** [comment]
OK, thanks! I'm not having the issues any more.
