### ISSUE TITLE
Build with python

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#971]
When I am trying to build with python (-DADIOS2_USE_Python=ON), it looks like cmake is trying to find "python3" first, not "python". 

I am wondering if this is the current case. I think it didn't do that way before.

I think it would be reasonable to search "python" first by default.

**Comment by williamfgc** [comment]
@chuckatkins please chime in on python3 having precedence over python 2.  @jychoi-hpc please check the docs: https://adios2.readthedocs.io/en/latest/installation/installation.html#enabling-the-python-bindings the minimum requirements section. You can always provide the python executable to cmake: -DPYTHON_EXECUTABLE=

**Comment by jychoi-hpc** [comment]
Sorry. I haven't checked the document. 

If I have all pythons in my path: python, python2, and python3, cmake will find python3 > python2 > python in that order. Is it right? 

It's not a big deal. I will use -DPYTHON_EXECUTABLE option. Thanks.

**Comment by williamfgc** [comment]
@jychoi-hpc yeah, it will try to find the toolchain: python-dev, numpy, mpi4py, not only the python executable. OK, thanks!
