### ISSUE TITLE
cmake error with xcode

### ISSUE THREAD

**Issue by JasonRuonanWang** [ornladios/ADIOS2#981]
CMake Error in source/utils/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /Users/jason/build/adios2_xcode/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/bpls.cmake

CMake Error in source/utils/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /Users/jason/build/adios2_xcode/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/bpls.cmake

CMake Error in source/utils/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /Users/jason/build/adios2_xcode/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/bpls.cmake

CMake Error in source/utils/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /Users/jason/build/adios2_xcode/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/bpls.cmake

CMake Error in source/utils/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /Users/jason/build/adios2_xcode/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/bpls.cmake

CMake Error in source/utils/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /Users/jason/build/adios2_xcode/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/bpls.cmake

-- Generating done
-- Build files have been written to: /Users/jason/build/adios2_xcode

**Comment by chuckatkins** [comment]
Fixed in current master.
