### ISSUE TITLE
Conda-Forge Feedstock

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#985]
Are you planning a conda-forge feedstock for quick installs?

Although the primary audience will barely be HPC with conda-forge, I find a conda-forge binary release quite useful for desktop applications such as [HDFcompass](https://github.com/HDFGroup/hdf-compass), people writing serial python scripts on small data and CI in [downstream projects](https://github.com/openPMD/openPMD-api).

Full disclosure: I am the current packer of the [ADIOS](https://github.com/conda-forge/adios-feedstock) and [ADIOS-Python](https://github.com/conda-forge/adios-python-feedstock) feedstocks for ADIOS1. (Happy to share the maintenance work.)

**Comment by williamfgc** [comment]
Hi @ax3l we don't have immediate plans or resources targeting specific package managers. That being said, we'll be very happy to work with you on a conda distribution if you're interested. Our priority is to get the December release out and have a stable cmake build backend for the C++11 library and bindings, so any package manager frontend can be then applied. BTW, package managers have become my preferred installation method. Let us know. Thanks!

**Comment by ax3l** [comment]
Hi @williamfgc, thank you for the quick answer. That sounds great! A student of ours (@franzpoeschel) is currently starting to explore ADIOS2 in detail to make it usable in [openPMD-api](https://github.com/openPMD/openPMD-api) and with that in [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/).

We will soon-ish need it in CI and CD. When we are there I will probably set up a conda-forge feedstock again and ping here for coordination. Time-scales match, that will work!

**Comment by williamfgc** [comment]
Hi @ax3l @franzpoeschel thanks for the update, looking forward to hearing about your experience with  openPMD-api/PIConGPU and the conda-forge feedstock. Let us know if you have any questions. For the python scripts applications on small data, desktop apps and CI cases we built a high-level simplified API that is all write/read (sync) based for a quick jump start. For a [Python example](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI.py). Similarly with [C++](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/engine/bp/TestStreamWriteReadHighLevelAPI.cpp) Thanks!

**Comment by ax3l** [comment]
Excellent, we will write the openPMD bindings against the native C++11 API and should use the ADIOS2 python API again in projects like [HDF-Compass](https://github.com/HDFGroup/hdf-compass) so we have a file explorer at hands.

**Comment by williamfgc** [comment]
@ax3l my bad, actually @chuckatkins has something you can start with: (adios2-conda scripts)[https://github.com/ornladios/ADIOS2/tree/master/scripts/conda]

**Comment by williamfgc** [comment]
resolved in [conda-forge adios2 feedstock](https://github.com/conda-forge/adios2-feedstock). Thanks to @ax3l
