### ISSUE TITLE
Python function to check no. of steps available 

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#987]
Using the low-level Python Read API, is there a way to get the number of timesteps available for a variable?

**Comment by williamfgc** [comment]
@kshitij-v-mehta thanks. This implies complete reimplementation of the Variable object and all of its functions. It's on my list, I just haven't had the chance to look into it. Thanks!

**Comment by eisenhauer** [comment]
I'm going to close this because it's ancient, but opening another that is related, #3851 .
